// AUTO-GENERATED by scripts/build-story-cover-pack.mjs — do not edit by hand.
// Every story whose card cover ships inside this build.
export const OFFLINE_STORY_COVER_IDS: readonly string[] = [
  "story-fall-of-baghdad-1258",
  "story_at_the_gates_of_baghdad",
  "story_baghdad_before_the_storm",
];

/** Content version each bundled cover was built from (delta-sync input). */
export const OFFLINE_STORY_COVER_VERSIONS: Readonly<Record<string, number>> = {
  "story-fall-of-baghdad-1258": 1,
  "story_at_the_gates_of_baghdad": 1,
  "story_baghdad_before_the_storm": 1,
};
