// GENERATED by scripts/build-campaign-art-pack.mjs — do not edit by hand.
// Storage paths (bucket `campaign-key-art`) of every chapter image whose
// bytes ship inside this build under /campaign-key-art/<storage path>.
export const OFFLINE_CHAPTER_IMAGE_PATHS: readonly string[] = [];
