// GENERATED by scripts/build-campaign-art-pack.mjs — do not edit by hand.
// Storage paths (bucket `campaign-key-art`) of every chapter image whose
// bytes ship inside this build under /campaign-key-art/<storage path>.
export const OFFLINE_CHAPTER_IMAGE_PATHS: readonly string[] = [
  "chapters/ch1/20260906-1788642265386-pyx711.webp",
  "chapters/ch2/20260906-1788645084052-zuevvi.webp",
  "chapters/ch4/20260905-1788640957573-ohgkn2.webp",
  "chapters/ch5/20260906-1788671886161-1xlq24.webp",
];
