// /admin/atlas-calibration — Phase 0.1 anchor measurement tool.
//
// Dev-only workflow for visually placing the 16 calibration anchors on the
// frozen Atlas v1 raster (14192×7088). Stays out of the live atlas UX:
// nothing here imports or mutates AtlasShell, atlas-hubs, or atlas-regions.
//
// Workflow per docs/atlas/atlas-calibration-plan.md §3.4:
//   1. Pick an anchor from the sidebar (or hit "Locate")
//   2. Zoom to ~100% (1:1 pixel button) and pan to the labelled feature
//   3. Drag the pin onto the feature; the read-out shows live APS pixels
//   4. Press "Confirm" to flip verified:true for that anchor
//   5. Repeat for all 16, then Export → paste the snippet into
//      src/data/atlas-anchors.ts
//
// Work-in-progress is persisted to localStorage so a refresh never loses
// reviewer effort. Optional second-reviewer mode diffs an imported export
// against the current placements with the 8 px tolerance from the plan.

import { createFileRoute, Link } from "@tanstack/react-router";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  ChevronLeft, Crosshair, Download, Locate, MaximizeIcon, RotateCcw,
  ScanSearch, ShieldCheck, Upload, X,
} from "lucide-react";
import { AdminGate } from "@/lib/admin-guard";
import atlasMaster from "@/assets/atlas/atlas-v1-master.jpg.asset.json";
import {
  ATLAS_ANCHORS_V1,
  ATLAS_V1_PIXEL_SIZE,
  type AtlasAnchor,
} from "@/data/atlas-anchors";

export const Route = createFileRoute("/admin/atlas-calibration")({
  head: () => ({
    meta: [
      { title: "معايرة الأطلس — إرث" },
      { name: "robots", content: "noindex,nofollow" },
    ],
  }),
  component: () => <AdminGate><CalibrationPage /></AdminGate>,
});

const STORAGE_KEY = "atlas-calibration-wip-v1";
const PIN_TOLERANCE_PX = 8;
const RASTER = ATLAS_V1_PIXEL_SIZE;

// Anchors flagged by the Phase 0.1 validator as needing rework
// (high affine residuals or close-pair drift). Surfaced in the UI so the
// reviewer can target them on the re-export pass.
const NEEDS_REVIEW: ReadonlySet<string> = new Set([
  "samarkand", "bukhara", "mecca", "medina", "marrakech",
]);

// Sister pairs that should sit visually close on the raster — drawn as a
// dashed connector so any gross mismatch is immediately obvious.
const SISTER_PAIRS: ReadonlyArray<readonly [string, string]> = [
  ["samarkand", "bukhara"],
];

type WorkingAnchor = AtlasAnchor;

type ReviewerB = { id: string; aps: { x: number; y: number } }[] | null;

function loadWip(): WorkingAnchor[] {
  if (typeof window === "undefined") return [...ATLAS_ANCHORS_V1];
  try {
    const raw = window.localStorage.getItem(STORAGE_KEY);
    if (!raw) return [...ATLAS_ANCHORS_V1];
    const parsed = JSON.parse(raw) as WorkingAnchor[];
    // Merge: only override aps/verified for ids that still exist.
    return ATLAS_ANCHORS_V1.map((a) => {
      const hit = parsed.find((p) => p.id === a.id);
      return hit ? { ...a, aps: hit.aps, verified: !!hit.verified } : a;
    });
  } catch {
    return [...ATLAS_ANCHORS_V1];
  }
}

function saveWip(rows: WorkingAnchor[]) {
  try {
    window.localStorage.setItem(
      STORAGE_KEY,
      JSON.stringify(rows.map((r) => ({ id: r.id, aps: r.aps, verified: r.verified }))),
    );
  } catch { /* ignore quota */ }
}

function formatExport(rows: WorkingAnchor[]): string {
  const lines: string[] = [];
  lines.push("// Generated by /admin/atlas-calibration — paste into src/data/atlas-anchors.ts");
  lines.push("// Replace the SEEDS array with the snippet below, OR replace each anchor's");
  lines.push("// aps + verified fields individually.");
  lines.push("");
  lines.push("const SEEDS: AnchorSeed[] = [");
  for (const r of rows) {
    const notes = r.notes ? `, notes: ${JSON.stringify(r.notes)}` : "";
    lines.push(
      `  { id: ${JSON.stringify(r.id)}, name: ${JSON.stringify(r.name)}, region: ${JSON.stringify(r.region)}, lon: ${r.lon}, lat: ${r.lat}, aps: { x: ${Math.round(r.aps.x)}, y: ${Math.round(r.aps.y)} }, verified: ${r.verified}${notes} },`,
    );
  }
  lines.push("];");
  lines.push("");
  return lines.join("\n");
}

function CalibrationPage() {
  const [rows, setRows] = useState<WorkingAnchor[]>(() => loadWip());
  const [selectedId, setSelectedId] = useState<string>(rows[0]?.id ?? "");
  const [reviewerB, setReviewerB] = useState<ReviewerB>(null);
  const [showExport, setShowExport] = useState(false);

  useEffect(() => { saveWip(rows); }, [rows]);

  const selected = rows.find((r) => r.id === selectedId) ?? null;

  // ── Viewer transform (image-pixel → screen) ────────────────────────────
  const wrapRef = useRef<HTMLDivElement>(null);
  const [wrapSize, setWrapSize] = useState({ w: 1, h: 1 });
  const [scale, setScale] = useState(0.06); // fits 14192-wide into ~850px by default
  const [tx, setTx] = useState(0);
  const [ty, setTy] = useState(0);
  const [cursorAps, setCursorAps] = useState<{ x: number; y: number } | null>(null);

  useEffect(() => {
    const el = wrapRef.current;
    if (!el) return;
    const update = () => setWrapSize({ w: el.clientWidth || 1, h: el.clientHeight || 1 });
    update();
    const ro = new ResizeObserver(update);
    ro.observe(el);
    return () => ro.disconnect();
  }, []);

  const fitToScreen = useCallback(() => {
    const sx = wrapSize.w / RASTER.width;
    const sy = wrapSize.h / RASTER.height;
    const s = Math.min(sx, sy) * 0.96;
    setScale(s);
    setTx((wrapSize.w - RASTER.width * s) / 2);
    setTy((wrapSize.h - RASTER.height * s) / 2);
  }, [wrapSize.w, wrapSize.h]);

  // First-fit once we know the wrap size.
  const didFit = useRef(false);
  useEffect(() => {
    if (!didFit.current && wrapSize.w > 10 && wrapSize.h > 10) {
      didFit.current = true;
      fitToScreen();
    }
  }, [wrapSize, fitToScreen]);

  const setOneToOne = useCallback(() => {
    const cx = wrapSize.w / 2;
    const cy = wrapSize.h / 2;
    // Keep the current center pixel under cursor → new scale = 1.
    const ax = (cx - tx) / scale;
    const ay = (cy - ty) / scale;
    setScale(1);
    setTx(cx - ax);
    setTy(cy - ay);
  }, [scale, tx, ty, wrapSize.w, wrapSize.h]);

  const centerOn = useCallback((aps: { x: number; y: number }, targetScale = 1) => {
    const s = targetScale;
    setScale(s);
    setTx(wrapSize.w / 2 - aps.x * s);
    setTy(wrapSize.h / 2 - aps.y * s);
  }, [wrapSize.w, wrapSize.h]);

  // ── Pan (middle/right drag, or shift+drag on empty space) ───────────────
  const pan = useRef<{ x: number; y: number; tx: number; ty: number } | null>(null);
  const onWrapPointerDown = (e: React.PointerEvent) => {
    // Only start pan on empty stage clicks (target is the stage img/bg).
    const target = e.target as HTMLElement;
    if (target.dataset.role !== "stage") return;
    wrapRef.current?.setPointerCapture(e.pointerId);
    pan.current = { x: e.clientX, y: e.clientY, tx, ty };
  };
  const onWrapPointerMove = (e: React.PointerEvent) => {
    const rect = wrapRef.current?.getBoundingClientRect();
    if (rect) {
      const sx = e.clientX - rect.left;
      const sy = e.clientY - rect.top;
      const ax = (sx - tx) / scale;
      const ay = (sy - ty) / scale;
      if (ax >= 0 && ax < RASTER.width && ay >= 0 && ay < RASTER.height) {
        setCursorAps({ x: ax, y: ay });
      } else {
        setCursorAps(null);
      }
    }
    if (!pan.current) return;
    setTx(pan.current.tx + (e.clientX - pan.current.x));
    setTy(pan.current.ty + (e.clientY - pan.current.y));
  };
  const onWrapPointerUp = () => { pan.current = null; };

  // ── Wheel zoom around cursor ───────────────────────────────────────────
  useEffect(() => {
    const el = wrapRef.current;
    if (!el) return;
    const onWheel = (e: WheelEvent) => {
      e.preventDefault();
      const rect = el.getBoundingClientRect();
      const sx = e.clientX - rect.left;
      const sy = e.clientY - rect.top;
      const step = Math.min(0.25, Math.abs(e.deltaY) * 0.0015);
      const factor = e.deltaY < 0 ? 1 + step : 1 / (1 + step);
      setScale((prev) => {
        const next = Math.max(0.01, Math.min(8, prev * factor));
        const k = next / prev;
        setTx((tx0) => sx - (sx - tx0) * k);
        setTy((ty0) => sy - (sy - ty0) * k);
        return next;
      });
    };
    el.addEventListener("wheel", onWheel, { passive: false });
    return () => el.removeEventListener("wheel", onWheel);
  }, []);

  // ── Pin drag (in screen space → APS update) ────────────────────────────
  // dragOffset = client cursor minus pin's pixel-space anchor in raster coords,
  // so dragging is sub-pixel stable regardless of zoom level.
  const dragPin = useRef<{ id: string; dxAps: number; dyAps: number } | null>(null);
  const onPinPointerDown = (e: React.PointerEvent, id: string) => {
    e.stopPropagation();
    setSelectedId(id);
    const target = e.currentTarget as HTMLElement;
    target.setPointerCapture(e.pointerId);
    const rect = wrapRef.current?.getBoundingClientRect();
    if (!rect) return;
    const row = rows.find((r) => r.id === id)!;
    const cursorAx = (e.clientX - rect.left - tx) / scale;
    const cursorAy = (e.clientY - rect.top - ty) / scale;
    dragPin.current = {
      id,
      dxAps: row.aps.x - cursorAx,
      dyAps: row.aps.y - cursorAy,
    };
  };
  const onPinPointerMove = (e: React.PointerEvent) => {
    if (!dragPin.current) return;
    const rect = wrapRef.current?.getBoundingClientRect();
    if (!rect) return;
    const cursorAx = (e.clientX - rect.left - tx) / scale;
    const cursorAy = (e.clientY - rect.top - ty) / scale;
    const ax = cursorAx + dragPin.current.dxAps;
    const ay = cursorAy + dragPin.current.dyAps;
    const id = dragPin.current.id;
    setRows((prev) => prev.map((r) =>
      r.id === id
        ? {
            ...r,
            // Dragging clears verified — must re-confirm.
            verified: false,
            aps: {
              x: Math.max(0, Math.min(RASTER.width - 1, ax)),
              y: Math.max(0, Math.min(RASTER.height - 1, ay)),
            },
          }
        : r,
    ));
  };
  const onPinPointerUp = () => { dragPin.current = null; };

  const confirmSelected = () => {
    if (!selected) return;
    setRows((prev) => prev.map((r) => (r.id === selected.id ? { ...r, verified: true } : r)));
  };
  const unconfirmSelected = () => {
    if (!selected) return;
    setRows((prev) => prev.map((r) => (r.id === selected.id ? { ...r, verified: false } : r)));
  };
  const resetAll = () => {
    if (!confirm("إعادة تعيين كل الإحداثيات إلى القيم المبدئية؟")) return;
    setRows([...ATLAS_ANCHORS_V1]);
  };

  const verifiedCount = rows.filter((r) => r.verified).length;

  // ── Reviewer-B comparison ──────────────────────────────────────────────
  const onImportReviewerB = async (file: File) => {
    const text = await file.text();
    // Accept either a raw JSON array or the SEEDS snippet — extract id/aps pairs.
    const re = /id:\s*["']([^"']+)["'][^}]*?aps:\s*\{\s*x:\s*(-?\d+(?:\.\d+)?)\s*,\s*y:\s*(-?\d+(?:\.\d+)?)/g;
    const out: { id: string; aps: { x: number; y: number } }[] = [];
    let m: RegExpExecArray | null;
    while ((m = re.exec(text))) out.push({ id: m[1], aps: { x: +m[2], y: +m[3] } });
    if (!out.length) {
      try {
        const arr = JSON.parse(text) as { id: string; aps: { x: number; y: number } }[];
        if (Array.isArray(arr)) setReviewerB(arr);
        else alert("ملف غير مفهوم.");
      } catch { alert("ملف غير مفهوم."); }
      return;
    }
    setReviewerB(out);
  };

  const diffById = useMemo(() => {
    const map = new Map<string, number>();
    if (!reviewerB) return map;
    for (const r of rows) {
      const b = reviewerB.find((x) => x.id === r.id);
      if (!b) continue;
      map.set(r.id, Math.hypot(r.aps.x - b.aps.x, r.aps.y - b.aps.y));
    }
    return map;
  }, [rows, reviewerB]);

  // ── Render ─────────────────────────────────────────────────────────────
  return (
    <div className="flex h-screen w-screen bg-stone-950 text-stone-100" dir="rtl">
      {/* Sidebar */}
      <aside className="flex w-80 shrink-0 flex-col border-l border-stone-800 bg-stone-900/80">
        <header className="flex items-center gap-2 border-b border-stone-800 p-3">
          <Link to="/admin" className="rounded p-1 text-stone-400 hover:bg-stone-800 hover:text-stone-100">
            <ChevronLeft className="size-4" />
          </Link>
          <div className="flex-1">
            <h1 className="text-sm font-bold">معايرة الأطلس (Phase 0.1)</h1>
            <p className="text-[11px] text-stone-400">
              {verifiedCount}/{rows.length} مؤكد · Atlas v1 ({RASTER.width}×{RASTER.height})
            </p>
          </div>
        </header>

        <div className="border-b border-stone-800 bg-amber-500/5 px-3 py-2 text-[11px] leading-snug text-amber-200/90">
          ⚠️ ضع المرساة على الموقع الجغرافي الفعلي للمدينة قدر الإمكان، لا على
          النص أو الاسم المرسوم. التسميات قد تكون بعيدة عن النقطة الحقيقية.
        </div>

        <div className="flex flex-wrap gap-1.5 border-b border-stone-800 p-2 text-[11px]">
          <ToolBtn onClick={fitToScreen} icon={MaximizeIcon} label="ملاءمة" />
          <ToolBtn onClick={setOneToOne} icon={ScanSearch} label="1:1" />
          <ToolBtn onClick={() => selected && centerOn(selected.aps, 1)} icon={Locate} label="تموقع" />
          <ToolBtn onClick={resetAll} icon={RotateCcw} label="تصفير" />
          <ToolBtn onClick={() => setShowExport(true)} icon={Download} label="تصدير" />
          <label className="inline-flex cursor-pointer items-center gap-1 rounded border border-stone-700 bg-stone-800 px-2 py-1 hover:bg-stone-700">
            <Upload className="size-3.5" />
            <span>مراجع ب</span>
            <input
              type="file" accept=".ts,.txt,.json" className="hidden"
              onChange={(e) => { const f = e.target.files?.[0]; if (f) onImportReviewerB(f); e.target.value = ""; }}
            />
          </label>
          {reviewerB && (
            <button onClick={() => setReviewerB(null)} className="inline-flex items-center gap-1 rounded border border-stone-700 bg-stone-800 px-2 py-1 hover:bg-stone-700">
              <X className="size-3.5" /> إلغاء المقارنة
            </button>
          )}
        </div>

        <ul className="flex-1 overflow-y-auto p-2">
          {[...rows]
            .sort((a, b) => Number(NEEDS_REVIEW.has(b.id)) - Number(NEEDS_REVIEW.has(a.id)))
            .map((r) => {
            const diff = diffById.get(r.id);
            const drift = diff != null && diff > PIN_TOLERANCE_PX;
            const active = r.id === selectedId;
            const needsReview = NEEDS_REVIEW.has(r.id);
            return (
              <li key={r.id}>
                <button
                  onClick={() => { setSelectedId(r.id); centerOn(r.aps, Math.max(scale, 1)); }}
                  className={`flex w-full items-center gap-2 rounded px-2 py-1.5 text-right text-[12px] ${
                    active ? "bg-amber-500/15 ring-1 ring-amber-400/40" : "hover:bg-stone-800"
                  } ${needsReview ? "ring-1 ring-rose-500/40" : ""}`}
                >
                  <span className={`size-2 rounded-full ${r.verified ? "bg-emerald-400" : "bg-stone-500"}`} />
                  <span className="flex-1 truncate">{r.name}</span>
                  {needsReview && (
                    <span className="rounded bg-rose-500/25 px-1 text-[10px] font-bold text-rose-200" title="مرساة تحتاج مراجعة (بواقي عالية)">
                      مراجعة
                    </span>
                  )}
                  {drift && (
                    <span className="rounded bg-rose-500/20 px-1 text-[10px] text-rose-300" title={`فرق ${diff!.toFixed(0)} px`}>
                      Δ {diff!.toFixed(0)}
                    </span>
                  )}
                  {diff != null && !drift && (
                    <span className="rounded bg-emerald-500/15 px-1 text-[10px] text-emerald-300">≤8</span>
                  )}
                </button>
              </li>
            );
          })}
        </ul>

        {selected && (
          <div className="border-t border-stone-800 p-3 text-[12px]">
            <p className="font-bold">{selected.name}</p>
            <p className="text-stone-400">{selected.region}</p>
            <p className="mt-1 text-stone-300">
              lon/lat: {selected.lon}, {selected.lat}
            </p>
            <p className="font-mono text-amber-300">
              APS: {Math.round(selected.aps.x)}, {Math.round(selected.aps.y)}
            </p>
            {selected.notes && <p className="mt-1 text-[11px] text-stone-400">{selected.notes}</p>}
            {NEEDS_REVIEW.has(selected.id) && (
              <p className="mt-2 rounded border border-rose-500/40 bg-rose-500/10 px-2 py-1 text-[11px] text-rose-200">
                ⚠️ هذه المرساة سببت بواقي عالية في التحقق. أعد قياسها بعناية على
                الموقع الجغرافي الفعلي (ليس على نص الاسم) ثم أكدها مجدداً.
              </p>
            )}
            <div className="mt-2 flex gap-2">
              {selected.verified ? (
                <button onClick={unconfirmSelected} className="flex-1 rounded bg-stone-700 px-2 py-1.5 text-[12px] hover:bg-stone-600">
                  إلغاء التأكيد
                </button>
              ) : (
                <button onClick={confirmSelected} className="flex-1 inline-flex items-center justify-center gap-1 rounded bg-emerald-600 px-2 py-1.5 text-[12px] font-bold hover:bg-emerald-500">
                  <ShieldCheck className="size-4" /> تأكيد
                </button>
              )}
            </div>
          </div>
        )}
      </aside>

      {/* Viewer */}
      <div
        ref={wrapRef}
        className="relative flex-1 overflow-hidden bg-stone-900"
        style={{ touchAction: "none", cursor: pan.current ? "grabbing" : "default" }}
        onPointerDown={onWrapPointerDown}
        onPointerMove={(e) => { onWrapPointerMove(e); onPinPointerMove(e); }}
        onPointerUp={(e) => { onWrapPointerUp(); onPinPointerUp(); }}
      >
        <div
          data-role="stage"
          style={{
            position: "absolute",
            left: 0, top: 0,
            transform: `translate(${tx}px, ${ty}px) scale(${scale})`,
            transformOrigin: "0 0",
            width: RASTER.width,
            height: RASTER.height,
            cursor: "crosshair",
          }}
        >
          <img
            data-role="stage"
            src={atlasMaster.url}
            width={RASTER.width}
            height={RASTER.height}
            draggable={false}
            alt="Atlas v1 master"
            style={{ display: "block", userSelect: "none", pointerEvents: "auto" }}
          />
          {/* Sister-pair connectors — visually flag pairs that should sit close. */}
          <svg
            width={RASTER.width}
            height={RASTER.height}
            style={{ position: "absolute", inset: 0, pointerEvents: "none" }}
          >
            {SISTER_PAIRS.map(([aId, bId]) => {
              const a = rows.find((r) => r.id === aId);
              const b = rows.find((r) => r.id === bId);
              if (!a || !b) return null;
              const dist = Math.hypot(a.aps.x - b.aps.x, a.aps.y - b.aps.y);
              // ~13 km between Samarkand/Bukhara → expect ≲ 250 px at v1 scale.
              const tooFar = dist > 350;
              return (
                <g key={`${aId}-${bId}`}>
                  <line
                    x1={a.aps.x} y1={a.aps.y} x2={b.aps.x} y2={b.aps.y}
                    stroke={tooFar ? "rgba(244,63,94,0.85)" : "rgba(16,185,129,0.7)"}
                    strokeWidth={Math.max(2, 4 / scale)}
                    strokeDasharray={`${12 / scale} ${8 / scale}`}
                  />
                  <text
                    x={(a.aps.x + b.aps.x) / 2}
                    y={(a.aps.y + b.aps.y) / 2 - 8 / scale}
                    fontSize={14 / scale}
                    fontWeight={700}
                    fill={tooFar ? "#fecdd3" : "#a7f3d0"}
                    textAnchor="middle"
                    style={{ paintOrder: "stroke", stroke: "rgba(0,0,0,0.7)", strokeWidth: 3 / scale }}
                  >
                    {Math.round(dist)} px {tooFar ? "⚠️ بعيد جداً" : ""}
                  </text>
                </g>
              );
            })}
          </svg>
          {/* Pins */}
          {rows.map((r) => {
            const active = r.id === selectedId;
            const reviewerHit = reviewerB?.find((x) => x.id === r.id);
            return (
              <div key={r.id} style={{ position: "absolute", left: r.aps.x, top: r.aps.y }}>
                {/* Reviewer-B ghost pin */}
                {reviewerHit && (
                  <div
                    style={{
                      position: "absolute",
                      left: (reviewerHit.aps.x - r.aps.x),
                      top: (reviewerHit.aps.y - r.aps.y),
                      width: 0, height: 0,
                      pointerEvents: "none",
                    }}
                  >
                    <div
                      style={{
                        position: "absolute",
                        transform: `translate(-50%, -50%) scale(${1 / scale})`,
                        width: 14, height: 14,
                        border: "2px dashed rgba(244,114,182,0.9)",
                        borderRadius: "50%",
                      }}
                    />
                  </div>
                )}
                <div
                  onPointerDown={(e) => onPinPointerDown(e, r.id)}
                  title={r.name}
                  style={{
                    position: "absolute",
                    transform: `translate(-50%, -50%) scale(${1 / scale})`,
                    cursor: "grab",
                    pointerEvents: "auto",
                  }}
                >
                  {NEEDS_REVIEW.has(r.id) && (
                    <div
                      style={{
                        position: "absolute",
                        top: "50%", left: "50%",
                        transform: "translate(-50%, -50%)",
                        width: 32, height: 32,
                        borderRadius: "50%",
                        border: "2px dashed rgba(244,63,94,0.95)",
                        boxShadow: "0 0 0 2px rgba(244,63,94,0.2)",
                        pointerEvents: "none",
                      }}
                    />
                  )}
                  <div
                    style={{
                      width: active ? 20 : 14,
                      height: active ? 20 : 14,
                      borderRadius: "50%",
                      background: r.verified ? "rgba(16,185,129,0.95)" : "rgba(251,191,36,0.95)",
                      border: active ? "2px solid #fff" : "2px solid rgba(0,0,0,0.6)",
                      boxShadow: "0 1px 3px rgba(0,0,0,0.6)",
                    }}
                  />
                  <div
                    style={{
                      position: "absolute",
                      top: 12, left: 14,
                      whiteSpace: "nowrap",
                      fontSize: 11,
                      fontWeight: 700,
                      color: "#fef3c7",
                      background: "rgba(0,0,0,0.55)",
                      padding: "1px 4px",
                      borderRadius: 3,
                      pointerEvents: "none",
                    }}
                  >
                    {r.name}
                  </div>
                </div>
              </div>
            );
          })}
        </div>

        {/* HUD */}
        <div className="pointer-events-none absolute bottom-2 left-2 flex items-center gap-2 rounded bg-stone-950/80 px-2 py-1 font-mono text-[11px] text-amber-200">
          <Crosshair className="size-3.5" />
          {cursorAps
            ? <>APS {Math.round(cursorAps.x)}, {Math.round(cursorAps.y)} · {(scale * 100).toFixed(0)}%</>
            : <>خارج الأطلس · {(scale * 100).toFixed(0)}%</>}
        </div>
      </div>

      {/* Export modal */}
      {showExport && (
        <div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4" onClick={() => setShowExport(false)}>
          <div className="flex max-h-[80vh] w-full max-w-3xl flex-col rounded-xl border border-stone-700 bg-stone-900 p-4" onClick={(e) => e.stopPropagation()}>
            <header className="mb-2 flex items-center justify-between">
              <h2 className="font-bold">تصدير ATLAS_ANCHORS_V1</h2>
              <div className="flex gap-2">
                <button
                  onClick={() => navigator.clipboard.writeText(formatExport(rows))}
                  className="rounded bg-emerald-600 px-3 py-1 text-[12px] font-bold hover:bg-emerald-500"
                >نسخ</button>
                <button
                  onClick={() => {
                    const blob = new Blob([formatExport(rows)], { type: "text/plain" });
                    const url = URL.createObjectURL(blob);
                    const a = document.createElement("a");
                    a.href = url; a.download = "atlas-anchors-v1.measured.ts"; a.click();
                    URL.revokeObjectURL(url);
                  }}
                  className="rounded bg-stone-700 px-3 py-1 text-[12px] hover:bg-stone-600"
                >تنزيل</button>
                <button onClick={() => setShowExport(false)} className="rounded p-1 hover:bg-stone-800"><X className="size-4" /></button>
              </div>
            </header>
            <p className="mb-2 text-[11px] text-stone-400">
              الصق هذا في <code>src/data/atlas-anchors.ts</code> مكان مصفوفة <code>SEEDS</code>.
              {verifiedCount < rows.length && (
                <span className="text-amber-400"> · لم تؤكد بعد {rows.length - verifiedCount} مرساة.</span>
              )}
            </p>
            <textarea
              readOnly
              value={formatExport(rows)}
              className="flex-1 overflow-auto rounded bg-stone-950 p-3 font-mono text-[11px] text-stone-200"
            />
          </div>
        </div>
      )}
    </div>
  );
}

function ToolBtn({ onClick, icon: Icon, label }: { onClick: () => void; icon: React.ComponentType<{ className?: string }>; label: string }) {
  return (
    <button
      onClick={onClick}
      className="inline-flex items-center gap-1 rounded border border-stone-700 bg-stone-800 px-2 py-1 hover:bg-stone-700"
    >
      <Icon className="size-3.5" /> {label}
    </button>
  );
}
