import type { ContentPack, PackEntity } from "./types";

// ============================================================
// Content Pack 003 — الدولة العباسية (The Abbasid State)
// ------------------------------------------------------------
// Same architecture as Packs 001 (Ayyubid) and 002 (Umayyad).
// Pure data — no UI or engine changes required.
// ============================================================

const E = (e: PackEntity): PackEntity => e;

const FIGURE_IDS = [
  ["as-saffah","أبو العباس السفّاح","Abu al-Abbas as-Saffah",750,754,
    "مؤسّس الدولة العباسية وأوّل خلفائها، أعلن الخلافة في الكوفة بعد سقوط بني أمية.",
    ["abbasid.event.found-abbasid","abbasid.event.fall-umayyad","abbasid.city.kufa","abbasid.battle.zab"]],
  ["al-mansur","أبو جعفر المنصور","Al-Mansur",754,775,
    "ثاني خلفاء بني العباس، باني بغداد المدوّرة ومُرسي أسس الدولة الإدارية والعسكرية.",
    ["abbasid.city.baghdad","abbasid.event.build-baghdad","abbasid.landmark.round-city","abbasid.landmark.mansur-mosque","abbasid.figure.abu-muslim"]],
  ["al-mahdi","المهدي","Al-Mahdi",775,785,
    "الخليفة الثالث الذي وسّع الإدارة ونظّم البريد وحمى الحدود من البيزنطيين.",
    ["abbasid.city.baghdad","abbasid.event.byzantine-wars"]],
  ["harun-al-rashid","هارون الرشيد","Harun al-Rashid",786,809,
    "خليفة العصر الذهبي، ازدهرت في عهده العلوم والفنون وبيت الحكمة، وراسل شارلمان.",
    ["abbasid.event.golden-age","abbasid.event.house-of-wisdom","abbasid.event.byzantine-wars","abbasid.battle.amorium","abbasid.city.baghdad"]],
  ["al-amin","الأمين","Al-Amin",809,813,
    "ابن هارون الرشيد، خاض حرب الخلافة الكبرى مع أخيه المأمون فانهزم وقُتل في بغداد.",
    ["abbasid.event.amin-mamun-war","abbasid.city.baghdad"]],
  ["al-mamun","المأمون","Al-Ma'mun",813,833,
    "خليفة العلم والفلسفة، رعى حركة الترجمة وبيت الحكمة، وأثار فتنة خلق القرآن.",
    ["abbasid.event.house-of-wisdom","abbasid.event.translation-movement","abbasid.event.mihna","abbasid.figure.al-khwarizmi","abbasid.landmark.house-of-wisdom"]],
  ["al-mutasim","المعتصم بالله","Al-Mu'tasim",833,842,
    "أخو المأمون، أسّس سامراء واستعان بالأتراك، وقاد فتح عمورية ردًّا على نداء امرأة.",
    ["abbasid.city.samarra","abbasid.event.found-samarra","abbasid.battle.amorium","abbasid.event.byzantine-wars"]],
  ["al-wathiq","الواثق","Al-Wathiq",842,847,
    "خليفةٌ عبّاسي امتدّ في عهده نفوذ القوّاد الأتراك واستمرّت محنة خلق القرآن.",
    ["abbasid.city.samarra","abbasid.event.mihna"]],
  ["al-mutawakkil","المتوكل على الله","Al-Mutawakkil",847,861,
    "أنهى محنة خلق القرآن وأعاد للسنّة هيبتها، وشيّد جامع سامراء والملوية.",
    ["abbasid.landmark.malwiya","abbasid.landmark.samarra-mosque","abbasid.city.samarra","abbasid.event.mihna"]],
  ["al-mustansir","المستنصر بالله","Al-Mustansir",1226,1242,
    "خليفةٌ عبّاسي متأخّر، شيّد المدرسة المستنصرية ببغداد، أحد أعرق مراكز العلم في العالم الإسلامي.",
    ["abbasid.landmark.mustansiriyah","abbasid.city.baghdad"]],
  ["al-mustasim","المستعصم بالله","Al-Musta'sim",1242,1258,
    "آخر خلفاء بني العباس في بغداد، سقطت في عهده العاصمة على يد المغول سنة 1258م.",
    ["abbasid.figure.hulagu","abbasid.battle.siege-baghdad","abbasid.event.fall-baghdad"]],
  ["abu-muslim","أبو مسلم الخراساني","Abu Muslim al-Khurasani",747,755,
    "قائد الدعوة العباسية في خراسان، صانع الثورة التي قلبت بني أمية، قتله المنصور لاحقًا.",
    ["abbasid.event.abbasid-revolution","abbasid.event.found-abbasid","abbasid.figure.al-mansur"]],
  ["nizam-al-mulk","نظام الملك","Nizam al-Mulk",1064,1092,
    "وزير السلاجقة العظيم، مؤسّس المدارس النظامية ومنظّم الإدارة في زمن الخلافة العباسية المتأخرة.",
    ["abbasid.landmark.nizamiyya","abbasid.event.seljuk-rise","abbasid.city.baghdad"]],
  ["salahuddin","صلاح الدين الأيوبي","Salah al-Din al-Ayyubi",1171,1193,
    "مؤسّس الدولة الأيوبية، حمى الخلافة العباسية اسميًا وأعاد القدس بعد حطين سنة 1187م.",
    ["abbasid.state.abbasid","abbasid.city.baghdad"]],
  ["hulagu","هولاكو خان","Hulagu Khan",1256,1265,
    "قائد المغول الذي اجتاح بلاد الإسلام وأسقط بغداد سنة 1258م، فأنهى الخلافة العباسية.",
    ["abbasid.battle.siege-baghdad","abbasid.event.mongol-invasion","abbasid.event.fall-baghdad","abbasid.figure.al-mustasim"]],
] as const;

const SCHOLAR_IDS = [
  ["abu-hanifa","الإمام أبو حنيفة النعمان","Abu Hanifa",699,767,
    "إمام المذهب الحنفي، أحد أعلام الفقه الإسلامي في الكوفة في فجر الدولة العباسية.",
    ["abbasid.city.kufa","abbasid.event.golden-age"]],
  ["al-shafii","الإمام الشافعي","Al-Shafi'i",767,820,
    "مؤسّس علم أصول الفقه وإمام المذهب الشافعي، صاحب الرسالة والأم.",
    ["abbasid.city.baghdad","abbasid.city.makkah","abbasid.artifact.manuscript-shafii"]],
  ["ahmad-ibn-hanbal","الإمام أحمد بن حنبل","Ahmad ibn Hanbal",780,855,
    "إمام أهل السنة، صبر في محنة خلق القرآن ولم يقل بخلقه، فأنقذ السنّة من فتنةٍ كبرى.",
    ["abbasid.event.mihna","abbasid.city.baghdad"]],
  ["al-bukhari","الإمام البخاري","Al-Bukhari",810,870,
    "أمير المؤمنين في الحديث، جامع أصحّ كتب الحديث على الإطلاق: صحيح البخاري.",
    ["abbasid.artifact.manuscript-bukhari","abbasid.city.bukhara"]],
  ["muslim","الإمام مسلم بن الحجاج","Imam Muslim",817,875,
    "صاحب صحيح مسلم، ثاني أصحّ كتب الحديث بعد صحيح البخاري.",
    ["abbasid.city.nishapur","abbasid.artifact.manuscript-bukhari"]],
  ["al-tabari","الإمام الطبري","Al-Tabari",839,923,
    "إمام المفسّرين والمؤرّخين، صاحب جامع البيان وتاريخ الأمم والملوك.",
    ["abbasid.city.baghdad","abbasid.event.golden-age"]],
  ["al-khwarizmi","الخوارزمي","Al-Khwarizmi",780,850,
    "أبو علم الجبر والخوارزميات، عمل في بيت الحكمة في زمن المأمون.",
    ["abbasid.landmark.house-of-wisdom","abbasid.artifact.manuscript-khwarizmi","abbasid.figure.al-mamun"]],
  ["ibn-al-haytham","ابن الهيثم","Ibn al-Haytham",965,1040,
    "أبو علم البصريات الحديث، صاحب كتاب المناظر، أحد عمالقة العصر الذهبي.",
    ["abbasid.event.golden-age","abbasid.artifact.astrolabe"]],
  ["al-razi","أبو بكر الرازي","Al-Razi",854,925,
    "طبيبٌ وكيميائي فذّ، صاحب الحاوي في الطب، أوّل من فرّق بين الجدري والحصبة.",
    ["abbasid.event.golden-age","abbasid.city.baghdad"]],
  ["al-biruni","البيروني","Al-Biruni",973,1048,
    "عالم موسوعي في الفلك والرياضيات والتاريخ والجغرافيا، صاحب تحقيق ما للهند.",
    ["abbasid.event.golden-age","abbasid.artifact.observatory"]],
  ["al-jahiz","الجاحظ","Al-Jahiz",776,868,
    "أديب العربية وصاحب البيان والتبيين والحيوان، ركن من أركان النثر العباسي.",
    ["abbasid.city.basra","abbasid.city.baghdad","abbasid.event.golden-age"]],
  ["ibn-sina","ابن سينا","Ibn Sina (Avicenna)",980,1037,
    "الشيخ الرئيس، صاحب القانون في الطب والشفاء، أعظم أطباء العصور الوسطى.",
    ["abbasid.event.golden-age","abbasid.city.bukhara"]],
] as const;

const CITY_IDS = [
  ["baghdad","بغداد","Baghdad","عاصمة الدولة العباسية، مدينة السلام التي أسّسها المنصور سنة 762م، فصارت قلب الحضارة الإسلامية.",
    762,1258,["abbasid.figure.al-mansur","abbasid.event.build-baghdad","abbasid.landmark.round-city","abbasid.landmark.house-of-wisdom"]],
  ["samarra","سامراء","Samarra","عاصمة المعتصم وخلفائه، مدينة الجند الأتراك ومنبر الملوية الشهير.",
    836,892,["abbasid.figure.al-mutasim","abbasid.event.found-samarra","abbasid.landmark.malwiya","abbasid.landmark.samarra-mosque"]],
  ["kufa","الكوفة","Kufa","مهد إعلان الخلافة العباسية وقاعدة الفقه العراقي.",
    750,1258,["abbasid.figure.as-saffah","abbasid.event.found-abbasid","abbasid.figure.abu-hanifa"]],
  ["basra","البصرة","Basra","ميناء العراق وعاصمة الأدب واللغة في العصر العباسي.",
    750,1258,["abbasid.figure.al-jahiz","abbasid.event.golden-age"]],
  ["makkah","مكة","Mecca","الحرم المكي، قبلة المسلمين وموسم الحج طوال العصر العباسي.",
    750,1258,["abbasid.figure.al-shafii"]],
  ["madina","المدينة","Medina","مدينة النبي ﷺ، مركز الفقه والحديث في القرون العباسية.",
    750,1258,["abbasid.event.golden-age"]],
  ["damascus","دمشق","Damascus","عاصمة الأمويين السابقة، مدينة شامية رئيسية في العصر العباسي.",
    750,1258,["abbasid.state.abbasid"]],
  ["cairo","القاهرة","Cairo","عاصمة مصر الإسلامية، نمت في ظل الفاطميين والأيوبيين ضمن العالم العباسي الواسع.",
    969,1258,["abbasid.figure.salahuddin"]],
  ["nishapur","نيسابور","Nishapur","قاعدة خراسان الكبرى، حاضرة العلم وموطن كثير من المحدّثين والفلاسفة.",
    750,1258,["abbasid.figure.muslim","abbasid.event.seljuk-rise"]],
  ["bukhara","بخارى","Bukhara","حاضرة ما وراء النهر، قبّة العلم في المشرق، موطن البخاري وابن سينا.",
    750,1258,["abbasid.figure.al-bukhari","abbasid.figure.ibn-sina"]],
  ["samarqand","سمرقند","Samarkand","لؤلؤة ما وراء النهر، مركزٌ تجاريٌّ وعلميٌّ في العصر العباسي.",
    750,1258,["abbasid.battle.talas","abbasid.event.golden-age"]],
  ["mosul","الموصل","Mosul","حاضرة الجزيرة الفراتية ومركز إماراتها المتعاقبة تحت ظل العباسيين.",
    750,1258,["abbasid.state.abbasid"]],
] as const;

const BATTLE_IDS = [
  ["zab","معركة الزاب الكبرى","Battle of the Zab",750,750,
    "المعركة الفاصلة سنة 750م التي سحق فيها العباسيون جيش مروان بن محمد، فانتهت دولة بني أمية وقامت دولة بني العباس.",
    ["abbasid.figure.as-saffah","abbasid.figure.abu-muslim","abbasid.event.fall-umayyad","abbasid.event.found-abbasid"]],
  ["amorium","فتح عمورية","Sack of Amorium",838,838,
    "حملة المعتصم على عمورية البيزنطية ردًّا على نداء امرأة هاشمية، من أعظم انتصارات الدولة على الروم.",
    ["abbasid.figure.al-mutasim","abbasid.event.byzantine-wars"]],
  ["talas","معركة نهر طلاس","Battle of Talas",751,751,
    "معركةٌ بين المسلمين بقيادة زياد بن صالح وجيش أسرة تانغ الصينية، حسمت نفوذ الإسلام في آسيا الوسطى ونقلت صناعة الورق إلى العالم الإسلامي.",
    ["abbasid.city.samarqand","abbasid.event.golden-age"]],
  ["siege-baghdad","حصار بغداد","Siege of Baghdad",1258,1258,
    "حصار المغول بقيادة هولاكو لبغداد سنة 1258م، انتهى بسقوط المدينة وقتل الخليفة المستعصم وانهيار الخلافة.",
    ["abbasid.figure.hulagu","abbasid.figure.al-mustasim","abbasid.event.fall-baghdad","abbasid.event.mongol-invasion"]],
  ["ankara","معركة أنقرة","Battle of Ankara",838,838,
    "اشتباكٌ بين جيش المعتصم وقوات البيزنطيين قبيل عمورية، مهّد للنصر الكبير.",
    ["abbasid.figure.al-mutasim","abbasid.event.byzantine-wars"]],
  ["byzantine-campaigns","حملات الروم العباسية","Abbasid-Byzantine Campaigns",780,900,
    "سلسلة الغزوات الصيفية والشتوية المتبادلة بين الخلافة العباسية والإمبراطورية البيزنطية.",
    ["abbasid.figure.al-mahdi","abbasid.figure.harun-al-rashid","abbasid.figure.al-mutasim","abbasid.event.byzantine-wars"]],
  ["dijla","معركة دجلة","Battle of the Tigris",1258,1258,
    "اشتباكاتٌ على ضفاف دجلة قبيل سقوط بغداد، انكسر فيها جيش الخليفة أمام جحافل المغول.",
    ["abbasid.figure.hulagu","abbasid.event.fall-baghdad"]],
  ["rayy","معركة الري","Battle of Rayy",811,811,
    "معركةٌ فاصلة في حرب الأمين والمأمون، انتصر فيها طاهر بن الحسين لصالح المأمون.",
    ["abbasid.figure.al-amin","abbasid.figure.al-mamun","abbasid.event.amin-mamun-war"]],
] as const;

const EVENT_IDS = [
  ["abbasid-revolution","قيام الدولة العباسية","Abbasid Revolution",747,750,
    "حركة الدعوة العباسية في خراسان بقيادة أبي مسلم الخراساني التي أسقطت بني أمية وأقامت الخلافة العباسية.",
    ["abbasid.figure.abu-muslim","abbasid.figure.as-saffah","abbasid.battle.zab","abbasid.event.found-abbasid"]],
  ["fall-umayyad","سقوط الدولة الأموية","Fall of the Umayyad State",750,750,
    "نهاية بني أمية في المشرق بعد معركة الزاب وفرار آخر خلفائهم.",
    ["abbasid.battle.zab","abbasid.figure.as-saffah"]],
  ["found-abbasid","تأسيس الدولة العباسية","Founding of the Abbasid State",750,750,
    "إعلان أبي العباس السفّاح الخلافة العباسية في الكوفة بعد سقوط بني أمية.",
    ["abbasid.figure.as-saffah","abbasid.city.kufa","abbasid.state.abbasid"]],
  ["build-baghdad","بناء بغداد","Construction of Baghdad",762,766,
    "بناء المنصور لمدينة السلام المدوّرة على ضفاف دجلة لتكون عاصمة الخلافة الجديدة.",
    ["abbasid.figure.al-mansur","abbasid.city.baghdad","abbasid.landmark.round-city"]],
  ["golden-age","العصر الذهبي الإسلامي","Islamic Golden Age",786,1100,
    "قرونٌ ازدهرت فيها العلوم والفلسفة والطب والفلك في العالم الإسلامي، تمحورت حول بغداد.",
    ["abbasid.figure.harun-al-rashid","abbasid.figure.al-mamun","abbasid.event.house-of-wisdom","abbasid.event.translation-movement"]],
  ["house-of-wisdom","بيت الحكمة","House of Wisdom",786,833,
    "أعظم مؤسّسة علمية في العصر العباسي ببغداد، أوجها في عهد هارون الرشيد والمأمون.",
    ["abbasid.landmark.house-of-wisdom","abbasid.figure.harun-al-rashid","abbasid.figure.al-mamun","abbasid.figure.al-khwarizmi"]],
  ["translation-movement","حركة الترجمة","The Translation Movement",750,900,
    "حركة ضخمة لنقل علوم اليونان والفرس والهند إلى العربية، نواة العصر الذهبي.",
    ["abbasid.landmark.house-of-wisdom","abbasid.figure.al-mamun"]],
  ["mihna","فتنة خلق القرآن","The Mihna",833,851,
    "محنةٌ فرضها المأمون ثم المعتصم والواثق على العلماء بالقول بخلق القرآن، صبر فيها أحمد بن حنبل حتى رفعها المتوكل.",
    ["abbasid.figure.al-mamun","abbasid.figure.al-mutasim","abbasid.figure.ahmad-ibn-hanbal","abbasid.figure.al-mutawakkil"]],
  ["found-samarra","تأسيس سامراء","Founding of Samarra",836,836,
    "اختيار المعتصم لسامراء عاصمةً جديدة بعد توترات الجند الأتراك مع أهل بغداد.",
    ["abbasid.figure.al-mutasim","abbasid.city.samarra"]],
  ["sciences-bloom","ازدهار العلوم","Blossoming of the Sciences",800,1100,
    "نهضة الرياضيات والفلك والطب والكيمياء على يد الخوارزمي والرازي وابن سينا والبيروني.",
    ["abbasid.figure.al-khwarizmi","abbasid.figure.al-razi","abbasid.figure.ibn-sina","abbasid.figure.al-biruni","abbasid.figure.ibn-al-haytham"]],
  ["byzantine-wars","الحروب مع البيزنطيين","Wars with the Byzantines",780,900,
    "صراعٌ طويل على حدود الأناضول، شهد فتح عمورية ومعارك أنقرة والثغور.",
    ["abbasid.battle.amorium","abbasid.battle.ankara","abbasid.battle.byzantine-campaigns","abbasid.figure.harun-al-rashid","abbasid.figure.al-mutasim"]],
  ["caliphate-weakening","ضعف الخلافة","Weakening of the Caliphate",900,1050,
    "تفكّك سلطة الخلفاء وصعود الأمراء والولاة المستقلين في الأطراف.",
    ["abbasid.event.buyid-rise","abbasid.event.seljuk-rise"]],
  ["buyid-rise","ظهور البويهيين","Rise of the Buyids",932,1055,
    "سيطرة البويهيين الشيعة على بغداد وتحويل الخلفاء العباسيين إلى رمز روحي.",
    ["abbasid.city.baghdad","abbasid.event.caliphate-weakening"]],
  ["seljuk-rise","ظهور السلاجقة","Rise of the Seljuks",1037,1194,
    "صعود السلاجقة الأتراك وإعادتهم هيبة الخلافة السنّية في وجه البويهيين والفاطميين.",
    ["abbasid.figure.nizam-al-mulk","abbasid.landmark.nizamiyya","abbasid.city.nishapur"]],
  ["mongol-invasion","اجتياح المغول","The Mongol Invasion",1219,1258,
    "زحف المغول من الشرق الذي اكتسح خراسان وفارس وانتهى بسقوط بغداد.",
    ["abbasid.figure.hulagu","abbasid.event.fall-baghdad","abbasid.battle.siege-baghdad"]],
  ["fall-baghdad","سقوط بغداد","Fall of Baghdad",1258,1258,
    "اجتياح المغول لبغداد ومقتل الخليفة المستعصم وانتهاء الخلافة العباسية في المشرق.",
    ["abbasid.figure.hulagu","abbasid.figure.al-mustasim","abbasid.battle.siege-baghdad","abbasid.event.mongol-invasion"]],
  ["amin-mamun-war","حرب الأمين والمأمون","Fourth Fitna (Amin–Ma'mun War)",811,813,
    "حرب الخلافة بين أبناء هارون الرشيد، انتهت بقتل الأمين وتولّي المأمون.",
    ["abbasid.figure.al-amin","abbasid.figure.al-mamun","abbasid.battle.rayy"]],
] as const;

const LANDMARK_IDS = [
  ["house-of-wisdom","بيت الحكمة","House of Wisdom","أعظم مكتبة ومركز ترجمة في تاريخ الإسلام، في قلب بغداد العباسية.",
    786,1258,["abbasid.event.house-of-wisdom","abbasid.event.translation-movement","abbasid.figure.al-mamun","abbasid.figure.al-khwarizmi"]],
  ["round-city","مدينة بغداد المدوّرة","Round City of Baghdad","تصميم المنصور الفريد لعاصمته على شكل دائرة كاملة بأربعة أبواب.",
    762,766,["abbasid.figure.al-mansur","abbasid.city.baghdad","abbasid.event.build-baghdad"]],
  ["mansur-mosque","جامع المنصور","Mosque of al-Mansur","الجامع الجامع في قلب بغداد المدوّرة، أوّل جوامع العاصمة العباسية.",
    766,1258,["abbasid.figure.al-mansur","abbasid.city.baghdad"]],
  ["samarra-city","مدينة سامراء","City of Samarra","العاصمة الجديدة التي أنشأها المعتصم لجنده الأتراك على ضفاف دجلة.",
    836,892,["abbasid.figure.al-mutasim","abbasid.event.found-samarra","abbasid.city.samarra"]],
  ["malwiya","الملوية","Malwiya Minaret","مئذنة جامع سامراء الكبير الحلزونية، أيقونة العمارة العباسية.",
    848,852,["abbasid.figure.al-mutawakkil","abbasid.landmark.samarra-mosque","abbasid.city.samarra"]],
  ["samarra-mosque","جامع سامراء الكبير","Great Mosque of Samarra","جامع المتوكّل العظيم في سامراء، صاحب المئذنة الملوية.",
    848,852,["abbasid.figure.al-mutawakkil","abbasid.landmark.malwiya","abbasid.city.samarra"]],
  ["nizamiyya","المدرسة النظامية","Nizamiyya Madrasa","شبكة المدارس التي أسّسها نظام الملك في بغداد ونيسابور وغيرها لنشر علوم السنّة.",
    1065,1258,["abbasid.figure.nizam-al-mulk","abbasid.city.baghdad","abbasid.event.seljuk-rise"]],
  ["mustansiriyah","المدرسة المستنصرية","Mustansiriya Madrasa","مدرسةٌ شاملة شيّدها المستنصر ببغداد، تجمع المذاهب الأربعة في صرحٍ واحد.",
    1227,1258,["abbasid.figure.al-mustansir","abbasid.city.baghdad"]],
  ["caliphal-palace","قصر الخلافة","Caliphal Palace","قصرٌ ضخم على ضفاف دجلة، مقرّ الخلافة العباسية ومركز الإدارة.",
    762,1258,["abbasid.city.baghdad","abbasid.figure.al-mansur"]],
  ["baghdad-libraries","مكتبات بغداد","Libraries of Baghdad","شبكةٌ هائلة من المكتبات الخاصة والعامة جعلت بغداد عاصمة الكتاب.",
    800,1258,["abbasid.event.golden-age","abbasid.event.translation-movement","abbasid.landmark.house-of-wisdom"]],
] as const;

const ARTIFACT_IDS = [
  ["manuscript-house-of-wisdom","مخطوط بيت الحكمة","Manuscript from the House of Wisdom",
    "مخطوطةٌ علميّة من مخطوطات بيت الحكمة، نتاج حركة الترجمة العباسية.",
    830,1258,"📜","legendary",["abbasid.landmark.house-of-wisdom","abbasid.event.translation-movement"]],
  ["astrolabe","أسطرلاب عباسي","Abbasid Astrolabe",
    "أداة فلكيّة دقيقة طوّرها علماء العباسيين لقياس مواقع النجوم وأوقات الصلاة.",
    830,1258,"🧭","epic",["abbasid.figure.al-khwarizmi","abbasid.event.sciences-bloom","abbasid.figure.ibn-al-haytham"]],
  ["dinar-abbasid","الدينار العباسي","Abbasid Gold Dinar",
    "عملةٌ ذهبيّة عباسيّة تحمل اسم الخليفة وآياتٍ قرآنية، رمزٌ لاقتصاد الدولة.",
    750,1258,"💰","epic",["abbasid.state.abbasid","abbasid.city.baghdad"]],
  ["caliphal-seal","ختم الخليفة العباسي","Seal of the Abbasid Caliph",
    "ختمٌ خليفيٌّ يُختم به المراسيم الرسمية للدولة العباسية.",
    750,1258,"🪧","epic",["abbasid.state.abbasid","abbasid.landmark.caliphal-palace"]],
  ["idrisi-map","خريطة الإدريسي","Tabula Rogeriana – Idrisi Map",
    "أعظم خرائط العصور الوسطى، رسمها الشريف الإدريسي لروجر الثاني، مرجعٌ جغرافي لقرون.",
    1154,1258,"🗺️","legendary",["abbasid.event.golden-age"]],
  ["manuscript-bukhari","مخطوط صحيح البخاري","Manuscript of Sahih al-Bukhari",
    "نسخةٌ خطّيّة من صحيح البخاري، أصحّ كتب الحديث، نتاج عصر التدوين العباسي.",
    846,1258,"📖","legendary",["abbasid.figure.al-bukhari"]],
  ["manuscript-shafii","مخطوط الرسالة للشافعي","Manuscript of al-Risala (al-Shafi'i)",
    "مخطوطةٌ نادرة من الرسالة، أوّل مؤلَّف في أصول الفقه.",
    820,1258,"📜","epic",["abbasid.figure.al-shafii"]],
  ["manuscript-khwarizmi","مخطوط الجبر للخوارزمي","Manuscript of al-Jabr by al-Khwarizmi",
    "مخطوطة كتاب الجبر والمقابلة، الأصل الذي اشتُقّ منه علم الجبر الحديث.",
    830,1258,"📐","legendary",["abbasid.figure.al-khwarizmi","abbasid.landmark.house-of-wisdom"]],
  ["banner-abbasid","راية الدولة العباسية","Abbasid Black Banner",
    "الراية السوداء، شارة الخلافة العباسية منذ ظهور دعوتها في خراسان.",
    750,1258,"🏴","rare",["abbasid.state.abbasid","abbasid.figure.abu-muslim"]],
  ["observatory","مرصد فلكي عباسي","Abbasid Astronomical Observatory",
    "مرصدٌ شيّده العباسيون في زمن المأمون لرصد النجوم وحساب درجة الأرض.",
    828,1258,"🔭","epic",["abbasid.figure.al-mamun","abbasid.figure.al-biruni","abbasid.event.sciences-bloom"]],
] as const;

const ACHIEVEMENT_IDS = [
  ["abbasid-historian","مؤرخ الدولة العباسية","Historian of the Abbasid State",
    "يُمنح لمن قرأ جميع شخصيات وأحداث الدولة العباسية في المتحف.",
    ["abbasid.state.abbasid"]],
  ["master-of-baghdad","سيد بغداد","Master of Baghdad",
    "لقبٌ شرفيّ يُمنح لمن أتمّ مسار بغداد ومدينتها المدوّرة وبيت حكمتها.",
    ["abbasid.city.baghdad","abbasid.landmark.round-city","abbasid.landmark.house-of-wisdom"]],
  ["abbasid-collector","جامع التراث العباسي","Collector of Abbasid Heritage",
    "يُمنح لمن جمع كلّ الآثار والمخطوطات العباسية في مجموعته.",
    ["abbasid.artifact.dinar-abbasid","abbasid.artifact.banner-abbasid","abbasid.artifact.manuscript-bukhari","abbasid.artifact.manuscript-khwarizmi"]],
  ["wisdom-scholar","عالم بيت الحكمة","Scholar of the House of Wisdom",
    "يُمنح لمن أتقن كل اختبارات حركة الترجمة وعلماء بيت الحكمة.",
    ["abbasid.landmark.house-of-wisdom","abbasid.figure.al-khwarizmi","abbasid.figure.al-mamun"]],
  ["golden-age-expert","خبير العصر الذهبي","Expert of the Golden Age",
    "يُمنح لمن أكمل قصص العلوم والفلسفة والطب في العصر الذهبي.",
    ["abbasid.event.golden-age","abbasid.event.sciences-bloom","abbasid.figure.ibn-sina","abbasid.figure.al-razi","abbasid.figure.al-biruni"]],
] as const;

const FUTURE_CAMPAIGN_IDS = [
  ["future-mansur",      "حملة أبو جعفر المنصور",754,775,"حملةٌ قادمة عن باني بغداد ومُؤسّس النظام الإداري العباسي. (قريبًا)"],
  ["future-harun",       "حملة هارون الرشيد",   786,809,"حملةٌ قادمة عن خليفة العصر الذهبي وعلاقاته بشارلمان. (قريبًا)"],
  ["future-mamun",       "حملة المأمون",        813,833,"حملةٌ قادمة عن المأمون وحركة الترجمة وبيت الحكمة. (قريبًا)"],
  ["future-house-of-wisdom","بيت الحكمة",       786,1100,"حملةٌ قادمة تجوب علماء بيت الحكمة وإنجازاتهم. (قريبًا)"],
  ["future-fall-baghdad","سقوط بغداد",          1256,1258,"حملةٌ قادمة عن اجتياح المغول وسقوط الخلافة. (قريبًا)"],
  ["future-golden-age",  "العصر الذهبي الإسلامي",786,1100,"حملةٌ قادمة تستعرض قرون النهضة العلمية. (قريبًا)"],
] as const;

const entities: PackEntity[] = [
  // ---------- STATE ----------
  E({
    id: "abbasid.state.abbasid",
    title: "الدولة العباسية",
    latin: "Abbasid State",
    type: "state",
    description:
      "ثاني الخلافات الكبرى في الإسلام، أسّسها أبو العباس السفّاح سنة 750م، عاصمتها بغداد. شهدت العصر الذهبي للحضارة الإسلامية وانتهت بسقوط بغداد على يد المغول سنة 1258م.",
    period: { label: "750 – 1258 م", startYear: 750, endYear: 1258 },
    relatedEntities: [
      "abbasid.figure.as-saffah","abbasid.figure.al-mansur","abbasid.figure.harun-al-rashid",
      "abbasid.figure.al-mamun","abbasid.figure.al-mutasim","abbasid.figure.al-mustasim",
      "abbasid.city.baghdad","abbasid.city.samarra","abbasid.city.kufa",
      "abbasid.event.found-abbasid","abbasid.event.golden-age","abbasid.event.house-of-wisdom",
      "abbasid.event.fall-baghdad",
    ],
    unlockables: [
      { kind: "campaign", refId: "abbasid", label: "حملات الدولة العباسية" },
    ],
    image: { alt: "راية الدولة العباسية", glyph: "🏴", tone: "from-stone-700/40 to-slate-900" },
    timelinePosition: 750,
    rarity: "legendary",
    meta: {
      founder: "أبو العباس السفّاح",
      capital: "بغداد",
      majorCities: ["بغداد","سامراء","الكوفة","البصرة","نيسابور","بخارى"],
      majorFigures: ["السفّاح","المنصور","هارون الرشيد","المأمون","المعتصم","المتوكل","المستعصم"],
      majorBattles: ["الزاب","عمورية","طلاس","حصار بغداد"],
      majorEvents: ["تأسيس الدولة","بناء بغداد","العصر الذهبي","بيت الحكمة","سقوط بغداد"],
    },
    bridges: { era: "abbasid" },
  }),

  // ---------- FIGURES (Caliphs & Statesmen) ----------
  ...FIGURE_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `abbasid.figure.${slug}`,
    title, latin, type: "figure", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["abbasid.state.abbasid", ...related],
    unlockables: [{ kind: "figure", refId: `abbasid.figure.${slug}`, label: title }],
    image: { alt: title, glyph: "🪶", tone: "from-stone-700/40 to-slate-900" },
    timelinePosition: startYear,
    rarity: "epic",
    meta: { titles: [title] },
    bridges: { era: "abbasid" },
  })),

  // ---------- SCHOLARS & CIVILIZATION FIGURES ----------
  ...SCHOLAR_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `abbasid.figure.${slug}`,
    title, latin, type: "figure", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["abbasid.state.abbasid","abbasid.event.golden-age", ...related],
    unlockables: [{ kind: "figure", refId: `abbasid.figure.${slug}`, label: title }],
    image: { alt: title, glyph: "📚", tone: "from-emerald-800/40 to-slate-900" },
    timelinePosition: startYear,
    rarity: "epic",
    meta: { kind: "scholar", titles: [title] },
    bridges: { era: "abbasid" },
  })),

  // ---------- CITIES ----------
  ...CITY_IDS.map(([slug, title, latin, description, startYear, endYear, related]) => E({
    id: `abbasid.city.${slug}`,
    title, latin, type: "city", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["abbasid.state.abbasid", ...related],
    unlockables: [{ kind: "city", refId: `abbasid.city.${slug}`, label: title }],
    image: { alt: title, glyph: "🏙️", tone: "from-amber-700/30 to-slate-900" },
    timelinePosition: startYear,
    rarity: "rare",
    bridges: { cityId: slug, era: "abbasid" },
  })),

  // ---------- BATTLES ----------
  ...BATTLE_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `abbasid.battle.${slug}`,
    title, latin, type: "battle", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["abbasid.state.abbasid", ...related],
    unlockables: [{ kind: "battle", refId: `abbasid.battle.${slug}`, label: title }],
    image: { alt: title, glyph: "⚔️", tone: "from-red-800/40 to-slate-900" },
    timelinePosition: startYear,
    rarity: "epic",
    bridges: { battleId: slug, era: "abbasid" },
  })),

  // ---------- EVENTS ----------
  ...EVENT_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `abbasid.event.${slug}`,
    title, latin, type: "event", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["abbasid.state.abbasid", ...related],
    unlockables: [{ kind: "event", refId: `abbasid.event.${slug}`, label: title }],
    image: { alt: title, glyph: "📜", tone: "from-emerald-800/40 to-slate-900" },
    timelinePosition: startYear,
    rarity: "rare",
    bridges: { era: "abbasid" },
  })),

  // ---------- LANDMARKS ----------
  ...LANDMARK_IDS.map(([slug, title, latin, description, startYear, endYear, related]) => E({
    id: `abbasid.landmark.${slug}`,
    title, latin, type: "landmark", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["abbasid.state.abbasid", ...related],
    unlockables: [{ kind: "landmark", refId: `abbasid.landmark.${slug}`, label: title }],
    image: { alt: title, glyph: "🕌", tone: "from-amber-700/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "epic",
    bridges: { era: "abbasid" },
  })),

  // ---------- ARTIFACTS ----------
  ...ARTIFACT_IDS.map(([slug, title, latin, description, startYear, endYear, glyph, rarity, related]) => E({
    id: `abbasid.artifact.${slug}`,
    title, latin, type: "artifact", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["abbasid.state.abbasid", ...related],
    unlockables: [{ kind: "artifact", refId: `abbasid.artifact.${slug}`, label: title }],
    image: { alt: title, glyph: glyph as string, tone: "from-amber-700/40 to-slate-900" },
    timelinePosition: startYear,
    rarity: rarity as "common" | "rare" | "epic" | "legendary",
    bridges: { era: "abbasid" },
  })),

  // ---------- ACHIEVEMENTS ----------
  ...ACHIEVEMENT_IDS.map(([slug, title, latin, description, related]) => E({
    id: `abbasid.achievement.${slug}`,
    title, latin, type: "achievement", description,
    period: { label: "750 – 1258 م", startYear: 750, endYear: 1258 },
    relatedEntities: ["abbasid.state.abbasid", ...related],
    unlockables: [{ kind: "title", refId: `abbasid.achievement.${slug}`, label: title }],
    image: { alt: title, glyph: "🏅", tone: "from-gold/40 to-slate-900" },
    timelinePosition: 900,
    rarity: "legendary",
    bridges: { era: "abbasid" },
  })),

  // ---------- FUTURE CAMPAIGN PLACEHOLDERS (locked) ----------
  ...FUTURE_CAMPAIGN_IDS.map(([slug, title, startYear, endYear, description]) => E({
    id: `abbasid.event.${slug}`,
    title, type: "event", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["abbasid.state.abbasid"],
    unlockables: [],
    image: { alt: title, glyph: "🔒", tone: "from-stone-700/40 to-slate-900" },
    timelinePosition: startYear,
    rarity: "legendary",
    meta: { locked: true, kind: "campaign-placeholder" },
    bridges: { era: "abbasid" },
  })),
];

export const ABBASID_PACK: ContentPack = {
  id: "pack-003-abbasid",
  order: 3,
  title: "الدولة العباسية",
  subtitle: "المجموعة 3 · من بغداد إلى العصر الذهبي",
  summary:
    "حزمة محتوى تاريخية شاملة عن الدولة العباسية: التأسيس، بناء بغداد، بيت الحكمة، العصر الذهبي، والسقوط على يد المغول.",
  era: "abbasid",
  period: { label: "750 – 1258 م", startYear: 750, endYear: 1258 },
  cover: { alt: "غلاف الدولة العباسية", glyph: "🏴", tone: "from-stone-700/40 to-slate-900" },
  entities,
};