import type { ContentPack, PackEntity } from "./types";

// ============================================================
// Content Pack 005 — الأندلس الإسلامية (Islamic Iberia)
// ------------------------------------------------------------
// Pure data pack. Auto-registers via packs/registry.ts and surfaces in
// Encyclopedia, State pages, Search, Timeline, Atlas, Related-History Graph,
// Content Audit, Museum, and the Future Campaign system.
// ============================================================

const E = (e: PackEntity): PackEntity => e;

// ---------- FIGURES ----------
const FIGURE_IDS = [
  ["tariq-ibn-ziyad","طارق بن زياد","Tariq ibn Ziyad",670,720,
    "القائد البربري المسلم، عبر المضيق الذي حمل اسمه (جبل طارق) سنة 711م وفتح الأندلس بانتصاره في وادي لكة على لذريق ملك القوط.",
    ["andalusia.event.fath-andalus","andalusia.battle.wadi-lakka","andalusia.figure.musa-ibn-nusayr","andalusia.artifact.sword-tariq"]],
  ["musa-ibn-nusayr","موسى بن نصير","Musa ibn Nusayr",640,716,
    "والي إفريقية الأموي ومخطّط فتح الأندلس، أرسل طارقًا ثم لحق به ليكمل فتح شمال شبه الجزيرة الأيبيرية.",
    ["andalusia.figure.tariq-ibn-ziyad","andalusia.event.fath-andalus","andalusia.battle.wadi-lakka"]],
  ["abd-al-rahman-i","عبد الرحمن الداخل","Abd al-Rahman I (al-Dakhil)",731,788,
    "صقر قريش، نجا من مذبحة العباسيين لبني أمية وعبر إلى الأندلس فأسّس إمارة قرطبة الأموية سنة 756م، وبنى جامع قرطبة الأكبر.",
    ["andalusia.event.imarat-qurtuba","andalusia.city.cordoba","andalusia.landmark.cordoba-mosque","andalusia.figure.hisham-i"]],
  ["hisham-i","هشام الرضا","Hisham I",757,796,
    "ابن عبد الرحمن الداخل، ثاني أمراء قرطبة، اشتُهر بالعدل وبتمكين الفقه المالكي في الأندلس.",
    ["andalusia.figure.abd-al-rahman-i","andalusia.city.cordoba","andalusia.event.imarat-qurtuba"]],
  ["abd-al-rahman-iii","عبد الرحمن الناصر","Abd al-Rahman III al-Nasir",891,961,
    "أعظم خلفاء الأندلس، أعلن الخلافة الأموية في قرطبة سنة 929م، وأسّس مدينة الزهراء، وأوصل قرطبة إلى ذروة مجدها.",
    ["andalusia.event.khilafat-qurtuba","andalusia.event.azhar-qurtuba","andalusia.landmark.madinat-al-zahra","andalusia.city.cordoba","andalusia.figure.al-hakam-ii"]],
  ["al-hakam-ii","الحكم المستنصر","Al-Hakam II al-Mustansir",915,976,
    "الخليفة العالم، جمع في مكتبة قرطبة نحو 400 ألف مجلد، ورعى العلوم والفلاسفة والمترجمين في عصر قرطبة الذهبي.",
    ["andalusia.figure.abd-al-rahman-iii","andalusia.city.cordoba","andalusia.landmark.cordoba-libraries","andalusia.event.azhar-qurtuba"]],
  ["al-mansur-ibn-abi-amir","المنصور بن أبي عامر","Al-Mansur ibn Abi Amir",938,1002,
    "الحاجب القوي الذي حكم باسم هشام المؤيد، شنّ نحو 50 غزوة على ممالك الشمال النصرانية ووصل سانتياغو دي كومبوستيلا.",
    ["andalusia.event.asr-al-mansur","andalusia.city.cordoba","andalusia.event.muluk-tawaif"]],
  ["al-mutamid","المعتمد بن عباد","Al-Mu'tamid ibn Abbad",1040,1095,
    "ملك إشبيلية الشاعر، أبرز ملوك الطوائف، استنجد بيوسف بن تاشفين فكان النصر في الزلاقة ثم نُفي إلى أغمات.",
    ["andalusia.event.muluk-tawaif","andalusia.figure.yusuf-ibn-tashfin","andalusia.battle.zallaqa","andalusia.city.seville"]],
  ["yusuf-ibn-tashfin","يوسف بن تاشفين","Yusuf ibn Tashfin",1009,1106,
    "أمير المرابطين وفاتح المغرب، عبر إلى الأندلس بدعوة ملوك الطوائف وحقّق النصر العظيم في الزلاقة سنة 1086م.",
    ["andalusia.battle.zallaqa","andalusia.event.murabitun-entry","andalusia.figure.al-mutamid"]],
  ["yaqub-al-mansur","يعقوب المنصور الموحّدي","Ya'qub al-Mansur (Almohad)",1160,1199,
    "الخليفة الموحّدي الذي هزم ألفونسو الثامن في معركة الأرك سنة 1195م، أحد أعظم انتصارات المسلمين في الأندلس.",
    ["andalusia.battle.al-arak","andalusia.event.muwahhidun-entry"]],
  ["abu-abdullah-al-saghir","أبو عبد الله الصغير","Boabdil (Muhammad XII)",1460,1533,
    "آخر ملوك بني الأحمر في غرناطة، سلّم مفاتيح المدينة لفرناندو وإيزابيلا سنة 1492م فبكى على ما فقد.",
    ["andalusia.event.fall-granada","andalusia.city.granada","andalusia.landmark.alhambra","andalusia.artifact.granada-key","andalusia.figure.ferdinand-ii","andalusia.figure.isabella-i"]],
  ["ferdinand-ii","فرناندو الثاني","Ferdinand II of Aragon",1452,1516,
    "ملك أراغون وشريك إيزابيلا في حروب الاسترداد، تسلّم مفاتيح غرناطة سنة 1492م فأنهى الحكم الإسلامي في الأندلس. (شخصية مرتبطة)",
    ["andalusia.event.fall-granada","andalusia.figure.isabella-i","andalusia.figure.abu-abdullah-al-saghir"]],
  ["isabella-i","إيزابيلا الأولى","Isabella I of Castile",1451,1504,
    "ملكة قشتالة وشريكة فرناندو في إسقاط غرناطة، أطلقت محاكم التفتيش وطرد المسلمين واليهود من إسبانيا. (شخصية مرتبطة)",
    ["andalusia.event.fall-granada","andalusia.event.end-islamic-andalus","andalusia.figure.ferdinand-ii"]],
  ["mehmed-ii","محمد الفاتح","Mehmed II (related)",1432,1481,
    "السلطان العثماني فاتح القسطنطينية، أرسل أسطولًا لإجلاء مسلمي الأندلس بعد سقوط غرناطة. (شخصية مرتبطة)",
    ["andalusia.event.fall-granada","andalusia.event.end-islamic-andalus"]],
] as const;

// ---------- SCHOLARS ----------
const SCHOLAR_IDS = [
  ["abbas-ibn-firnas","عباس بن فرناس","Abbas ibn Firnas",810,887,
    "مخترع وفلكي قرطبي، أوّل من حاول الطيران بأجنحة في التاريخ المعروف، وله إسهامات في صناعة الزجاج والساعات المائية.",
    ["andalusia.city.cordoba","andalusia.event.azhar-qurtuba"]],
  ["al-zahrawi","الزهراوي","Al-Zahrawi (Albucasis)",936,1013,
    "أبو القاسم الزهراوي، أبو الجراحة الحديثة، صاحب «التصريف لمن عجز عن التأليف» الذي درّس في جامعات أوروبا قرونًا.",
    ["andalusia.city.cordoba","andalusia.artifact.manuscript-al-zahrawi","andalusia.figure.al-hakam-ii"]],
  ["ibn-hazm","ابن حزم","Ibn Hazm",994,1064,
    "إمام أهل الظاهر في الأندلس، صاحب «المحلّى» في الفقه و«طوق الحمامة» في النفس والمحبة، فقيهٌ ومتكلّم ومؤرّخ.",
    ["andalusia.city.cordoba","andalusia.event.muluk-tawaif"]],
  ["ibn-rushd","ابن رشد","Ibn Rushd (Averroes)",1126,1198,
    "أبو الوليد ابن رشد، فقيه وفيلسوف قرطبي، شارح أرسطو الأكبر، أثّر في الفلسفة المدرسية الأوروبية تأثيرًا عميقًا.",
    ["andalusia.city.cordoba","andalusia.artifact.manuscript-ibn-rushd","andalusia.figure.ibn-tufayl"]],
  ["ibn-tufayl","ابن طفيل","Ibn Tufayl",1105,1185,
    "فيلسوف وطبيب أندلسي، صاحب «حيّ بن يقظان»، رواية فلسفية ألهمت أوروبا في عصر النهضة.",
    ["andalusia.figure.ibn-rushd","andalusia.event.muwahhidun-entry"]],
  ["al-shatibi","الشاطبي","Al-Shatibi",1320,1388,
    "أبو إسحاق الشاطبي الغرناطي، إمام المقاصد، صاحب «الموافقات» في أصول الفقه و«الاعتصام» في السنّة والبدعة.",
    ["andalusia.city.granada","andalusia.figure.ibn-al-khatib"]],
  ["ibn-al-baitar","ابن البيطار","Ibn al-Baitar",1197,1248,
    "صيدلي وعالم نبات أندلسي، صاحب «الجامع لمفردات الأدوية والأغذية»، أعظم موسوعة نباتية صيدلية في القرون الوسطى.",
    ["andalusia.city.malaga","andalusia.event.muwahhidun-entry"]],
  ["ibn-al-khatib","لسان الدين بن الخطيب","Ibn al-Khatib",1313,1374,
    "وزير غرناطة ومؤرّخها الأكبر، صاحب «الإحاطة في أخبار غرناطة»، أديبٌ ومؤرّخٌ وطبيب من أعمدة الأدب الأندلسي.",
    ["andalusia.city.granada","andalusia.landmark.alhambra","andalusia.figure.al-shatibi"]],
] as const;

// ---------- CITIES ----------
const CITY_IDS = [
  ["cordoba","قرطبة","Cordoba",
    "حاضرة الأندلس الكبرى وعاصمة الإمارة ثم الخلافة الأموية، وصلت في القرن العاشر إلى نحو نصف مليون نسمة وأكبر مكتبات أوروبا.",
    756,1236,["andalusia.landmark.cordoba-mosque","andalusia.landmark.madinat-al-zahra","andalusia.landmark.cordoba-libraries","andalusia.figure.abd-al-rahman-i","andalusia.figure.abd-al-rahman-iii","andalusia.figure.al-hakam-ii"]],
  ["granada","غرناطة","Granada",
    "آخر معاقل الإسلام في الأندلس، عاصمة بني الأحمر النصريين، حاضرة قصر الحمراء، سقطت سنة 1492م.",
    1238,1492,["andalusia.landmark.alhambra","andalusia.landmark.granada-walls","andalusia.landmark.granada-madrasas","andalusia.figure.abu-abdullah-al-saghir","andalusia.event.fall-granada"]],
  ["seville","إشبيلية","Seville",
    "حاضرة جنوب الأندلس وعاصمة دولة بني عبّاد في عهد الطوائف، ثم عاصمة الموحدين في الغرب، فيها الخيرالدة وبرج الذهب.",
    712,1248,["andalusia.figure.al-mutamid","andalusia.landmark.giralda","andalusia.landmark.golden-tower","andalusia.event.fall-seville"]],
  ["toledo","طليطلة","Toledo",
    "حاضرة وسط الأندلس وعاصمة ملوك الطوائف الذِنّونيين، سقطت في يد ألفونسو السادس سنة 1085م فاهتزّ العالم الإسلامي.",
    712,1085,["andalusia.battle.siege-toledo","andalusia.event.fall-toledo","andalusia.event.muluk-tawaif"]],
  ["malaga","مالقة","Malaga",
    "ثغر الأندلس الجنوبي وميناء غرناطة، حصنٌ منيع سقط بعد حصارٍ طويل سنة 1487م قبل غرناطة بخمس سنوات.",
    743,1487,["andalusia.event.fall-malaga","andalusia.landmark.malaga-fortress","andalusia.figure.ibn-al-baitar"]],
  ["zaragoza","سرقسطة","Zaragoza",
    "حاضرة الثغر الأعلى للأندلس وعاصمة بني هود في زمن الطوائف، فيها قصر الجعفرية، سقطت سنة 1118م.",
    714,1118,["andalusia.landmark.aljaferia","andalusia.event.muluk-tawaif"]],
  ["almeria","المرية","Almeria",
    "ثغر الأندلس الشرقي ومصنع أساطيلها وحرائرها، اشتُهرت بصناعة الحرير والسفن في عهد الخلافة.",
    955,1489,["andalusia.event.azhar-qurtuba","andalusia.event.fall-granada"]],
  ["jaen","جيان","Jaen",
    "حصنٌ أندلسي على الحدود الشمالية لمملكة غرناطة، قاعدة دفاع المسلمين في الحدود ضد قشتالة.",
    712,1246,["andalusia.battle.al-uqab","andalusia.city.granada"]],
  ["valencia","بلنسية","Valencia",
    "حاضرة شرق الأندلس على البحر، عاصمة دولة بني عامر في الطوائف، سقطت بيد جايمي الأول سنة 1238م.",
    714,1238,["andalusia.event.muluk-tawaif","andalusia.event.muwahhidun-entry"]],
  ["madinat-al-zahra-city","الزهراء","Madinat al-Zahra",
    "المدينة-القصر التي بناها عبد الرحمن الناصر غرب قرطبة سنة 936م لتكون عاصمته الجديدة، أعجوبةٌ معمارية دُمّرت في الفتنة.",
    936,1010,["andalusia.figure.abd-al-rahman-iii","andalusia.landmark.madinat-al-zahra","andalusia.event.azhar-qurtuba"]],
] as const;

// ---------- BATTLES ----------
const BATTLE_IDS = [
  ["wadi-lakka","معركة وادي لكة","Battle of Guadalete",711,711,
    "المعركة الفاصلة التي هزم فيها طارق بن زياد ملك القوط لذريق، وفتحت الأندلس أمام جيوش المسلمين.",
    ["andalusia.figure.tariq-ibn-ziyad","andalusia.figure.musa-ibn-nusayr","andalusia.event.fath-andalus","andalusia.artifact.sword-tariq"]],
  ["zallaqa","معركة الزلاقة","Battle of Zallaqa (Sagrajas)",1086,1086,
    "النصر العظيم ليوسف بن تاشفين والمعتمد بن عباد على ألفونسو السادس قرب بطليوس، فأوقف زحف الاسترداد عقودًا.",
    ["andalusia.figure.yusuf-ibn-tashfin","andalusia.figure.al-mutamid","andalusia.event.murabitun-entry"]],
  ["al-arak","معركة الأرك","Battle of Alarcos",1195,1195,
    "انتصار الخليفة الموحّدي يعقوب المنصور على ألفونسو الثامن ملك قشتالة، أحد أعظم انتصارات المسلمين في الأندلس.",
    ["andalusia.figure.yaqub-al-mansur","andalusia.event.muwahhidun-entry"]],
  ["al-uqab","معركة العقاب","Battle of Las Navas de Tolosa",1212,1212,
    "الهزيمة الكبرى للموحدين أمام تحالف ممالك قشتالة وأراغون ونافار، نقطة التحوّل الكبرى التي بدأ بعدها الانهيار.",
    ["andalusia.city.jaen","andalusia.event.end-islamic-andalus","andalusia.event.muwahhidun-entry"]],
  ["siege-toledo","حصار طليطلة","Siege of Toledo",1085,1085,
    "حصار ألفونسو السادس لطليطلة في زمن الطوائف وسقوطها في يده، الصدمة التي استدعت المرابطين إلى الأندلس.",
    ["andalusia.city.toledo","andalusia.event.fall-toledo","andalusia.event.muluk-tawaif","andalusia.event.murabitun-entry"]],
  ["siege-seville","حصار إشبيلية","Siege of Seville",1247,1248,
    "حصار فرناندو الثالث الكاستيلي لإشبيلية وسقوطها سنة 1248م، نهاية حاضرة الأندلس الكبرى تحت الموحدين.",
    ["andalusia.city.seville","andalusia.event.fall-seville","andalusia.landmark.giralda"]],
  ["fall-cordoba-battle","سقوط قرطبة","Fall of Cordoba",1236,1236,
    "دخول فرناندو الثالث قرطبة سنة 1236م بعد سبعة قرون من حكم المسلمين، وتحويل جامعها الكبير إلى كاتدرائية.",
    ["andalusia.city.cordoba","andalusia.event.fall-cordoba","andalusia.landmark.cordoba-mosque"]],
  ["fall-malaga-battle","سقوط مالقة","Fall of Malaga",1487,1487,
    "سقوط مالقة بعد حصارٍ مديد أمام جيوش فرناندو وإيزابيلا، وقطع شريان غرناطة البحري قبل سقوطها.",
    ["andalusia.city.malaga","andalusia.event.fall-malaga","andalusia.event.fall-granada"]],
  ["fall-granada-battle","سقوط غرناطة","Fall of Granada",1491,1492,
    "الحصار الأخير لغرناطة وتسليم أبي عبد الله الصغير مفاتيحها لفرناندو وإيزابيلا في 2 يناير 1492م.",
    ["andalusia.city.granada","andalusia.figure.abu-abdullah-al-saghir","andalusia.figure.ferdinand-ii","andalusia.figure.isabella-i","andalusia.event.fall-granada","andalusia.event.end-islamic-andalus","andalusia.artifact.granada-key"]],
  ["shadhuna","معركة شذونة","Battle of Shadhuna",712,712,
    "موقعةٌ تابعة لفتح الأندلس بقيادة موسى بن نصير قرب شذونة، ثبّتت سيطرة المسلمين على الجنوب بعد وادي لكة.",
    ["andalusia.figure.musa-ibn-nusayr","andalusia.event.fath-andalus"]],
] as const;

// ---------- EVENTS ----------
const EVENT_IDS = [
  ["fath-andalus","فتح الأندلس","Conquest of al-Andalus",711,716,
    "حملة طارق بن زياد وموسى بن نصير على شبه الجزيرة الأيبيرية، انتهت بسيطرة المسلمين على معظمها في خمس سنوات.",
    ["andalusia.figure.tariq-ibn-ziyad","andalusia.figure.musa-ibn-nusayr","andalusia.battle.wadi-lakka","andalusia.battle.shadhuna"]],
  ["imarat-qurtuba","قيام إمارة قرطبة","Establishment of the Emirate of Cordoba",756,756,
    "إعلان عبد الرحمن الداخل استقلال الأندلس عن العباسيين وتأسيس إمارة قرطبة الأموية بعد عبوره الأموي الفريد.",
    ["andalusia.figure.abd-al-rahman-i","andalusia.city.cordoba","andalusia.landmark.cordoba-mosque"]],
  ["khilafat-qurtuba","قيام الخلافة الأموية في الأندلس","Establishment of the Cordoba Caliphate",929,929,
    "إعلان عبد الرحمن الناصر نفسه أمير المؤمنين سنة 929م، فقامت الخلافة الأموية الثانية في الأندلس مستقلّةً عن العباسيين والفاطميين.",
    ["andalusia.figure.abd-al-rahman-iii","andalusia.city.cordoba","andalusia.event.azhar-qurtuba"]],
  ["azhar-qurtuba","ازدهار قرطبة","Golden Age of Cordoba",929,1009,
    "قرنٌ من الذروة الحضارية تحت الناصر والحكم والحاجب المنصور، صارت قرطبة أعظم حواضر أوروبا علمًا وعمرانًا واقتصادًا.",
    ["andalusia.figure.abd-al-rahman-iii","andalusia.figure.al-hakam-ii","andalusia.figure.al-mansur-ibn-abi-amir","andalusia.landmark.madinat-al-zahra","andalusia.landmark.cordoba-libraries","andalusia.figure.al-zahrawi","andalusia.figure.abbas-ibn-firnas"]],
  ["build-zahra","بناء مدينة الزهراء","Building of Madinat al-Zahra",936,976,
    "بناء عبد الرحمن الناصر مدينته-القصر غرب قرطبة لتكون عاصمته الجديدة، تحفةٌ معمارية أُتمّت في عهد الحكم المستنصر.",
    ["andalusia.figure.abd-al-rahman-iii","andalusia.figure.al-hakam-ii","andalusia.landmark.madinat-al-zahra","andalusia.city.madinat-al-zahra-city"]],
  ["asr-al-mansur","عصر المنصور بن أبي عامر","Era of al-Mansur ibn Abi Amir",978,1002,
    "ربع قرنٍ من غزوات المنصور على ممالك الشمال النصرانية، وصل فيها سانتياغو دي كومبوستيلا وحمل أجراسها إلى قرطبة.",
    ["andalusia.figure.al-mansur-ibn-abi-amir","andalusia.city.cordoba","andalusia.event.muluk-tawaif"]],
  ["muluk-tawaif","ملوك الطوائف","Taifa Kingdoms",1031,1086,
    "تفكّك الخلافة الأموية في الأندلس إلى نحو عشرين دويلة متصارعة (إشبيلية، طليطلة، سرقسطة، بلنسية…) مهّدت لاستنجاد بالمرابطين.",
    ["andalusia.figure.al-mutamid","andalusia.city.seville","andalusia.city.toledo","andalusia.city.zaragoza","andalusia.event.fall-toledo","andalusia.event.murabitun-entry"]],
  ["murabitun-entry","دخول المرابطين","Almoravid Intervention in al-Andalus",1086,1147,
    "عبور يوسف بن تاشفين والمرابطين الأمازيغ إلى الأندلس بدعوة ملوك الطوائف، وضمّ دويلاتهم تحت رايتهم بعد الزلاقة.",
    ["andalusia.figure.yusuf-ibn-tashfin","andalusia.battle.zallaqa","andalusia.event.muluk-tawaif"]],
  ["muwahhidun-entry","دخول الموحدين","Almohad Intervention in al-Andalus",1147,1212,
    "خلافة الموحدين تخلف المرابطين في الأندلس والمغرب، أعادت الوحدة ثم انكسرت في العقاب فبدأت موجة الاسترداد الكبرى.",
    ["andalusia.figure.yaqub-al-mansur","andalusia.battle.al-arak","andalusia.battle.al-uqab"]],
  ["fall-toledo","سقوط طليطلة","Fall of Toledo",1085,1085,
    "أوّل سقوطٍ كبير لحاضرة أندلسية مركزية في يد ألفونسو السادس، صدمةٌ هزّت العالم الإسلامي ودفعت الطوائف لاستنجاد المرابطين.",
    ["andalusia.city.toledo","andalusia.battle.siege-toledo","andalusia.event.muluk-tawaif","andalusia.event.murabitun-entry"]],
  ["fall-cordoba","سقوط قرطبة","Fall of Cordoba (Event)",1236,1236,
    "خروج قرطبة من الحكم الإسلامي بعد 480 سنة، وانتقالها إلى مملكة قشتالة وتحويل جامعها الأكبر إلى كاتدرائية.",
    ["andalusia.city.cordoba","andalusia.battle.fall-cordoba-battle","andalusia.landmark.cordoba-mosque","andalusia.event.end-islamic-andalus"]],
  ["fall-seville","سقوط إشبيلية","Fall of Seville",1248,1248,
    "سقوط إشبيلية عاصمة الموحدين في الغرب في يد فرناندو الثالث الكاستيلي بعد حصارٍ بحري وبري طويل.",
    ["andalusia.city.seville","andalusia.battle.siege-seville","andalusia.landmark.giralda","andalusia.event.end-islamic-andalus"]],
  ["fall-malaga","سقوط مالقة","Fall of Malaga",1487,1487,
    "سقوط ثغر مالقة في يد فرناندو وإيزابيلا قبل غرناطة بخمس سنوات، وقطع نجدتها البحرية من المغرب.",
    ["andalusia.city.malaga","andalusia.battle.fall-malaga-battle","andalusia.event.fall-granada"]],
  ["fall-granada","سقوط غرناطة","Fall of Granada",1491,1492,
    "تسليم أبي عبد الله الصغير مفاتيح غرناطة لفرناندو وإيزابيلا في يناير 1492م، وانتهاء الوجود السياسي للإسلام في الأندلس.",
    ["andalusia.figure.abu-abdullah-al-saghir","andalusia.city.granada","andalusia.landmark.alhambra","andalusia.battle.fall-granada-battle","andalusia.artifact.granada-key","andalusia.event.end-islamic-andalus"]],
  ["end-islamic-andalus","نهاية الحكم الإسلامي في الأندلس","End of Muslim Rule in al-Andalus",1492,1614,
    "ما تلا سقوط غرناطة من محاكم تفتيش وتنصير قسري وطرد المورسكيّين سنة 1609م، فطُويت صفحة الإسلام في الأندلس.",
    ["andalusia.event.fall-granada","andalusia.figure.ferdinand-ii","andalusia.figure.isabella-i","andalusia.figure.mehmed-ii"]],
] as const;

// ---------- LANDMARKS ----------
const LANDMARK_IDS = [
  ["cordoba-mosque","جامع قرطبة الأكبر","Great Mosque of Cordoba",
    "تحفة العمارة الأندلسية، بدأ بناءه عبد الرحمن الداخل سنة 785م ووسّعه خلفاؤه، أعمدته وأقواسه ذات الحُمرة والبيض من أعجب آيات الفن الإسلامي.",
    785,1236,["andalusia.city.cordoba","andalusia.figure.abd-al-rahman-i","andalusia.figure.al-hakam-ii","andalusia.event.fall-cordoba"]],
  ["alhambra","قصر الحمراء","Alhambra Palace",
    "قصر بني الأحمر النصريين فوق هضبة السبيكة في غرناطة، آخر تحفة معمارية للإسلام في الأندلس، بدائع الزخرفة والمياه والحدائق.",
    1238,1492,["andalusia.city.granada","andalusia.figure.abu-abdullah-al-saghir","andalusia.figure.ibn-al-khatib","andalusia.event.fall-granada"]],
  ["madinat-al-zahra","مدينة الزهراء","Madinat al-Zahra",
    "المدينة-القصر التي بناها عبد الرحمن الناصر سنة 936م غرب قرطبة، أعجوبةٌ من المرمر والذهب دُمّرت في فتنة قرطبة.",
    936,1010,["andalusia.city.cordoba","andalusia.city.madinat-al-zahra-city","andalusia.figure.abd-al-rahman-iii","andalusia.event.build-zahra","andalusia.event.azhar-qurtuba"]],
  ["golden-tower","برج الذهب","Torre del Oro (Tower of Gold)",
    "برجٌ شامخٌ بناه الموحدون على ضفّة الوادي الكبير في إشبيلية سنة 1220م لحماية مينائها وسلسلة سفنها الحربية.",
    1220,1248,["andalusia.city.seville","andalusia.event.muwahhidun-entry"]],
  ["giralda","الخيرالدة","La Giralda (Minaret of Seville)",
    "مئذنة جامع إشبيلية الكبير التي بناها الموحدون سنة 1198م، تحوّلت بعد السقوط إلى برج الكاتدرائية، ولا تزال أيقونة المدينة.",
    1198,1248,["andalusia.city.seville","andalusia.event.muwahhidun-entry","andalusia.event.fall-seville"]],
  ["granada-walls","أسوار غرناطة","Walls of Granada",
    "منظومة الأسوار والأبراج التي حصّنت غرناطة النصرية أمام جيوش قشتالة، صمدت قرنين ونصفًا قبل أن تسقط سنة 1492م.",
    1238,1492,["andalusia.city.granada","andalusia.landmark.alhambra","andalusia.event.fall-granada"]],
  ["aljaferia","قصر الجعفرية","Aljafería Palace",
    "قصر بني هود في سرقسطة، أبدع نموذج لعمارة الطوائف، صار بعد السقوط مقرّ ملوك أراغون النصارى.",
    1065,1118,["andalusia.city.zaragoza","andalusia.event.muluk-tawaif"]],
  ["malaga-fortress","قصبة مالقة","Alcazaba of Malaga",
    "قصبة مالقة الحصينة فوق التلّ المطلّ على البحر، صمدت طويلًا أمام حصار فرناندو وإيزابيلا قبل أن تسقط سنة 1487م.",
    1057,1487,["andalusia.city.malaga","andalusia.event.fall-malaga"]],
  ["cordoba-libraries","مكتبات قرطبة","Libraries of Cordoba",
    "مكتبة الحكم المستنصر وحدها بلغت 400 ألف مجلد، وكانت قرطبة تضمّ نحو سبعين مكتبة عامة في زمن الخلافة، أكبر تجمّع كتب في أوروبا قاطبة.",
    961,1013,["andalusia.figure.al-hakam-ii","andalusia.city.cordoba","andalusia.event.azhar-qurtuba"]],
  ["granada-madrasas","مدارس غرناطة","Madrasas of Granada",
    "مدارس بني الأحمر في غرناطة وعلى رأسها المدرسة اليوسفية، حفظت العلوم الإسلامية حتى السقوط، وتلامذتها من علماء الأندلس الأخيرين.",
    1349,1492,["andalusia.city.granada","andalusia.figure.al-shatibi","andalusia.figure.ibn-al-khatib"]],
] as const;

// ---------- ARTIFACTS ----------
const ARTIFACT_IDS = [
  ["sword-tariq","سيف طارق بن زياد","Sword of Tariq ibn Ziyad",
    "السيف الذي حمله طارق بن زياد يوم وادي لكة، رمز فتح الأندلس وعبور المسلمين إلى أوروبا.",
    711,1492,"🗡️","legendary",["andalusia.figure.tariq-ibn-ziyad","andalusia.battle.wadi-lakka","andalusia.event.fath-andalus"]],
  ["manuscript-al-zahrawi","مخطوطة التصريف للزهراوي","Al-Tasrif Manuscript",
    "موسوعة الجراحة الكبرى للزهراوي، صارت مرجع الجراحين في أوروبا لخمسة قرون بعد ترجمتها إلى اللاتينية.",
    1000,1492,"📜","legendary",["andalusia.figure.al-zahrawi","andalusia.city.cordoba","andalusia.event.azhar-qurtuba"]],
  ["manuscript-ibn-rushd","مخطوطة شروح ابن رشد","Manuscripts of Ibn Rushd",
    "شروح ابن رشد على أرسطو التي أعادت تقديم الفلسفة اليونانية إلى أوروبا اللاتينية وأشعلت الفكر المدرسي.",
    1180,1492,"📜","legendary",["andalusia.figure.ibn-rushd","andalusia.city.cordoba"]],
  ["andalusia-banner","راية الأندلس","Banner of al-Andalus",
    "الراية الأموية ثم النصرية في الأندلس، رمز سبعة قرون من الحضارة الإسلامية في غرب أوروبا.",
    756,1492,"🏴","epic",["andalusia.state.andalusia","andalusia.figure.abd-al-rahman-iii"]],
  ["granada-key","مفتاح غرناطة","Key of Granada",
    "المفتاح الرمزي الذي سلّمه أبو عبد الله الصغير لفرناندو وإيزابيلا في 2 يناير 1492م، أعظم رمز نهاية الأندلس.",
    1492,1492,"🔑","legendary",["andalusia.figure.abu-abdullah-al-saghir","andalusia.figure.ferdinand-ii","andalusia.figure.isabella-i","andalusia.event.fall-granada","andalusia.event.end-islamic-andalus"]],
  ["andalusia-map","خريطة الأندلس الإسلامية","Map of Islamic al-Andalus",
    "خريطة أندلسية تبيّن الكور والثغور من شذونة إلى سرقسطة، ومسار التراجع من فتح وادي لكة إلى سقوط غرناطة.",
    900,1492,"🗺️","epic",["andalusia.state.andalusia","andalusia.city.cordoba","andalusia.city.granada","andalusia.city.toledo","andalusia.city.seville"]],
  ["andalusi-dinar","دينار أندلسي","Andalusi Gold Dinar",
    "الدينار الأموي الأندلسي ثم النصري، عملة قرطبة وغرناطة التي تداولها التجار في المتوسط وأوروبا قرونًا.",
    929,1492,"💰","epic",["andalusia.state.andalusia","andalusia.figure.abd-al-rahman-iii","andalusia.city.cordoba"]],
  ["andalusia-seal","ختم الخلافة الأندلسية","Seal of the Cordoba Caliphate",
    "الختم الذي وقّع به خلفاء قرطبة مراسيمهم إلى الولاة والقضاة من سرقسطة إلى المرية.",
    929,1031,"🪧","epic",["andalusia.figure.abd-al-rahman-iii","andalusia.figure.al-hakam-ii","andalusia.event.khilafat-qurtuba"]],
  ["cordoba-decree","مرسوم قرطبة","Cordoban Decree",
    "مرسومٌ خلافي من قرطبة، نموذج للسجلّ الإداري الأموي في الأندلس في عصر ذروتها.",
    929,1031,"📃","rare",["andalusia.figure.abd-al-rahman-iii","andalusia.figure.al-hakam-ii","andalusia.event.azhar-qurtuba"]],
  ["andalusia-medal","وسام حضارة الأندلس","Medal of Andalusi Civilization",
    "وسامٌ شرفي يُمنح لمن أتمّ مسيرة الحضارة الأندلسية من فتح وادي لكة إلى سقوط غرناطة.",
    711,1492,"🏵️","legendary",["andalusia.state.andalusia","andalusia.event.azhar-qurtuba","andalusia.event.fall-granada"]],
] as const;

// ---------- ACHIEVEMENTS ----------
const ACHIEVEMENT_IDS = [
  ["andalusia-conqueror","فاتح الأندلس","Conqueror of al-Andalus",
    "يُمنح لمن أكمل قصص فتح الأندلس وطارق بن زياد وموسى بن نصير ومعركة وادي لكة.",
    ["andalusia.figure.tariq-ibn-ziyad","andalusia.figure.musa-ibn-nusayr","andalusia.battle.wadi-lakka","andalusia.event.fath-andalus"]],
  ["andalusia-historian","مؤرّخ الأندلس","Historian of al-Andalus",
    "يُمنح لمن قرأ جميع شخصيات وأحداث الأندلس في الموسوعة.",
    ["andalusia.state.andalusia","andalusia.figure.ibn-hazm","andalusia.figure.ibn-al-khatib","andalusia.event.azhar-qurtuba","andalusia.event.fall-granada"]],
  ["andalusia-collector","جامع التراث الأندلسي","Collector of Andalusi Heritage",
    "يُمنح لمن جمع كلّ الآثار والمخطوطات الأندلسية في مجموعته.",
    ["andalusia.artifact.manuscript-al-zahrawi","andalusia.artifact.manuscript-ibn-rushd","andalusia.artifact.andalusi-dinar","andalusia.artifact.granada-key","andalusia.artifact.andalusia-medal"]],
  ["cordoba-master","سيد قرطبة","Master of Cordoba",
    "يُمنح لمن أتمّ مسار قرطبة وجامعها ومدينة الزهراء ومكتبات الحكم المستنصر.",
    ["andalusia.city.cordoba","andalusia.landmark.cordoba-mosque","andalusia.landmark.madinat-al-zahra","andalusia.landmark.cordoba-libraries"]],
  ["andalusia-civilization-guardian","حارس الحضارة الأندلسية","Guardian of Andalusi Civilization",
    "يُمنح لمن جمع جميع إنجازات الأندلس وأكمل قصة سقوط غرناطة.",
    ["andalusia.state.andalusia","andalusia.event.fall-granada","andalusia.event.end-islamic-andalus","andalusia.landmark.alhambra"]],
] as const;

// ---------- FUTURE CAMPAIGN PLACEHOLDERS (locked) ----------
const FUTURE_CAMPAIGN_IDS = [
  ["future-tariq",        "حملة طارق بن زياد",        710,716,"حملةٌ قادمة تروي عبور طارق بن زياد المضيق وفتح الأندلس. (قريبًا)"],
  ["future-abd-al-rahman","حملة عبد الرحمن الداخل",   750,788,"حملةٌ قادمة عن رحلة صقر قريش حتى تأسيس إمارة قرطبة. (قريبًا)"],
  ["future-cordoba-golden","عصر قرطبة الذهبي",         929,1009,"حملةٌ قادمة عن قرن الذروة الأموي في الأندلس. (قريبًا)"],
  ["future-tawaif",       "ملوك الطوائف",             1031,1086,"حملةٌ قادمة عن تفكك الخلافة واستنجاد ملوك الطوائف بالمرابطين. (قريبًا)"],
  ["future-zallaqa",      "معركة الزلاقة",            1086,1086,"حملةٌ قادمة عن نصر يوسف بن تاشفين والمعتمد بن عباد. (قريبًا)"],
  ["future-fall-granada", "سقوط غرناطة",              1491,1492,"حملةٌ قادمة عن آخر أيام الأندلس وتسليم المفاتيح. (قريبًا)"],
] as const;

const entities: PackEntity[] = [
  // ---------- STATE ----------
  E({
    id: "andalusia.state.andalusia",
    title: "الأندلس الإسلامية",
    latin: "Islamic al-Andalus",
    type: "state",
    description:
      "الأندلس الإسلامية، حضارةٌ امتدّت 781 سنة في شبه الجزيرة الأيبيرية، من فتح طارق بن زياد سنة 711م إلى سقوط غرناطة سنة 1492م. مرّت بإمارة قرطبة فالخلافة الأموية فملوك الطوائف فالمرابطين فالموحدين فمملكة غرناطة النصرية. حاضرتاها الكبريان قرطبة وغرناطة.",
    period: { label: "711 – 1492 م", startYear: 711, endYear: 1492 },
    relatedEntities: [
      "andalusia.figure.tariq-ibn-ziyad","andalusia.figure.musa-ibn-nusayr",
      "andalusia.figure.abd-al-rahman-i","andalusia.figure.abd-al-rahman-iii",
      "andalusia.figure.al-hakam-ii","andalusia.figure.al-mansur-ibn-abi-amir",
      "andalusia.figure.al-mutamid","andalusia.figure.yusuf-ibn-tashfin",
      "andalusia.figure.yaqub-al-mansur","andalusia.figure.abu-abdullah-al-saghir",
      "andalusia.city.cordoba","andalusia.city.granada","andalusia.city.seville",
      "andalusia.city.toledo","andalusia.city.malaga","andalusia.city.zaragoza",
      "andalusia.battle.wadi-lakka","andalusia.battle.zallaqa","andalusia.battle.al-arak",
      "andalusia.battle.al-uqab","andalusia.battle.fall-granada-battle",
      "andalusia.event.fath-andalus","andalusia.event.khilafat-qurtuba",
      "andalusia.event.azhar-qurtuba","andalusia.event.muluk-tawaif",
      "andalusia.event.fall-granada","andalusia.event.end-islamic-andalus",
    ],
    unlockables: [
      { kind: "campaign", refId: "andalusia", label: "حملات الأندلس الإسلامية" },
    ],
    image: { alt: "راية الأندلس", glyph: "🕌", tone: "from-amber-700/40 to-rose-950" },
    timelinePosition: 711,
    rarity: "legendary",
    meta: {
      founder: "طارق بن زياد / عبد الرحمن الداخل",
      capital: "قرطبة (ثم غرناطة)",
      majorCities: ["قرطبة","غرناطة","إشبيلية","طليطلة","مالقة","سرقسطة","المرية","جيان","بلنسية","الزهراء"],
      majorFigures: ["طارق بن زياد","موسى بن نصير","عبد الرحمن الداخل","عبد الرحمن الناصر","الحكم المستنصر","المنصور بن أبي عامر","المعتمد بن عباد","يوسف بن تاشفين","أبو عبد الله الصغير"],
      majorBattles: ["وادي لكة","الزلاقة","الأرك","العقاب","حصار طليطلة","سقوط غرناطة"],
      majorEvents: ["فتح الأندلس","قيام الخلافة","ازدهار قرطبة","ملوك الطوائف","سقوط غرناطة","نهاية الحكم الإسلامي"],
    },
    bridges: { era: "andalusia" },
  }),

  // ---------- FIGURES ----------
  ...FIGURE_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `andalusia.figure.${slug}`,
    title, latin, type: "figure", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["andalusia.state.andalusia", ...related],
    unlockables: [{ kind: "figure", refId: `andalusia.figure.${slug}`, label: title }],
    image: { alt: title, glyph: "🪶", tone: "from-amber-700/40 to-rose-950" },
    timelinePosition: startYear,
    rarity: "epic",
    meta: { titles: [title] },
    bridges: { era: "andalusia" },
  })),

  // ---------- SCHOLARS ----------
  ...SCHOLAR_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `andalusia.figure.${slug}`,
    title, latin, type: "figure", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["andalusia.state.andalusia", ...related],
    unlockables: [{ kind: "figure", refId: `andalusia.figure.${slug}`, label: title }],
    image: { alt: title, glyph: "📚", tone: "from-emerald-800/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "epic",
    meta: { kind: "scholar", titles: [title] },
    bridges: { era: "andalusia" },
  })),

  // ---------- CITIES ----------
  ...CITY_IDS.map(([slug, title, latin, description, startYear, endYear, related]) => E({
    id: `andalusia.city.${slug}`,
    title, latin, type: "city", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["andalusia.state.andalusia", ...related],
    unlockables: [{ kind: "city", refId: `andalusia.city.${slug}`, label: title }],
    image: { alt: title, glyph: "🏙️", tone: "from-amber-700/30 to-rose-950" },
    timelinePosition: startYear,
    rarity: "rare",
    bridges: { cityId: slug, era: "andalusia" },
  })),

  // ---------- BATTLES ----------
  ...BATTLE_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `andalusia.battle.${slug}`,
    title, latin, type: "battle", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["andalusia.state.andalusia", ...related],
    unlockables: [{ kind: "battle", refId: `andalusia.battle.${slug}`, label: title }],
    image: { alt: title, glyph: "⚔️", tone: "from-red-800/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "epic",
    bridges: { era: "andalusia" },
  })),

  // ---------- EVENTS ----------
  ...EVENT_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `andalusia.event.${slug}`,
    title, latin, type: "event", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["andalusia.state.andalusia", ...related],
    unlockables: [{ kind: "event", refId: `andalusia.event.${slug}`, label: title }],
    image: { alt: title, glyph: "📜", tone: "from-emerald-800/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "rare",
    bridges: { era: "andalusia" },
  })),

  // ---------- LANDMARKS ----------
  ...LANDMARK_IDS.map(([slug, title, latin, description, startYear, endYear, related]) => E({
    id: `andalusia.landmark.${slug}`,
    title, latin, type: "landmark", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["andalusia.state.andalusia", ...related],
    unlockables: [{ kind: "landmark", refId: `andalusia.landmark.${slug}`, label: title }],
    image: { alt: title, glyph: "🕌", tone: "from-amber-700/40 to-rose-950" },
    timelinePosition: startYear,
    rarity: "epic",
    bridges: { era: "andalusia" },
  })),

  // ---------- ARTIFACTS ----------
  ...ARTIFACT_IDS.map(([slug, title, latin, description, startYear, endYear, glyph, rarity, related]) => E({
    id: `andalusia.artifact.${slug}`,
    title, latin, type: "artifact", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["andalusia.state.andalusia", ...related],
    unlockables: [{ kind: "artifact", refId: `andalusia.artifact.${slug}`, label: title }],
    image: { alt: title, glyph: glyph as string, tone: "from-amber-700/40 to-rose-950" },
    timelinePosition: startYear,
    rarity: rarity as "common" | "rare" | "epic" | "legendary",
    bridges: { era: "andalusia" },
  })),

  // ---------- ACHIEVEMENTS ----------
  ...ACHIEVEMENT_IDS.map(([slug, title, latin, description, related]) => E({
    id: `andalusia.achievement.${slug}`,
    title, latin, type: "achievement", description,
    period: { label: "711 – 1492 م", startYear: 711, endYear: 1492 },
    relatedEntities: ["andalusia.state.andalusia", ...related],
    unlockables: [{ kind: "title", refId: `andalusia.achievement.${slug}`, label: title }],
    image: { alt: title, glyph: "🏅", tone: "from-amber-600/40 to-rose-950" },
    timelinePosition: 1100,
    rarity: "legendary",
    bridges: { era: "andalusia" },
  })),

  // ---------- FUTURE CAMPAIGN PLACEHOLDERS (locked) ----------
  ...FUTURE_CAMPAIGN_IDS.map(([slug, title, startYear, endYear, description]) => E({
    id: `andalusia.event.${slug}`,
    title, type: "event", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["andalusia.state.andalusia"],
    unlockables: [],
    image: { alt: title, glyph: "🔒", tone: "from-stone-700/40 to-slate-900" },
    timelinePosition: startYear,
    rarity: "legendary",
    meta: { locked: true, kind: "campaign-placeholder" },
    bridges: { era: "andalusia" },
  })),
];

export const ANDALUSIA_PACK: ContentPack = {
  id: "pack-005-andalusia",
  order: 5,
  title: "الأندلس الإسلامية",
  subtitle: "المجموعة 5 · قرطبة وغرناطة وسبعة قرون من الحضارة",
  summary:
    "حزمة محتوى تاريخية شاملة عن الأندلس الإسلامية من فتح طارق بن زياد إلى سقوط غرناطة: قرطبة وخلافتها، الزهراء، الطوائف، المرابطون، الموحدون، ومملكة غرناطة النصرية.",
  era: "andalusia",
  period: { label: "711 – 1492 م", startYear: 711, endYear: 1492 },
  cover: { alt: "غلاف الأندلس الإسلامية", glyph: "🕌", tone: "from-amber-700/40 to-rose-950" },
  entities,
};