import type { ContentPack, PackEntity } from "./types";

// ============================================================
// Content Pack 001 — الدولة الأيوبية (The Ayyubid State)
// ------------------------------------------------------------
// All ids follow the convention: ayyubid.<type>.<slug>
// `bridges` link pack entities to legacy data in src/lib/data.ts
// and src/lib/cities.ts so existing routes (figure, battle, city,
// campaigns, world map, museum, timeline) continue to work.
// ============================================================

const E = (e: PackEntity): PackEntity => e;

const entities: PackEntity[] = [
  // ---------- STATE ----------
  E({
    id: "ayyubid.state.ayyubid",
    title: "الدولة الأيوبية",
    latin: "Ayyubid State",
    type: "state",
    description:
      "دولةٌ سُنّيّة أسّسها صلاح الدين الأيوبي عام 1171م بعد إنهاء الدولة الفاطمية في مصر، فامتدّ سلطانها على مصر والشام والحجاز واليمن، وبلغت ذروتها بتحرير القدس عام 1187م، وانتهت رسميًّا عام 1250م على يد المماليك.",
    period: { label: "1171 – 1250 م", startYear: 1171, endYear: 1250 },
    relatedEntities: [
      "ayyubid.figure.salahuddin",
      "ayyubid.figure.nuruddin",
      "ayyubid.figure.al-adil",
      "ayyubid.figure.al-kamil",
      "ayyubid.city.cairo",
      "ayyubid.city.damascus",
      "ayyubid.city.jerusalem",
      "ayyubid.city.aleppo",
      "ayyubid.battle.hattin",
      "ayyubid.battle.arsuf",
      "ayyubid.event.end-fatimid",
      "ayyubid.event.liberate-jerusalem",
    ],
    unlockables: [
      { kind: "campaign", refId: "ayyubid", label: "حملة صلاح الدين الكبرى" },
    ],
    image: { alt: "راية الدولة الأيوبية", glyph: "🦅", tone: "from-amber-700/40 to-zinc-900" },
    timelinePosition: 1171,
    rarity: "legendary",
    meta: {
      founder: "صلاح الدين الأيوبي",
      capital: "القاهرة",
      majorCities: ["القاهرة", "دمشق", "القدس", "حلب"],
      majorFigures: ["صلاح الدين الأيوبي", "نور الدين زنكي", "الملك العادل", "الملك الكامل"],
      majorBattles: ["حطين", "أرسوف"],
      majorEvents: ["إنهاء الدولة الفاطمية", "تحرير القدس"],
    },
    bridges: { era: "ayyubid" },
  }),

  // ---------- FIGURES ----------
  E({
    id: "ayyubid.figure.salahuddin",
    title: "صلاح الدين الأيوبي",
    latin: "Salah ad-Din al-Ayyubi",
    type: "figure",
    description:
      "السلطان الناصر صلاح الدين يوسف بن أيوب، مؤسس الدولة الأيوبية ومحرّر القدس بعد 88 عامًا من الاحتلال الصليبي، أنموذج القائد الفارس في التاريخ الإسلامي.",
    period: { label: "1137 – 1193 م", startYear: 1137, endYear: 1193 },
    relatedEntities: [
      "ayyubid.state.ayyubid",
      "ayyubid.city.jerusalem",
      "ayyubid.city.damascus",
      "ayyubid.city.cairo",
      "ayyubid.battle.hattin",
      "ayyubid.battle.arsuf",
      "ayyubid.event.liberate-jerusalem",
      "ayyubid.figure.nuruddin",
    ],
    unlockables: [
      { kind: "campaign", refId: "ayyubid", label: "حملة صلاح الدين" },
      { kind: "artifact", refId: "ayyubid.artifact.sword-salahuddin", label: "سيف صلاح الدين" },
      { kind: "event", refId: "ayyubid.event.liberate-jerusalem", label: "تحرير القدس" },
    ],
    image: { alt: "صورة رمزية لصلاح الدين الأيوبي", glyph: "🗡️", tone: "from-amber-600/40 to-slate-900" },
    timelinePosition: 1137,
    rarity: "legendary",
    meta: {
      titles: ["الناصر", "السلطان صلاح الدين", "محرّر القدس"],
      tags: ["الحملات الصليبية"],
    },
    bridges: { characterId: "salahuddin", era: "ayyubid" },
  }),

  E({
    id: "ayyubid.figure.nuruddin",
    title: "نور الدين زنكي",
    latin: "Nur ad-Din Zangi",
    type: "figure",
    description:
      "الملك العادل نور الدين محمود بن زنكي، موحّد الشام في مواجهة الصليبيين، ومُعدّ الأرض السياسية والعسكرية التي قام عليها مشروع صلاح الدين.",
    period: { label: "1118 – 1174 م", startYear: 1118, endYear: 1174 },
    relatedEntities: [
      "ayyubid.city.damascus",
      "ayyubid.city.aleppo",
      "ayyubid.figure.salahuddin",
      "ayyubid.state.ayyubid",
    ],
    unlockables: [
      { kind: "campaign", refId: "nuruddin", label: "حملة نور الدين" },
      { kind: "lore", refId: "nuruddin", label: "دمشق الزنكية" },
    ],
    image: { alt: "رمز نور الدين زنكي", glyph: "🕌", tone: "from-emerald-700/40 to-slate-900" },
    timelinePosition: 1118,
    rarity: "epic",
    meta: { titles: ["الملك العادل", "شيخ المجاهدين"] },
    bridges: { storyId: "nuruddin", era: "ayyubid" },
  }),

  E({
    id: "ayyubid.figure.al-adil",
    title: "الملك العادل",
    latin: "Al-Adil I",
    type: "figure",
    description:
      "السلطان سيف الدين أبو بكر بن أيوب، شقيق صلاح الدين وأحد أعمدة الدولة الأيوبية، تولّى السلطنة وأعاد توحيد البيت الأيوبي بعد وفاة أخيه.",
    period: { label: "1145 – 1218 م", startYear: 1145, endYear: 1218 },
    relatedEntities: [
      "ayyubid.state.ayyubid",
      "ayyubid.figure.salahuddin",
      "ayyubid.figure.al-kamil",
      "ayyubid.city.cairo",
      "ayyubid.city.damascus",
    ],
    unlockables: [],
    image: { alt: "رمز الملك العادل", glyph: "⚖️", tone: "from-amber-700/30 to-slate-900" },
    timelinePosition: 1145,
    rarity: "rare",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.figure.al-kamil",
    title: "الملك الكامل",
    latin: "Al-Kamil",
    type: "figure",
    description:
      "السلطان ناصر الدين محمد بن العادل، السلطان الأيوبي الذي ردّ الحملة الصليبية الخامسة عن مصر عند المنصورة، وعقد معاهدة يافا الشهيرة مع فردريك الثاني.",
    period: { label: "1177 – 1238 م", startYear: 1177, endYear: 1238 },
    relatedEntities: [
      "ayyubid.state.ayyubid",
      "ayyubid.figure.al-adil",
      "ayyubid.city.cairo",
      "ayyubid.city.jerusalem",
    ],
    unlockables: [],
    image: { alt: "رمز الملك الكامل", glyph: "👑", tone: "from-amber-600/30 to-slate-900" },
    timelinePosition: 1177,
    rarity: "rare",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.figure.najmuddin-ayyub",
    title: "نجم الدين أيوب",
    latin: "Najm ad-Din Ayyub",
    type: "figure",
    description:
      "والد صلاح الدين، أمير تكريت ثم بعلبك ودمشق في خدمة الزنكيين، مؤسس البيت الأيوبي ورجل السياسة الذي مهّد لابنه طريق السلطان.",
    period: { label: "ت 1173 م", startYear: 1100, endYear: 1173 },
    relatedEntities: ["ayyubid.figure.salahuddin","ayyubid.figure.shirkuh","ayyubid.city.tikrit","ayyubid.city.damascus","ayyubid.event.move-to-damascus"],
    unlockables: [],
    image: { alt: "نجم الدين أيوب", glyph: "🪶", tone: "from-amber-700/30 to-slate-900" },
    timelinePosition: 1132,
    rarity: "epic",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.figure.shirkuh",
    title: "أسد الدين شيركوه",
    latin: "Asad ad-Din Shirkuh",
    type: "figure",
    description:
      "عمّ صلاح الدين وقائد جيش نور الدين في حملات مصر الثلاث، فاتح القاهرة ووزير الفاطميين قُبيل نهايتهم.",
    period: { label: "ت 1169 م", startYear: 1110, endYear: 1169 },
    relatedEntities: ["ayyubid.figure.salahuddin","ayyubid.figure.nuruddin","ayyubid.city.cairo","ayyubid.event.egypt-campaigns","ayyubid.event.end-fatimid"],
    unlockables: [],
    image: { alt: "أسد الدين شيركوه", glyph: "🦁", tone: "from-stone-700/40 to-slate-900" },
    timelinePosition: 1163,
    rarity: "epic",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.figure.al-muazzam-isa",
    title: "المعظم عيسى",
    latin: "Al-Muazzam Isa",
    type: "figure",
    description:
      "ملك دمشق الأيوبي، عُرف بهدم أسوار القدس خشية استعادتها بيد الصليبيين، وكان عالمًا فقيهًا وفارسًا مقدامًا.",
    period: { label: "1180 – 1227 م", startYear: 1180, endYear: 1227 },
    relatedEntities: ["ayyubid.city.damascus","ayyubid.city.jerusalem","ayyubid.figure.al-adil","ayyubid.landmark.walls-jerusalem"],
    unlockables: [],
    image: { alt: "المعظم عيسى", glyph: "🏛️", tone: "from-amber-700/30 to-slate-900" },
    timelinePosition: 1218,
    rarity: "rare",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.figure.al-ashraf-musa",
    title: "الأشرف موسى",
    latin: "Al-Ashraf Musa",
    type: "figure",
    description:
      "السلطان الأيوبي في الجزيرة الفراتية ودمشق، موحّد جبهة الأيوبيين شرقًا في وجه الخوارزميين والصليبيين.",
    period: { label: "1178 – 1237 م", startYear: 1178, endYear: 1237 },
    relatedEntities: ["ayyubid.figure.al-kamil","ayyubid.figure.al-adil","ayyubid.city.damascus","ayyubid.city.aleppo"],
    unlockables: [],
    image: { alt: "الأشرف موسى", glyph: "⚜️", tone: "from-amber-700/30 to-slate-900" },
    timelinePosition: 1229,
    rarity: "rare",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.figure.as-salih-ayyub",
    title: "الصالح أيوب",
    latin: "As-Salih Ayyub",
    type: "figure",
    description:
      "السلطان نجم الدين أيوب بن الكامل، آخر سلاطين الأيوبيين الأقوياء، استقدم المماليك البحرية وصدّ الحملة الصليبية السابعة عند المنصورة.",
    period: { label: "1205 – 1249 م", startYear: 1205, endYear: 1249 },
    relatedEntities: ["ayyubid.figure.al-kamil","ayyubid.figure.turanshah","ayyubid.figure.shajar-al-durr","ayyubid.battle.mansurah","ayyubid.event.rise-as-salih"],
    unlockables: [],
    image: { alt: "الصالح أيوب", glyph: "🗝️", tone: "from-slate-700/40 to-slate-900" },
    timelinePosition: 1240,
    rarity: "epic",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.figure.turanshah",
    title: "توران شاه",
    latin: "Turanshah",
    type: "figure",
    description:
      "السلطان المعظم توران شاه بن الصالح أيوب، انتصر على لويس التاسع في المنصورة ثم اغتيل على يد المماليك لتنتهي معه الأسرة الأيوبية في مصر.",
    period: { label: "ت 1250 م", startYear: 1228, endYear: 1250 },
    relatedEntities: ["ayyubid.figure.as-salih-ayyub","ayyubid.figure.shajar-al-durr","ayyubid.battle.mansurah","ayyubid.event.end-ayyubid"],
    unlockables: [],
    image: { alt: "توران شاه", glyph: "🏹", tone: "from-rose-800/40 to-slate-900" },
    timelinePosition: 1250,
    rarity: "rare",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.figure.shajar-al-durr",
    title: "شجر الدر",
    latin: "Shajar al-Durr",
    type: "figure",
    description:
      "زوجة الصالح أيوب، أخفت موت زوجها لتدير المعركة ضد الصليبيين، ثم تولّت السلطنة لتكون أوّل سلطانة في تاريخ مصر الإسلامي.",
    period: { label: "ت 1257 م", startYear: 1220, endYear: 1257 },
    relatedEntities: ["ayyubid.figure.as-salih-ayyub","ayyubid.figure.turanshah","ayyubid.battle.mansurah","ayyubid.event.shajar-rule","ayyubid.event.end-ayyubid"],
    unlockables: [],
    image: { alt: "شجر الدر", glyph: "💎", tone: "from-fuchsia-800/30 to-slate-900" },
    timelinePosition: 1250,
    rarity: "legendary",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.figure.richard-lionheart",
    title: "ريتشارد قلب الأسد",
    latin: "Richard the Lionheart",
    type: "figure",
    description:
      "ملك إنجلترا وقائد الحملة الصليبية الثالثة، خصم صلاح الدين في معارك أرسوف ويافا، وشريكه في صلح الرملة عام 1192م.",
    period: { label: "1157 – 1199 م", startYear: 1157, endYear: 1199 },
    relatedEntities: ["ayyubid.figure.salahuddin","ayyubid.battle.arsuf","ayyubid.battle.jaffa","ayyubid.battle.acre-siege","ayyubid.event.third-crusade","ayyubid.event.ramla-treaty"],
    unlockables: [],
    image: { alt: "ريتشارد قلب الأسد", glyph: "🦁", tone: "from-rose-900/40 to-slate-900" },
    timelinePosition: 1191,
    rarity: "epic",
  }),

  // ---------- CITIES ----------
  E({
    id: "ayyubid.city.jerusalem",
    title: "القدس",
    latin: "Jerusalem",
    type: "city",
    description:
      "أولى القبلتين وثالث الحرمين، حرّرها عمر بن الخطاب صلحًا ثم استعادها صلاح الدين سنة 583هـ بعد معركة حطين.",
    period: { label: "حاضرة منذ القدم", startYear: 638, endYear: 2025 },
    relatedEntities: [
      "ayyubid.landmark.al-aqsa",
      "ayyubid.battle.hattin",
      "ayyubid.figure.salahuddin",
      "ayyubid.event.liberate-jerusalem",
    ],
    unlockables: [],
    image: { alt: "أسوار القدس", glyph: "🕍", tone: "from-amber-700/30 to-slate-900" },
    timelinePosition: 1187,
    rarity: "legendary",
    meta: { region: "الشام", landmarks: ["المسجد الأقصى", "قبة الصخرة"], tags: ["الفتح العمري", "الحملات الصليبية"] },
    bridges: { cityId: "jerusalem", regionId: "shaam" },
  }),

  E({
    id: "ayyubid.city.damascus",
    title: "دمشق",
    latin: "Damascus",
    type: "city",
    description:
      "حاضرة الشام الكبرى وعاصمة الدولة الأموية، صارت في زمن نور الدين والأيوبيين قلب الجهاد ومركز توحيد المسلمين.",
    period: { label: "حاضرة منذ القدم", startYear: 661, endYear: 2025 },
    relatedEntities: [
      "ayyubid.landmark.umayyad-mosque",
      "ayyubid.figure.nuruddin",
      "ayyubid.figure.salahuddin",
      "ayyubid.state.ayyubid",
    ],
    unlockables: [],
    image: { alt: "مآذن دمشق", glyph: "🕌", tone: "from-emerald-700/30 to-slate-900" },
    timelinePosition: 1154,
    rarity: "epic",
    meta: { region: "الشام", landmarks: ["المسجد الأموي"], tags: ["الدولة الأموية", "الدولة الأيوبية"] },
    bridges: { cityId: "damascus", regionId: "shaam" },
  }),

  E({
    id: "ayyubid.city.cairo",
    title: "القاهرة",
    latin: "Cairo",
    type: "city",
    description:
      "قاهرة المعزّ، عاصمة الفاطميين ثم الأيوبيين، ومنارة العلم بجامع الأزهر، حصّنها صلاح الدين بقلعته الشهيرة على المقطّم.",
    period: { label: "تأسست 969م", startYear: 969, endYear: 2025 },
    relatedEntities: [
      "ayyubid.landmark.al-azhar",
      "ayyubid.landmark.citadel-salahuddin",
      "ayyubid.figure.salahuddin",
      "ayyubid.state.ayyubid",
      "ayyubid.event.end-fatimid",
    ],
    unlockables: [],
    image: { alt: "قلعة القاهرة", glyph: "🏯", tone: "from-amber-700/30 to-slate-900" },
    timelinePosition: 1171,
    rarity: "legendary",
    meta: { region: "مصر", landmarks: ["الأزهر", "قلعة صلاح الدين"], tags: ["الدولة الفاطمية", "الدولة الأيوبية"] },
    bridges: { cityId: "cairo", regionId: "egypt" },
  }),

  E({
    id: "ayyubid.city.aleppo",
    title: "حلب",
    latin: "Aleppo",
    type: "city",
    description:
      "مدينة الشمال الشاميّ وقلعتها الشامخة، قاعدةُ الزنكيين ثم الأيوبيين في مواجهة الصليبيين والممالك الصغيرة.",
    period: { label: "حاضرة منذ القدم", startYear: 1128, endYear: 2025 },
    relatedEntities: [
      "ayyubid.figure.nuruddin",
      "ayyubid.state.ayyubid",
    ],
    unlockables: [],
    image: { alt: "قلعة حلب", glyph: "🏰", tone: "from-stone-700/40 to-slate-900" },
    timelinePosition: 1146,
    rarity: "epic",
    meta: { region: "الشام", landmarks: ["قلعة حلب"], tags: ["الدولة الزنكية", "الدولة الأيوبية"] },
    bridges: { regionId: "shaam" },
  }),

  E({
    id: "ayyubid.city.karak",
    title: "الكرك",
    latin: "Karak",
    type: "city",
    description:
      "قلعةٌ صليبية حصينة شرق الأردن سيطر منها أرناط على طرق الحج، فحاصرها صلاح الدين مرّتين قبل أن تسقط في يد الأيوبيين بعد حطين.",
    period: { label: "حاضرة منذ القرن 12 م", startYear: 1142, endYear: 2025 },
    relatedEntities: ["ayyubid.landmark.castle-karak","ayyubid.battle.karak-siege","ayyubid.figure.salahuddin","ayyubid.state.ayyubid"],
    unlockables: [],
    image: { alt: "قلعة الكرك", glyph: "🏰", tone: "from-stone-700/40 to-slate-900" },
    timelinePosition: 1183,
    rarity: "epic",
    meta: { region: "الشام" },
    bridges: { regionId: "shaam" },
  }),

  E({
    id: "ayyubid.city.acre",
    title: "عكا",
    latin: "Acre",
    type: "city",
    description:
      "ميناءُ الشام الكبير على المتوسط، حرّرها صلاح الدين بعد حطين ثم استعادها الصليبيون عام 1191م بعد حصارٍ مرير.",
    period: { label: "حاضرة منذ القدم", startYear: 1104, endYear: 2025 },
    relatedEntities: ["ayyubid.battle.acre-siege","ayyubid.landmark.castle-acre","ayyubid.figure.salahuddin","ayyubid.event.third-crusade","ayyubid.state.ayyubid"],
    unlockables: [],
    image: { alt: "ميناء عكا", glyph: "⚓", tone: "from-sky-800/40 to-slate-900" },
    timelinePosition: 1187,
    rarity: "epic",
    meta: { region: "الشام" },
    bridges: { regionId: "shaam" },
  }),

  E({
    id: "ayyubid.city.ascalon",
    title: "عسقلان",
    latin: "Ascalon",
    type: "city",
    description:
      "ثغرٌ فلسطينيّ على المتوسط، استعادها صلاح الدين بعد حطين وهدم أسوارها بنفسه لمنع عودة الصليبيين إليها.",
    period: { label: "ثغر إسلامي", startYear: 1153, endYear: 2025 },
    relatedEntities: ["ayyubid.figure.salahuddin","ayyubid.battle.ramla","ayyubid.event.ramla-treaty","ayyubid.state.ayyubid"],
    unlockables: [],
    image: { alt: "أسوار عسقلان", glyph: "🛡️", tone: "from-stone-700/40 to-slate-900" },
    timelinePosition: 1187,
    rarity: "rare",
    meta: { region: "الشام" },
    bridges: { regionId: "shaam" },
  }),

  E({
    id: "ayyubid.city.damietta",
    title: "دمياط",
    latin: "Damietta",
    type: "city",
    description:
      "مدينةٌ ساحلية مصرية على الفرع الشرقي للنيل، كانت بوابة الحملات الصليبية الخامسة والسابعة على مصر.",
    period: { label: "ثغر مصر", startYear: 1200, endYear: 2025 },
    relatedEntities: ["ayyubid.battle.damietta-campaign","ayyubid.battle.mansurah","ayyubid.figure.al-kamil","ayyubid.figure.as-salih-ayyub","ayyubid.state.ayyubid"],
    unlockables: [],
    image: { alt: "ثغر دمياط", glyph: "⛵", tone: "from-sky-800/40 to-slate-900" },
    timelinePosition: 1219,
    rarity: "epic",
    meta: { region: "مصر" },
    bridges: { regionId: "egypt" },
  }),

  E({
    id: "ayyubid.city.alexandria",
    title: "الإسكندرية",
    latin: "Alexandria",
    type: "city",
    description:
      "ثغرُ مصر الأكبر على المتوسط ومركز التجارة والعلم، حصّنها صلاح الدين وردّ عنها هجمات الأساطيل الصليبية.",
    period: { label: "حاضرة منذ القدم", startYear: 1160, endYear: 2025 },
    relatedEntities: ["ayyubid.figure.salahuddin","ayyubid.figure.shirkuh","ayyubid.event.egypt-campaigns","ayyubid.state.ayyubid"],
    unlockables: [],
    image: { alt: "مرفأ الإسكندرية", glyph: "🏛️", tone: "from-sky-700/40 to-slate-900" },
    timelinePosition: 1167,
    rarity: "epic",
    meta: { region: "مصر" },
    bridges: { regionId: "egypt" },
  }),

  E({
    id: "ayyubid.city.tikrit",
    title: "تكريت",
    latin: "Tikrit",
    type: "city",
    description:
      "بلدةٌ على نهر دجلة شمالي بغداد، حكمها نجم الدين أيوب وشيركوه، وفيها وُلد صلاح الدين سنة 1137م.",
    period: { label: "حاضرة منذ القدم", startYear: 1130, endYear: 2025 },
    relatedEntities: ["ayyubid.figure.salahuddin","ayyubid.figure.najmuddin-ayyub","ayyubid.figure.shirkuh","ayyubid.event.salahuddin-birth"],
    unlockables: [],
    image: { alt: "تكريت على دجلة", glyph: "🏞️", tone: "from-amber-800/30 to-slate-900" },
    timelinePosition: 1137,
    rarity: "rare",
    meta: { region: "العراق" },
  }),

  // ---------- BATTLES ----------
  E({
    id: "ayyubid.battle.hattin",
    title: "معركة حطين",
    latin: "Battle of Hattin",
    type: "battle",
    description:
      "معركةٌ فاصلة في الجليل أوقع فيها صلاح الدين بجيش مملكة بيت المقدس الصليبية بكاملها، فانفتح بها طريق تحرير القدس.",
    period: { label: "4 يوليو 1187 م", startYear: 1187, endYear: 1187 },
    relatedEntities: [
      "ayyubid.figure.salahuddin",
      "ayyubid.city.jerusalem",
      "ayyubid.state.ayyubid",
      "ayyubid.event.liberate-jerusalem",
    ],
    unlockables: [
      { kind: "event", refId: "ayyubid.event.liberate-jerusalem", label: "تحرير القدس" },
      { kind: "artifact", refId: "ayyubid.artifact.sword-salahuddin", label: "سيف صلاح الدين" },
      { kind: "achievement", refId: "ayyubid.achievement.liberator", label: "إنجاز محرّر القدس" },
    ],
    image: { alt: "ساحة حطين", glyph: "⚔️", tone: "from-rose-800/40 to-slate-900" },
    timelinePosition: 1187,
    rarity: "legendary",
    meta: {
      commanders: ["صلاح الدين الأيوبي"],
      result: "نصرٌ مؤزَّر للمسلمين",
      tags: ["الحملات الصليبية"],
    },
    bridges: { battleId: "hattin", storyId: "hattin", era: "ayyubid" },
  }),

  E({
    id: "ayyubid.battle.arsuf",
    title: "معركة أرسوف",
    latin: "Battle of Arsuf",
    type: "battle",
    description:
      "اشتباكٌ كبير على الساحل الفلسطيني بين صلاح الدين وريتشارد قلب الأسد ضمن الحملة الصليبية الثالثة، أعاد تشكيل موازين الصراع دون أن يقلب ميزان السلطة.",
    period: { label: "7 سبتمبر 1191 م", startYear: 1191, endYear: 1191 },
    relatedEntities: [
      "ayyubid.figure.salahuddin",
      "ayyubid.state.ayyubid",
    ],
    unlockables: [],
    image: { alt: "ساحل أرسوف", glyph: "🛡️", tone: "from-sky-800/40 to-slate-900" },
    timelinePosition: 1191,
    rarity: "epic",
    meta: {
      commanders: ["صلاح الدين الأيوبي", "ريتشارد قلب الأسد"],
      tags: ["الحملات الصليبية"],
    },
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.battle.ramla",
    title: "معركة الرملة",
    type: "battle",
    description:
      "اشتباكٌ مبكر بين صلاح الدين ومملكة بيت المقدس قرب الرملة، أظهر صعوبة مواجهة الفرسان الصليبيين في السهل الساحلي.",
    period: { label: "1177 م", startYear: 1177, endYear: 1177 },
    relatedEntities: ["ayyubid.figure.salahuddin","ayyubid.city.ascalon","ayyubid.state.ayyubid"],
    unlockables: [],
    image: { alt: "سهل الرملة", glyph: "⚔️", tone: "from-rose-800/30 to-slate-900" },
    timelinePosition: 1177,
    rarity: "rare",
    meta: { tags: ["الحملات الصليبية"] },
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.battle.acre-siege",
    title: "حصار عكا",
    type: "battle",
    description:
      "حصارٌ صليبيٌّ طويل لعكا (1189–1191م) شاركت فيه أساطيل أوروبا، انتهى بسقوط المدينة في يد الصليبيين رغم محاولات صلاح الدين فك الحصار.",
    period: { label: "1189 – 1191 م", startYear: 1189, endYear: 1191 },
    relatedEntities: ["ayyubid.figure.salahuddin","ayyubid.figure.richard-lionheart","ayyubid.city.acre","ayyubid.event.third-crusade","ayyubid.state.ayyubid"],
    unlockables: [],
    image: { alt: "حصار عكا", glyph: "🏹", tone: "from-sky-900/40 to-slate-900" },
    timelinePosition: 1189,
    rarity: "epic",
    meta: { tags: ["الحملات الصليبية"] },
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.battle.jaffa",
    title: "معركة يافا",
    type: "battle",
    description:
      "معركة ميدانية بين صلاح الدين وريتشارد قلب الأسد عند يافا، مهّدت لصلح الرملة وأنهت فعليًا الحملة الصليبية الثالثة.",
    period: { label: "5 أغسطس 1192 م", startYear: 1192, endYear: 1192 },
    relatedEntities: ["ayyubid.figure.salahuddin","ayyubid.figure.richard-lionheart","ayyubid.event.ramla-treaty","ayyubid.event.third-crusade"],
    unlockables: [],
    image: { alt: "ساحل يافا", glyph: "⚔️", tone: "from-rose-800/40 to-slate-900" },
    timelinePosition: 1192,
    rarity: "epic",
    meta: { tags: ["الحملات الصليبية"] },
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.battle.karak-siege",
    title: "حصار الكرك",
    type: "battle",
    description:
      "حصارُ صلاح الدين لقلعة الكرك مرتين (1183 و 1184م) لتأديب أرناط بعد اعتداءاته على قوافل الحجاج.",
    period: { label: "1183 – 1184 م", startYear: 1183, endYear: 1184 },
    relatedEntities: ["ayyubid.figure.salahuddin","ayyubid.city.karak","ayyubid.landmark.castle-karak","ayyubid.state.ayyubid"],
    unlockables: [],
    image: { alt: "حصار الكرك", glyph: "🛡️", tone: "from-stone-800/40 to-slate-900" },
    timelinePosition: 1183,
    rarity: "rare",
    meta: { tags: ["الحملات الصليبية"] },
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.battle.damietta-campaign",
    title: "حملة دمياط",
    type: "battle",
    description:
      "الحملة الصليبية الخامسة على مصر (1217–1221م)، احتلّ فيها الصليبيون دمياط قبل أن يهزمهم الملك الكامل ويستردّها.",
    period: { label: "1217 – 1221 م", startYear: 1217, endYear: 1221 },
    relatedEntities: ["ayyubid.figure.al-kamil","ayyubid.city.damietta","ayyubid.state.ayyubid"],
    unlockables: [],
    image: { alt: "ثغر دمياط", glyph: "⚓", tone: "from-sky-900/40 to-slate-900" },
    timelinePosition: 1219,
    rarity: "epic",
    meta: { tags: ["الحملات الصليبية"] },
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.battle.mansurah",
    title: "معركة المنصورة",
    type: "battle",
    description:
      "هزيمةٌ كبرى للويس التاسع وحملته الصليبية السابعة على مصر، انتصر فيها الصالح أيوب وتوران شاه والمماليك البحرية.",
    period: { label: "فبراير 1250 م", startYear: 1250, endYear: 1250 },
    relatedEntities: ["ayyubid.figure.as-salih-ayyub","ayyubid.figure.turanshah","ayyubid.figure.shajar-al-durr","ayyubid.city.damietta","ayyubid.event.end-ayyubid"],
    unlockables: [],
    image: { alt: "ميدان المنصورة", glyph: "🗡️", tone: "from-emerald-800/40 to-slate-900" },
    timelinePosition: 1250,
    rarity: "legendary",
    meta: { tags: ["الحملات الصليبية"] },
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.battle.gaza",
    title: "معركة غزة",
    type: "battle",
    description:
      "معركةٌ في جنوب فلسطين بين الأيوبيين وحلفائهم الخوارزميين من جهة والصليبيين من جهة أخرى، أعادت السيطرة الإسلامية على القدس عام 1244م.",
    period: { label: "17 أكتوبر 1244 م", startYear: 1244, endYear: 1244 },
    relatedEntities: ["ayyubid.figure.as-salih-ayyub","ayyubid.city.jerusalem","ayyubid.state.ayyubid"],
    unlockables: [],
    image: { alt: "ميدان غزة", glyph: "⚔️", tone: "from-rose-800/40 to-slate-900" },
    timelinePosition: 1244,
    rarity: "epic",
    meta: { tags: ["الحملات الصليبية"] },
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.battle.bait-nuba",
    title: "معركة بيت نوبا",
    type: "battle",
    description:
      "مواجهةٌ في تلال بيت نوبا قرب القدس بين جيش صلاح الدين والصليبيين بقيادة ريتشارد، أوقفت زحفهم نحو المدينة المقدسة.",
    period: { label: "1192 م", startYear: 1192, endYear: 1192 },
    relatedEntities: ["ayyubid.figure.salahuddin","ayyubid.figure.richard-lionheart","ayyubid.city.jerusalem","ayyubid.event.third-crusade"],
    unlockables: [],
    image: { alt: "تلال بيت نوبا", glyph: "🛡️", tone: "from-emerald-800/30 to-slate-900" },
    timelinePosition: 1192,
    rarity: "rare",
    meta: { tags: ["الحملات الصليبية"] },
    bridges: { era: "ayyubid" },
  }),

  // ---------- EVENTS ----------
  E({
    id: "ayyubid.event.end-fatimid",
    title: "إنهاء الدولة الفاطمية",
    type: "event",
    description:
      "أعلن صلاح الدين الخطبة للخليفة العباسي في القاهرة عام 1171م، فطُويت صفحة الدولة الفاطمية وقامت الدولة الأيوبية السنّيّة على أنقاضها.",
    period: { label: "1171 م", startYear: 1171, endYear: 1171 },
    relatedEntities: [
      "ayyubid.state.ayyubid",
      "ayyubid.figure.salahuddin",
      "ayyubid.city.cairo",
    ],
    unlockables: [],
    image: { alt: "إعلان الدولة الأيوبية", glyph: "📜", tone: "from-amber-700/30 to-slate-900" },
    timelinePosition: 1171,
    rarity: "epic",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.event.liberate-jerusalem",
    title: "تحرير القدس",
    type: "event",
    description:
      "في رجب 583هـ / أكتوبر 1187م دخل صلاح الدين القدس صلحًا، فأُعيد الأذان إلى المسجد الأقصى بعد 88 عامًا من الاحتلال الصليبي.",
    period: { label: "2 أكتوبر 1187 م", startYear: 1187, endYear: 1187 },
    relatedEntities: [
      "ayyubid.figure.salahuddin",
      "ayyubid.battle.hattin",
      "ayyubid.city.jerusalem",
      "ayyubid.state.ayyubid",
      "ayyubid.landmark.al-aqsa",
    ],
    unlockables: [
      { kind: "achievement", refId: "ayyubid.achievement.liberator", label: "لقب محرّر القدس" },
      { kind: "artifact", refId: "ayyubid.artifact.victory-manuscript", label: "مخطوط النصر" },
      { kind: "card", refId: "ayyubid.city.jerusalem", label: "بطاقة القدس التاريخية" },
    ],
    image: { alt: "دخول صلاح الدين القدس", glyph: "🕊️", tone: "from-emerald-700/40 to-slate-900" },
    timelinePosition: 1187,
    rarity: "legendary",
    bridges: { storyId: "jerusalem-liberation", era: "ayyubid" },
  }),

  E({
    id: "ayyubid.event.salahuddin-birth",
    title: "مولد صلاح الدين",
    type: "event",
    description:
      "وُلد صلاح الدين يوسف بن أيوب في قلعة تكريت سنة 532هـ / 1137م في ليلة رحيل أسرته منها.",
    period: { label: "1137 م", startYear: 1137, endYear: 1137 },
    relatedEntities: ["ayyubid.figure.salahuddin","ayyubid.figure.najmuddin-ayyub","ayyubid.city.tikrit"],
    unlockables: [],
    image: { alt: "مولد صلاح الدين", glyph: "🌙", tone: "from-amber-700/30 to-slate-900" },
    timelinePosition: 1137,
    rarity: "rare",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.event.move-to-damascus",
    title: "انتقال الأسرة إلى دمشق",
    type: "event",
    description:
      "انتقلت أسرة أيوب من تكريت إلى الموصل ثم بعلبك فدمشق في خدمة الزنكيين، فنشأ صلاح الدين في كنف نور الدين.",
    period: { label: "نحو 1140 م", startYear: 1140, endYear: 1154 },
    relatedEntities: ["ayyubid.figure.najmuddin-ayyub","ayyubid.figure.salahuddin","ayyubid.figure.nuruddin","ayyubid.city.damascus"],
    unlockables: [],
    image: { alt: "رحلة الأسرة", glyph: "🐪", tone: "from-amber-700/30 to-slate-900" },
    timelinePosition: 1140,
    rarity: "rare",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.event.serve-nuruddin",
    title: "خدمة نور الدين زنكي",
    type: "event",
    description:
      "خدم صلاح الدين وأبوه وعمّه في بلاط نور الدين زنكي بدمشق، فتدرّب على فنون الحرب والسياسة في معسكر الجهاد.",
    period: { label: "1154 – 1163 م", startYear: 1154, endYear: 1163 },
    relatedEntities: ["ayyubid.figure.salahuddin","ayyubid.figure.nuruddin","ayyubid.figure.najmuddin-ayyub","ayyubid.city.damascus"],
    unlockables: [],
    image: { alt: "بلاط نور الدين", glyph: "📜", tone: "from-emerald-800/30 to-slate-900" },
    timelinePosition: 1154,
    rarity: "rare",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.event.egypt-campaigns",
    title: "الحملة إلى مصر",
    type: "event",
    description:
      "الحملات الثلاث التي قادها أسد الدين شيركوه ومعه صلاح الدين بأمر نور الدين، وانتهت بدخول القاهرة وتولّي شيركوه الوزارة.",
    period: { label: "1164 – 1169 م", startYear: 1164, endYear: 1169 },
    relatedEntities: ["ayyubid.figure.shirkuh","ayyubid.figure.salahuddin","ayyubid.figure.nuruddin","ayyubid.city.cairo","ayyubid.city.alexandria","ayyubid.event.end-fatimid"],
    unlockables: [],
    image: { alt: "حملة شيركوه", glyph: "🐫", tone: "from-amber-800/30 to-slate-900" },
    timelinePosition: 1164,
    rarity: "epic",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.event.found-ayyubid",
    title: "تأسيس الدولة الأيوبية",
    type: "event",
    description:
      "أعلن صلاح الدين قيام الدولة الأيوبية في مصر عام 1171م، فبدأت مرحلة جديدة من توحيد الجبهة الإسلامية ضد الصليبيين.",
    period: { label: "1171 م", startYear: 1171, endYear: 1171 },
    relatedEntities: ["ayyubid.state.ayyubid","ayyubid.figure.salahuddin","ayyubid.event.end-fatimid","ayyubid.city.cairo"],
    unlockables: [],
    image: { alt: "تأسيس الدولة", glyph: "🏛️", tone: "from-amber-700/40 to-slate-900" },
    timelinePosition: 1171,
    rarity: "legendary",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.event.unify-egypt-sham",
    title: "توحيد مصر والشام",
    type: "event",
    description:
      "بعد وفاة نور الدين ضمّ صلاح الدين دمشق وحلب والجزيرة إلى مصر، فاكتمل المشروع الأيوبي قبل المواجهة الكبرى مع الصليبيين.",
    period: { label: "1174 – 1183 م", startYear: 1174, endYear: 1183 },
    relatedEntities: ["ayyubid.figure.salahuddin","ayyubid.city.damascus","ayyubid.city.aleppo","ayyubid.city.cairo","ayyubid.state.ayyubid"],
    unlockables: [],
    image: { alt: "توحيد الجبهة", glyph: "🤝", tone: "from-emerald-700/30 to-slate-900" },
    timelinePosition: 1174,
    rarity: "epic",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.event.third-crusade",
    title: "الحملة الصليبية الثالثة",
    type: "event",
    description:
      "حملةُ ملوك أوروبا الثلاثة (ريتشارد، فيليب، فردريك) لاستعادة القدس بعد حطين، انتهت بصلح الرملة دون تحقيق هدفها الأكبر.",
    period: { label: "1189 – 1192 م", startYear: 1189, endYear: 1192 },
    relatedEntities: ["ayyubid.figure.salahuddin","ayyubid.figure.richard-lionheart","ayyubid.battle.arsuf","ayyubid.battle.acre-siege","ayyubid.battle.jaffa","ayyubid.battle.bait-nuba","ayyubid.event.ramla-treaty"],
    unlockables: [],
    image: { alt: "الحملة الثالثة", glyph: "✝️", tone: "from-rose-900/40 to-slate-900" },
    timelinePosition: 1189,
    rarity: "legendary",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.event.ramla-treaty",
    title: "صلح الرملة",
    type: "event",
    description:
      "معاهدة هدنة بين صلاح الدين وريتشارد قلب الأسد سنة 1192م، أبقت القدس بيد المسلمين مع سماح للحجاج المسيحيين بزيارتها.",
    period: { label: "سبتمبر 1192 م", startYear: 1192, endYear: 1192 },
    relatedEntities: ["ayyubid.figure.salahuddin","ayyubid.figure.richard-lionheart","ayyubid.event.third-crusade","ayyubid.city.jerusalem","ayyubid.city.ascalon"],
    unlockables: [
      { kind: "artifact", refId: "ayyubid.artifact.ramla-manuscript", label: "مخطوطة صلح الرملة" },
    ],
    image: { alt: "وثيقة الصلح", glyph: "🕊️", tone: "from-emerald-700/30 to-slate-900" },
    timelinePosition: 1192,
    rarity: "epic",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.event.salahuddin-death",
    title: "وفاة صلاح الدين",
    type: "event",
    description:
      "تُوفّي صلاح الدين في دمشق في 27 صفر 589هـ / 4 مارس 1193م، ودُفن بجوار الجامع الأموي، فطُويت معه صفحةُ القائد المحرر.",
    period: { label: "4 مارس 1193 م", startYear: 1193, endYear: 1193 },
    relatedEntities: ["ayyubid.figure.salahuddin","ayyubid.city.damascus","ayyubid.landmark.umayyad-mosque","ayyubid.figure.al-adil"],
    unlockables: [],
    image: { alt: "وفاة السلطان", glyph: "🕯️", tone: "from-slate-700/40 to-slate-900" },
    timelinePosition: 1193,
    rarity: "legendary",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.event.rise-as-salih",
    title: "صعود الصالح أيوب",
    type: "event",
    description:
      "تولّى الصالح نجم الدين أيوب سلطنة مصر سنة 1240م، فأعاد للأسرة الأيوبية هيبتها بتجنيد المماليك البحرية.",
    period: { label: "1240 م", startYear: 1240, endYear: 1240 },
    relatedEntities: ["ayyubid.figure.as-salih-ayyub","ayyubid.figure.shajar-al-durr","ayyubid.city.cairo","ayyubid.state.ayyubid"],
    unlockables: [],
    image: { alt: "صعود الصالح أيوب", glyph: "🗝️", tone: "from-amber-700/30 to-slate-900" },
    timelinePosition: 1240,
    rarity: "epic",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.event.shajar-rule",
    title: "تولي شجر الدر",
    type: "event",
    description:
      "بعد مقتل توران شاه بايع المماليك شجر الدر سلطانةً على مصر سنة 1250م، فكانت أوّل امرأة تحكم في مصر الإسلامية.",
    period: { label: "1250 م", startYear: 1250, endYear: 1250 },
    relatedEntities: ["ayyubid.figure.shajar-al-durr","ayyubid.figure.turanshah","ayyubid.battle.mansurah","ayyubid.event.end-ayyubid"],
    unlockables: [],
    image: { alt: "بيعة شجر الدر", glyph: "💎", tone: "from-fuchsia-800/30 to-slate-900" },
    timelinePosition: 1250,
    rarity: "legendary",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.event.end-ayyubid",
    title: "نهاية الدولة الأيوبية",
    type: "event",
    description:
      "بمقتل توران شاه وتولّي شجر الدر آلت السلطة إلى المماليك سنة 1250م، فطُويت صفحة الدولة الأيوبية في مصر بعد قرنٍ من قيامها.",
    period: { label: "1250 م", startYear: 1250, endYear: 1250 },
    relatedEntities: ["ayyubid.state.ayyubid","ayyubid.figure.turanshah","ayyubid.figure.shajar-al-durr","ayyubid.event.shajar-rule"],
    unlockables: [],
    image: { alt: "نهاية الأيوبيين", glyph: "📕", tone: "from-slate-700/40 to-slate-900" },
    timelinePosition: 1250,
    rarity: "legendary",
    bridges: { era: "ayyubid" },
  }),

  // ---------- LANDMARKS ----------
  E({
    id: "ayyubid.landmark.al-aqsa",
    title: "المسجد الأقصى",
    type: "landmark",
    description:
      "أولى القبلتين وثالث الحرمين، مسرى النبي ﷺ وموضع الإسراء، عاد إلى المسلمين بتحرير صلاح الدين للقدس.",
    period: { label: "أُسّس قديمًا", startYear: 638, endYear: 2025 },
    relatedEntities: [
      "ayyubid.city.jerusalem",
      "ayyubid.figure.salahuddin",
      "ayyubid.event.liberate-jerusalem",
    ],
    unlockables: [],
    image: { alt: "قبة المسجد الأقصى", glyph: "🕌", tone: "from-emerald-700/40 to-slate-900" },
    timelinePosition: 638,
    rarity: "legendary",
    meta: { city: "القدس", tags: ["الفتح العمري", "الحملات الصليبية"] },
  }),

  E({
    id: "ayyubid.landmark.citadel-salahuddin",
    title: "قلعة صلاح الدين",
    type: "landmark",
    description:
      "قلعةٌ شامخة على جبل المقطّم بناها صلاح الدين لتكون مقرّ الحكم وحصنًا منيعًا للقاهرة في وجه الحملات الصليبية.",
    period: { label: "بدأ بناؤها 1176 م", startYear: 1176, endYear: 2025 },
    relatedEntities: [
      "ayyubid.city.cairo",
      "ayyubid.figure.salahuddin",
      "ayyubid.state.ayyubid",
    ],
    unlockables: [],
    image: { alt: "قلعة صلاح الدين بالقاهرة", glyph: "🏯", tone: "from-amber-700/30 to-slate-900" },
    timelinePosition: 1176,
    rarity: "epic",
    meta: { city: "القاهرة" },
  }),

  E({
    id: "ayyubid.landmark.dome-of-rock",
    title: "قبة الصخرة",
    type: "landmark",
    description:
      "أيقونة القدس المعمارية، بناها عبد الملك بن مروان فوق صخرة المسرى، ورمّمها صلاح الدين بعد التحرير.",
    period: { label: "بُنيت 691 م", startYear: 691, endYear: 2025 },
    relatedEntities: ["ayyubid.city.jerusalem","ayyubid.landmark.al-aqsa","ayyubid.event.liberate-jerusalem"],
    unlockables: [],
    image: { alt: "قبة الصخرة", glyph: "🕌", tone: "from-amber-600/40 to-slate-900" },
    timelinePosition: 691,
    rarity: "legendary",
    meta: { city: "القدس" },
  }),

  E({
    id: "ayyubid.landmark.umayyad-mosque",
    title: "المسجد الأموي",
    type: "landmark",
    description:
      "جامع دمشق الكبير، رمز الخلافة الأموية وقلب دمشق الروحي، يضمّ ضريح صلاح الدين في فنائه الشمالي.",
    period: { label: "بُني 715 م", startYear: 715, endYear: 2025 },
    relatedEntities: ["ayyubid.city.damascus","ayyubid.figure.salahuddin","ayyubid.event.salahuddin-death"],
    unlockables: [],
    image: { alt: "صحن المسجد الأموي", glyph: "🕌", tone: "from-emerald-700/40 to-slate-900" },
    timelinePosition: 715,
    rarity: "legendary",
    meta: { city: "دمشق" },
  }),

  E({
    id: "ayyubid.landmark.citadel-damascus",
    title: "قلعة دمشق",
    type: "landmark",
    description:
      "قلعةُ دمشق الحصينة، مقرّ حكم نور الدين ثم الأيوبيين، وأحد أقوى حصون الشام في وجه الحملات الصليبية.",
    period: { label: "وُسِّعت في القرن 12 م", startYear: 1076, endYear: 2025 },
    relatedEntities: ["ayyubid.city.damascus","ayyubid.figure.nuruddin","ayyubid.figure.al-adil"],
    unlockables: [],
    image: { alt: "قلعة دمشق", glyph: "🏯", tone: "from-stone-700/40 to-slate-900" },
    timelinePosition: 1076,
    rarity: "epic",
    meta: { city: "دمشق" },
  }),

  E({
    id: "ayyubid.landmark.citadel-aleppo",
    title: "قلعة حلب",
    type: "landmark",
    description:
      "قلعةٌ شامخة فوق تلٍّ في قلب حلب، أعاد الأيوبيون بناءها وجعلوها رمزًا لقوة الدولة في شمال الشام.",
    period: { label: "وُسِّعت 1213 م", startYear: 1213, endYear: 2025 },
    relatedEntities: ["ayyubid.city.aleppo","ayyubid.figure.nuruddin","ayyubid.state.ayyubid"],
    unlockables: [],
    image: { alt: "قلعة حلب", glyph: "🏰", tone: "from-stone-700/40 to-slate-900" },
    timelinePosition: 1213,
    rarity: "epic",
    meta: { city: "حلب" },
  }),

  E({
    id: "ayyubid.landmark.castle-karak",
    title: "قلعة الكرك",
    type: "landmark",
    description:
      "قلعةٌ صليبية حصينة في جنوب الأردن، حاصرها صلاح الدين مرتين وضمّها الأيوبيون بعد حطين.",
    period: { label: "بُنيت 1142 م", startYear: 1142, endYear: 2025 },
    relatedEntities: ["ayyubid.city.karak","ayyubid.battle.karak-siege","ayyubid.figure.salahuddin"],
    unlockables: [],
    image: { alt: "قلعة الكرك", glyph: "🏰", tone: "from-stone-700/40 to-slate-900" },
    timelinePosition: 1142,
    rarity: "epic",
    meta: { city: "الكرك" },
  }),

  E({
    id: "ayyubid.landmark.madrasa-salahiyya",
    title: "المدرسة الصلاحية",
    type: "landmark",
    description:
      "مدرسةٌ أوقفها صلاح الدين بالقرب من المسجد الأقصى لتعليم الفقه الشافعي، رمز إحياء التعليم السنّي في القدس.",
    period: { label: "أُسّست 1192 م", startYear: 1192, endYear: 2025 },
    relatedEntities: ["ayyubid.city.jerusalem","ayyubid.figure.salahuddin","ayyubid.event.liberate-jerusalem"],
    unlockables: [],
    image: { alt: "المدرسة الصلاحية", glyph: "📚", tone: "from-amber-700/30 to-slate-900" },
    timelinePosition: 1192,
    rarity: "epic",
    meta: { city: "القدس" },
  }),

  E({
    id: "ayyubid.landmark.walls-jerusalem",
    title: "أسوار القدس",
    type: "landmark",
    description:
      "أسوار المدينة المقدسة التي رمّمها صلاح الدين بعد التحرير، ثم هدمها المعظم عيسى خشية عودة الصليبيين إليها.",
    period: { label: "رُمِّمت 1192 م", startYear: 1192, endYear: 1219 },
    relatedEntities: ["ayyubid.city.jerusalem","ayyubid.figure.salahuddin","ayyubid.figure.al-muazzam-isa"],
    unlockables: [],
    image: { alt: "أسوار القدس", glyph: "🧱", tone: "from-stone-700/40 to-slate-900" },
    timelinePosition: 1192,
    rarity: "epic",
    meta: { city: "القدس" },
  }),

  E({
    id: "ayyubid.landmark.castle-acre",
    title: "قلعة عكا",
    type: "landmark",
    description:
      "قلعةُ المدينة الساحلية وثكنتها العسكرية، شاهدةٌ على حصار عكا الكبير في الحملة الصليبية الثالثة.",
    period: { label: "وُسِّعت في القرن 12 م", startYear: 1150, endYear: 2025 },
    relatedEntities: ["ayyubid.city.acre","ayyubid.battle.acre-siege","ayyubid.event.third-crusade"],
    unlockables: [],
    image: { alt: "قلعة عكا", glyph: "🏰", tone: "from-sky-800/30 to-slate-900" },
    timelinePosition: 1150,
    rarity: "rare",
    meta: { city: "عكا" },
  }),

  // ---------- ARTIFACTS ----------
  E({
    id: "ayyubid.artifact.sword-salahuddin",
    title: "سيف صلاح الدين",
    type: "artifact",
    description:
      "سيفٌ أسطوريّ يُنسب إلى السلطان صلاح الدين، رمزٌ للنخوة والفروسية في الذاكرة الإسلامية.",
    period: { label: "القرن 12 م", startYear: 1180, endYear: 1193 },
    relatedEntities: [
      "ayyubid.figure.salahuddin",
      "ayyubid.battle.hattin",
    ],
    unlockables: [
      { kind: "achievement", refId: "ayyubid.achievement.liberator", label: "محرّر القدس" },
    ],
    image: { alt: "سيف صلاح الدين", glyph: "🗡️", tone: "from-amber-600/40 to-slate-900" },
    timelinePosition: 1187,
    rarity: "legendary",
    meta: { unlockRule: "إكمال حملة صلاح الدين" },
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.artifact.victory-manuscript",
    title: "مخطوط النصر",
    type: "artifact",
    description:
      "مخطوطةٌ تُخلِّد دخول صلاح الدين القدس وعودة الأذان إلى الأقصى، تُعرض في خزانة المتحف.",
    period: { label: "القرن 12 م", startYear: 1187, endYear: 1187 },
    relatedEntities: [
      "ayyubid.event.liberate-jerusalem",
      "ayyubid.city.jerusalem",
    ],
    unlockables: [],
    image: { alt: "مخطوط تاريخي", glyph: "📜", tone: "from-amber-700/30 to-slate-900" },
    timelinePosition: 1187,
    rarity: "epic",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.artifact.armor-salahuddin",
    title: "درع صلاح الدين",
    type: "artifact",
    description: "درعٌ زرديّ يُنسب إلى السلطان صلاح الدين، رمزٌ لفروسيته في معارك الجهاد.",
    period: { label: "القرن 12 م", startYear: 1180, endYear: 1193 },
    relatedEntities: ["ayyubid.figure.salahuddin","ayyubid.battle.hattin"],
    unlockables: [],
    image: { alt: "درع الزرد", glyph: "🛡️", tone: "from-stone-700/40 to-slate-900" },
    timelinePosition: 1187,
    rarity: "epic",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.artifact.helmet-ayyubid",
    title: "خوذة أيوبيّة",
    type: "artifact",
    description: "خوذةٌ حديدية بطراز الفارس الأيوبي، تحمل نقوشًا قرآنية على الحافة.",
    period: { label: "القرن 12 م", startYear: 1170, endYear: 1200 },
    relatedEntities: ["ayyubid.state.ayyubid","ayyubid.battle.hattin","ayyubid.battle.arsuf"],
    unlockables: [],
    image: { alt: "خوذة أيوبية", glyph: "⛑️", tone: "from-stone-700/40 to-slate-900" },
    timelinePosition: 1187,
    rarity: "rare",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.artifact.ayyubid-banner",
    title: "راية الدولة الأيوبية",
    type: "artifact",
    description: "رايةٌ صفراء تحمل النسر الأيوبي، رفعها صلاح الدين فوق القدس بعد التحرير.",
    period: { label: "القرن 12 م", startYear: 1171, endYear: 1250 },
    relatedEntities: ["ayyubid.state.ayyubid","ayyubid.figure.salahuddin","ayyubid.event.liberate-jerusalem"],
    unlockables: [],
    image: { alt: "راية النسر الأيوبي", glyph: "🚩", tone: "from-amber-700/40 to-slate-900" },
    timelinePosition: 1171,
    rarity: "legendary",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.artifact.ayyubid-seal",
    title: "ختم الدولة الأيوبية",
    type: "artifact",
    description: "ختمٌ سلطاني نُقش عليه اسم صلاح الدين وألقابه، يُختم به الرسائل والمعاهدات.",
    period: { label: "القرن 12 م", startYear: 1171, endYear: 1193 },
    relatedEntities: ["ayyubid.state.ayyubid","ayyubid.figure.salahuddin","ayyubid.event.ramla-treaty"],
    unlockables: [],
    image: { alt: "ختم سلطاني", glyph: "🔖", tone: "from-amber-700/30 to-slate-900" },
    timelinePosition: 1180,
    rarity: "epic",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.artifact.ayyubid-dinar",
    title: "دينار أيوبي",
    type: "artifact",
    description: "دينارٌ ذهبيّ ضربه صلاح الدين في القاهرة، عليه شهادة التوحيد واسم الخليفة العباسي.",
    period: { label: "القرن 12 م", startYear: 1175, endYear: 1193 },
    relatedEntities: ["ayyubid.state.ayyubid","ayyubid.city.cairo","ayyubid.figure.salahuddin"],
    unlockables: [],
    image: { alt: "دينار ذهبي", glyph: "🪙", tone: "from-amber-600/40 to-slate-900" },
    timelinePosition: 1180,
    rarity: "rare",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.artifact.jerusalem-manuscript",
    title: "مخطوطة تحرير القدس",
    type: "artifact",
    description: "وثيقةٌ تروي تفاصيل دخول صلاح الدين القدس وعفوه عن أهلها، نسخها فقهاء دمشق.",
    period: { label: "القرن 12 م", startYear: 1187, endYear: 1187 },
    relatedEntities: ["ayyubid.event.liberate-jerusalem","ayyubid.figure.salahuddin","ayyubid.city.jerusalem"],
    unlockables: [],
    image: { alt: "مخطوطة التحرير", glyph: "📜", tone: "from-amber-700/40 to-slate-900" },
    timelinePosition: 1187,
    rarity: "epic",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.artifact.ramla-manuscript",
    title: "مخطوطة صلح الرملة",
    type: "artifact",
    description: "وثيقة معاهدة الرملة بين صلاح الدين وريتشارد قلب الأسد، تُحدّد ترتيبات الهدنة وزيارة الحجاج.",
    period: { label: "1192 م", startYear: 1192, endYear: 1192 },
    relatedEntities: ["ayyubid.event.ramla-treaty","ayyubid.figure.salahuddin","ayyubid.figure.richard-lionheart"],
    unlockables: [],
    image: { alt: "وثيقة الصلح", glyph: "📃", tone: "from-emerald-700/30 to-slate-900" },
    timelinePosition: 1192,
    rarity: "epic",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.artifact.nuruddin-letter",
    title: "رسالة نور الدين",
    type: "artifact",
    description: "رسالةٌ من نور الدين زنكي إلى أسد الدين شيركوه بشأن الحملة على مصر، شاهدٌ نادر على لحظة التأسيس.",
    period: { label: "نحو 1164 م", startYear: 1164, endYear: 1169 },
    relatedEntities: ["ayyubid.figure.nuruddin","ayyubid.figure.shirkuh","ayyubid.event.egypt-campaigns"],
    unlockables: [],
    image: { alt: "رسالة قديمة", glyph: "✉️", tone: "from-emerald-700/30 to-slate-900" },
    timelinePosition: 1164,
    rarity: "epic",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.artifact.ayyubid-bow",
    title: "قوس أيوبي",
    type: "artifact",
    description: "قوسٌ مركّب من خشب التوت والقرن، اعتمده الفرسان الأيوبيون في معاركهم على الفرسان الصليبيين.",
    period: { label: "القرن 12 م", startYear: 1170, endYear: 1200 },
    relatedEntities: ["ayyubid.state.ayyubid","ayyubid.battle.arsuf","ayyubid.battle.hattin"],
    unlockables: [],
    image: { alt: "قوس مركّب", glyph: "🏹", tone: "from-amber-800/30 to-slate-900" },
    timelinePosition: 1187,
    rarity: "rare",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.artifact.ayyubid-spear",
    title: "رمح أيوبي",
    type: "artifact",
    description: "رمحٌ طويل بسنانٍ مثلّث، سلاح فرسان الخيل الأيوبيين في المواجهات المفتوحة.",
    period: { label: "القرن 12 م", startYear: 1170, endYear: 1200 },
    relatedEntities: ["ayyubid.state.ayyubid","ayyubid.battle.hattin"],
    unlockables: [],
    image: { alt: "رمح فارس", glyph: "🛡️", tone: "from-stone-700/40 to-slate-900" },
    timelinePosition: 1187,
    rarity: "rare",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.artifact.hattin-map",
    title: "خريطة حطين",
    type: "artifact",
    description: "خريطةٌ تخطيطية لميدان حطين تُبيّن مواقع الجيشين وتحركات صلاح الدين قبل الهجوم الأخير.",
    period: { label: "نسخت لاحقًا", startYear: 1187, endYear: 1300 },
    relatedEntities: ["ayyubid.battle.hattin","ayyubid.figure.salahuddin"],
    unlockables: [],
    image: { alt: "خريطة حطين", glyph: "🗺️", tone: "from-amber-700/30 to-slate-900" },
    timelinePosition: 1187,
    rarity: "epic",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.artifact.jerusalem-key",
    title: "مفتاح القدس الرمزي",
    type: "artifact",
    description: "مفتاحٌ نُقش عليه اسم صلاح الدين، يرمز إلى تسلّم القدس صلحًا من الصليبيين.",
    period: { label: "1187 م", startYear: 1187, endYear: 1187 },
    relatedEntities: ["ayyubid.event.liberate-jerusalem","ayyubid.city.jerusalem","ayyubid.figure.salahuddin"],
    unlockables: [],
    image: { alt: "مفتاح القدس", glyph: "🗝️", tone: "from-amber-600/40 to-slate-900" },
    timelinePosition: 1187,
    rarity: "legendary",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.artifact.fatimid-decree",
    title: "مرسوم إنهاء الدولة الفاطمية",
    type: "artifact",
    description: "مرسومٌ سلطاني يُعلن إعادة الخطبة للعباسيين في القاهرة، وثيقةٌ نادرة على تحوّل المذهب الرسمي لمصر.",
    period: { label: "1171 م", startYear: 1171, endYear: 1171 },
    relatedEntities: ["ayyubid.event.end-fatimid","ayyubid.city.cairo","ayyubid.figure.salahuddin"],
    unlockables: [],
    image: { alt: "مرسوم سلطاني", glyph: "📜", tone: "from-amber-700/30 to-slate-900" },
    timelinePosition: 1171,
    rarity: "legendary",
    bridges: { era: "ayyubid" },
  }),

  E({
    id: "ayyubid.artifact.liberator-medal",
    title: "وسام محرر القدس",
    type: "artifact",
    description: "وسامٌ ذهبي يُمنح للاعب عند إكمال حملة صلاح الدين وحدث تحرير القدس.",
    period: { label: "إنجاز رقمي", startYear: 1187, endYear: 1187 },
    relatedEntities: ["ayyubid.achievement.liberator","ayyubid.event.liberate-jerusalem","ayyubid.figure.salahuddin"],
    unlockables: [
      { kind: "achievement", refId: "ayyubid.achievement.liberator", label: "محرّر القدس" },
    ],
    image: { alt: "وسام محرر القدس", glyph: "🏅", tone: "from-amber-600/50 to-slate-900" },
    timelinePosition: 1187,
    rarity: "legendary",
  }),

  // ---------- ACHIEVEMENT ----------
  E({
    id: "ayyubid.achievement.liberator",
    title: "محرّر القدس",
    type: "achievement",
    description:
      "لقبٌ فخريّ يُمنح لمن يُكمل حملة صلاح الدين الكبرى وحدث تحرير القدس داخل المتحف.",
    period: { label: "إنجاز", startYear: 1187, endYear: 1187 },
    relatedEntities: [
      "ayyubid.figure.salahuddin",
      "ayyubid.event.liberate-jerusalem",
      "ayyubid.battle.hattin",
    ],
    unlockables: [
      { kind: "xp", refId: "xp-500", label: "500 نقطة خبرة" },
      { kind: "frame", refId: "frame-liberator", label: "إطار شخصي خاص" },
      { kind: "badge", refId: "badge-legendary-liberator", label: "وسام أسطوري" },
    ],
    image: { alt: "وسام محرّر القدس", glyph: "🏅", tone: "from-amber-600/50 to-slate-900" },
    timelinePosition: 1187,
    rarity: "legendary",
    meta: {
      unlockRules: [
        "إكمال حملة صلاح الدين",
        "إكمال حدث تحرير القدس",
      ],
    },
  }),

  E({
    id: "ayyubid.achievement.ayyubid-collector",
    title: "جامع آثار الأيوبيين",
    type: "achievement",
    description: "يُمنح عند جمع جميع الآثار والمخطوطات الأيوبية في المتحف.",
    period: { label: "إنجاز", startYear: 1171, endYear: 1250 },
    relatedEntities: ["ayyubid.state.ayyubid","ayyubid.artifact.ayyubid-banner","ayyubid.artifact.ayyubid-dinar","ayyubid.artifact.ayyubid-seal"],
    unlockables: [
      { kind: "xp", refId: "xp-300", label: "300 نقطة خبرة" },
      { kind: "badge", refId: "badge-ayyubid-collector", label: "وسام الجامع الأيوبي" },
    ],
    image: { alt: "وسام الجامع", glyph: "🏺", tone: "from-amber-700/40 to-slate-900" },
    timelinePosition: 1200,
    rarity: "epic",
    meta: { unlockRules: ["جمع كل آثار الحزمة الأيوبية"] },
  }),

  E({
    id: "ayyubid.achievement.ayyubid-historian",
    title: "مؤرخ الدولة الأيوبية",
    type: "achievement",
    description: "يُمنح عند قراءة جميع أحداث وفصول الحقبة الأيوبية وفهم تسلسلها.",
    period: { label: "إنجاز", startYear: 1171, endYear: 1250 },
    relatedEntities: ["ayyubid.state.ayyubid","ayyubid.event.found-ayyubid","ayyubid.event.liberate-jerusalem","ayyubid.event.end-ayyubid"],
    unlockables: [
      { kind: "xp", refId: "xp-400", label: "400 نقطة خبرة" },
      { kind: "title", refId: "title-ayyubid-historian", label: "لقب مؤرخ الأيوبيين" },
    ],
    image: { alt: "وسام المؤرخ", glyph: "📚", tone: "from-emerald-700/40 to-slate-900" },
    timelinePosition: 1200,
    rarity: "epic",
    meta: { unlockRules: ["إكمال كل أحداث الحزمة الأيوبية"] },
  }),

  E({
    id: "ayyubid.achievement.crusades-expert",
    title: "خبير الحملات الصليبية",
    type: "achievement",
    description: "يُمنح عند إكمال كل معارك المواجهة بين الأيوبيين والصليبيين.",
    period: { label: "إنجاز", startYear: 1187, endYear: 1250 },
    relatedEntities: ["ayyubid.battle.hattin","ayyubid.battle.arsuf","ayyubid.battle.jaffa","ayyubid.battle.acre-siege","ayyubid.battle.mansurah","ayyubid.event.third-crusade"],
    unlockables: [
      { kind: "xp", refId: "xp-400", label: "400 نقطة خبرة" },
      { kind: "badge", refId: "badge-crusades-expert", label: "وسام خبير الحملات" },
    ],
    image: { alt: "وسام الحملات", glyph: "🛡️", tone: "from-rose-800/40 to-slate-900" },
    timelinePosition: 1192,
    rarity: "epic",
    meta: { unlockRules: ["إكمال كل معارك الصراع الصليبي"] },
  }),

  E({
    id: "ayyubid.achievement.hattin-master",
    title: "سيد حطين",
    type: "achievement",
    description: "يُمنح عند إكمال فصل حطين وامتحانه بنجاحٍ تام داخل حملة صلاح الدين.",
    period: { label: "إنجاز", startYear: 1187, endYear: 1187 },
    relatedEntities: ["ayyubid.battle.hattin","ayyubid.figure.salahuddin","ayyubid.artifact.hattin-map"],
    unlockables: [
      { kind: "xp", refId: "xp-250", label: "250 نقطة خبرة" },
      { kind: "title", refId: "title-hattin-master", label: "لقب سيد حطين" },
    ],
    image: { alt: "وسام حطين", glyph: "⚔️", tone: "from-amber-700/40 to-slate-900" },
    timelinePosition: 1187,
    rarity: "epic",
    meta: { unlockRules: ["إكمال فصل حطين بامتحانه"] },
  }),

  // ---------- FUTURE CAMPAIGN PLACEHOLDERS (locked) ----------
  E({
    id: "ayyubid.event.future-nuruddin-campaign",
    title: "حملة نور الدين زنكي",
    type: "event",
    description: "حملةٌ قادمة تستعرض مشروع نور الدين في توحيد الشام وتمهيد الطريق لصلاح الدين. (قريبًا)",
    period: { label: "1146 – 1174 م", startYear: 1146, endYear: 1174 },
    relatedEntities: ["ayyubid.figure.nuruddin","ayyubid.city.damascus","ayyubid.city.aleppo"],
    unlockables: [],
    image: { alt: "حملة نور الدين", glyph: "🕌", tone: "from-emerald-800/40 to-slate-900" },
    timelinePosition: 1146,
    rarity: "legendary",
    meta: { locked: true, kind: "campaign-placeholder" },
  }),

  E({
    id: "ayyubid.event.future-fall-fatimid",
    title: "سقوط الدولة الفاطمية",
    type: "event",
    description: "حملةٌ قادمة تستعرض نهاية الخلافة الفاطمية في مصر وتحوّل البلاد إلى السنّة. (قريبًا)",
    period: { label: "1164 – 1171 م", startYear: 1164, endYear: 1171 },
    relatedEntities: ["ayyubid.figure.shirkuh","ayyubid.figure.salahuddin","ayyubid.city.cairo","ayyubid.event.end-fatimid"],
    unlockables: [],
    image: { alt: "سقوط الفاطميين", glyph: "📕", tone: "from-rose-800/40 to-slate-900" },
    timelinePosition: 1171,
    rarity: "legendary",
    meta: { locked: true, kind: "campaign-placeholder" },
  }),

  E({
    id: "ayyubid.event.future-third-crusade",
    title: "الحملة الصليبية الثالثة",
    type: "event",
    description: "حملةٌ قادمة تروي المواجهة الكبرى بين صلاح الدين وريتشارد قلب الأسد. (قريبًا)",
    period: { label: "1189 – 1192 م", startYear: 1189, endYear: 1192 },
    relatedEntities: ["ayyubid.event.third-crusade","ayyubid.figure.richard-lionheart","ayyubid.battle.arsuf","ayyubid.battle.jaffa"],
    unlockables: [],
    image: { alt: "الحملة الثالثة", glyph: "✝️", tone: "from-rose-900/40 to-slate-900" },
    timelinePosition: 1189,
    rarity: "legendary",
    meta: { locked: true, kind: "campaign-placeholder" },
  }),

  E({
    id: "ayyubid.event.future-shajar-end",
    title: "شجر الدر ونهاية الأيوبيين",
    type: "event",
    description: "حملةٌ قادمة تروي صعود شجر الدر، انتصار المنصورة، وانتقال السلطة إلى المماليك. (قريبًا)",
    period: { label: "1249 – 1250 م", startYear: 1249, endYear: 1250 },
    relatedEntities: ["ayyubid.figure.shajar-al-durr","ayyubid.figure.turanshah","ayyubid.battle.mansurah","ayyubid.event.end-ayyubid"],
    unlockables: [],
    image: { alt: "نهاية الأيوبيين", glyph: "💎", tone: "from-fuchsia-800/40 to-slate-900" },
    timelinePosition: 1250,
    rarity: "legendary",
    meta: { locked: true, kind: "campaign-placeholder" },
  }),
];

export const AYYUBID_PACK: ContentPack = {
  id: "pack-001-ayyubid",
  order: 1,
  title: "الدولة الأيوبية",
  subtitle: "المجموعة 1 · صلاح الدين وتحرير القدس",
  summary:
    "أوّل حزمة محتوى تاريخية في إرث: دولةٌ سنّية أعادت الجهاد إلى الشام ومصر وحرّرت القدس.",
  era: "ayyubid",
  period: { label: "1171 – 1250 م", startYear: 1171, endYear: 1250 },
  cover: { alt: "غلاف الدولة الأيوبية", glyph: "🦅", tone: "from-amber-700/40 to-slate-900" },
  entities,
};