import type { ContentPack, PackEntity } from "./types";

// ============================================================
// Content Pack 004 — الدولة المملوكية (The Mamluk Sultanate)
// ------------------------------------------------------------
// Same architecture as Packs 001 (Ayyubid), 002 (Umayyad), 003 (Abbasid).
// Pure data — no UI or engine changes required. Mamluk entities
// automatically surface in the Encyclopedia, Atlas, Museum, Timeline,
// Related-History Graph, and Achievements via the pack registry.
// ============================================================

const E = (e: PackEntity): PackEntity => e;

// ---------- FIGURES (Sultans & Statesmen) ----------
const FIGURE_IDS = [
  ["shajar-al-durr","شجر الدر","Shajar al-Durr",1250,1257,
    "سلطانة مصر بعد وفاة الصالح أيوب وانتصار المنصورة، أوّل امرأة تحكم في الإسلام السنّي رسميًّا، وفي عهدها بدأ التحوّل إلى الدولة المملوكية.",
    ["mamluk.event.rise-mamluk","mamluk.event.end-ayyubid","mamluk.battle.mansurah","mamluk.figure.aybak","mamluk.figure.louis-ix"]],
  ["aybak","عز الدين أيبك","Izz al-Din Aybak",1250,1257,
    "أوّل سلاطين المماليك البحرية، تزوّج شجر الدر وأرسى دعائم الدولة الجديدة في القاهرة.",
    ["mamluk.figure.shajar-al-durr","mamluk.event.rise-mamluk","mamluk.city.cairo"]],
  ["qutuz","سيف الدين قطز","Sayf al-Din Qutuz",1259,1260,
    "السلطان الذي قاد المماليك في عين جالوت سنة ١٢٦٠م وكسر أسطورة المغول الذين لا يُهزمون، فحفظ مصر والشام للإسلام.",
    ["mamluk.battle.ain-jalut","mamluk.figure.baybars","mamluk.event.defeat-mongols","mamluk.artifact.sword-qutuz","abbasid.figure.hulagu"]],
  ["baybars","الظاهر بيبرس","Al-Zahir Baybars",1260,1277,
    "السلطان الظاهر ركن الدين بيبرس البندقداري، أعظم سلاطين المماليك، حطّم الصليبيين والمغول وأعاد الخلافة العباسية الرمزية إلى القاهرة.",
    ["mamluk.battle.ain-jalut","mamluk.battle.homs-2","mamluk.event.reforms-baybars","mamluk.event.end-crusader-states","mamluk.city.cairo","mamluk.artifact.armor-baybars","mamluk.artifact.seal-baybars","abbasid.figure.hulagu"]],
  ["qalawun","المنصور قلاوون","Al-Mansur Qalawun",1279,1290,
    "السلطان المنصور سيف الدين قلاوون الألفي، أسّس سلالةً امتدّت قرنًا، حرّر طرابلس وكثيرًا من حصون الصليبيين وأنشأ مارستان قلاوون الشهير.",
    ["mamluk.battle.homs-2","mamluk.event.end-crusader-states","mamluk.city.tripoli","mamluk.figure.al-ashraf-khalil","mamluk.figure.an-nasir-muhammad"]],
  ["al-ashraf-khalil","الأشرف خليل","Al-Ashraf Khalil",1290,1293,
    "ابن قلاوون، فاتح عكا سنة ١٢٩١م ومنهي وجود الإمارات الصليبية في الشام بشكلٍ نهائي.",
    ["mamluk.battle.siege-acre","mamluk.event.fall-acre","mamluk.event.end-crusader-states","mamluk.city.acre","mamluk.figure.qalawun"]],
  ["an-nasir-muhammad","الناصر محمد بن قلاوون",  "Al-Nasir Muhammad",1293,1341,
    "أطول سلاطين المماليك حكمًا، شهد عهده ازدهارًا عمرانيًّا واقتصاديًّا هائلًا في القاهرة ومسحًا شاملًا للأراضي وتجديد القلعة.",
    ["mamluk.city.cairo","mamluk.landmark.citadel","mamluk.event.cairo-prosperity","mamluk.figure.qalawun"]],
  ["barquq","الظاهر برقوق","Al-Zahir Barquq",1382,1399,
    "مؤسّس دولة المماليك البرجية (الجراكسة) بعد المماليك البحرية، صدّ غزو تيمورلنك المرتقب وأعاد ترتيب الدولة.",
    ["mamluk.state.mamluk","mamluk.city.cairo","mamluk.figure.al-mu'ayyad-shaykh"]],
  ["al-mu'ayyad-shaykh","المؤيد شيخ","Al-Mu'ayyad Shaykh",1412,1421,
    "سلطانٌ برجيّ بنى الجامع المؤيدي المشهور بقاهرة المعزّ، وأعاد ضبط حدود الدولة في الشام.",
    ["mamluk.city.cairo","mamluk.figure.barquq","mamluk.landmark.citadel"]],
  ["barsbay","الأشرف برسباي","Al-Ashraf Barsbay",1422,1438,
    "السلطان الذي ضمّ قبرص سنة ١٤٢٦م وفرض الجزية على ملكها، ونظّم تجارة البهارات في موانئ المماليك.",
    ["mamluk.event.cyprus-annexation","mamluk.battle.cyprus-campaign","mamluk.city.alexandria"]],
  ["qaitbay","الأشرف قايتباي","Al-Ashraf Qaitbay",1468,1496,
    "أعظم سلاطين البرجية في العمارة، شيّد قلعة قايتباي في الإسكندرية وكثيرًا من المساجد والمدارس، وحارب العثمانيين والبرتغاليين.",
    ["mamluk.landmark.qaitbay-citadel","mamluk.city.alexandria","mamluk.event.discovery-cape","mamluk.figure.qansuh-al-ghuri"]],
  ["qansuh-al-ghuri","قانصوه الغوري","Qansuh al-Ghuri",1501,1516,
    "أحد آخر سلاطين المماليك، قُتل في مرج دابق أمام السلطان سليم الأول العثماني فدخل الشام تحت العثمانيين.",
    ["mamluk.battle.marj-dabiq","mamluk.event.fall-mamluk","mamluk.figure.tuman-bay","mamluk.city.aleppo"]],
  ["tuman-bay","طومان باي","Tuman Bay II",1516,1517,
    "آخر سلاطين المماليك، انكسر في الريدانية ودخل سليم الأول القاهرة، فأُعدم على باب زويلة سنة ١٥١٧م.",
    ["mamluk.battle.ridaniya","mamluk.event.fall-mamluk","mamluk.city.cairo","mamluk.figure.qansuh-al-ghuri"]],
  ["louis-ix","لويس التاسع","Louis IX of France",1248,1254,
    "ملك فرنسا وقائد الحملة الصليبية السابعة، انكسر جيشه في المنصورة وأُسر قبل أن يُفدى ويعود إلى أوروبا. (شخصية مرتبطة)",
    ["mamluk.battle.mansurah","mamluk.event.end-ayyubid","mamluk.figure.shajar-al-durr"]],
] as const;

// ---------- SCHOLARS ----------
const SCHOLAR_IDS = [
  ["ibn-taymiyyah","ابن تيمية","Ibn Taymiyyah",1263,1328,
    "شيخ الإسلام تقيّ الدين أحمد بن تيمية الحرّاني، إمامٌ مجدّد في زمن المماليك، حرّض على جهاد التتار وكتب عشرات المجلدات في العقيدة والفقه.",
    ["mamluk.figure.ibn-al-qayyim","mamluk.city.damascus","mamluk.event.defeat-mongols"]],
  ["ibn-al-qayyim","ابن القيم","Ibn al-Qayyim al-Jawziyya",1292,1350,
    "شمس الدين محمد بن أبي بكر، تلميذ ابن تيمية الأشهر وصاحب «زاد المعاد» و«مدارج السالكين».",
    ["mamluk.figure.ibn-taymiyyah","mamluk.city.damascus"]],
  ["al-dhahabi","الإمام الذهبي","Al-Dhahabi",1274,1348,
    "شمس الدين الذهبي، مؤرّخ الإسلام الأكبر وصاحب «سير أعلام النبلاء» و«تاريخ الإسلام».",
    ["mamluk.figure.ibn-taymiyyah","mamluk.city.damascus","mamluk.figure.al-mizzi"]],
  ["ibn-kathir","ابن كثير","Ibn Kathir",1300,1373,
    "الحافظ عماد الدين إسماعيل بن كثير، صاحب «البداية والنهاية» وأشهر تفاسير القرآن في العصر المملوكي.",
    ["mamluk.city.damascus","mamluk.figure.al-mizzi","mamluk.figure.ibn-taymiyyah"]],
  ["al-mizzi","المزّي","Al-Mizzi",1256,1341,
    "جمال الدين يوسف المزّي، شيخ المحدّثين في زمنه وصاحب «تهذيب الكمال» في رجال الحديث.",
    ["mamluk.city.damascus","mamluk.figure.al-dhahabi","mamluk.figure.ibn-kathir"]],
  ["al-izz","العز بن عبد السلام","Al-Izz ibn Abd al-Salam",1181,1262,
    "سلطان العلماء، أفتى ببيع أمراء المماليك في السوق ليُعتقوا، وكان من حُداة قطز إلى عين جالوت.",
    ["mamluk.figure.qutuz","mamluk.battle.ain-jalut","mamluk.city.cairo","mamluk.city.damascus"]],
  ["ibn-hajar","ابن حجر العسقلاني","Ibn Hajar al-Asqalani",1372,1449,
    "أمير المؤمنين في الحديث في زمن المماليك البرجية، صاحب «فتح الباري» شرح صحيح البخاري.",
    ["mamluk.city.cairo","mamluk.figure.al-suyuti"]],
  ["al-suyuti","الإمام السيوطي","Jalal al-Din al-Suyuti",1445,1505,
    "جلال الدين السيوطي، موسوعةٌ مشت على قدمين، صنّف نحو ٦٠٠ مصنّف في التفسير والحديث واللغة.",
    ["mamluk.city.cairo","mamluk.figure.ibn-hajar"]],
] as const;

// ---------- CITIES ----------
const CITY_IDS = [
  ["cairo","القاهرة","Cairo",
    "عاصمة الدولة المملوكية وعروس المدن الإسلامية في زمنها، شهدت أعظم ازدهارٍ عمراني وعلميٍّ تحت قلاوون والناصر محمد وقايتباي.",
    1250,1517,["mamluk.landmark.citadel","mamluk.landmark.sultan-hassan-mosque","mamluk.landmark.khan-el-khalili","mamluk.figure.baybars","mamluk.figure.an-nasir-muhammad"]],
  ["damascus","دمشق","Damascus",
    "ثغر الشام الكبير وعاصمة نيابة دمشق المملوكية، حصنٌ في وجه المغول ومنبر علماء كابن تيمية والذهبي وابن كثير.",
    1250,1517,["mamluk.landmark.damascus-citadel","mamluk.landmark.zahiriyya-madrasa","mamluk.figure.ibn-taymiyyah","mamluk.figure.al-dhahabi"]],
  ["aleppo","حلب","Aleppo",
    "ثغر الشام الشمالي ونيابة المماليك الكبرى أمام المغول والعثمانيين، سقطت بعد مرج دابق سنة ١٥١٦م.",
    1250,1516,["mamluk.battle.marj-dabiq","mamluk.figure.qansuh-al-ghuri"]],
  ["jerusalem","القدس","Jerusalem",
    "بيت المقدس تحت رعاية المماليك، شهدت ترميمًا واسعًا للأقصى وبناء عشرات المدارس والأسبلة.",
    1260,1517,["mamluk.landmark.al-aqsa-mosque","mamluk.figure.baybars","mamluk.figure.qaitbay"]],
  ["gaza","غزة","Gaza",
    "ثغرٌ ساحلي على طريق مصر إلى الشام، نقطة عبور جيوش بيبرس وقلاوون نحو الصليبيين والمغول.",
    1260,1517,["mamluk.landmark.gaza-citadel","mamluk.figure.baybars"]],
  ["acre","عكا","Acre",
    "آخر معاقل الصليبيين الكبرى في الشام، فتحها الأشرف خليل سنة ١٢٩١م فطُويت صفحة الإمارات الصليبية.",
    1250,1291,["mamluk.battle.siege-acre","mamluk.event.fall-acre","mamluk.figure.al-ashraf-khalil"]],
  ["alexandria","الإسكندرية","Alexandria",
    "ثغر مصر الكبير وميناء تجارة البهارات، شيّد فيها قايتباي قلعته الشهيرة مكان منارة الإسكندرية القديمة.",
    1250,1517,["mamluk.landmark.qaitbay-citadel","mamluk.figure.barsbay","mamluk.figure.qaitbay","mamluk.event.discovery-cape"]],
  ["karak","الكرك","Karak",
    "حصنٌ منيع في شرق الأردن ورثه المماليك عن الأيوبيين، قاعدة عمليات نحو الكرك والشوبك والشام.",
    1250,1517,["mamluk.figure.baybars","mamluk.state.mamluk"]],
  ["safed","صفد","Safed",
    "حصنٌ صليبيٌّ منيع في الجليل الأعلى، فتحه بيبرس سنة ١٢٦٦م فصار من أعظم نيابات المماليك في الشام.",
    1266,1517,["mamluk.battle.safed-conquest","mamluk.figure.baybars"]],
  ["tripoli","طرابلس","Tripoli (Lebanon)",
    "ثغرٌ ساحليّ شامي فتحه قلاوون من الصليبيين سنة ١٢٨٩م، فحُسمت بذلك مقدّمة سقوط عكا.",
    1289,1517,["mamluk.figure.qalawun","mamluk.event.end-crusader-states"]],
] as const;

// ---------- BATTLES ----------
const BATTLE_IDS = [
  ["ain-jalut","معركة عين جالوت","Battle of Ain Jalut",1260,1260,
    "المعركة الفاصلة بين المماليك بقيادة قطز وبيبرس وجيش المغول بقيادة كتبغا في فلسطين سنة ١٢٦٠م، كسرت أسطورة المغول الذين لا يُهزمون.",
    ["mamluk.figure.qutuz","mamluk.figure.baybars","mamluk.event.defeat-mongols","mamluk.artifact.manuscript-ain-jalut","abbasid.figure.hulagu"]],
  ["mansurah","معركة المنصورة","Battle of Mansurah",1250,1250,
    "موقعةٌ كبرى في الدلتا انكسر فيها لويس التاسع وأُسر، وفُتح الباب لقيام دولة المماليك في مصر.",
    ["mamluk.figure.shajar-al-durr","mamluk.figure.louis-ix","mamluk.event.end-ayyubid","mamluk.event.rise-mamluk"]],
  ["siege-acre","حصار عكا","Siege of Acre",1291,1291,
    "حصارٌ مملوكيٌّ بقيادة الأشرف خليل لعكا آخر معاقل الصليبيين، انتهى بسقوطها بعد ٤٤ يومًا.",
    ["mamluk.figure.al-ashraf-khalil","mamluk.city.acre","mamluk.event.fall-acre","mamluk.event.end-crusader-states","mamluk.artifact.manuscript-fall-acre"]],
  ["homs-2","معركة حمص الثانية","Second Battle of Homs",1281,1281,
    "موقعةٌ كبرى بين قلاوون وجيش المغول بقيادة منكوتمر، انتصر فيها المماليك وكسروا الموجة المغولية الثانية على الشام.",
    ["mamluk.figure.qalawun","mamluk.figure.baybars","mamluk.event.defeat-mongols","mamluk.city.damascus"]],
  ["caesarea-conquest","فتح قيسارية","Conquest of Caesarea",1265,1265,
    "فتح بيبرس لميناء قيسارية الصليبي على ساحل فلسطين سنة ١٢٦٥م.",
    ["mamluk.figure.baybars","mamluk.event.end-crusader-states"]],
  ["arsuf-conquest","فتح أرسوف","Conquest of Arsuf",1265,1265,
    "فتح بيبرس لمدينة أرسوف على ساحل فلسطين بعد قيسارية مباشرة، وتفكيك دفاعاتها الصليبية.",
    ["mamluk.figure.baybars","mamluk.event.end-crusader-states"]],
  ["safed-conquest","فتح صفد","Conquest of Safed",1266,1266,
    "فتح بيبرس لحصن صفد الصليبي المنيع في الجليل الأعلى سنة ١٢٦٦م، وتحويلها إلى مقرّ نيابة مملوكية.",
    ["mamluk.figure.baybars","mamluk.city.safed","mamluk.event.end-crusader-states"]],
  ["marj-dabiq","معركة مرج دابق","Battle of Marj Dabiq",1516,1516,
    "موقعةٌ كبرى شمال حلب بين قانصوه الغوري والسلطان سليم الأول العثماني، انكسر فيها المماليك وقُتل الغوري فصار الشام عثمانيًّا.",
    ["mamluk.figure.qansuh-al-ghuri","mamluk.city.aleppo","mamluk.event.fall-mamluk"]],
  ["ridaniya","معركة الريدانية","Battle of Ridaniya",1517,1517,
    "الموقعة الأخيرة شمال القاهرة بين طومان باي وسليم الأول، انتهت بسقوط القاهرة ودخول مصر تحت الحكم العثماني.",
    ["mamluk.figure.tuman-bay","mamluk.city.cairo","mamluk.event.fall-mamluk"]],
  ["cyprus-campaign","حملة قبرص","Cyprus Campaigns",1424,1426,
    "ثلاث حملات بحرية مملوكية على قبرص في عهد الأشرف برسباي، انتهت بأسر ملك قبرص جانوس ودفعه الجزية.",
    ["mamluk.figure.barsbay","mamluk.event.cyprus-annexation","mamluk.city.alexandria"]],
] as const;

// ---------- EVENTS ----------
const EVENT_IDS = [
  ["rise-mamluk","قيام الدولة المملوكية","Rise of the Mamluk Sultanate",1250,1250,
    "تحوّل السلطة في مصر من البيت الأيوبي إلى المماليك البحرية بعد المنصورة ووفاة الصالح أيوب، بمبادرة شجر الدر ثم أيبك.",
    ["mamluk.figure.shajar-al-durr","mamluk.figure.aybak","mamluk.event.end-ayyubid","mamluk.battle.mansurah"]],
  ["end-ayyubid","نهاية الدولة الأيوبية","End of the Ayyubid State in Egypt",1250,1250,
    "اغتيال توران شاه ودخول المماليك في السلطة، يُعدّ نقطة تحوّل من الأيوبيين إلى المماليك.",
    ["mamluk.event.rise-mamluk","mamluk.figure.shajar-al-durr","mamluk.battle.mansurah"]],
  ["defeat-mongols","هزيمة المغول","Defeating the Mongols",1260,1281,
    "سلسلة الانتصارات المملوكية على المغول من عين جالوت إلى حمص الثانية، حفظت العالم الإسلامي من اجتياحٍ شامل.",
    ["mamluk.battle.ain-jalut","mamluk.battle.homs-2","mamluk.figure.qutuz","mamluk.figure.baybars","mamluk.figure.qalawun","abbasid.figure.hulagu"]],
  ["end-crusader-states","نهاية الإمارات الصليبية","End of the Crusader States",1265,1291,
    "تحرير بيبرس وقلاوون والأشرف خليل لقيسارية وأرسوف وصفد وطرابلس وعكا، وإسقاط آخر دويلات الفرنجة في الشام.",
    ["mamluk.figure.baybars","mamluk.figure.qalawun","mamluk.figure.al-ashraf-khalil","mamluk.battle.siege-acre","mamluk.event.fall-acre","mamluk.battle.caesarea-conquest","mamluk.battle.arsuf-conquest","mamluk.battle.safed-conquest"]],
  ["fall-acre","سقوط عكا","Fall of Acre",1291,1291,
    "سقوط آخر معاقل الصليبيين الكبرى في الشام على يد الأشرف خليل، إيذانًا بطيّ صفحة الحملات الصليبية في المشرق.",
    ["mamluk.battle.siege-acre","mamluk.figure.al-ashraf-khalil","mamluk.event.end-crusader-states","mamluk.artifact.manuscript-fall-acre"]],
  ["cairo-prosperity","ازدهار القاهرة","Prosperity of Cairo",1280,1390,
    "قرنٌ من ازدهار العمران والاقتصاد في القاهرة المملوكية، بنى فيه السلاطين عشرات المساجد والمدارس والأسبلة.",
    ["mamluk.city.cairo","mamluk.figure.qalawun","mamluk.figure.an-nasir-muhammad","mamluk.landmark.citadel","mamluk.landmark.khan-el-khalili","mamluk.landmark.sultan-hassan-mosque"]],
  ["citadel-expansion","بناء القلعة والتوسعات المملوكية","Citadel and Mamluk Construction",1260,1496,
    "توسعة قلعة الجبل في القاهرة وبناء قصور السلاطين وأبراج الإسكندرية ومئات المساجد في الشام والحجاز.",
    ["mamluk.landmark.citadel","mamluk.landmark.qaitbay-citadel","mamluk.figure.an-nasir-muhammad","mamluk.figure.qaitbay"]],
  ["reforms-baybars","إصلاحات بيبرس","Reforms of Baybars",1260,1277,
    "إعادة تنظيم البريد السلطاني، وإحياء الخلافة العباسية الرمزية في القاهرة، وتقنين القضاء على المذاهب الأربعة.",
    ["mamluk.figure.baybars","mamluk.city.cairo","mamluk.artifact.seal-baybars","mamluk.artifact.sultan-decree"]],
  ["armenian-campaigns","الحملات على الأرمن","Mamluk Campaigns against Cilician Armenia",1266,1375,
    "سلسلة حملات على مملكة قيليقية الأرمنية حليفة المغول والصليبيين، انتهت بضمّها سنة ١٣٧٥م.",
    ["mamluk.figure.baybars","mamluk.figure.qalawun","mamluk.state.mamluk"]],
  ["cyprus-annexation","ضم قبرص","Annexation of Cyprus",1426,1426,
    "أسر ملك قبرص جانوس بعد حملة برسباي البحرية، وإلزام مملكة قبرص بدفع الجزية للسلطنة المملوكية.",
    ["mamluk.figure.barsbay","mamluk.battle.cyprus-campaign","mamluk.city.alexandria"]],
  ["discovery-cape","اكتشاف طريق رأس الرجاء الصالح","Discovery of the Cape Route and its Impact",1488,1517,
    "دوران البرتغاليين حول رأس الرجاء الصالح كسر احتكار المماليك لتجارة البهارات، فبدأ الضعف الاقتصادي للسلطنة.",
    ["mamluk.figure.qaitbay","mamluk.city.alexandria","mamluk.event.fall-mamluk"]],
  ["marj-dabiq-event","معركة مرج دابق (الحدث)","Marj Dabiq Event",1516,1516,
    "هزيمة قانصوه الغوري أمام سليم الأول العثماني شمال حلب، وانتقال الشام كاملًا إلى الدولة العثمانية.",
    ["mamluk.battle.marj-dabiq","mamluk.figure.qansuh-al-ghuri","mamluk.event.fall-mamluk"]],
  ["ridaniya-event","معركة الريدانية (الحدث)","Ridaniya Event",1517,1517,
    "كسر طومان باي شمال القاهرة، ودخول سليم الأول العاصمة، وإعدام آخر سلاطين المماليك على باب زويلة.",
    ["mamluk.battle.ridaniya","mamluk.figure.tuman-bay","mamluk.event.fall-mamluk"]],
  ["fall-mamluk","سقوط الدولة المملوكية","Fall of the Mamluk Sultanate",1516,1517,
    "نهاية السلطنة المملوكية بعد مرج دابق والريدانية، وتحوّل مصر والشام والحجاز إلى ولاياتٍ عثمانية.",
    ["mamluk.battle.marj-dabiq","mamluk.battle.ridaniya","mamluk.figure.qansuh-al-ghuri","mamluk.figure.tuman-bay"]],
] as const;

// ---------- LANDMARKS ----------
const LANDMARK_IDS = [
  ["citadel","قلعة الجبل","Citadel of the Mountain (Cairo Citadel)",
    "قلعة صلاح الدين على هضبة المقطّم، صارت في عهد المماليك مقرّ السلطنة والإدارة وقصور السلاطين.",
    1176,1517,["mamluk.city.cairo","mamluk.figure.an-nasir-muhammad","mamluk.event.citadel-expansion"]],
  ["sultan-hassan-mosque","مسجد السلطان حسن","Mosque of Sultan Hassan",
    "تحفة العمارة المملوكية في القاهرة، أعظم مساجد السلطنة بناءً وأكثرها هيبة، مع مدرسته الأربع المذاهب.",
    1356,1517,["mamluk.city.cairo","mamluk.landmark.sultan-hassan-madrasa","mamluk.event.cairo-prosperity"]],
  ["sultan-hassan-madrasa","مدرسة السلطان حسن","Madrasa of Sultan Hassan",
    "مدرسةٌ ملحقة بالمسجد، تضمّ أروقة للمذاهب الأربعة وكُتّابًا لتعليم الأيتام، نموذجٌ متكامل للمؤسسة التعليمية المملوكية.",
    1356,1517,["mamluk.city.cairo","mamluk.landmark.sultan-hassan-mosque","mamluk.event.cairo-prosperity"]],
  ["qaitbay-citadel","قلعة قايتباي","Citadel of Qaitbay (Alexandria)",
    "قلعةٌ ساحلية بناها الأشرف قايتباي سنة ١٤٧٧م مكان منارة الإسكندرية القديمة، حصنٌ في وجه العثمانيين والبرتغاليين.",
    1477,1517,["mamluk.figure.qaitbay","mamluk.city.alexandria","mamluk.event.citadel-expansion"]],
  ["baybars-khanqah","خانقاه بيبرس","Khanqah of Baybars",
    "أحد أوائل الخانقاوات الكبرى في القاهرة المملوكية، شيّدها بيبرس لإقامة الصوفية وتعليم العلوم.",
    1267,1517,["mamluk.figure.baybars","mamluk.city.cairo","mamluk.event.reforms-baybars"]],
  ["khan-el-khalili","سوق خان الخليلي","Khan el-Khalili",
    "أعظم أسواق القاهرة الإسلامية، أنشأه جركس الخليلي زمن برقوق، صار قلب التجارة المملوكية ومحجّ التجار الأجانب.",
    1382,1517,["mamluk.city.cairo","mamluk.figure.barquq","mamluk.event.cairo-prosperity"]],
  ["zahiriyya-madrasa","المدرسة الظاهرية","Zahiriyya Madrasa (Damascus)",
    "مدرسةٌ بناها أبناء بيبرس في دمشق لتكون مدرسةً ومقبرةً للسلطان الظاهر، تحفةٌ من الفسيفساء الشامية.",
    1277,1517,["mamluk.figure.baybars","mamluk.city.damascus"]],
  ["damascus-citadel","قلعة دمشق","Citadel of Damascus",
    "حصن دمشق التاريخي، ورثه المماليك عن الأيوبيين ووسّعوه، صدّ هجمات المغول في حملات غازان وتيمور.",
    1250,1517,["mamluk.city.damascus","mamluk.figure.baybars","mamluk.figure.qalawun"]],
  ["al-aqsa-mosque","المسجد الأقصى","Al-Aqsa Mosque",
    "ثالث المساجد المباركة، حظي في زمن المماليك بأعمال ترميمٍ واسعة وأوقافٍ ضخمة من سلاطينهم.",
    1260,1517,["mamluk.city.jerusalem","mamluk.figure.baybars","mamluk.figure.qaitbay"]],
  ["gaza-citadel","القلعة المملوكية في غزة","Mamluk Citadel of Gaza",
    "حصنٌ مملوكي على الطريق بين مصر والشام، مقرّ نيابة غزة وعتاد جيوش بيبرس وقلاوون نحو الشام.",
    1260,1517,["mamluk.city.gaza","mamluk.figure.baybars","mamluk.event.end-crusader-states"]],
] as const;

// ---------- ARTIFACTS ----------
const ARTIFACT_IDS = [
  ["sword-qutuz","سيف قطز","Sword of Qutuz",
    "السيف الذي حمله السلطان قطز يوم عين جالوت، رمز كسر هيبة المغول التي لا تُهزم.",
    1260,1517,"🗡️","legendary",["mamluk.figure.qutuz","mamluk.battle.ain-jalut","mamluk.event.defeat-mongols"]],
  ["mamluk-banner","راية المماليك","Mamluk Banner",
    "الراية السلطانية الصفراء بشعار الأسد، شارة الجيش المملوكي من عين جالوت إلى الريدانية.",
    1250,1517,"🏴","rare",["mamluk.state.mamluk","mamluk.figure.baybars"]],
  ["armor-baybars","درع بيبرس","Armor of Baybars",
    "درع السلطان الظاهر بيبرس، تحفةٌ من تحف صناعة الأسلحة المملوكية في القاهرة ودمشق.",
    1260,1517,"🛡️","epic",["mamluk.figure.baybars","mamluk.event.reforms-baybars"]],
  ["mamluk-dinar","دينار مملوكي","Mamluk Gold Dinar",
    "عملةٌ ذهبيّة سلطانية تحمل اسم السلطان وألقابه، عمودٌ من أعمدة اقتصاد الدولة وتجارتها مع أوروبا.",
    1250,1517,"💰","epic",["mamluk.state.mamluk","mamluk.city.alexandria","mamluk.city.cairo"]],
  ["seal-baybars","ختم السلطان بيبرس","Seal of Sultan Baybars",
    "الختم السلطاني الذي وقّع به بيبرس مراسيمه إلى الولاة والقضاة من السودان إلى الأناضول.",
    1260,1517,"🪧","epic",["mamluk.figure.baybars","mamluk.artifact.sultan-decree","mamluk.event.reforms-baybars"]],
  ["manuscript-ain-jalut","مخطوطة عين جالوت","Manuscript of Ain Jalut",
    "مخطوطةٌ مملوكيّة تروي تفاصيل المعركة ومراسلات قطز وبيبرس قبل النصر.",
    1260,1517,"📜","legendary",["mamluk.battle.ain-jalut","mamluk.figure.qutuz","mamluk.figure.baybars"]],
  ["manuscript-fall-acre","مخطوطة سقوط عكا","Manuscript of the Fall of Acre",
    "وثيقةٌ تصف حصار الأشرف خليل لعكا وسقوطها وانطواء صفحة الصليبيين في الشام.",
    1291,1517,"📜","legendary",["mamluk.event.fall-acre","mamluk.figure.al-ashraf-khalil","mamluk.battle.siege-acre"]],
  ["mamluk-map","خريطة الدولة المملوكية","Map of the Mamluk Sultanate",
    "خريطةٌ مملوكية تبيّن النيابات الكبرى من برقة إلى الفرات ومن طرسوس إلى الحجاز.",
    1300,1517,"🗺️","epic",["mamluk.state.mamluk","mamluk.city.cairo","mamluk.city.damascus","mamluk.city.aleppo"]],
  ["sultan-decree","مرسوم سلطاني","Sultanic Decree",
    "مرسومٌ سلطاني موقّع بالختم السلطاني، أداة الحكم المملوكي إلى نوّاب الشام والحجاز.",
    1260,1517,"📃","rare",["mamluk.artifact.seal-baybars","mamluk.figure.baybars","mamluk.event.reforms-baybars"]],
  ["islam-protector-medal","وسام حامي الإسلام","Medal of the Protector of Islam",
    "وسامٌ شرفي يُمنح لقادة جيش المماليك بعد الانتصار على المغول والصليبيين، شعاره الأسد والسيفان.",
    1260,1517,"🏵️","legendary",["mamluk.event.defeat-mongols","mamluk.event.end-crusader-states","mamluk.figure.baybars","mamluk.figure.qutuz"]],
] as const;

// ---------- ACHIEVEMENTS ----------
const ACHIEVEMENT_IDS = [
  ["ain-jalut-hero","بطل عين جالوت","Hero of Ain Jalut",
    "يُمنح لمن أكمل قصص عين جالوت وقطز وبيبرس وكسر المغول.",
    ["mamluk.battle.ain-jalut","mamluk.figure.qutuz","mamluk.figure.baybars","mamluk.event.defeat-mongols"]],
  ["mashriq-defender","حامي المشرق الإسلامي","Defender of the Islamic East",
    "يُمنح لمن أكمل سلسلة الانتصارات على المغول والصليبيين تحت قلاوون وبيبرس.",
    ["mamluk.figure.baybars","mamluk.figure.qalawun","mamluk.event.defeat-mongols","mamluk.event.end-crusader-states"]],
  ["mamluk-historian","مؤرّخ الدولة المملوكية","Historian of the Mamluk State",
    "يُمنح لمن قرأ جميع شخصيات وأحداث الدولة المملوكية في الموسوعة.",
    ["mamluk.state.mamluk","mamluk.figure.ibn-taymiyyah","mamluk.figure.al-suyuti","mamluk.event.cairo-prosperity"]],
  ["mamluk-collector","جامع التراث المملوكي","Collector of Mamluk Heritage",
    "يُمنح لمن جمع كلّ الآثار والمخطوطات المملوكية في مجموعته.",
    ["mamluk.artifact.mamluk-dinar","mamluk.artifact.seal-baybars","mamluk.artifact.manuscript-ain-jalut","mamluk.artifact.manuscript-fall-acre","mamluk.artifact.islam-protector-medal"]],
  ["cairo-master","سيد القاهرة","Master of Cairo",
    "يُمنح لمن أتمّ مسار القاهرة المملوكية وقلعة الجبل ومسجد السلطان حسن وخان الخليلي.",
    ["mamluk.city.cairo","mamluk.landmark.citadel","mamluk.landmark.sultan-hassan-mosque","mamluk.landmark.khan-el-khalili"]],
] as const;

// ---------- FUTURE CAMPAIGN PLACEHOLDERS (locked) ----------
const FUTURE_CAMPAIGN_IDS = [
  ["future-qutuz",        "حملة قطز",              1259,1260,"حملةٌ قادمة تروي صعود قطز ومواجهته للمغول حتى عين جالوت. (قريبًا)"],
  ["future-baybars",      "حملة الظاهر بيبرس",     1260,1277,"حملةٌ قادمة عن بيبرس وحربه المزدوجة على المغول والصليبيين. (قريبًا)"],
  ["future-ain-jalut",    "معركة عين جالوت",       1260,1260,"حملةٌ قادمة تجوب يومًا واحدًا غيّر مصير العالم الإسلامي. (قريبًا)"],
  ["future-fall-acre",    "سقوط عكا",              1290,1291,"حملةٌ قادمة عن آخر معاقل الصليبيين في الشام. (قريبًا)"],
  ["future-qansuh-ghuri", "قانصوه الغوري",         1501,1516,"حملةٌ قادمة عن المواجهة مع العثمانيين حتى مرج دابق. (قريبًا)"],
  ["future-fall-mamluk",  "سقوط الدولة المملوكية", 1516,1517,"حملةٌ قادمة عن نهاية السلطنة على يد سليم الأول. (قريبًا)"],
] as const;

const entities: PackEntity[] = [
  // ---------- STATE ----------
  E({
    id: "mamluk.state.mamluk",
    title: "الدولة المملوكية",
    latin: "Mamluk Sultanate",
    type: "state",
    description:
      "سلطنة المماليك، قامت في مصر والشام والحجاز سنة ١٢٥٠م بعد سقوط الأيوبيين، حفظت العالم الإسلامي من اجتياح المغول ومحت آخر دويلات الصليبيين، عاصمتها القاهرة، وانتهت سنة ١٥١٧م على يد العثمانيين.",
    period: { label: "١٢٥٠ – ١٥١٧ م", startYear: 1250, endYear: 1517 },
    relatedEntities: [
      "mamluk.figure.shajar-al-durr","mamluk.figure.aybak","mamluk.figure.qutuz",
      "mamluk.figure.baybars","mamluk.figure.qalawun","mamluk.figure.al-ashraf-khalil",
      "mamluk.figure.an-nasir-muhammad","mamluk.figure.barquq","mamluk.figure.barsbay",
      "mamluk.figure.qaitbay","mamluk.figure.qansuh-al-ghuri","mamluk.figure.tuman-bay",
      "mamluk.city.cairo","mamluk.city.damascus","mamluk.city.aleppo","mamluk.city.jerusalem","mamluk.city.alexandria",
      "mamluk.battle.ain-jalut","mamluk.battle.siege-acre","mamluk.battle.marj-dabiq","mamluk.battle.ridaniya",
      "mamluk.event.rise-mamluk","mamluk.event.defeat-mongols","mamluk.event.end-crusader-states",
      "mamluk.event.cairo-prosperity","mamluk.event.fall-mamluk",
    ],
    unlockables: [
      { kind: "campaign", refId: "mamluk", label: "حملات الدولة المملوكية" },
    ],
    image: { alt: "راية الدولة المملوكية", glyph: "🦁", tone: "from-amber-700/40 to-stone-900" },
    timelinePosition: 1250,
    rarity: "legendary",
    meta: {
      founder: "شجر الدر / عز الدين أيبك",
      capital: "القاهرة",
      majorCities: ["القاهرة","دمشق","حلب","القدس","الإسكندرية","عكا","غزة","صفد","طرابلس","الكرك"],
      majorFigures: ["شجر الدر","قطز","بيبرس","قلاوون","الأشرف خليل","الناصر محمد","برقوق","برسباي","قايتباي","قانصوه الغوري","طومان باي"],
      majorBattles: ["عين جالوت","المنصورة","حصار عكا","حمص الثانية","مرج دابق","الريدانية"],
      majorEvents: ["قيام الدولة","هزيمة المغول","نهاية الصليبيين","ازدهار القاهرة","سقوط الدولة"],
    },
    bridges: { era: "mamluk" },
  }),

  // ---------- FIGURES (Sultans & Statesmen) ----------
  ...FIGURE_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `mamluk.figure.${slug}`,
    title, latin, type: "figure", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["mamluk.state.mamluk", ...related],
    unlockables: [{ kind: "figure", refId: `mamluk.figure.${slug}`, label: title }],
    image: { alt: title, glyph: "🦁", tone: "from-amber-700/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "epic",
    meta: { titles: [title] },
    bridges: {
      characterId: slug === "baybars" ? "baybars" : undefined,
      era: "mamluk",
    },
  })),

  // ---------- SCHOLARS ----------
  ...SCHOLAR_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `mamluk.figure.${slug}`,
    title, latin, type: "figure", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["mamluk.state.mamluk", ...related],
    unlockables: [{ kind: "figure", refId: `mamluk.figure.${slug}`, label: title }],
    image: { alt: title, glyph: "📚", tone: "from-emerald-800/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "epic",
    meta: { kind: "scholar", titles: [title] },
    bridges: { era: "mamluk" },
  })),

  // ---------- CITIES ----------
  ...CITY_IDS.map(([slug, title, latin, description, startYear, endYear, related]) => E({
    id: `mamluk.city.${slug}`,
    title, latin, type: "city", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["mamluk.state.mamluk", ...related],
    unlockables: [{ kind: "city", refId: `mamluk.city.${slug}`, label: title }],
    image: { alt: title, glyph: "🏙️", tone: "from-amber-700/30 to-stone-900" },
    timelinePosition: startYear,
    rarity: "rare",
    bridges: { cityId: slug, era: "mamluk" },
  })),

  // ---------- BATTLES ----------
  ...BATTLE_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `mamluk.battle.${slug}`,
    title, latin, type: "battle", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["mamluk.state.mamluk", ...related],
    unlockables: [{ kind: "battle", refId: `mamluk.battle.${slug}`, label: title }],
    image: { alt: title, glyph: "⚔️", tone: "from-red-800/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "epic",
    bridges: {
      battleId: slug === "ain-jalut" ? "b-ain-jalut" : undefined,
      era: "mamluk",
    },
  })),

  // ---------- EVENTS ----------
  ...EVENT_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `mamluk.event.${slug}`,
    title, latin, type: "event", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["mamluk.state.mamluk", ...related],
    unlockables: [{ kind: "event", refId: `mamluk.event.${slug}`, label: title }],
    image: { alt: title, glyph: "📜", tone: "from-emerald-800/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "rare",
    bridges: { era: "mamluk" },
  })),

  // ---------- LANDMARKS ----------
  ...LANDMARK_IDS.map(([slug, title, latin, description, startYear, endYear, related]) => E({
    id: `mamluk.landmark.${slug}`,
    title, latin, type: "landmark", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["mamluk.state.mamluk", ...related],
    unlockables: [{ kind: "landmark", refId: `mamluk.landmark.${slug}`, label: title }],
    image: { alt: title, glyph: "🕌", tone: "from-amber-700/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "epic",
    bridges: { era: "mamluk" },
  })),

  // ---------- ARTIFACTS ----------
  ...ARTIFACT_IDS.map(([slug, title, latin, description, startYear, endYear, glyph, rarity, related]) => E({
    id: `mamluk.artifact.${slug}`,
    title, latin, type: "artifact", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["mamluk.state.mamluk", ...related],
    unlockables: [{ kind: "artifact", refId: `mamluk.artifact.${slug}`, label: title }],
    image: { alt: title, glyph: glyph as string, tone: "from-amber-700/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: rarity as "common" | "rare" | "epic" | "legendary",
    bridges: { era: "mamluk" },
  })),

  // ---------- ACHIEVEMENTS ----------
  ...ACHIEVEMENT_IDS.map(([slug, title, latin, description, related]) => E({
    id: `mamluk.achievement.${slug}`,
    title, latin, type: "achievement", description,
    period: { label: "١٢٥٠ – ١٥١٧ م", startYear: 1250, endYear: 1517 },
    relatedEntities: ["mamluk.state.mamluk", ...related],
    unlockables: [{ kind: "title", refId: `mamluk.achievement.${slug}`, label: title }],
    image: { alt: title, glyph: "🏅", tone: "from-amber-600/40 to-stone-900" },
    timelinePosition: 1350,
    rarity: "legendary",
    bridges: { era: "mamluk" },
  })),

  // ---------- FUTURE CAMPAIGN PLACEHOLDERS (locked) ----------
  ...FUTURE_CAMPAIGN_IDS.map(([slug, title, startYear, endYear, description]) => E({
    id: `mamluk.event.${slug}`,
    title, type: "event", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["mamluk.state.mamluk"],
    unlockables: [],
    image: { alt: title, glyph: "🔒", tone: "from-stone-700/40 to-slate-900" },
    timelinePosition: startYear,
    rarity: "legendary",
    meta: { locked: true, kind: "campaign-placeholder" },
    bridges: { era: "mamluk" },
  })),
];

export const MAMLUK_PACK: ContentPack = {
  id: "pack-004-mamluk",
  order: 4,
  title: "الدولة المملوكية",
  subtitle: "المجموعة ٤ · كاسرو المغول وحماة الشام",
  summary:
    "حزمة محتوى تاريخية شاملة عن الدولة المملوكية: قيامها بعد المنصورة، عين جالوت، نهاية الصليبيين، ازدهار القاهرة، حتى سقوطها على يد العثمانيين.",
  era: "mamluk",
  period: { label: "١٢٥٠ – ١٥١٧ م", startYear: 1250, endYear: 1517 },
  cover: { alt: "غلاف الدولة المملوكية", glyph: "🦁", tone: "from-amber-700/40 to-stone-900" },
  entities,
};