import type { ContentPack, PackEntity } from "./types";

// ============================================================
// Content Pack 011 — دولة الموحدين (Almohad State)
// 1121 – 1269 CE. Capital: Marrakesh.
// Strong cross-pack links to Andalusia, Almoravid, Ayyubid, Mamluk packs.
// ============================================================

const E = (e: PackEntity): PackEntity => e;

// ---------- FIGURES ----------
const FIGURE_IDS = [
  ["ibn-tumart","محمد بن تومرت (المهدي)","Muhammad ibn Tumart (al-Mahdi)",1080,1130,
    "مؤسس حركة الموحدين، فقيه أشعري من قبائل المصامدة في الأطلس، تتلمذ على الغزالي في المشرق، أعلن المهدوية وأقام دعوة التوحيد في تنمل ضدّ المرابطين.",
    ["muwahhidun.event.dawa","muwahhidun.event.foundation","muwahhidun.figure.abd-al-mumin","murabitun.event.almohad-rise","murabitun.figure.ali-yusuf","muwahhidun.city.marrakesh"]],
  ["abd-al-mumin","عبد المؤمن بن علي","Abd al-Mu'min ibn Ali",1094,1163,
    "أوّل خلفاء الموحدين بعد ابن تومرت، فاتح مراكش سنة ٥٤١هـ فأنهى دولة المرابطين، وحّد المغرب من برقة إلى المحيط، وعبر إلى الأندلس.",
    ["muwahhidun.event.fall-murabitun","muwahhidun.event.foundation","muwahhidun.event.unify-maghrib","muwahhidun.event.control-andalus","muwahhidun.battle.marrakesh-conquest","muwahhidun.battle.bijaya-conquest","muwahhidun.battle.shilb-siege","muwahhidun.figure.ibn-tumart","muwahhidun.figure.abu-yaqub-yusuf","muwahhidun.city.marrakesh","muwahhidun.city.bijaya","muwahhidun.city.tlemcen","muwahhidun.artifact.sword-abd-mumin","muwahhidun.artifact.muwahhid-banner","murabitun.state.murabitun","murabitun.figure.tashfin-ali","murabitun.event.fall"]],
  ["abu-yaqub-yusuf","أبو يعقوب يوسف","Abu Yaqub Yusuf",1135,1184,
    "ثاني خلفاء الموحدين، راعي العلم والفلسفة، قرّب ابن طفيل وابن رشد، وسّع الدولة في الأندلس، استُشهد في حصار شنترين.",
    ["muwahhidun.event.golden-age","muwahhidun.figure.abd-al-mumin","muwahhidun.figure.yaqub-al-mansur","muwahhidun.figure.ibn-tufayl","muwahhidun.figure.ibn-rushd","muwahhidun.event.control-andalus","muwahhidun.city.seville","muwahhidun.figure.yusuf-abd-mumin"]],
  ["yaqub-al-mansur","أبو يوسف يعقوب المنصور","Abu Yusuf Ya'qub al-Mansur",1160,1199,
    "ذروة الدولة الموحدية، انتصر في الأرك سنة ٥٩١هـ على ألفونسو الثامن، تلقّب بأمير المؤمنين والمنصور، بنى الخيرالدة وصومعة الكتبية وبدأ صومعة حسان.",
    ["muwahhidun.battle.al-arak","muwahhidun.event.al-arak-event","muwahhidun.event.golden-age","muwahhidun.landmark.kutubiyya-minaret","muwahhidun.landmark.kutubiyya-mosque","muwahhidun.landmark.giralda","muwahhidun.landmark.hassan-tower","muwahhidun.landmark.oudaya-kasbah","muwahhidun.landmark.rabat-walls","muwahhidun.figure.abu-yaqub-yusuf","muwahhidun.figure.al-nasir","muwahhidun.figure.alfonso-viii","muwahhidun.figure.ibn-rushd","muwahhidun.artifact.sealed-decree","muwahhidun.artifact.al-arak-manuscript","muwahhidun.artifact.al-arak-medal","muwahhidun.city.marrakesh","muwahhidun.city.rabat","muwahhidun.city.seville","andalusia.battle.al-arak","andalusia.event.muwahhidun-entry","andalusia.landmark.giralda","andalusia.figure.yaqub-al-mansur"]],
  ["al-nasir","محمد الناصر","Muhammad al-Nasir",1182,1213,
    "خليفة الموحدين الذي هُزم في العقاب سنة ٦٠٩هـ أمام تحالف ملوك إسبانيا، نكسة كبرى أفقدت الدولة هيبتها وعجّلت بسقوط الأندلس.",
    ["muwahhidun.battle.al-uqab","muwahhidun.event.al-uqab-event","muwahhidun.event.decline-begins","muwahhidun.figure.yaqub-al-mansur","muwahhidun.figure.alfonso-viii","muwahhidun.figure.idris-al-mamun","muwahhidun.artifact.al-uqab-manuscript","andalusia.battle.al-uqab","muwahhidun.city.seville"]],
  ["idris-al-mamun","إدريس المأمون","Idris al-Ma'mun",1185,1232,
    "خليفة موحدي تخلّى عن عقيدة ابن تومرت وحاول العودة إلى المالكية السنية، شهد عهده تفكّك الدولة ودخول بني مرين على المغرب.",
    ["muwahhidun.event.fragmentation","muwahhidun.event.decline-begins","muwahhidun.figure.al-nasir","muwahhidun.figure.al-rashid","muwahhidun.city.marrakesh"]],
  ["al-rashid","عبد الواحد الرشيد","Abd al-Wahid al-Rashid",1218,1242,
    "خليفة موحدي حكم في زمن انحسار شديد، اقتصر سلطانه على مراكش وما حولها، انكسر أمام بني مرين في فحص البلوط.",
    ["muwahhidun.battle.fahs-al-ballut","muwahhidun.event.fragmentation","muwahhidun.figure.idris-al-mamun","muwahhidun.city.marrakesh","muwahhidun.event.decline-begins"]],
  ["yusuf-abd-mumin","يوسف بن عبد المؤمن","Yusuf ibn Abd al-Mu'min",1135,1184,
    "اسم آخر يُطلق على الخليفة أبي يعقوب يوسف، ابن مؤسس الدولة الموحدية، راعي الفلاسفة وقاهر البرتغاليين.",
    ["muwahhidun.figure.abu-yaqub-yusuf","muwahhidun.figure.abd-al-mumin","muwahhidun.event.golden-age","muwahhidun.battle.shilb-siege"]],
  ["abu-said-othman","أبو سعيد عثمان الموحدي","Abu Sa'id Uthman",1140,1199,
    "أمير موحدي على إشبيلية في عهد المنصور، عُرف بالعدل والعمارة، عاصر بناء الخيرالدة وكان واليًا على الأندلس الجنوبية.",
    ["muwahhidun.city.seville","muwahhidun.landmark.giralda","muwahhidun.figure.yaqub-al-mansur","muwahhidun.event.golden-age","muwahhidun.event.control-andalus","andalusia.city.seville","andalusia.landmark.giralda"]],
  ["alfonso-viii","ألفونسو الثامن","Alfonso VIII of Castile",1155,1214,
    "ملك قشتالة، هزمه المنصور في الأرك سنة ٥٩١هـ، ثم انتصر في العقاب سنة ٦٠٩هـ بتحالف صليبي عام، نقطة تحوّل سقوط الأندلس.",
    ["muwahhidun.battle.al-arak","muwahhidun.battle.al-uqab","muwahhidun.figure.yaqub-al-mansur","muwahhidun.figure.al-nasir","muwahhidun.event.al-arak-event","muwahhidun.event.al-uqab-event","andalusia.battle.al-arak","andalusia.battle.al-uqab"]],
] as const;

// ---------- SCHOLARS ----------
const SCHOLAR_IDS = [
  ["ibn-rushd","ابن رشد الحفيد","Ibn Rushd (Averroes)",1126,1198,
    "الفيلسوف والقاضي الأكبر في عصر الموحدين، شارح أرسطو الأعظم، صاحب بداية المجتهد وفصل المقال، قرّبه أبو يعقوب يوسف ثم نُكِب في عهد المنصور.",
    ["muwahhidun.figure.abu-yaqub-yusuf","muwahhidun.figure.yaqub-al-mansur","muwahhidun.figure.ibn-tufayl","muwahhidun.event.golden-age","muwahhidun.city.cordoba","muwahhidun.city.marrakesh","andalusia.city.cordoba"]],
  ["ibn-tufayl","ابن طفيل","Ibn Tufayl",1105,1185,
    "فيلسوف الأندلس في عصر الموحدين، صاحب حيّ بن يقظان، طبيب أبي يعقوب يوسف، وهو من قدّم ابن رشد للخليفة.",
    ["muwahhidun.figure.abu-yaqub-yusuf","muwahhidun.figure.ibn-rushd","muwahhidun.event.golden-age","muwahhidun.city.marrakesh"]],
  ["ibn-al-baitar","ابن البيطار","Ibn al-Baytar",1197,1248,
    "إمام علم النبات والصيدلة في عصره، صاحب الجامع لمفردات الأدوية والأغذية، رحل من مالقة إلى الموحدين ثم إلى الأيوبيين بدمشق.",
    ["muwahhidun.figure.yaqub-al-mansur","muwahhidun.figure.al-nasir","andalusia.figure.ibn-al-baitar","ayyubid.state.ayyubid","muwahhidun.city.seville"]],
  ["ibn-zuhr","أبو بكر بن زهر","Abu Bakr ibn Zuhr",1110,1162,
    "طبيب الأندلس الكبير في عصر الموحدين، من أسرة بني زهر الإشبيلية الشهيرة، طبيب أبي يعقوب يوسف، صاحب تجارب طبية رائدة.",
    ["muwahhidun.figure.abu-yaqub-yusuf","muwahhidun.figure.ibn-tufayl","muwahhidun.city.seville","muwahhidun.event.golden-age","andalusia.city.seville"]],
  ["al-shatibi","أبو إسحاق الشاطبي","Abu Ishaq al-Shatibi",1320,1388,
    "أصولي الأندلس الكبير في غرناطة بعد سقوط الموحدين، صاحب الموافقات والاعتصام، حافظ على ميراث الفقه المالكي المغربي الأندلسي.",
    ["muwahhidun.event.fall","muwahhidun.event.fragmentation","andalusia.city.granada","muwahhidun.city.granada"]],
  ["ibn-madda","ابن مضاء القرطبي","Ibn Mada' al-Qurtubi",1119,1196,
    "قاضي قضاة الموحدين، نحوي ثائر على نظرية العامل، صاحب كتاب الرد على النحاة، من أبرز فقهاء بلاط المنصور.",
    ["muwahhidun.figure.yaqub-al-mansur","muwahhidun.event.golden-age","muwahhidun.city.cordoba","muwahhidun.city.marrakesh","andalusia.city.cordoba"]],
  ["ibn-rushd-jadd","أبو الوليد ابن رشد الجدّ","Abu al-Walid Ibn Rushd al-Jadd",1058,1126,
    "جدّ الفيلسوف، قاضي قضاة قرطبة في زمن المرابطين، إمام المالكية في زمنه، عاصر بدايات دعوة ابن تومرت قبل قيام دولة الموحدين.",
    ["muwahhidun.figure.ibn-rushd","muwahhidun.figure.ibn-tumart","muwahhidun.city.cordoba","murabitun.figure.ibn-rushd-jadd","murabitun.figure.ali-yusuf","andalusia.city.cordoba"]],
  ["ibn-al-arabi","ابن العربي الحاتمي","Ibn al-Arabi al-Hatimi",1165,1240,
    "الشيخ الأكبر، صوفي الأندلس وفيلسوفها، نشأ في إشبيلية في عصر الموحدين، رحل إلى المشرق وألّف الفتوحات المكية وفصوص الحكم في زمن الأيوبيين.",
    ["muwahhidun.figure.yaqub-al-mansur","muwahhidun.figure.al-nasir","muwahhidun.event.golden-age","muwahhidun.city.seville","ayyubid.state.ayyubid","andalusia.city.seville"]],
] as const;

// ---------- CITIES ----------
const CITY_IDS = [
  ["marrakesh","مراكش","Marrakesh",
    "عاصمة الموحدين بعد إسقاطهم للمرابطين، حاضرة الخلافة الغربية، فيها صومعة الكتبية وقصورها الكبرى وقبر ابن تومرت في تنمل قربها.",
    1147,1269,["muwahhidun.figure.abd-al-mumin","muwahhidun.figure.yaqub-al-mansur","muwahhidun.figure.ibn-tumart","muwahhidun.landmark.kutubiyya-minaret","muwahhidun.landmark.kutubiyya-mosque","muwahhidun.landmark.marrakesh-palaces","muwahhidun.battle.marrakesh-conquest","muwahhidun.event.fall-murabitun","murabitun.city.marrakesh"]],
  ["fes","فاس","Fes",
    "حاضرة المغرب الأقصى الأقدم، انتقلت للموحدين بعد المرابطين، فيها مسجد القرويين وحلقاته العلمية في عصر ابن رشد وابن طفيل.",
    1145,1269,["muwahhidun.figure.abd-al-mumin","muwahhidun.event.unify-maghrib","muwahhidun.event.golden-age","murabitun.city.fes"]],
  ["rabat","الرباط","Rabat (Ribat al-Fath)",
    "أسسها عبد المؤمن كرباطٍ على ساحل المحيط وأكملها المنصور، اتخذها قاعدة العبور إلى الأندلس، فيها برج حسان وقصبة الوداية.",
    1150,1269,["muwahhidun.figure.abd-al-mumin","muwahhidun.figure.yaqub-al-mansur","muwahhidun.landmark.hassan-tower","muwahhidun.landmark.oudaya-kasbah","muwahhidun.landmark.rabat-walls","muwahhidun.event.control-andalus"]],
  ["seville","إشبيلية","Seville",
    "عاصمة الموحدين في الأندلس، فيها الخيرالدة (صومعة جامعها الكبير)، ومنها دارت معركتا الأرك والعقاب، آخر حواضر الموحدين في الأندلس.",
    1147,1248,["muwahhidun.figure.yaqub-al-mansur","muwahhidun.figure.abu-yaqub-yusuf","muwahhidun.figure.abu-said-othman","muwahhidun.figure.ibn-zuhr","muwahhidun.figure.ibn-al-arabi","muwahhidun.landmark.giralda","muwahhidun.landmark.andalus-fortresses","muwahhidun.battle.seville-siege","muwahhidun.event.control-andalus","andalusia.city.seville","andalusia.landmark.giralda"]],
  ["cordoba","قرطبة","Cordoba",
    "حاضرة الأندلس العلمية، تولّاها الموحدون بعد المرابطين، فيها قضى ابن رشد ووُلد، وحلقاتها استمرت تحت رعاية المنصور وأبي يعقوب يوسف.",
    1148,1236,["muwahhidun.figure.ibn-rushd","muwahhidun.figure.ibn-madda","muwahhidun.figure.ibn-rushd-jadd","muwahhidun.event.control-andalus","andalusia.city.cordoba"]],
  ["granada","غرناطة","Granada",
    "حاضرة الأندلس الجنوبية، ورثت في زمن الموحدين قوة كبرى قبل قيام بني الأحمر، فيها بقيت آثار العمارة الموحدية في القصور والأسوار.",
    1147,1238,["muwahhidun.event.control-andalus","muwahhidun.landmark.andalus-fortresses","andalusia.city.granada","muwahhidun.figure.al-shatibi"]],
  ["sala","سلا","Sala (Salé)",
    "ميناء المحيط أمام الرباط، حاضرة الموحدين البحرية، منها انطلقت أساطيلهم إلى الأندلس وقاومت غارات النصارى.",
    1150,1269,["muwahhidun.city.rabat","muwahhidun.event.control-andalus","muwahhidun.figure.yaqub-al-mansur"]],
  ["ceuta","سبتة","Ceuta",
    "بوابة العبور إلى الأندلس على المضيق، تنازعها الموحدون مع البنو غانية ثم استقرّت لهم، ميناء العسكر والتجارة.",
    1148,1269,["muwahhidun.figure.abd-al-mumin","muwahhidun.event.control-andalus","muwahhidun.event.unify-maghrib","murabitun.city.ceuta"]],
  ["tlemcen","تلمسان","Tlemcen",
    "حاضرة المغرب الأوسط، فتحها عبد المؤمن في طريقه إلى إفريقية، صارت لاحقًا قاعدة بني عبد الواد بعد سقوط الموحدين.",
    1145,1269,["muwahhidun.figure.abd-al-mumin","muwahhidun.event.unify-maghrib","muwahhidun.city.bijaya","muwahhidun.event.fragmentation"]],
  ["bijaya","بجاية","Bejaia (Bijaya)",
    "حاضرة الساحل الجزائري، فتحها عبد المؤمن سنة ٥٤٧هـ من الحماديين، ضمّ بها الموحدون المغرب الأوسط إلى دولتهم.",
    1152,1269,["muwahhidun.figure.abd-al-mumin","muwahhidun.battle.bijaya-conquest","muwahhidun.event.unify-maghrib"]],
] as const;

// ---------- BATTLES ----------
const BATTLE_IDS = [
  ["al-arak","معركة الأرك","Battle of Alarcos",1195,1195,
    "نصر يعقوب المنصور الفاصل على ألفونسو الثامن في الأرك سنة ٥٩١هـ، أعظم انتصارات الموحدين، أعاد هيبة الإسلام في الأندلس بعد عقودٍ من الانتكاسات.",
    ["muwahhidun.figure.yaqub-al-mansur","muwahhidun.figure.alfonso-viii","muwahhidun.event.al-arak-event","muwahhidun.event.golden-age","muwahhidun.artifact.al-arak-manuscript","muwahhidun.artifact.al-arak-medal","andalusia.battle.al-arak"]],
  ["al-uqab","معركة العقاب","Battle of Las Navas de Tolosa",1212,1212,
    "هزيمة محمد الناصر أمام تحالف ملوك إسبانيا في حصن العقاب سنة ٦٠٩هـ، نكسة كبرى أعجلت بسقوط الأندلس وانهيار الدولة الموحدية.",
    ["muwahhidun.figure.al-nasir","muwahhidun.figure.alfonso-viii","muwahhidun.event.al-uqab-event","muwahhidun.event.decline-begins","muwahhidun.artifact.al-uqab-manuscript","andalusia.battle.al-uqab"]],
  ["shilb-siege","حصار شِلب","Siege of Silves (Shilb)",1191,1191,
    "استعاد يعقوب المنصور شِلب من البرتغاليين في غرب الأندلس، أحد انتصارات عصره قبيل الأرك بأربع سنوات.",
    ["muwahhidun.figure.yaqub-al-mansur","muwahhidun.figure.abu-yaqub-yusuf","muwahhidun.event.control-andalus","muwahhidun.event.golden-age"]],
  ["seville-siege","حصار إشبيلية","Siege of Seville",1248,1248,
    "حصار فرناندو الثالث القشتالي لإشبيلية حتى سقوطها سنة ٦٤٦هـ، انتهت بها سيادة الموحدين في الأندلس وانتقل أهلها إلى غرناطة والمغرب.",
    ["muwahhidun.event.fragmentation","muwahhidun.city.seville","muwahhidun.landmark.giralda","muwahhidun.event.decline-begins","andalusia.event.fall-seville","andalusia.city.seville"]],
  ["bijaya-conquest","فتح بجاية","Conquest of Bejaia",1152,1152,
    "فتح عبد المؤمن بجاية من الحماديين سنة ٥٤٧هـ، أحد مراحل توحيد المغرب الأوسط في الدولة الموحدية الفتيّة.",
    ["muwahhidun.figure.abd-al-mumin","muwahhidun.city.bijaya","muwahhidun.event.unify-maghrib"]],
  ["marrakesh-conquest","فتح مراكش","Conquest of Marrakesh",1147,1147,
    "حاصر عبد المؤمن مراكش وفتحها سنة ٥٤١هـ فأنهى دولة المرابطين وأقام الخلافة الموحدية على أنقاضها.",
    ["muwahhidun.figure.abd-al-mumin","muwahhidun.city.marrakesh","muwahhidun.event.fall-murabitun","muwahhidun.event.foundation","murabitun.event.fall","murabitun.figure.tashfin-ali"]],
  ["wadi-makhazin-early","معركة وادي المخازن المبكرة","Early Battle of Wadi al-Makhazin",1238,1238,
    "مناوشة بحرية على وادي المخازن بين أساطيل الموحدين والبرتغاليين، أحد مظاهر الصراع البحري في طور انحسار الدولة.",
    ["muwahhidun.event.fragmentation","muwahhidun.event.decline-begins","muwahhidun.figure.idris-al-mamun"]],
  ["fahs-al-ballut","معركة فحص البلوط","Battle of Fahs al-Ballut",1238,1238,
    "موقعة مغربية بين الموحدين وقوّات بني مرين الصاعدة في فحص البلوط قرب فاس، خسرها الرشيد فبدأ صعود المرينيين على حساب الموحدين.",
    ["muwahhidun.figure.al-rashid","muwahhidun.event.fragmentation","muwahhidun.city.fes","muwahhidun.event.decline-begins"]],
] as const;

// ---------- EVENTS ----------
const EVENT_IDS = [
  ["dawa","قيام دعوة الموحدين","Rise of the Almohad Movement",1121,1130,
    "أطلق ابن تومرت دعوته في جبال الأطلس على أساس التوحيد الأشعري ومحاربة بدع المرابطين، أسّس تنظيم العشرة والخمسين والقبائل في تنمل.",
    ["muwahhidun.figure.ibn-tumart","muwahhidun.figure.abd-al-mumin","muwahhidun.event.foundation","murabitun.event.almohad-rise","murabitun.figure.ali-yusuf"]],
  ["fall-murabitun","سقوط المرابطين","Fall of the Almoravids",1145,1147,
    "تتابعت هزائم المرابطين أمام الموحدين، فسقطت فاس ثم تلمسان ثم وهران ثم مراكش سنة ٥٤١هـ على يد عبد المؤمن، فانتهت دولة المرابطين.",
    ["muwahhidun.figure.abd-al-mumin","muwahhidun.battle.marrakesh-conquest","muwahhidun.event.foundation","murabitun.event.fall","murabitun.figure.tashfin-ali","murabitun.state.murabitun"]],
  ["foundation","تأسيس الدولة الموحدية","Founding of the Almohad State",1147,1147,
    "بدخول عبد المؤمن مراكش وإسقاط المرابطين قامت دولة الموحدين وحلّت محلّ خصومها في المغرب الأقصى، أوّل دولة بربرية تتلقّب بالخلافة.",
    ["muwahhidun.figure.abd-al-mumin","muwahhidun.figure.ibn-tumart","muwahhidun.event.fall-murabitun","muwahhidun.city.marrakesh","muwahhidun.event.unify-maghrib"]],
  ["unify-maghrib","توحيد المغرب","Unification of the Maghreb",1147,1160,
    "وحّد عبد المؤمن المغرب من برقة شرقًا إلى المحيط غربًا، أول مرة منذ الفتوح الأولى تجتمع المغارب الثلاثة تحت دولة واحدة.",
    ["muwahhidun.figure.abd-al-mumin","muwahhidun.battle.bijaya-conquest","muwahhidun.city.tlemcen","muwahhidun.city.bijaya","muwahhidun.city.fes","muwahhidun.city.ceuta"]],
  ["control-andalus","السيطرة على الأندلس","Almohad Control of al-Andalus",1147,1212,
    "عبر الموحدون من سبتة وضمّوا الأندلس بعد الفوضى التي تلت ضعف المرابطين، صارت إشبيلية عاصمتهم الأندلسية حتى العقاب.",
    ["muwahhidun.figure.abd-al-mumin","muwahhidun.figure.abu-yaqub-yusuf","muwahhidun.figure.yaqub-al-mansur","muwahhidun.city.seville","muwahhidun.city.cordoba","muwahhidun.city.granada","muwahhidun.battle.shilb-siege","andalusia.event.muwahhidun-entry"]],
  ["al-arak-event","معركة الأرك","Day of Alarcos",1195,1195,
    "نصر يعقوب المنصور التاريخي على ألفونسو الثامن، رفع المعنويات الإسلامية في الأندلس وأخّر سقوطها قرنين كاملين.",
    ["muwahhidun.battle.al-arak","muwahhidun.figure.yaqub-al-mansur","muwahhidun.figure.alfonso-viii","muwahhidun.event.golden-age","andalusia.battle.al-arak"]],
  ["golden-age","عصر الازدهار الموحدي","Almohad Golden Age",1163,1199,
    "ذروة الدولة في عهد أبي يعقوب يوسف ويعقوب المنصور: ابن رشد وابن طفيل وابن زهر وابن العربي، صومعة الكتبية والخيرالدة وبرج حسان.",
    ["muwahhidun.figure.abu-yaqub-yusuf","muwahhidun.figure.yaqub-al-mansur","muwahhidun.figure.ibn-rushd","muwahhidun.figure.ibn-tufayl","muwahhidun.figure.ibn-zuhr","muwahhidun.landmark.kutubiyya-minaret","muwahhidun.landmark.giralda","muwahhidun.landmark.hassan-tower","muwahhidun.event.al-arak-event"]],
  ["build-kutubiyya-minaret","بناء صومعة الكتبية","Building of the Kutubiyya Minaret",1184,1199,
    "أمر يعقوب المنصور ببناء صومعة الكتبية في مراكش، تحفة العمارة الموحدية وأخت الخيرالدة وحسان، رمز الخلافة الموحدية.",
    ["muwahhidun.figure.yaqub-al-mansur","muwahhidun.landmark.kutubiyya-minaret","muwahhidun.landmark.kutubiyya-mosque","muwahhidun.city.marrakesh","muwahhidun.event.golden-age"]],
  ["build-giralda","بناء الخيرالدة","Building of the Giralda",1184,1198,
    "بنى المنصور صومعة جامع إشبيلية الكبير (الخيرالدة)، أعظم منارة في الأندلس، تحوّلت إلى برج كاتدرائية إشبيلية بعد سقوط المدينة.",
    ["muwahhidun.figure.yaqub-al-mansur","muwahhidun.landmark.giralda","muwahhidun.city.seville","muwahhidun.event.golden-age","andalusia.landmark.giralda","andalusia.city.seville"]],
  ["al-uqab-event","معركة العقاب","Day of Las Navas",1212,1212,
    "تحالف ألفونسو الثامن مع ملوك أراغون ونافار والبرتغال وفرنسا ضد محمد الناصر، انكسر الموحدون فبدأ سقوط الأندلس وتفكّك الدولة.",
    ["muwahhidun.battle.al-uqab","muwahhidun.figure.al-nasir","muwahhidun.figure.alfonso-viii","muwahhidun.event.decline-begins","andalusia.battle.al-uqab"]],
  ["decline-begins","بداية الانحسار","Beginning of the Decline",1213,1230,
    "بعد العقاب فقد الموحدون هيبتهم، خسروا مدن الأندلس واحدة تلو الأخرى أمام قشتالة وليون وأراغون والبرتغال، وبدأت القبائل المغربية تنفصل.",
    ["muwahhidun.event.al-uqab-event","muwahhidun.figure.al-nasir","muwahhidun.figure.idris-al-mamun","muwahhidun.event.fragmentation"]],
  ["fragmentation","تفكك الدولة","Fragmentation of the State",1230,1248,
    "تنازع الخلفاء وانفصلت الفروع: بنو مرين في فاس، بنو حفص في تونس، بنو عبد الواد في تلمسان، بنو الأحمر في غرناطة، تقلّص نفوذ الموحدين إلى مراكش وحدها.",
    ["muwahhidun.figure.idris-al-mamun","muwahhidun.figure.al-rashid","muwahhidun.battle.fahs-al-ballut","muwahhidun.battle.seville-siege","muwahhidun.event.fall"]],
  ["fall","سقوط الدولة الموحدية","Fall of the Almohad State",1269,1269,
    "سقطت مراكش في يد بني مرين سنة ٦٦٨هـ بعد قرنٍ ونصف من الحكم، فانتهت دولة الموحدين وبدأت دولة بني مرين في المغرب.",
    ["muwahhidun.figure.al-rashid","muwahhidun.event.fragmentation","muwahhidun.city.marrakesh","muwahhidun.event.decline-begins"]],
] as const;

// ---------- LANDMARKS ----------
const LANDMARK_IDS = [
  ["kutubiyya-minaret","صومعة الكتبية","Kutubiyya Minaret",
    "منارة جامع الكتبية في مراكش، أيقونة العمارة الموحدية، شقيقة الخيرالدة وبرج حسان، بنيت في عهد المنصور سنة ٥٩٢هـ.",
    1184,1269,["muwahhidun.figure.yaqub-al-mansur","muwahhidun.landmark.kutubiyya-mosque","muwahhidun.city.marrakesh","muwahhidun.event.build-kutubiyya-minaret","muwahhidun.event.golden-age"]],
  ["giralda","الخيرالدة","La Giralda",
    "صومعة جامع إشبيلية الموحدي الكبير، بناها المنصور، أعظم آثار الموحدين في الأندلس، تحوّلت إلى برج كاتدرائية بعد سقوط المدينة.",
    1184,1269,["muwahhidun.figure.yaqub-al-mansur","muwahhidun.city.seville","muwahhidun.event.build-giralda","muwahhidun.event.golden-age","andalusia.landmark.giralda","andalusia.city.seville","muwahhidun.battle.seville-siege"]],
  ["hassan-tower","برج حسان","Hassan Tower",
    "صومعة جامع حسان الموحدي بالرباط، شرع فيها المنصور وأراد أن يجعلها أعظم مسجد في الإسلام، توفي قبل إتمامها فبقيت ناقصة.",
    1195,1199,["muwahhidun.figure.yaqub-al-mansur","muwahhidun.city.rabat","muwahhidun.event.golden-age","muwahhidun.landmark.rabat-walls"]],
  ["oudaya-kasbah","قصبة الوداية","Kasbah of the Udaya",
    "قلعة الرباط الموحدية على المحيط، بناها عبد المؤمن وأتمها المنصور، قاعدة العبور إلى الأندلس وحامية المدينة الجديدة.",
    1150,1199,["muwahhidun.figure.abd-al-mumin","muwahhidun.figure.yaqub-al-mansur","muwahhidun.city.rabat","muwahhidun.landmark.rabat-walls","muwahhidun.event.control-andalus"]],
  ["rabat-walls","أسوار الرباط","Walls of Rabat",
    "أسوار الرباط التي بناها المنصور لتجعلها عاصمة العبور إلى الأندلس، حلقات الدفاع الموحدية الكبرى على المحيط.",
    1184,1199,["muwahhidun.figure.yaqub-al-mansur","muwahhidun.city.rabat","muwahhidun.landmark.oudaya-kasbah","muwahhidun.landmark.hassan-tower"]],
  ["kutubiyya-mosque","جامع الكتبية","Kutubiyya Mosque",
    "جامع الموحدين الكبير في مراكش، بناه عبد المؤمن على أنقاض جامع المرابطين، فيه صومعة الكتبية الشهيرة وتحفة العمارة الموحدية.",
    1147,1199,["muwahhidun.figure.abd-al-mumin","muwahhidun.figure.yaqub-al-mansur","muwahhidun.landmark.kutubiyya-minaret","muwahhidun.city.marrakesh","muwahhidun.event.build-kutubiyya-minaret"]],
  ["marrakesh-palaces","قصور مراكش الموحدية","Almohad Palaces of Marrakesh",
    "قصور الخلافة الموحدية في مراكش، فيها مجالس ابن رشد وابن طفيل وحلقات العلم، مركز الحكم في ذروة الدولة.",
    1147,1269,["muwahhidun.city.marrakesh","muwahhidun.figure.abd-al-mumin","muwahhidun.figure.yaqub-al-mansur","muwahhidun.figure.abu-yaqub-yusuf","muwahhidun.figure.ibn-rushd","muwahhidun.event.golden-age"]],
  ["andalus-fortresses","حصون الأندلس الموحدية","Almohad Fortresses of al-Andalus",
    "سلسلة حصون موحدية في الأندلس من إشبيلية إلى غرناطة، عزّزت الدفاع عن الجبهة بعد الزلاقة وقبل العقاب.",
    1147,1248,["muwahhidun.city.seville","muwahhidun.city.granada","muwahhidun.city.cordoba","muwahhidun.event.control-andalus","muwahhidun.battle.al-arak","muwahhidun.battle.al-uqab"]],
] as const;

// ---------- ARTIFACTS ----------
const ARTIFACT_IDS = [
  ["muwahhid-banner","راية الموحدين","Banner of the Almohads",
    "الراية الحمراء للموحدين التي رُفعت من تنمل إلى مراكش إلى الأرك، رمز الخلافة الغربية الكبرى.",
    1121,1269,"🏴","epic",["muwahhidun.figure.ibn-tumart","muwahhidun.figure.abd-al-mumin","muwahhidun.figure.yaqub-al-mansur","muwahhidun.event.foundation"]],
  ["sword-abd-mumin","سيف عبد المؤمن","Sword of Abd al-Mu'min",
    "سيف مؤسس الخلافة الموحدية، حمله في فتح مراكش وتوحيد المغرب، أيقونة قيام الدولة.",
    1147,1163,"🗡️","legendary",["muwahhidun.figure.abd-al-mumin","muwahhidun.battle.marrakesh-conquest","muwahhidun.event.foundation","muwahhidun.event.unify-maghrib"]],
  ["muwahhid-seal","ختم الدولة الموحدية","Seal of the Almohad State",
    "ختم خلفاء الموحدين على مراسيمهم إلى الأندلس وإفريقية، يحمل لقب أمير المؤمنين الذي تلقّبوا به أوّل دولة بربرية.",
    1147,1269,"🪧","epic",["muwahhidun.figure.abd-al-mumin","muwahhidun.figure.yaqub-al-mansur","muwahhidun.event.foundation","muwahhidun.artifact.caliphate-decree"]],
  ["muwahhid-dinar","دينار موحدي","Almohad Dinar",
    "العملة الذهبية الموحدية المربعة الفريدة، ضُربت بمراكش وإشبيلية وفاس، شاهدة على قوة الاقتصاد الموحدي وامتداده.",
    1147,1269,"🪙","legendary",["muwahhidun.figure.abd-al-mumin","muwahhidun.figure.yaqub-al-mansur","muwahhidun.city.marrakesh","muwahhidun.city.seville","muwahhidun.event.golden-age"]],
  ["al-arak-manuscript","مخطوطة الأرك","Manuscript of Alarcos",
    "وثيقة تروي تفاصيل معركة الأرك ونصر المنصور على ألفونسو الثامن، شاهدة على ذروة قوة الموحدين سنة ٥٩١هـ.",
    1195,1250,"📜","legendary",["muwahhidun.battle.al-arak","muwahhidun.figure.yaqub-al-mansur","muwahhidun.figure.alfonso-viii","muwahhidun.event.al-arak-event"]],
  ["al-uqab-manuscript","مخطوطة العقاب","Manuscript of Las Navas",
    "وثيقة تروي تفاصيل معركة العقاب وهزيمة الناصر، شاهدة على نقطة التحوّل التي بدأت بعدها نهاية الإسلام في الأندلس.",
    1212,1260,"📜","legendary",["muwahhidun.battle.al-uqab","muwahhidun.figure.al-nasir","muwahhidun.figure.alfonso-viii","muwahhidun.event.al-uqab-event","muwahhidun.event.decline-begins"]],
  ["muwahhid-map","خريطة الدولة الموحدية","Map of the Almohad State",
    "خريطة تبيّن امتداد الموحدين من برقة إلى المحيط، ومن طنجة إلى ما وراء جبل طارق في الأندلس، أوسع دولة في المغرب الإسلامي.",
    1160,1212,"🗺️","epic",["muwahhidun.event.unify-maghrib","muwahhidun.event.control-andalus","muwahhidun.event.golden-age","muwahhidun.figure.abd-al-mumin","muwahhidun.figure.yaqub-al-mansur"]],
  ["caliphate-decree","مرسوم الخلافة","Decree of the Caliphate",
    "مرسوم تلقّب فيه عبد المؤمن بأمير المؤمنين، أول مرة يتسمّى به حاكم مغربي مستقل عن الخلافة العباسية.",
    1147,1163,"📜","legendary",["muwahhidun.figure.abd-al-mumin","muwahhidun.event.foundation","muwahhidun.artifact.muwahhid-seal"]],
  ["al-arak-medal","وسام الأرك","Medal of Alarcos",
    "وسام شرفي يُمنح لمن أكمل مسار يعقوب المنصور ومعركة الأرك.",
    1195,1269,"🏵️","legendary",["muwahhidun.battle.al-arak","muwahhidun.figure.yaqub-al-mansur","muwahhidun.event.al-arak-event","muwahhidun.event.golden-age"]],
  ["sealed-decree","سجل العمران الموحدي","Almohad Construction Register",
    "سجل أوامر المنصور ببناء صومعة الكتبية والخيرالدة وبرج حسان وأسوار الرباط، نموذج العمارة الإمبراطورية الموحدية.",
    1184,1199,"📚","epic",["muwahhidun.landmark.kutubiyya-minaret","muwahhidun.landmark.giralda","muwahhidun.landmark.hassan-tower","muwahhidun.landmark.rabat-walls","muwahhidun.figure.yaqub-al-mansur","muwahhidun.event.golden-age"]],
] as const;

// ---------- ACHIEVEMENTS ----------
const ACHIEVEMENT_IDS = [
  ["al-arak-hero","بطل الأرك","Hero of Alarcos",
    "يُمنح لمن أكمل قصص يعقوب المنصور ومعركة الأرك ونصر الموحدين على قشتالة.",
    ["muwahhidun.figure.yaqub-al-mansur","muwahhidun.battle.al-arak","muwahhidun.event.al-arak-event","muwahhidun.figure.alfonso-viii","muwahhidun.artifact.al-arak-manuscript","muwahhidun.artifact.al-arak-medal","andalusia.battle.al-arak"]],
  ["muwahhid-historian","مؤرّخ الموحدين","Historian of the Almohads",
    "يُمنح لمن قرأ جميع شخصيات وأحداث دولة الموحدين في الموسوعة.",
    ["muwahhidun.state.muwahhidun","muwahhidun.figure.ibn-tumart","muwahhidun.figure.abd-al-mumin","muwahhidun.figure.yaqub-al-mansur","muwahhidun.event.foundation","muwahhidun.event.fall","muwahhidun.event.golden-age"]],
  ["muwahhid-collector","جامع التراث الموحدي","Collector of Almohad Heritage",
    "يُمنح لمن جمع كلّ آثار ومخطوطات الموحدين في مجموعته.",
    ["muwahhidun.artifact.muwahhid-banner","muwahhidun.artifact.sword-abd-mumin","muwahhidun.artifact.muwahhid-dinar","muwahhidun.artifact.muwahhid-seal","muwahhidun.artifact.al-arak-manuscript","muwahhidun.artifact.al-uqab-manuscript","muwahhidun.artifact.caliphate-decree","muwahhidun.artifact.sealed-decree"]],
  ["lord-marrakesh","سيد مراكش","Lord of Marrakesh",
    "يُمنح لمن أتمّ مسار عبد المؤمن والمنصور في عمارة مراكش وفتحها.",
    ["muwahhidun.city.marrakesh","muwahhidun.figure.abd-al-mumin","muwahhidun.figure.yaqub-al-mansur","muwahhidun.landmark.kutubiyya-minaret","muwahhidun.landmark.kutubiyya-mosque","muwahhidun.landmark.marrakesh-palaces","muwahhidun.battle.marrakesh-conquest"]],
  ["andalus-protector","حامي الأندلس","Protector of al-Andalus",
    "يُمنح لمن أكمل قصص العبور إلى الأندلس وحصار شِلب والأرك وبناء الخيرالدة.",
    ["muwahhidun.event.control-andalus","muwahhidun.battle.shilb-siege","muwahhidun.battle.al-arak","muwahhidun.landmark.giralda","muwahhidun.figure.yaqub-al-mansur","muwahhidun.figure.abu-yaqub-yusuf","andalusia.event.muwahhidun-entry"]],
] as const;

// ---------- FUTURE CAMPAIGN PLACEHOLDERS (locked) ----------
const FUTURE_CAMPAIGN_IDS = [
  ["future-ibn-tumart",  "حملة ابن تومرت",       1121,1130,"حملةٌ قادمة عن مؤسس دعوة الموحدين ومهديّهم. (قريبًا)"],
  ["future-abd-mumin",   "حملة عبد المؤمن",      1130,1163,"حملةٌ قادمة عن أوّل خلفاء الموحدين ومؤسس الدولة. (قريبًا)"],
  ["future-al-arak",     "معركة الأرك",          1195,1195,"حملةٌ قادمة عن النصر التاريخي للمنصور. (قريبًا)"],
  ["future-mansur",      "عصر المنصور الموحدي",  1184,1199,"حملةٌ قادمة عن ذروة الخلافة الموحدية. (قريبًا)"],
  ["future-al-uqab",     "معركة العقاب",         1212,1212,"حملةٌ قادمة عن نكسة العقاب وبداية النهاية. (قريبًا)"],
  ["future-fall",        "سقوط الموحدين",        1230,1269,"حملةٌ قادمة عن تفكّك الدولة وصعود بني مرين. (قريبًا)"],
] as const;

const entities: PackEntity[] = [
  // ---------- STATE ----------
  E({
    id: "muwahhidun.state.muwahhidun",
    title: "دولة الموحدين",
    latin: "Almohad Caliphate",
    type: "state",
    description:
      "دولة الموحدين، خلافة بربرية أسّسها ابن تومرت في جبال الأطلس سنة ٥١٥هـ/١١٢١م على أساس التوحيد الأشعري، أسقط تلميذه عبد المؤمن دولة المرابطين سنة ٥٤١هـ/١١٤٧م ودخل مراكش، ووحّد المغرب من برقة إلى المحيط ومدّ سلطانه على الأندلس. بلغت ذروتها في عهد يعقوب المنصور بانتصار الأرك سنة ٥٩١هـ/١١٩٥م، وبدأ انحدارها بعد العقاب سنة ٦٠٩هـ/١٢١٢م، حتى سقطت مراكش بيد بني مرين سنة ٦٦٨هـ/١٢٦٩م.",
    period: { label: "٥١٥ – ٦٦٨ هـ / ١١٢١ – ١٢٦٩ م", startYear: 1121, endYear: 1269 },
    relatedEntities: [
      "muwahhidun.figure.ibn-tumart","muwahhidun.figure.abd-al-mumin","muwahhidun.figure.abu-yaqub-yusuf",
      "muwahhidun.figure.yaqub-al-mansur","muwahhidun.figure.al-nasir","muwahhidun.figure.idris-al-mamun",
      "muwahhidun.figure.al-rashid","muwahhidun.figure.yusuf-abd-mumin","muwahhidun.figure.abu-said-othman","muwahhidun.figure.alfonso-viii",
      "muwahhidun.figure.ibn-rushd","muwahhidun.figure.ibn-tufayl","muwahhidun.figure.ibn-al-baitar",
      "muwahhidun.figure.ibn-zuhr","muwahhidun.figure.al-shatibi","muwahhidun.figure.ibn-madda",
      "muwahhidun.figure.ibn-rushd-jadd","muwahhidun.figure.ibn-al-arabi",
      "muwahhidun.city.marrakesh","muwahhidun.city.fes","muwahhidun.city.rabat","muwahhidun.city.seville",
      "muwahhidun.city.cordoba","muwahhidun.city.granada","muwahhidun.city.sala","muwahhidun.city.ceuta",
      "muwahhidun.city.tlemcen","muwahhidun.city.bijaya",
      "muwahhidun.battle.al-arak","muwahhidun.battle.al-uqab","muwahhidun.battle.shilb-siege",
      "muwahhidun.battle.seville-siege","muwahhidun.battle.bijaya-conquest","muwahhidun.battle.marrakesh-conquest",
      "muwahhidun.battle.wadi-makhazin-early","muwahhidun.battle.fahs-al-ballut",
      "muwahhidun.event.dawa","muwahhidun.event.fall-murabitun","muwahhidun.event.foundation",
      "muwahhidun.event.unify-maghrib","muwahhidun.event.control-andalus","muwahhidun.event.al-arak-event",
      "muwahhidun.event.golden-age","muwahhidun.event.build-kutubiyya-minaret","muwahhidun.event.build-giralda",
      "muwahhidun.event.al-uqab-event","muwahhidun.event.decline-begins","muwahhidun.event.fragmentation","muwahhidun.event.fall",
      // cross-pack links
      "andalusia.state.andalusia","andalusia.event.muwahhidun-entry","andalusia.battle.al-arak","andalusia.battle.al-uqab",
      "murabitun.state.murabitun","murabitun.event.fall","murabitun.event.almohad-rise",
      "ayyubid.state.ayyubid","mamluk.state.mamluk",
    ],
    unlockables: [
      { kind: "campaign", refId: "muwahhidun", label: "حملات دولة الموحدين" },
    ],
    image: { alt: "راية دولة الموحدين", glyph: "🕌", tone: "from-red-900/40 to-stone-900" },
    timelinePosition: 1121,
    rarity: "legendary",
    meta: {
      founder: "محمد بن تومرت / عبد المؤمن بن علي",
      capital: "مراكش",
      majorCities: ["مراكش","فاس","الرباط","إشبيلية","قرطبة","غرناطة","سلا","سبتة","تلمسان","بجاية"],
      majorFigures: ["ابن تومرت","عبد المؤمن","أبو يعقوب يوسف","يعقوب المنصور","محمد الناصر","ابن رشد","ابن طفيل"],
      majorBattles: ["الأرك","العقاب","شِلب","إشبيلية","بجاية","مراكش","فحص البلوط"],
      majorEvents: ["قيام الدعوة","سقوط المرابطين","تأسيس الدولة","توحيد المغرب","السيطرة على الأندلس","الأرك","الازدهار","العقاب","الانحسار","التفكك","السقوط"],
    },
    bridges: { era: "muwahhidun" },
  }),

  // ---------- FIGURES ----------
  ...FIGURE_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `muwahhidun.figure.${slug}`,
    title, latin, type: "figure", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["muwahhidun.state.muwahhidun", ...related],
    unlockables: [{ kind: "figure", refId: `muwahhidun.figure.${slug}`, label: title }],
    image: { alt: title, glyph: "🕌", tone: "from-red-900/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "epic",
    meta: { titles: [title] },
    bridges: { era: "muwahhidun" },
  })),

  // ---------- SCHOLARS ----------
  ...SCHOLAR_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `muwahhidun.figure.${slug}`,
    title, latin, type: "figure", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["muwahhidun.state.muwahhidun", ...related],
    unlockables: [{ kind: "figure", refId: `muwahhidun.figure.${slug}`, label: title }],
    image: { alt: title, glyph: "📚", tone: "from-red-900/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "epic",
    meta: { kind: "scholar", titles: [title] },
    bridges: { era: "muwahhidun" },
  })),

  // ---------- CITIES ----------
  ...CITY_IDS.map(([slug, title, latin, description, startYear, endYear, related]) => E({
    id: `muwahhidun.city.${slug}`,
    title, latin, type: "city", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["muwahhidun.state.muwahhidun", ...related],
    unlockables: [{ kind: "city", refId: `muwahhidun.city.${slug}`, label: title }],
    image: { alt: title, glyph: "🏙️", tone: "from-red-900/30 to-stone-900" },
    timelinePosition: startYear,
    rarity: "rare",
    bridges: { cityId: slug, era: "muwahhidun" },
  })),

  // ---------- BATTLES ----------
  ...BATTLE_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `muwahhidun.battle.${slug}`,
    title, latin, type: "battle", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["muwahhidun.state.muwahhidun", ...related],
    unlockables: [{ kind: "battle", refId: `muwahhidun.battle.${slug}`, label: title }],
    image: { alt: title, glyph: "⚔️", tone: "from-red-800/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "epic",
    bridges: { era: "muwahhidun" },
  })),

  // ---------- EVENTS ----------
  ...EVENT_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `muwahhidun.event.${slug}`,
    title, latin, type: "event", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["muwahhidun.state.muwahhidun", ...related],
    unlockables: [{ kind: "event", refId: `muwahhidun.event.${slug}`, label: title }],
    image: { alt: title, glyph: "📜", tone: "from-red-900/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "rare",
    bridges: { era: "muwahhidun" },
  })),

  // ---------- LANDMARKS ----------
  ...LANDMARK_IDS.map(([slug, title, latin, description, startYear, endYear, related]) => E({
    id: `muwahhidun.landmark.${slug}`,
    title, latin, type: "landmark", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["muwahhidun.state.muwahhidun", ...related],
    unlockables: [{ kind: "landmark", refId: `muwahhidun.landmark.${slug}`, label: title }],
    image: { alt: title, glyph: "🕌", tone: "from-red-900/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "epic",
    bridges: { era: "muwahhidun" },
  })),

  // ---------- ARTIFACTS ----------
  ...ARTIFACT_IDS.map(([slug, title, latin, description, startYear, endYear, glyph, rarity, related]) => E({
    id: `muwahhidun.artifact.${slug}`,
    title, latin, type: "artifact", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["muwahhidun.state.muwahhidun", ...related],
    unlockables: [{ kind: "artifact", refId: `muwahhidun.artifact.${slug}`, label: title }],
    image: { alt: title, glyph: glyph as string, tone: "from-red-900/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: rarity as "common" | "rare" | "epic" | "legendary",
    bridges: { era: "muwahhidun" },
  })),

  // ---------- ACHIEVEMENTS ----------
  ...ACHIEVEMENT_IDS.map(([slug, title, latin, description, related]) => E({
    id: `muwahhidun.achievement.${slug}`,
    title, latin, type: "achievement", description,
    period: { label: "١١٢١ – ١٢٦٩ م", startYear: 1121, endYear: 1269 },
    relatedEntities: ["muwahhidun.state.muwahhidun", ...related],
    unlockables: [{ kind: "title", refId: `muwahhidun.achievement.${slug}`, label: title }],
    image: { alt: title, glyph: "🏅", tone: "from-amber-600/40 to-stone-900" },
    timelinePosition: 1195,
    rarity: "legendary",
    bridges: { era: "muwahhidun" },
  })),

  // ---------- FUTURE CAMPAIGN PLACEHOLDERS (locked) ----------
  ...FUTURE_CAMPAIGN_IDS.map(([slug, title, startYear, endYear, description]) => E({
    id: `muwahhidun.event.${slug}`,
    title, type: "event", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["muwahhidun.state.muwahhidun"],
    unlockables: [],
    image: { alt: title, glyph: "🔒", tone: "from-stone-700/40 to-slate-900" },
    timelinePosition: startYear,
    rarity: "legendary",
    meta: { locked: true, kind: "campaign-placeholder" },
    bridges: { era: "muwahhidun" },
  })),
];

export const MUWAHHIDUN_PACK: ContentPack = {
  id: "pack-011-muwahhidun",
  order: 28, // right after Murabitun (26) / Zengid (27)
  title: "دولة الموحدين",
  subtitle: "المجموعة ١١ · خلافة المصامدة وحماة الأندلس بعد المرابطين",
  summary:
    "حزمة محتوى تاريخية شاملة عن دولة الموحدين من دعوة ابن تومرت في الأطلس إلى فتح عبد المؤمن لمراكش وإسقاط المرابطين، وعصر يعقوب المنصور ونصر الأرك وبناء الخيرالدة وصومعة الكتبية وبرج حسان، حتى نكسة العقاب وسقوط الدولة بيد بني مرين.",
  era: "muwahhidun",
  period: { label: "٥١٥ – ٦٦٨ هـ / ١١٢١ – ١٢٦٩ م", startYear: 1121, endYear: 1269 },
  cover: { alt: "غلاف دولة الموحدين", glyph: "🕌", tone: "from-red-900/40 to-stone-900" },
  entities,
};