import type { ContentPack, PackEntity } from "./types";

// ============================================================
// Content Pack 006 — الدولة العثمانية (Ottoman Empire)
// ------------------------------------------------------------
// Pure data pack. Auto-registers via packs/registry.ts and surfaces in
// Encyclopedia, State pages, Search, Timeline, Atlas, Related-History Graph,
// Content Audit, Museum, and the Future Campaign system.
// ============================================================

const E = (e: PackEntity): PackEntity => e;

// ---------- FIGURES (Sultans) ----------
const FIGURE_IDS = [
  ["osman-i","عثمان بن أرطغرل","Osman I",1258,1326,
    "مؤسّس الدولة العثمانية في بيتنية شمال غرب الأناضول، أعطى الإمارة اسمها وأرسى دعائم الغزو على حدود البيزنطيين.",
    ["ottoman.event.founding","ottoman.city.bursa","ottoman.figure.orhan","ottoman.artifact.sword-osman"]],
  ["orhan","أورخان غازي","Orhan Ghazi",1281,1362,
    "ابن عثمان، فتح بورصة سنة 1326م وجعلها أوّل عاصمة عثمانية، ونظّم الإنكشارية وعبر إلى أوروبا.",
    ["ottoman.city.bursa","ottoman.figure.osman-i","ottoman.figure.murad-i","ottoman.event.founding"]],
  ["murad-i","مراد الأول","Murad I",1326,1389,
    "نقل العاصمة إلى أدرنة بعد فتحها، ووسّع الدولة في البلقان، استُشهد في كوسوفو بعد النصر.",
    ["ottoman.battle.kosovo","ottoman.city.edirne","ottoman.event.move-edirne","ottoman.event.balkans-expansion","ottoman.figure.bayezid-i"]],
  ["bayezid-i","بايزيد الأول الصاعقة","Bayezid I (Yıldırım)",1354,1403,
    "السلطان الصاعقة، انتصر في نيقوبوليس على تحالف صليبي، وأسر في أنقرة أمام تيمورلنك سنة 1402م.",
    ["ottoman.battle.nicopolis","ottoman.battle.ankara","ottoman.figure.mehmed-i","ottoman.event.balkans-expansion"]],
  ["mehmed-i","محمد الأول جلبي","Mehmed I (Çelebi)",1389,1421,
    "أعاد توحيد الدولة بعد فترة الفترة (الانقسام) التي تلت كارثة أنقرة، فلقّب بالمؤسّس الثاني.",
    ["ottoman.figure.bayezid-i","ottoman.figure.murad-ii","ottoman.battle.ankara"]],
  ["murad-ii","مراد الثاني","Murad II",1404,1451,
    "وطّد الدولة في الأناضول والروملي وانتصر في فارنا وكوسوفو الثانية، وأبوه محمد الفاتح.",
    ["ottoman.figure.mehmed-ii","ottoman.city.edirne","ottoman.event.balkans-expansion"]],
  ["mehmed-ii","محمد الفاتح","Mehmed II the Conqueror",1432,1481,
    "السلطان الفاتح، فتح القسطنطينية سنة 1453م فأسقط الدولة البيزنطية وأكمل بشارة النبي ﷺ، ولقّبه الناس بأبي الفتح.",
    ["ottoman.event.fall-constantinople","ottoman.event.end-byzantine","ottoman.battle.conquest-constantinople","ottoman.city.istanbul","ottoman.landmark.hagia-sophia","ottoman.landmark.topkapi","ottoman.artifact.urban-cannon","ottoman.artifact.conqueror-medal","ottoman.artifact.key-constantinople","ottoman.figure.constantine-xi","ottoman.figure.bayezid-ii"]],
  ["bayezid-ii","بايزيد الثاني","Bayezid II",1447,1512,
    "ابن الفاتح، آوى مسلمي ويهود الأندلس بعد سقوط غرناطة وأرسل أساطيله لإجلائهم إلى أراضي الدولة.",
    ["ottoman.figure.mehmed-ii","ottoman.figure.selim-i","ottoman.city.istanbul"]],
  ["selim-i","سليم الأول (سليم ياووز)","Selim I (the Grim)",1470,1520,
    "ضمّ الشام ومصر والحجاز إلى الدولة بعد مرج دابق والريدانية سنة 1517م، وحمل لقب خادم الحرمين الشريفين.",
    ["ottoman.battle.chaldiran","ottoman.battle.marj-dabiq","ottoman.battle.ridaniya","ottoman.event.annex-sham","ottoman.event.annex-egypt","ottoman.event.annex-hijaz","ottoman.figure.suleiman-i","ottoman.city.damascus","ottoman.city.cairo","ottoman.city.mecca"]],
  ["suleiman-i","سليمان القانوني","Suleiman the Magnificent",1494,1566,
    "أعظم سلاطين بني عثمان، حكم 46 سنة، بلغت الدولة في عهده ذروة اتساعها من فيينا إلى اليمن ومن الجزائر إلى بغداد.",
    ["ottoman.event.suleiman-era","ottoman.battle.siege-vienna-1","ottoman.landmark.suleymaniye-mosque","ottoman.city.istanbul","ottoman.city.baghdad","ottoman.figure.selim-ii"]],
  ["selim-ii","سليم الثاني","Selim II",1524,1574,
    "ابن سليمان، شهد عهده فتح قبرص وكارثة ليبانتو البحرية، وبداية ظهور حركة المنافسة الأوروبية البحرية.",
    ["ottoman.figure.suleiman-i","ottoman.event.suleiman-era"]],
  ["murad-iv","مراد الرابع","Murad IV",1612,1640,
    "السلطان الذي استرجع بغداد من الصفويين سنة 1638م، شدّد في الإدارة وأعاد هيبة الدولة بعد فترة ضعف.",
    ["ottoman.city.baghdad","ottoman.event.suleiman-era"]],
  ["abdul-hamid-ii","عبد الحميد الثاني","Abdülhamid II",1842,1918,
    "السلطان الذي قاوم تفكيك الدولة وأبى بيع فلسطين لهرتسل، أنشأ خط سكة حديد الحجاز قبل أن يُعزل سنة 1909م.",
    ["ottoman.landmark.hejaz-station","ottoman.event.tanzimat","ottoman.event.ww1","ottoman.event.abolish-caliphate"]],
  ["mehmed-vi","محمد السادس","Mehmed VI (Vahideddin)",1861,1926,
    "آخر سلاطين بني عثمان، نُفي بعد إعلان الجمهورية التركية وإلغاء السلطنة سنة 1922م.",
    ["ottoman.event.fall-ottoman","ottoman.event.abolish-caliphate","ottoman.event.ww1"]],
  ["constantine-xi","قسطنطين الحادي عشر","Constantine XI Palaiologos",1405,1453,
    "آخر أباطرة بيزنطة، قُتل في الدفاع عن القسطنطينية يوم فتحها على يد محمد الفاتح. (شخصية مرتبطة)",
    ["ottoman.event.fall-constantinople","ottoman.event.end-byzantine","ottoman.figure.mehmed-ii","ottoman.battle.conquest-constantinople"]],
] as const;

// ---------- SCHOLARS ----------
const SCHOLAR_IDS = [
  ["abu-al-suud","أبو السعود أفندي","Ebussuud Efendi",1490,1574,
    "شيخ الإسلام في عهد سليمان القانوني، وفّق بين الفقه الحنفي والقانون السلطاني، وصاحب تفسير «إرشاد العقل السليم».",
    ["ottoman.figure.suleiman-i","ottoman.city.istanbul","ottoman.event.suleiman-era"]],
  ["ibn-kemal","ابن كمال باشا","Ibn Kemal (Kemalpaşazâde)",1468,1534,
    "شيخ الإسلام والمؤرّخ، صاحب «تواريخ آل عثمان»، فقيهٌ مفتٍ وأديبٌ ومن أعلام علماء الدولة في زمن سليم وسليمان.",
    ["ottoman.figure.selim-i","ottoman.figure.suleiman-i","ottoman.city.istanbul"]],
  ["hajji-khalifa","حاجي خليفة (كاتب جلبي)","Hajji Khalifa / Kâtip Çelebi",1609,1657,
    "موسوعيٌّ عثماني، صاحب «كشف الظنون عن أسامي الكتب والفنون»، أعظم بيبليوغرافيا عربية حتى عصره.",
    ["ottoman.figure.murad-iv","ottoman.city.istanbul"]],
  ["katib-celebi","كاتب جلبي","Kâtib Çelebi (variant)",1609,1657,
    "اللقب التركي لحاجي خليفة، مؤرّخٌ وجغرافيّ، صاحب «جهان نما» في الجغرافيا و«تقويم التواريخ».",
    ["ottoman.figure.hajji-khalifa","ottoman.city.istanbul"]],
  ["mustafa-sabri","مصطفى صبري","Mustafa Sabri",1869,1954,
    "آخر شيخ إسلام في الدولة العثمانية، وقف ضد إلغاء الخلافة ونفي إلى مصر، صاحب «موقف العقل والعلم والعالم».",
    ["ottoman.figure.mehmed-vi","ottoman.event.abolish-caliphate","ottoman.event.fall-ottoman"]],
  ["dawud-al-qaysari","داود القيصري","Dawud al-Qaysari",1260,1350,
    "أوّل شيخ مدرسة عثمانية في إزنيق على يد أورخان غازي، فيلسوف صوفي شارح فصوص الحكم لابن عربي.",
    ["ottoman.figure.orhan","ottoman.event.founding"]],
  ["ali-qushji","علي القوشجي","Ali Qushji",1403,1474,
    "فلكيٌّ وعالم رياضيات من مدرسة سمرقند، استقدمه محمد الفاتح إلى إسطنبول وأسهم في تأسيس مدارسها الفلكية.",
    ["ottoman.figure.mehmed-ii","ottoman.city.istanbul","ottoman.event.fall-constantinople"]],
  ["ahmed-cevdet","أحمد جودت باشا","Ahmed Cevdet Pasha",1822,1895,
    "مؤرّخ وفقيه عثماني، أحد روّاد التنظيمات، رئيس لجنة «مجلة الأحكام العدلية» التي قنّنت الفقه الحنفي.",
    ["ottoman.event.tanzimat","ottoman.figure.abdul-hamid-ii","ottoman.city.istanbul"]],
] as const;

// ---------- CITIES ----------
const CITY_IDS = [
  ["istanbul","إسطنبول","Istanbul (Constantinople)",
    "عاصمة الدولة العثمانية الكبرى بعد فتحها سنة 1453م، حاضرة الخلافة الإسلامية حتى 1924م، ملتقى أوروبا وآسيا.",
    1453,1922,["ottoman.landmark.hagia-sophia","ottoman.landmark.topkapi","ottoman.landmark.suleymaniye-mosque","ottoman.landmark.blue-mosque","ottoman.landmark.constantinople-walls","ottoman.landmark.galata-tower","ottoman.landmark.dolmabahce","ottoman.figure.mehmed-ii","ottoman.figure.suleiman-i"]],
  ["bursa","بورصة","Bursa",
    "أوّل عاصمة عثمانية، فتحها أورخان غازي سنة 1326م، فيها مساجد السلاطين الأوائل ومدافنهم.",
    1326,1922,["ottoman.figure.orhan","ottoman.figure.osman-i","ottoman.event.founding"]],
  ["edirne","أدرنة","Edirne (Adrianople)",
    "العاصمة العثمانية الثانية بعد فتحها على يد مراد الأول سنة 1361م، حاضرة الدولة في البلقان قبل إسطنبول.",
    1361,1922,["ottoman.figure.murad-i","ottoman.figure.murad-ii","ottoman.event.move-edirne","ottoman.event.balkans-expansion"]],
  ["thessaloniki","سالونيك","Thessaloniki / Selânik",
    "ثغر المتوسط الشمالي وحاضرة الروملي العثمانية، فتحها مراد الثاني سنة 1430م وبقيت عثمانية حتى 1912م.",
    1430,1912,["ottoman.figure.murad-ii","ottoman.event.balkans-expansion"]],
  ["jerusalem","القدس","Jerusalem",
    "بيت المقدس تحت ولاية الدولة العثمانية من سنة 1517م، رمّم سليمان القانوني أسوارها وعنى بالأقصى.",
    1517,1917,["ottoman.figure.selim-i","ottoman.figure.suleiman-i","ottoman.event.annex-sham"]],
  ["damascus","دمشق","Damascus",
    "حاضرة الشام العثمانية بعد مرج دابق، انطلق منها ركب الحج الشامي السنوي إلى الحرمين لقرون.",
    1516,1918,["ottoman.figure.selim-i","ottoman.event.annex-sham","ottoman.battle.marj-dabiq","ottoman.landmark.hejaz-station"]],
  ["cairo","القاهرة","Cairo",
    "حاضرة مصر العثمانية بعد الريدانية، نقل منها سليم الأول الخلافة العباسية الرمزية إلى إسطنبول.",
    1517,1914,["ottoman.figure.selim-i","ottoman.event.annex-egypt","ottoman.battle.ridaniya"]],
  ["baghdad","بغداد","Baghdad",
    "حاضرة العراق العثمانية، تأرجحت بين العثمانيين والصفويين، استرجعها سليمان القانوني ثم مراد الرابع سنة 1638م.",
    1534,1917,["ottoman.figure.suleiman-i","ottoman.figure.murad-iv","ottoman.battle.chaldiran"]],
  ["mecca","مكة المكرمة","Mecca",
    "أمّ القرى تحت رعاية السلاطين العثمانيين بعد 1517م، فجعلوا «خادم الحرمين الشريفين» في طليعة ألقابهم.",
    1517,1916,["ottoman.figure.selim-i","ottoman.event.annex-hijaz"]],
  ["medina","المدينة المنورة","Medina",
    "حاضرة الحجاز ومُهاجر النبي ﷺ، تحت الرعاية العثمانية حتى نهاية الحرب العالمية الأولى، فيها محطّة سكة حديد الحجاز.",
    1517,1918,["ottoman.figure.selim-i","ottoman.figure.abdul-hamid-ii","ottoman.event.annex-hijaz","ottoman.landmark.hejaz-station"]],
] as const;

// ---------- BATTLES ----------
const BATTLE_IDS = [
  ["kosovo","معركة كوسوفو","Battle of Kosovo",1389,1389,
    "نصرٌ عثماني فاصل على الصرب وحلفائهم في البلقان، استُشهد فيه السلطان مراد الأول بعد المعركة.",
    ["ottoman.figure.murad-i","ottoman.figure.bayezid-i","ottoman.event.balkans-expansion"]],
  ["nicopolis","معركة نيقوبوليس","Battle of Nicopolis",1396,1396,
    "هزيمة بايزيد الصاعقة لتحالف صليبي كبير على نهر الدانوب، أعظم انتصارات العثمانيين في البلقان.",
    ["ottoman.figure.bayezid-i","ottoman.event.balkans-expansion"]],
  ["ankara","معركة أنقرة","Battle of Ankara",1402,1402,
    "هزيمة بايزيد الأول أمام تيمورلنك وأسره، فدخلت الدولة فترة الانقسام (الفترة) إلى أن وحّدها محمد الأول.",
    ["ottoman.figure.bayezid-i","ottoman.figure.mehmed-i"]],
  ["conquest-constantinople","فتح القسطنطينية","Conquest of Constantinople",1453,1453,
    "حصار محمد الفاتح للقسطنطينية 53 يومًا وفتحها في 29 مايو 1453م بمدفع أوربان وعبور السفن إلى القرن الذهبي.",
    ["ottoman.figure.mehmed-ii","ottoman.figure.constantine-xi","ottoman.event.fall-constantinople","ottoman.event.end-byzantine","ottoman.city.istanbul","ottoman.landmark.constantinople-walls","ottoman.landmark.hagia-sophia","ottoman.artifact.urban-cannon","ottoman.artifact.key-constantinople","ottoman.artifact.conquest-manuscript","ottoman.artifact.conqueror-medal"]],
  ["chaldiran","معركة جالديران","Battle of Chaldiran",1514,1514,
    "نصرٌ مدويّ لسليم الأول على الشاه إسماعيل الصفوي في شرق الأناضول، فتح الباب لضمّ الشام ومصر.",
    ["ottoman.figure.selim-i","ottoman.event.annex-sham","ottoman.event.annex-egypt","ottoman.city.baghdad"]],
  ["marj-dabiq","معركة مرج دابق","Battle of Marj Dabiq",1516,1516,
    "نصر سليم الأول على قانصوه الغوري شمال حلب، انتقل بها الشام كلّه إلى الدولة العثمانية.",
    ["ottoman.figure.selim-i","ottoman.city.damascus","ottoman.event.annex-sham"]],
  ["ridaniya","معركة الريدانية","Battle of Ridaniya",1517,1517,
    "نصر سليم الأول على طومان باي شمال القاهرة، دخلت بها مصر تحت الحكم العثماني وانتقلت الخلافة إلى آل عثمان.",
    ["ottoman.figure.selim-i","ottoman.city.cairo","ottoman.event.annex-egypt"]],
  ["siege-vienna-1","حصار فيينا الأول","First Siege of Vienna",1529,1529,
    "حصار سليمان القانوني الأوّل لفيينا، أعظم زحف عثماني نحو وسط أوروبا قبل أن يُرفع الحصار في الخريف.",
    ["ottoman.figure.suleiman-i","ottoman.event.suleiman-era","ottoman.event.vienna-siege"]],
  ["siege-vienna-2","حصار فيينا الثاني","Second Siege of Vienna",1683,1683,
    "حصار قره مصطفى باشا الكبير لفيينا، انكسر العثمانيون أمام يان سوبيسكي وبدأ تراجع الدولة في أوروبا.",
    ["ottoman.event.vienna-siege","ottoman.event.tanzimat"]],
  ["navarino","معركة نافارين","Battle of Navarino",1827,1827,
    "كارثة بحرية أمام تحالف بريطاني-فرنسي-روسي قرب اليونان، دُمّر فيها الأسطول العثماني-المصري، فتعجّل استقلال اليونان.",
    ["ottoman.event.tanzimat","ottoman.event.balkans-expansion"]],
] as const;

// ---------- EVENTS ----------
const EVENT_IDS = [
  ["founding","تأسيس الدولة العثمانية","Founding of the Ottoman State",1299,1326,
    "إعلان عثمان بن أرطغرل استقلال إمارته في سُكُود وبيتنية شمال غرب الأناضول، فقامت الدولة التي حملت اسمه.",
    ["ottoman.figure.osman-i","ottoman.figure.orhan","ottoman.city.bursa","ottoman.artifact.sword-osman"]],
  ["move-edirne","انتقال العاصمة إلى أدرنة","Moving the Capital to Edirne",1361,1365,
    "نقل مراد الأوّل العاصمة من بورصة إلى أدرنة بعد فتحها، إيذانًا بتحوّل ثقل الدولة إلى الروملي والبلقان.",
    ["ottoman.figure.murad-i","ottoman.city.edirne","ottoman.event.balkans-expansion"]],
  ["balkans-expansion","التوسّع في البلقان","Ottoman Expansion in the Balkans",1361,1453,
    "قرنٌ من التوسّع العثماني في البلقان من أدرنة وكوسوفو ونيقوبوليس إلى أبواب القسطنطينية.",
    ["ottoman.figure.murad-i","ottoman.figure.bayezid-i","ottoman.figure.murad-ii","ottoman.battle.kosovo","ottoman.battle.nicopolis","ottoman.city.edirne","ottoman.city.thessaloniki"]],
  ["fall-constantinople","فتح القسطنطينية","Fall of Constantinople",1453,1453,
    "سقوط أعظم حواضر النصرانية الشرقية على يد محمد الفاتح، تحقّق به وعد النبي ﷺ ودخل العثمانيون عصرهم الإمبراطوري.",
    ["ottoman.figure.mehmed-ii","ottoman.battle.conquest-constantinople","ottoman.event.end-byzantine","ottoman.city.istanbul","ottoman.landmark.hagia-sophia","ottoman.artifact.urban-cannon","ottoman.artifact.key-constantinople"]],
  ["end-byzantine","نهاية الدولة البيزنطية","End of the Byzantine Empire",1453,1453,
    "انتهاء 1100 سنة من حكم الروم الشرقيين في القسطنطينية، وانتقال «روما الجديدة» إلى يد آل عثمان.",
    ["ottoman.event.fall-constantinople","ottoman.figure.mehmed-ii","ottoman.figure.constantine-xi"]],
  ["annex-sham","ضمّ الشام","Annexation of Greater Syria",1516,1516,
    "انتقال الشام كاملًا إلى الدولة العثمانية بعد مرج دابق، فبقي تحت حكمها أربعة قرون حتى الحرب العالمية الأولى.",
    ["ottoman.figure.selim-i","ottoman.battle.marj-dabiq","ottoman.city.damascus","ottoman.city.jerusalem"]],
  ["annex-egypt","ضمّ مصر","Annexation of Egypt",1517,1517,
    "دخول سليم الأول القاهرة بعد الريدانية، ونقل الخلافة العباسية الرمزية إلى إسطنبول، فصار سلاطين بني عثمان خلفاء.",
    ["ottoman.figure.selim-i","ottoman.battle.ridaniya","ottoman.city.cairo"]],
  ["annex-hijaz","ضمّ الحجاز","Annexation of the Hijaz",1517,1517,
    "دخول الحجاز تحت الرعاية العثمانية بإرسال مفاتيح الحرمين إلى سليم الأول، فحمل لقب خادم الحرمين الشريفين.",
    ["ottoman.figure.selim-i","ottoman.city.mecca","ottoman.city.medina"]],
  ["suleiman-era","عصر سليمان القانوني","Era of Suleiman the Magnificent",1520,1566,
    "ذروة الدولة العثمانية في الاتساع والقوة والقانون والعمارة، من بلغراد إلى بغداد ومن الجزائر إلى اليمن.",
    ["ottoman.figure.suleiman-i","ottoman.battle.siege-vienna-1","ottoman.landmark.suleymaniye-mosque","ottoman.city.istanbul","ottoman.city.baghdad","ottoman.event.vienna-siege"]],
  ["vienna-siege","حصار فيينا","Sieges of Vienna",1529,1683,
    "الحصاران العثمانيان لفيينا في 1529 و1683م، أعمق نقطتي زحفٍ عثمانية في أوروبا، انتهى الثاني بالكسر.",
    ["ottoman.battle.siege-vienna-1","ottoman.battle.siege-vienna-2","ottoman.figure.suleiman-i"]],
  ["tanzimat","التنظيمات العثمانية","Tanzimat Reforms",1839,1876,
    "موجة الإصلاحات الإدارية والقانونية والعسكرية في الدولة العثمانية في القرن التاسع عشر، حاولت اللحاق بأوروبا.",
    ["ottoman.figure.abdul-hamid-ii","ottoman.figure.ahmed-cevdet","ottoman.battle.navarino","ottoman.battle.siege-vienna-2"]],
  ["ww1","الحرب العالمية الأولى","World War I",1914,1918,
    "دخول الدولة العثمانية الحرب إلى جانب ألمانيا، انتهت بهزيمتها وتفكيك ولاياتها العربية ومعاهدة سيفر.",
    ["ottoman.figure.mehmed-vi","ottoman.figure.abdul-hamid-ii","ottoman.event.fall-ottoman","ottoman.event.abolish-caliphate"]],
  ["abolish-caliphate","إلغاء الخلافة","Abolition of the Caliphate",1924,1924,
    "إلغاء مصطفى كمال الخلافة الإسلامية في 3 مارس 1924م بعد إلغاء السلطنة، فطُويت صفحة الخلافة بعد 13 قرنًا.",
    ["ottoman.figure.mehmed-vi","ottoman.figure.mustafa-sabri","ottoman.event.fall-ottoman","ottoman.event.ww1"]],
  ["fall-ottoman","سقوط الدولة العثمانية","Fall of the Ottoman Empire",1918,1922,
    "هزيمة الحرب الكبرى، احتلال إسطنبول، إعلان الجمهورية التركية وإلغاء السلطنة سنة 1922م ثم الخلافة سنة 1924م.",
    ["ottoman.figure.mehmed-vi","ottoman.event.ww1","ottoman.event.abolish-caliphate"]],
] as const;

// ---------- LANDMARKS ----------
const LANDMARK_IDS = [
  ["hagia-sophia","آيا صوفيا","Hagia Sophia",
    "كاتدرائية القسطنطينية الكبرى، حوّلها محمد الفاتح إلى مسجدٍ يوم الفتح سنة 1453م، أيقونة إسطنبول العثمانية.",
    537,1922,["ottoman.figure.mehmed-ii","ottoman.event.fall-constantinople","ottoman.city.istanbul"]],
  ["topkapi","قصر طوب قابي","Topkapı Palace",
    "قصر سلاطين بني عثمان فوق رأس السرايا في إسطنبول قرابة أربعة قرون، يضمّ الأمانات المقدّسة وعرش الفاتح.",
    1465,1856,["ottoman.figure.mehmed-ii","ottoman.figure.suleiman-i","ottoman.city.istanbul"]],
  ["blue-mosque","الجامع الأزرق (السلطان أحمد)","Sultan Ahmed (Blue) Mosque",
    "مسجد السلطان أحمد الأوّل، تحفة العمارة العثمانية المتأخرة بست مآذن وقبابٍ متعاقبة وقاشانيٍّ أزرق نادر.",
    1616,1922,["ottoman.city.istanbul","ottoman.landmark.suleymaniye-mosque"]],
  ["suleymaniye-mosque","جامع السليمانية","Süleymaniye Mosque",
    "تحفة المعمار سنان في عهد سليمان القانوني، أعظم مساجد إسطنبول وأكثرها وقارًا.",
    1557,1922,["ottoman.figure.suleiman-i","ottoman.city.istanbul","ottoman.event.suleiman-era"]],
  ["fatih-mosque","جامع الفاتح","Fatih Mosque (Mosque of the Conqueror)",
    "جامعٌ بناه محمد الفاتح بعد فتح القسطنطينية فوق مكان كنيسة الحواريين، فيه ضريحه ومدرسته.",
    1470,1922,["ottoman.figure.mehmed-ii","ottoman.city.istanbul","ottoman.event.fall-constantinople"]],
  ["constantinople-walls","أسوار القسطنطينية","Walls of Constantinople",
    "أسوار ثيودوسيوس الثلاثية التي حمت المدينة ألف سنة قبل أن يخترقها مدفع أوربان في مايو 1453م.",
    413,1453,["ottoman.battle.conquest-constantinople","ottoman.event.fall-constantinople","ottoman.artifact.urban-cannon"]],
  ["dolmabahce","قصر دولمة بهجة","Dolmabahçe Palace",
    "القصر السلطاني المتأخّر على ضفّة البوسفور، حلّ محلّ طوب قابي مقرًّا للسلاطين منذ 1856م حتى نهاية الدولة.",
    1856,1922,["ottoman.figure.abdul-hamid-ii","ottoman.figure.mehmed-vi","ottoman.city.istanbul","ottoman.event.tanzimat"]],
  ["galata-tower","برج غلطة","Galata Tower",
    "برجٌ شامخ في حيّ غلطة بإسطنبول، رمز المدينة منذ القرون الوسطى، ومنه راقب العثمانيون البوسفور.",
    1348,1922,["ottoman.city.istanbul","ottoman.event.fall-constantinople"]],
  ["hejaz-station","محطة الحجاز","Hejaz Railway Station",
    "خطّ سكة حديد الحجاز الذي أنشأه السلطان عبد الحميد الثاني من دمشق إلى المدينة لخدمة الحجاج، توقّف في الحرب الكبرى.",
    1908,1918,["ottoman.figure.abdul-hamid-ii","ottoman.city.damascus","ottoman.city.medina","ottoman.event.ww1"]],
  ["fatih-bridge","جسر السلطان محمد الفاتح","Fatih Sultan Mehmet Bridge (memorial)",
    "جسر الذكرى المعاصر فوق البوسفور باسم الفاتح، يخلّد ذكرى عبور أسطوله البرّي إلى القرن الذهبي يوم الفتح.",
    1453,1453,["ottoman.figure.mehmed-ii","ottoman.event.fall-constantinople","ottoman.city.istanbul"]],
] as const;

// ---------- ARTIFACTS ----------
const ARTIFACT_IDS = [
  ["sword-osman","سيف عثمان","Sword of Osman",
    "السيف الذي كان يُقلَّد لكلّ سلطان عثماني جديد عند جلوسه في جامع أبي أيوب الأنصاري، رمز السلطنة المقدّسة.",
    1299,1922,"🗡️","legendary",["ottoman.figure.osman-i","ottoman.event.founding","ottoman.figure.mehmed-ii","ottoman.figure.suleiman-i"]],
  ["conquest-banner","راية الفتح العثمانية","Ottoman Banner of Conquest",
    "الراية الحمراء بالهلال الذي رُفع على أسوار القسطنطينية يوم فتحها، شعار جيوش بني عثمان قرونًا.",
    1453,1922,"🏴","epic",["ottoman.event.fall-constantinople","ottoman.figure.mehmed-ii","ottoman.battle.conquest-constantinople"]],
  ["sultanic-firman","فرمان سلطاني","Sultanic Firman",
    "أمرٌ سلطاني مزخرف بالطغراء، أداة الحكم العثماني من إسطنبول إلى الولايات في العالم الإسلامي.",
    1453,1922,"📃","rare",["ottoman.artifact.ottoman-seal","ottoman.figure.suleiman-i","ottoman.figure.selim-i"]],
  ["ottoman-seal","ختم الخلافة العثمانية","Seal of the Ottoman Caliphate",
    "ختم الخلافة العثمانية بطغراء السلطان، شعار السلطنة على المراسيم والعهود مع الدول.",
    1517,1924,"🪧","epic",["ottoman.figure.selim-i","ottoman.figure.abdul-hamid-ii","ottoman.event.abolish-caliphate","ottoman.event.annex-egypt"]],
  ["ottoman-map","خريطة الدولة العثمانية","Map of the Ottoman Empire",
    "خريطةٌ تبيّن اتساع الدولة في عهد سليمان القانوني من فيينا إلى اليمن ومن الجزائر إلى بغداد.",
    1566,1683,"🗺️","epic",["ottoman.figure.suleiman-i","ottoman.event.suleiman-era","ottoman.city.istanbul","ottoman.city.baghdad"]],
  ["urban-cannon","مدفع أوربان","Urban's Great Cannon",
    "المدفع العملاق الذي صنعه أوربان المجري لمحمد الفاتح، حطّم أسوار القسطنطينية وغيّر فنّ الحصار في العالم.",
    1453,1453,"💣","legendary",["ottoman.figure.mehmed-ii","ottoman.battle.conquest-constantinople","ottoman.landmark.constantinople-walls","ottoman.event.fall-constantinople"]],
  ["conquest-manuscript","مخطوطة الفتح","Manuscript of the Conquest",
    "وثيقةٌ عثمانية تروي يوم فتح القسطنطينية وعبور السفن إلى القرن الذهبي وأحاديث البشارة النبوية.",
    1453,1922,"📜","legendary",["ottoman.event.fall-constantinople","ottoman.battle.conquest-constantinople","ottoman.figure.mehmed-ii"]],
  ["ottoman-dinar","دينار عثماني (سلطاني)","Ottoman Gold Coin (Sultani)",
    "العملة الذهبية السلطانية التي ضربها بايزيد الثاني وخلفاؤه على غرار الدينار، عملةُ تجارة المتوسط قرونًا.",
    1481,1922,"💰","epic",["ottoman.figure.bayezid-ii","ottoman.city.istanbul","ottoman.figure.suleiman-i"]],
  ["conqueror-medal","وسام الفاتح","Medal of the Conqueror",
    "وسامٌ شرفي يُمنح لمن أتمّ مسار محمد الفاتح وفتح القسطنطينية، شعاره الهلال والسيف.",
    1453,1922,"🏵️","legendary",["ottoman.figure.mehmed-ii","ottoman.event.fall-constantinople","ottoman.battle.conquest-constantinople"]],
  ["key-constantinople","مفتاح القسطنطينية","Key of Constantinople",
    "المفتاح الرمزي الذي قدّمه أهل المدينة لمحمد الفاتح يوم الفتح، رمز انتقال «الرومية» إلى الإسلام.",
    1453,1453,"🔑","legendary",["ottoman.figure.mehmed-ii","ottoman.figure.constantine-xi","ottoman.event.fall-constantinople","ottoman.event.end-byzantine"]],
] as const;

// ---------- ACHIEVEMENTS ----------
const ACHIEVEMENT_IDS = [
  ["constantinople-conqueror","فاتح القسطنطينية","Conqueror of Constantinople",
    "يُمنح لمن أكمل قصص محمد الفاتح ومعركة فتح القسطنطينية ومدفع أوربان.",
    ["ottoman.figure.mehmed-ii","ottoman.battle.conquest-constantinople","ottoman.event.fall-constantinople","ottoman.artifact.urban-cannon"]],
  ["ottoman-historian","مؤرّخ الدولة العثمانية","Historian of the Ottoman State",
    "يُمنح لمن قرأ جميع شخصيات وأحداث الدولة العثمانية في الموسوعة.",
    ["ottoman.state.ottoman","ottoman.figure.osman-i","ottoman.figure.suleiman-i","ottoman.figure.abdul-hamid-ii","ottoman.event.abolish-caliphate"]],
  ["ottoman-collector","جامع التراث العثماني","Collector of Ottoman Heritage",
    "يُمنح لمن جمع كلّ الآثار والمخطوطات العثمانية في مجموعته.",
    ["ottoman.artifact.sword-osman","ottoman.artifact.urban-cannon","ottoman.artifact.conquest-manuscript","ottoman.artifact.key-constantinople","ottoman.artifact.conqueror-medal"]],
  ["istanbul-master","سيد إسطنبول","Master of Istanbul",
    "يُمنح لمن أتمّ مسار إسطنبول وآيا صوفيا وطوب قابي وجامع السليمانية.",
    ["ottoman.city.istanbul","ottoman.landmark.hagia-sophia","ottoman.landmark.topkapi","ottoman.landmark.suleymaniye-mosque"]],
  ["caliphate-guardian","حارس الخلافة","Guardian of the Caliphate",
    "يُمنح لمن جمع إنجازات الدولة العثمانية وأكمل قصة إلغاء الخلافة سنة 1924م.",
    ["ottoman.state.ottoman","ottoman.event.abolish-caliphate","ottoman.event.fall-ottoman","ottoman.figure.mehmed-vi"]],
] as const;

// ---------- FUTURE CAMPAIGN PLACEHOLDERS (locked) ----------
const FUTURE_CAMPAIGN_IDS = [
  ["future-osman",         "حملة عثمان بن أرطغرل", 1280,1326,"حملةٌ قادمة عن نشأة الدولة العثمانية في بيتنية. (قريبًا)"],
  ["future-mehmed-ii",     "حملة محمد الفاتح",      1444,1481,"حملةٌ قادمة عن صعود محمد الفاتح وعصره. (قريبًا)"],
  ["future-constantinople","فتح القسطنطينية",       1452,1453,"حملةٌ قادمة عن أيام الحصار الـ53 وفتح المدينة. (قريبًا)"],
  ["future-selim-i",       "حملة سليم الأول",       1512,1520,"حملةٌ قادمة عن ضمّ الشام ومصر والحجاز إلى الدولة. (قريبًا)"],
  ["future-suleiman",      "عصر سليمان القانوني",   1520,1566,"حملةٌ قادمة عن ذروة الدولة العثمانية. (قريبًا)"],
  ["future-fall-ottoman",  "سقوط الدولة العثمانية", 1914,1924,"حملةٌ قادمة عن الحرب الكبرى وإلغاء الخلافة. (قريبًا)"],
] as const;

const entities: PackEntity[] = [
  // ---------- STATE ----------
  E({
    id: "ottoman.state.ottoman",
    title: "الدولة العثمانية",
    latin: "Ottoman Empire",
    type: "state",
    description:
      "الدولة العثمانية، أعظم دول الإسلام في العصر الحديث، قامت سنة 1299م على يد عثمان بن أرطغرل في بيتنية، فتحت القسطنطينية سنة 1453م على يد محمد الفاتح، وضمّت الشام ومصر والحجاز سنة 1517م، وبلغت ذروتها مع سليمان القانوني، وانتهت سنة 1922م ثم أُلغيت خلافتها سنة 1924م.",
    period: { label: "1299 – 1922 م", startYear: 1299, endYear: 1922 },
    relatedEntities: [
      "ottoman.figure.osman-i","ottoman.figure.orhan","ottoman.figure.murad-i",
      "ottoman.figure.bayezid-i","ottoman.figure.mehmed-i","ottoman.figure.murad-ii",
      "ottoman.figure.mehmed-ii","ottoman.figure.bayezid-ii","ottoman.figure.selim-i",
      "ottoman.figure.suleiman-i","ottoman.figure.murad-iv","ottoman.figure.abdul-hamid-ii",
      "ottoman.figure.mehmed-vi",
      "ottoman.city.istanbul","ottoman.city.bursa","ottoman.city.edirne",
      "ottoman.city.damascus","ottoman.city.cairo","ottoman.city.mecca","ottoman.city.medina",
      "ottoman.city.baghdad","ottoman.city.jerusalem",
      "ottoman.battle.kosovo","ottoman.battle.conquest-constantinople",
      "ottoman.battle.marj-dabiq","ottoman.battle.ridaniya","ottoman.battle.siege-vienna-1",
      "ottoman.event.founding","ottoman.event.fall-constantinople","ottoman.event.annex-sham",
      "ottoman.event.annex-egypt","ottoman.event.suleiman-era","ottoman.event.abolish-caliphate","ottoman.event.fall-ottoman",
    ],
    unlockables: [
      { kind: "campaign", refId: "ottoman", label: "حملات الدولة العثمانية" },
    ],
    image: { alt: "راية الدولة العثمانية", glyph: "☪️", tone: "from-red-800/40 to-stone-900" },
    timelinePosition: 1299,
    rarity: "legendary",
    meta: {
      founder: "عثمان بن أرطغرل",
      capital: "بورصة → أدرنة → القسطنطينية (إسطنبول)",
      majorCities: ["إسطنبول","بورصة","أدرنة","سالونيك","القدس","دمشق","القاهرة","بغداد","مكة","المدينة"],
      majorFigures: ["عثمان","أورخان","مراد الأول","بايزيد الأول","محمد الفاتح","سليم الأول","سليمان القانوني","عبد الحميد الثاني","محمد السادس"],
      majorBattles: ["كوسوفو","نيقوبوليس","أنقرة","فتح القسطنطينية","جالديران","مرج دابق","الريدانية","فيينا الأول","فيينا الثاني","نافارين"],
      majorEvents: ["التأسيس","فتح القسطنطينية","ضم الشام","ضم مصر","ضم الحجاز","عصر سليمان","التنظيمات","الحرب الكبرى","إلغاء الخلافة"],
    },
    bridges: { era: "ottoman" },
  }),

  // ---------- FIGURES (Sultans) ----------
  ...FIGURE_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `ottoman.figure.${slug}`,
    title, latin, type: "figure", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["ottoman.state.ottoman", ...related],
    unlockables: [{ kind: "figure", refId: `ottoman.figure.${slug}`, label: title }],
    image: { alt: title, glyph: "☪️", tone: "from-red-800/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "epic",
    meta: { titles: [title] },
    bridges: { era: "ottoman" },
  })),

  // ---------- SCHOLARS ----------
  ...SCHOLAR_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `ottoman.figure.${slug}`,
    title, latin, type: "figure", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["ottoman.state.ottoman", ...related],
    unlockables: [{ kind: "figure", refId: `ottoman.figure.${slug}`, label: title }],
    image: { alt: title, glyph: "📚", tone: "from-emerald-800/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "epic",
    meta: { kind: "scholar", titles: [title] },
    bridges: { era: "ottoman" },
  })),

  // ---------- CITIES ----------
  ...CITY_IDS.map(([slug, title, latin, description, startYear, endYear, related]) => E({
    id: `ottoman.city.${slug}`,
    title, latin, type: "city", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["ottoman.state.ottoman", ...related],
    unlockables: [{ kind: "city", refId: `ottoman.city.${slug}`, label: title }],
    image: { alt: title, glyph: "🏙️", tone: "from-red-800/30 to-stone-900" },
    timelinePosition: startYear,
    rarity: "rare",
    bridges: { cityId: slug, era: "ottoman" },
  })),

  // ---------- BATTLES ----------
  ...BATTLE_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `ottoman.battle.${slug}`,
    title, latin, type: "battle", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["ottoman.state.ottoman", ...related],
    unlockables: [{ kind: "battle", refId: `ottoman.battle.${slug}`, label: title }],
    image: { alt: title, glyph: "⚔️", tone: "from-red-800/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "epic",
    bridges: { era: "ottoman" },
  })),

  // ---------- EVENTS ----------
  ...EVENT_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `ottoman.event.${slug}`,
    title, latin, type: "event", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["ottoman.state.ottoman", ...related],
    unlockables: [{ kind: "event", refId: `ottoman.event.${slug}`, label: title }],
    image: { alt: title, glyph: "📜", tone: "from-emerald-800/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "rare",
    bridges: { era: "ottoman" },
  })),

  // ---------- LANDMARKS ----------
  ...LANDMARK_IDS.map(([slug, title, latin, description, startYear, endYear, related]) => E({
    id: `ottoman.landmark.${slug}`,
    title, latin, type: "landmark", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["ottoman.state.ottoman", ...related],
    unlockables: [{ kind: "landmark", refId: `ottoman.landmark.${slug}`, label: title }],
    image: { alt: title, glyph: "🕌", tone: "from-red-800/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "epic",
    bridges: { era: "ottoman" },
  })),

  // ---------- ARTIFACTS ----------
  ...ARTIFACT_IDS.map(([slug, title, latin, description, startYear, endYear, glyph, rarity, related]) => E({
    id: `ottoman.artifact.${slug}`,
    title, latin, type: "artifact", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["ottoman.state.ottoman", ...related],
    unlockables: [{ kind: "artifact", refId: `ottoman.artifact.${slug}`, label: title }],
    image: { alt: title, glyph: glyph as string, tone: "from-red-800/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: rarity as "common" | "rare" | "epic" | "legendary",
    bridges: { era: "ottoman" },
  })),

  // ---------- ACHIEVEMENTS ----------
  ...ACHIEVEMENT_IDS.map(([slug, title, latin, description, related]) => E({
    id: `ottoman.achievement.${slug}`,
    title, latin, type: "achievement", description,
    period: { label: "1299 – 1922 م", startYear: 1299, endYear: 1922 },
    relatedEntities: ["ottoman.state.ottoman", ...related],
    unlockables: [{ kind: "title", refId: `ottoman.achievement.${slug}`, label: title }],
    image: { alt: title, glyph: "🏅", tone: "from-amber-600/40 to-stone-900" },
    timelinePosition: 1600,
    rarity: "legendary",
    bridges: { era: "ottoman" },
  })),

  // ---------- FUTURE CAMPAIGN PLACEHOLDERS (locked) ----------
  ...FUTURE_CAMPAIGN_IDS.map(([slug, title, startYear, endYear, description]) => E({
    id: `ottoman.event.${slug}`,
    title, type: "event", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["ottoman.state.ottoman"],
    unlockables: [],
    image: { alt: title, glyph: "🔒", tone: "from-stone-700/40 to-slate-900" },
    timelinePosition: startYear,
    rarity: "legendary",
    meta: { locked: true, kind: "campaign-placeholder" },
    bridges: { era: "ottoman" },
  })),
];

export const OTTOMAN_PACK: ContentPack = {
  id: "pack-006-ottoman",
  order: 6,
  title: "الدولة العثمانية",
  subtitle: "المجموعة 6 · فاتحو القسطنطينية وحُماة الخلافة",
  summary:
    "حزمة محتوى تاريخية شاملة عن الدولة العثمانية من نشأتها في بيتنية إلى فتح القسطنطينية وضم الشام ومصر والحجاز وعصر سليمان القانوني حتى إلغاء الخلافة سنة 1924م.",
  era: "ottoman",
  period: { label: "1299 – 1922 م", startYear: 1299, endYear: 1922 },
  cover: { alt: "غلاف الدولة العثمانية", glyph: "☪️", tone: "from-red-800/40 to-stone-900" },
  entities,
};