import type { ContentPack, PackEntity } from "./types";

// ============================================================
// Content Pack 007 — الخلافة الراشدة (Rashidun Caliphate)
// ------------------------------------------------------------
// Pure data pack. Auto-registers via packs/registry.ts and surfaces in
// Encyclopedia, State pages, Search, Timeline, Atlas, Related-History Graph,
// Content Audit, Museum, and the Future Campaign system.
// ============================================================

const E = (e: PackEntity): PackEntity => e;

// ---------- FIGURES ----------
const FIGURE_IDS = [
  ["abu-bakr","أبو بكر الصديق","Abu Bakr al-Siddiq",573,634,
    "أوّل الخلفاء الراشدين، صاحب رسول الله ﷺ في الغار، حارب أهل الردة وجمع القرآن وأرسل جيوش الفتوح إلى الشام والعراق.",
    ["rashidun.event.bayah-abu-bakr","rashidun.event.ridda-wars","rashidun.event.collect-quran","rashidun.figure.umar","rashidun.figure.khalid","rashidun.city.medina"]],
  ["umar","عمر بن الخطاب","Umar ibn al-Khattab",584,644,
    "أمير المؤمنين الثاني، الفاروق، في عهده فُتحت الشام والعراق ومصر، ودوّن الدواوين وأرّخ بالهجرة، استُشهد على يد أبي لؤلؤة سنة ٢٣هـ.",
    ["rashidun.event.umar-martyrdom","rashidun.event.conquest-sham","rashidun.event.conquest-iraq","rashidun.event.conquest-jerusalem","rashidun.battle.yarmouk","rashidun.battle.qadisiyya","rashidun.artifact.umar-letter","rashidun.figure.uthman","rashidun.figure.khalid","rashidun.figure.amr-ibn-al-as","rashidun.figure.sad-ibn-abi-waqqas"]],
  ["uthman","عثمان بن عفان","Uthman ibn Affan",576,656,
    "أمير المؤمنين الثالث، ذو النورين، جمع الناس على مصحف واحد، اتسعت الفتوح في عهده شرقًا وغربًا، استُشهد في داره سنة ٣٥هـ بإيدي الثائرين فبدأت الفتنة الكبرى.",
    ["rashidun.event.uthmanic-mushaf","rashidun.event.uthman-martyrdom","rashidun.event.great-fitna","rashidun.figure.umar","rashidun.figure.ali","rashidun.artifact.uthmanic-mushaf"]],
  ["ali","علي بن أبي طالب","Ali ibn Abi Talib",601,661,
    "أمير المؤمنين الرابع، ابن عم النبي ﷺ وزوج فاطمة، نُقلت في عهده العاصمة إلى الكوفة، وقعت الجمل وصفّين، استُشهد على يد ابن ملجم سنة ٤٠هـ.",
    ["rashidun.battle.jamal","rashidun.battle.siffin","rashidun.event.ali-caliphate","rashidun.event.ali-martyrdom","rashidun.event.end-rashidun","rashidun.figure.hasan","rashidun.figure.husayn","rashidun.city.kufa","rashidun.figure.uthman"]],
  ["khalid","خالد بن الوليد","Khalid ibn al-Walid",592,642,
    "سيف الله المسلول، قائد فتح العراق ثم الشام، انتصاراته في اليرموك وأجنادين ودمشق غيّرت وجه العالم القديم في سنواتٍ معدودة.",
    ["rashidun.battle.yarmouk","rashidun.battle.ajnadayn","rashidun.battle.damascus-conquest","rashidun.battle.bridge","rashidun.event.conquest-sham","rashidun.event.conquest-iraq","rashidun.figure.abu-ubaidah","rashidun.figure.abu-bakr","rashidun.artifact.sword-khalid"]],
  ["abu-ubaidah","أبو عبيدة بن الجراح","Abu Ubaidah ibn al-Jarrah",583,639,
    "أمين هذه الأمة وأحد العشرة المبشّرين، أمير جيش الشام بعد خالد، فتح حمصًا وحلب وأنطاكية، استُشهد بطاعون عمواس.",
    ["rashidun.event.conquest-sham","rashidun.battle.yarmouk","rashidun.battle.damascus-conquest","rashidun.city.homs","rashidun.city.damascus","rashidun.figure.khalid"]],
  ["amr-ibn-al-as","عمرو بن العاص","Amr ibn al-As",583,664,
    "داهية العرب، فاتح مصر سنة ٢٠هـ، أسّس الفسطاط وبنى أوّل مساجدها، حضر صفّين ثم وُلّي مصر مرة أخرى.",
    ["rashidun.event.conquest-egypt","rashidun.city.fustat","rashidun.battle.siffin","rashidun.landmark.amr-mosque","rashidun.figure.umar"]],
  ["sad-ibn-abi-waqqas","سعد بن أبي وقاص","Sa'd ibn Abi Waqqas",595,674,
    "خال رسول الله ﷺ وأحد العشرة المبشّرين، قائد القادسية وفاتح المدائن وعاصمة الفرس، أسّس الكوفة سنة ١٧هـ.",
    ["rashidun.battle.qadisiyya","rashidun.battle.nahavand","rashidun.event.conquest-iraq","rashidun.city.kufa","rashidun.city.madain","rashidun.artifact.manuscript-qadisiyya","rashidun.figure.umar"]],
  ["muthanna","المثنى بن حارثة الشيباني","Al-Muthanna ibn Haritha",590,635,
    "قائد العرب على ثغر العراق قبل القادسية، صاحب البويب وممهّد طريق الفتح الفارسي قبل وصول سعد.",
    ["rashidun.battle.bridge","rashidun.battle.qadisiyya","rashidun.event.conquest-iraq","rashidun.figure.khalid","rashidun.figure.umar"]],
  ["ammar","عمار بن ياسر","Ammar ibn Yasir",570,657,
    "من السابقين الأوّلين، عذّبه المشركون في مكة، وُلّي الكوفة في عهد عمر، استُشهد في صفّين مع علي، فصدق فيه قول النبي ﷺ.",
    ["rashidun.battle.siffin","rashidun.figure.ali","rashidun.city.kufa","rashidun.event.great-fitna"]],
  ["hasan","الحسن بن علي","Al-Hasan ibn Ali",625,670,
    "سبط رسول الله ﷺ وريحانته، بويع بالخلافة بعد استشهاد أبيه، ثم تنازل لمعاوية في عام الجماعة سنة ٤١هـ فحقن الدماء.",
    ["rashidun.event.end-rashidun","rashidun.event.ali-martyrdom","rashidun.figure.ali","rashidun.figure.husayn"]],
  ["husayn","الحسين بن علي","Al-Husayn ibn Ali",626,680,
    "سبط رسول الله ﷺ وسيد شباب أهل الجنّة، رفض بيعة يزيد واستُشهد في كربلاء سنة ٦١هـ، أحد أعظم آلام تاريخ المسلمين.",
    ["rashidun.figure.ali","rashidun.figure.hasan","rashidun.event.end-rashidun"]],
] as const;

// ---------- SCHOLARS (Companions of fiqh/qur'an/hadith) ----------
const SCHOLAR_IDS = [
  ["zayd-ibn-thabit","زيد بن ثابت","Zayd ibn Thabit",611,665,
    "كاتب الوحي وأمين جمع القرآن، توّلى جمع المصحف في عهد أبي بكر ثم نسخه في عهد عثمان، إمام الفرائض والقراءات.",
    ["rashidun.event.collect-quran","rashidun.event.uthmanic-mushaf","rashidun.artifact.uthmanic-mushaf","rashidun.figure.abu-bakr","rashidun.figure.uthman"]],
  ["ibn-abbas","عبد الله بن عباس","Abdullah ibn Abbas",619,687,
    "حبر الأمة وترجمان القرآن، ابن عمّ النبي ﷺ، دعا له النبي بالفقه في الدين، أحد أعظم مفسري الصحابة.",
    ["rashidun.figure.ali","rashidun.city.medina","rashidun.figure.uthman"]],
  ["ibn-masud","عبد الله بن مسعود","Abdullah ibn Mas'ud",594,653,
    "صاحب نعل النبي ﷺ ومطهرته، إمام أهل الكوفة في القرآن والفقه، أحد القراء السبعة الذين أخذ عنهم العلم.",
    ["rashidun.city.kufa","rashidun.figure.umar","rashidun.figure.uthman"]],
  ["abu-musa","أبو موسى الأشعري","Abu Musa al-Ash'ari",602,665,
    "أمير البصرة في عهد عمر، فاتح الأهواز وأصفهان، الحَكَم في التحكيم بعد صفّين، صاحب الصوت الحسن بالقرآن.",
    ["rashidun.city.basra","rashidun.battle.nahavand","rashidun.event.great-fitna","rashidun.battle.siffin","rashidun.figure.umar"]],
  ["abu-darda","أبو الدرداء","Abu al-Darda'",600,652,
    "حكيم هذه الأمة، تولّى قضاء دمشق في عهد عمر وعثمان، من علماء الصحابة الأوائل في الشام.",
    ["rashidun.city.damascus","rashidun.figure.umar","rashidun.figure.uthman","rashidun.event.conquest-sham"]],
  ["muadh","معاذ بن جبل","Mu'adh ibn Jabal",603,639,
    "أعلم الصحابة بالحلال والحرام، أرسله النبي ﷺ إلى اليمن، وكان أحد قضاة الشام في عهد عمر، توفي في طاعون عمواس.",
    ["rashidun.city.damascus","rashidun.figure.abu-ubaidah","rashidun.figure.umar","rashidun.event.conquest-sham"]],
] as const;

// ---------- CITIES ----------
const CITY_IDS = [
  ["medina","المدينة المنورة","Medina",
    "عاصمة الخلافة الراشدة الأولى ودار النبي ﷺ، منها سيّر الخلفاء الجيوش إلى الشام والعراق ومصر وإليها رُدّت الغنائم.",
    632,656,["rashidun.landmark.prophet-mosque","rashidun.landmark.quba-mosque","rashidun.landmark.bayt-al-mal","rashidun.figure.abu-bakr","rashidun.figure.umar","rashidun.figure.uthman"]],
  ["mecca","مكة المكرمة","Mecca",
    "أمّ القرى ومهبط الوحي، حاضرة الحج وقبلة المسلمين، رعاها الخلفاء الراشدون وأقاموا فيها الحجّ كل عام.",
    632,661,["rashidun.landmark.sacred-mosque","rashidun.figure.umar","rashidun.figure.uthman"]],
  ["jerusalem","بيت المقدس","Jerusalem",
    "أولى القبلتين وثالث الحرمين، فتحها عمر بن الخطاب سنة ١٥هـ وكتب فيها العهدة العمرية لأهلها، بُنيت في زمن الصحابة مصلّى الأقصى.",
    637,661,["rashidun.event.conquest-jerusalem","rashidun.landmark.dome-rock","rashidun.landmark.umari-mosque","rashidun.landmark.jabiya-gate","rashidun.figure.umar"]],
  ["damascus","دمشق","Damascus",
    "حاضرة الشام، فتحها أبو عبيدة وخالد بن الوليد سنة ١٤هـ، صارت قاعدة جند الشام ودار قضاء أبي الدرداء.",
    635,661,["rashidun.battle.damascus-conquest","rashidun.event.conquest-sham","rashidun.figure.abu-ubaidah","rashidun.figure.khalid","rashidun.figure.abu-darda"]],
  ["kufa","الكوفة","Kufa",
    "مصرٌ مصّره عمر بن الخطاب سنة ١٧هـ على يد سعد بن أبي وقاص، صارت عاصمة علي بن أبي طالب وحاضرة العراق العسكرية والعلمية.",
    638,661,["rashidun.figure.sad-ibn-abi-waqqas","rashidun.figure.ali","rashidun.figure.ammar","rashidun.figure.ibn-masud","rashidun.landmark.imarah-house"]],
  ["basra","البصرة","Basra",
    "مصرٌ مصّره عمر بن الخطاب سنة ١٤هـ على شطّ العرب، قاعدة الفتح في فارس والأهواز ومنزل أبي موسى الأشعري.",
    635,661,["rashidun.figure.abu-musa","rashidun.battle.jamal","rashidun.event.conquest-iraq","rashidun.figure.umar"]],
  ["fustat","الفسطاط","Fustat",
    "أوّل عواصم الإسلام في مصر، أسّسها عمرو بن العاص سنة ٢١هـ شمال حصن بابليون، وبنى فيها أوّل جامع في إفريقيا.",
    641,661,["rashidun.figure.amr-ibn-al-as","rashidun.event.conquest-egypt","rashidun.landmark.amr-mosque","rashidun.landmark.fustat-camp"]],
  ["madain","المدائن","Ctesiphon (al-Mada'in)",
    "عاصمة الفرس الساسانيين، فتحها سعد بن أبي وقاص بعد القادسية سنة ١٦هـ، ودخل إيوان كسرى يُصلّي فيه.",
    637,661,["rashidun.battle.qadisiyya","rashidun.figure.sad-ibn-abi-waqqas","rashidun.event.conquest-iraq"]],
  ["homs","حمص","Homs",
    "ثغرٌ شامي كبير فتحه أبو عبيدة سنة ١٥هـ، صار قاعدة جند حمص ومن أوسع نيابات الشام في صدر الإسلام.",
    635,661,["rashidun.figure.abu-ubaidah","rashidun.event.conquest-sham","rashidun.battle.yarmouk"]],
  ["bayt-al-maqdis","إيلياء (بيت المقدس)","Aelia / Bayt al-Maqdis",
    "اسم القدس البيزنطي يوم الفتح، استلم عمر مفاتيحها من البطريرك صفرونيوس ودخلها ماشيًا وغلامه راكب.",
    637,661,["rashidun.event.conquest-jerusalem","rashidun.figure.umar","rashidun.landmark.dome-rock","rashidun.landmark.umari-mosque"]],
] as const;

// ---------- BATTLES ----------
const BATTLE_IDS = [
  ["yarmouk","معركة اليرموك","Battle of Yarmouk",636,636,
    "المعركة الفاصلة بين المسلمين بقيادة خالد بن الوليد وأبي عبيدة وجيش هرقل البيزنطي، حسمت سقوط الشام في يد المسلمين.",
    ["rashidun.figure.khalid","rashidun.figure.abu-ubaidah","rashidun.event.conquest-sham","rashidun.city.damascus","rashidun.city.homs","rashidun.artifact.manuscript-yarmouk"]],
  ["qadisiyya","معركة القادسية","Battle of al-Qadisiyya",636,636,
    "المعركة الفاصلة بين سعد بن أبي وقاص ورستم قائد كسرى، انهار بعدها جيش الفرس وفُتح طريق المدائن.",
    ["rashidun.figure.sad-ibn-abi-waqqas","rashidun.figure.muthanna","rashidun.event.conquest-iraq","rashidun.city.madain","rashidun.city.kufa","rashidun.artifact.manuscript-qadisiyya"]],
  ["nahavand","معركة نهاوند","Battle of Nahavand",642,642,
    "فتح الفتوح، آخر معارك الفرس الكبرى ضدّ المسلمين، انهار بعدها كيان الدولة الساسانية كلّه.",
    ["rashidun.event.conquest-iraq","rashidun.figure.umar","rashidun.figure.abu-musa"]],
  ["bridge","معركة الجسر","Battle of the Bridge",634,634,
    "نكسةٌ مبكّرة للمسلمين أمام الفرس على نهر الفرات، استُشهد فيها أبو عبيد الثقفي وانسحب المثنى بمن بقي.",
    ["rashidun.figure.muthanna","rashidun.event.conquest-iraq","rashidun.figure.umar"]],
  ["ajnadayn","معركة أجنادين","Battle of Ajnadayn",634,634,
    "أوّل معركة كبرى بين المسلمين والبيزنطيين في فلسطين، انتصر فيها خالد وعمرو بن العاص وفتح بها الباب للشام.",
    ["rashidun.figure.khalid","rashidun.figure.amr-ibn-al-as","rashidun.event.conquest-sham"]],
  ["damascus-conquest","فتح دمشق","Conquest of Damascus",635,635,
    "حصار خالد وأبي عبيدة لدمشق ستة أشهر ثم فتحها صلحًا وعنوة سنة ١٤هـ، أوّل حواضر الشام تسقط.",
    ["rashidun.figure.khalid","rashidun.figure.abu-ubaidah","rashidun.city.damascus","rashidun.event.conquest-sham"]],
  ["jerusalem-conquest","فتح بيت المقدس","Conquest of Jerusalem",637,637,
    "تسلّم عمر بن الخطاب مفاتيح بيت المقدس من البطريرك صفرونيوس بعد حصارٍ طويل، وكتب العهدة العمرية الشهيرة.",
    ["rashidun.figure.umar","rashidun.event.conquest-jerusalem","rashidun.city.jerusalem","rashidun.city.bayt-al-maqdis","rashidun.landmark.umari-mosque","rashidun.landmark.jabiya-gate"]],
  ["egypt-conquest","فتح مصر","Conquest of Egypt",640,642,
    "حملة عمرو بن العاص على مصر، فتح حصن بابليون ثم الإسكندرية وأسّس الفسطاط سنة ٢١هـ.",
    ["rashidun.figure.amr-ibn-al-as","rashidun.event.conquest-egypt","rashidun.city.fustat","rashidun.landmark.amr-mosque","rashidun.landmark.fustat-camp"]],
  ["siffin","معركة صفّين","Battle of Siffin",657,657,
    "موقعةٌ كبرى بين علي بن أبي طالب ومعاوية بن أبي سفيان قرب الفرات، انتهت برفع المصاحف ثم التحكيم وانقسام الأمة.",
    ["rashidun.figure.ali","rashidun.figure.ammar","rashidun.figure.abu-musa","rashidun.event.great-fitna"]],
  ["jamal","معركة الجمل","Battle of the Camel",656,656,
    "أولى موقعات الفتنة الكبرى بين علي وعائشة ومن معها من الصحابة، بعد مقتل عثمان، وقعت قرب البصرة.",
    ["rashidun.figure.ali","rashidun.city.basra","rashidun.event.great-fitna","rashidun.event.uthman-martyrdom"]],
] as const;

// ---------- EVENTS ----------
const EVENT_IDS = [
  ["prophet-death","وفاة النبي ﷺ","Passing of the Prophet ﷺ",632,632,
    "وفاة رسول الله ﷺ في ربيع الأول سنة ١١هـ، أعظم رزء أصاب الأمّة، وبداية عصر الخلافة الراشدة.",
    ["rashidun.event.bayah-abu-bakr","rashidun.figure.abu-bakr","rashidun.city.medina"]],
  ["bayah-abu-bakr","بيعة أبي بكر","Pledge to Abu Bakr",632,632,
    "بيعة الصحابة لأبي بكر في سقيفة بني ساعدة بعد وفاة النبي ﷺ، أوّل خلافة في الإسلام.",
    ["rashidun.figure.abu-bakr","rashidun.event.prophet-death","rashidun.city.medina"]],
  ["ridda-wars","حروب الردة","Wars of Apostasy",632,633,
    "حملات أبي بكر الصديق على مسيلمة الكذّاب وطليحة وسجاح وأهل الردة، حفظت كيان الدولة الفتيّة.",
    ["rashidun.figure.abu-bakr","rashidun.figure.khalid","rashidun.event.collect-quran"]],
  ["collect-quran","جمع القرآن","First Compilation of the Qur'an",633,634,
    "جمع أبي بكر القرآن في صحفٍ على يد زيد بن ثابت بعد استشهاد كثيرٍ من القرّاء في اليمامة.",
    ["rashidun.figure.abu-bakr","rashidun.figure.zayd-ibn-thabit","rashidun.event.ridda-wars","rashidun.event.uthmanic-mushaf"]],
  ["conquest-sham","فتح الشام","Conquest of Greater Syria",634,640,
    "فتح المسلمين الشام بقيادة خالد وأبي عبيدة وعمرو بن العاص، حسمته اليرموك وأجنادين وفتح دمشق وحمص والقدس.",
    ["rashidun.battle.yarmouk","rashidun.battle.ajnadayn","rashidun.battle.damascus-conquest","rashidun.figure.khalid","rashidun.figure.abu-ubaidah","rashidun.figure.umar","rashidun.city.damascus","rashidun.city.homs","rashidun.city.jerusalem"]],
  ["conquest-iraq","فتح العراق","Conquest of Iraq",633,642,
    "فتح المسلمين العراق وفارس بقيادة خالد ثم المثنى ثم سعد بن أبي وقاص، حسمته القادسية ونهاوند.",
    ["rashidun.battle.qadisiyya","rashidun.battle.nahavand","rashidun.battle.bridge","rashidun.figure.sad-ibn-abi-waqqas","rashidun.figure.muthanna","rashidun.figure.khalid","rashidun.city.kufa","rashidun.city.basra","rashidun.city.madain"]],
  ["conquest-egypt","فتح مصر","Conquest of Egypt",640,642,
    "حملة عمرو بن العاص على مصر بإذن عمر، انتهت بفتح بابليون والإسكندرية وتأسيس الفسطاط.",
    ["rashidun.figure.amr-ibn-al-as","rashidun.battle.egypt-conquest","rashidun.city.fustat","rashidun.landmark.amr-mosque"]],
  ["conquest-jerusalem","فتح بيت المقدس","Conquest of Jerusalem",637,637,
    "تسلّم عمر بن الخطاب مفاتيح القدس بنفسه وكتب العهدة العمرية الشهيرة لأهلها، صلّى عند الصخرة وأمر بتنظيفها.",
    ["rashidun.figure.umar","rashidun.battle.jerusalem-conquest","rashidun.city.jerusalem","rashidun.landmark.dome-rock","rashidun.landmark.umari-mosque","rashidun.landmark.jabiya-gate"]],
  ["umar-martyrdom","استشهاد عمر بن الخطاب","Martyrdom of Umar",644,644,
    "طعن أبو لؤلؤة المجوسي عمر في صلاة الفجر في المسجد النبوي، فجعل الخلافة شورى بين الستة، فبويع عثمان.",
    ["rashidun.figure.umar","rashidun.figure.uthman","rashidun.city.medina","rashidun.landmark.prophet-mosque"]],
  ["uthmanic-mushaf","جمع المصحف العثماني","The Uthmanic Codex",650,656,
    "جمع عثمان الناس على مصحفٍ واحد بقيادة زيد بن ثابت، ووزّع المصاحف على الأمصار، أعظم منجزات الخلافة بعد الفتوح.",
    ["rashidun.figure.uthman","rashidun.figure.zayd-ibn-thabit","rashidun.artifact.uthmanic-mushaf","rashidun.event.collect-quran"]],
  ["great-fitna","الفتنة الكبرى","The Great Fitna",656,661,
    "أحداث الفتنة منذ مقتل عثمان إلى الجمل وصفّين والتحكيم واستشهاد علي، ونهاية الخلافة الراشدة.",
    ["rashidun.event.uthman-martyrdom","rashidun.battle.jamal","rashidun.battle.siffin","rashidun.figure.ali","rashidun.figure.uthman","rashidun.figure.ammar","rashidun.event.end-rashidun"]],
  ["uthman-martyrdom","استشهاد عثمان بن عفان","Martyrdom of Uthman",656,656,
    "حصار الثائرين دار عثمان في المدينة قتلوه بين يديه المصحف، فاشتعلت نار الفتنة في الأمّة.",
    ["rashidun.figure.uthman","rashidun.event.great-fitna","rashidun.battle.jamal","rashidun.city.medina"]],
  ["ali-caliphate","خلافة علي بن أبي طالب","Caliphate of Ali",656,661,
    "بيعة علي بعد مقتل عثمان، نقله العاصمة إلى الكوفة، ومواجهة الجمل وصفّين والخوارج حتى استشهاده.",
    ["rashidun.figure.ali","rashidun.city.kufa","rashidun.battle.jamal","rashidun.battle.siffin","rashidun.event.great-fitna"]],
  ["ali-martyrdom","استشهاد علي بن أبي طالب","Martyrdom of Ali",661,661,
    "طعن ابن ملجم الخارجي علي بن أبي طالب في مسجد الكوفة فجر ١٧ رمضان سنة ٤٠هـ، فبويع الحسن.",
    ["rashidun.figure.ali","rashidun.figure.hasan","rashidun.city.kufa","rashidun.event.end-rashidun"]],
  ["end-rashidun","نهاية الخلافة الراشدة","End of the Rashidun Caliphate",661,661,
    "تنازل الحسن بن علي لمعاوية في عام الجماعة سنة ٤١هـ فحقن الدماء، وانتهت الخلافة الراشدة وبدأت الدولة الأموية.",
    ["rashidun.figure.hasan","rashidun.figure.ali","rashidun.event.ali-martyrdom","rashidun.event.great-fitna"]],
] as const;

// ---------- LANDMARKS ----------
const LANDMARK_IDS = [
  ["prophet-mosque","المسجد النبوي","The Prophet's Mosque",
    "مسجد رسول الله ﷺ في المدينة، قبلة الخلفاء الراشدين ومنبرهم، وُسّع في عهد عمر وعثمان.",
    622,661,["rashidun.city.medina","rashidun.figure.abu-bakr","rashidun.figure.umar","rashidun.figure.uthman","rashidun.event.umar-martyrdom"]],
  ["sacred-mosque","المسجد الحرام","The Sacred Mosque",
    "الكعبة المشرّفة وحرم مكة، عُني الخلفاء الراشدون بتوسيعه وعمارته وأبقوا الحجّ سنّة الناس كل عام.",
    632,661,["rashidun.city.mecca","rashidun.figure.umar","rashidun.figure.uthman"]],
  ["dome-rock","الصخرة المشرّفة","The Sacred Rock (Dome of the Rock site)",
    "صخرة الإسراء والمعراج في القدس، أمر عمر بكشفها وتنظيفها بعد فتح القدس وصلّى عندها.",
    637,661,["rashidun.figure.umar","rashidun.city.jerusalem","rashidun.event.conquest-jerusalem"]],
  ["quba-mosque","مسجد قباء","Quba Mosque",
    "أوّل مسجد بُني في الإسلام، حافظ عليه الخلفاء الراشدون وسارت إليه راحلتهم كل سبت اقتداءً بالنبي ﷺ.",
    622,661,["rashidun.city.medina","rashidun.figure.abu-bakr"]],
  ["fath-mosque","مسجد الفتح","Mosque of al-Fath",
    "مسجدٌ على جبل سَلْع في المدينة، عند مكان دعاء النبي ﷺ يوم الأحزاب، حافظ عليه الراشدون كرمز للنصر.",
    627,661,["rashidun.city.medina","rashidun.figure.abu-bakr"]],
  ["bayt-al-mal","بيت المال","Bayt al-Mal (Public Treasury)",
    "أوّل خزانة عامة للمسلمين في المدينة، ثم في الكوفة، نظّمها عمر بن الخطاب ودوّن الدواوين ووزّع العطاء.",
    634,661,["rashidun.figure.umar","rashidun.city.medina","rashidun.city.kufa","rashidun.artifact.diwan-jund"]],
  ["imarah-house","دار الإمارة بالكوفة","Dar al-Imarah of Kufa",
    "مقرّ الإمارة في الكوفة الذي بناه سعد بن أبي وقاص، صار قصر علي بن أبي طالب وحاضرة دولته.",
    638,661,["rashidun.city.kufa","rashidun.figure.sad-ibn-abi-waqqas","rashidun.figure.ali"]],
  ["fustat-camp","معسكر الفسطاط","Camp of Fustat",
    "مقرّ خيمة عمرو بن العاص شمال حصن بابليون، صار نواة مدينة الفسطاط أوّل عواصم الإسلام في إفريقيا.",
    641,661,["rashidun.figure.amr-ibn-al-as","rashidun.city.fustat","rashidun.event.conquest-egypt"]],
  ["amr-mosque","الجامع العمري بالفسطاط","Mosque of Amr ibn al-As",
    "أوّل مسجدٍ بُني في مصر وإفريقيا، أنشأه عمرو بن العاص بالفسطاط سنة ٢١هـ.",
    641,661,["rashidun.figure.amr-ibn-al-as","rashidun.city.fustat","rashidun.event.conquest-egypt"]],
  ["umari-mosque","الجامع العمري (القدس)","Umari Mosque (Jerusalem)",
    "موضع صلاة عمر بن الخطاب يوم تسلّم القدس، نواة المسجد الأقصى المبني لاحقًا، شاهد العهدة العمرية.",
    637,661,["rashidun.figure.umar","rashidun.city.jerusalem","rashidun.event.conquest-jerusalem"]],
  ["jabiya-gate","باب الجابية","Bab al-Jabiya (Damascus Gate)",
    "الباب الغربي لدمشق، دخل منه خالد بن الوليد يوم فتح دمشق سنة ١٤هـ في حين دخل أبو عبيدة من باب آخر صلحًا.",
    635,661,["rashidun.figure.khalid","rashidun.figure.abu-ubaidah","rashidun.city.damascus","rashidun.battle.damascus-conquest"]],
] as const;

// ---------- ARTIFACTS ----------
const ARTIFACT_IDS = [
  ["uthmanic-mushaf","المصحف العثماني","The Uthmanic Codex",
    "نسخة المصحف الإمام التي أمر عثمان بنسخها وتوزيعها على الأمصار، أعظم وثيقةٍ في حفظ القرآن في تاريخ الأمّة.",
    650,661,"📖","legendary",["rashidun.figure.uthman","rashidun.figure.zayd-ibn-thabit","rashidun.event.uthmanic-mushaf","rashidun.event.collect-quran"]],
  ["conquest-banner","راية الفتوحات الراشدة","Banner of the Rashidun Conquests",
    "الراية السوداء والبيضاء التي رُفعت على جيوش المسلمين من اليرموك إلى نهاوند، رمز فتوح الخلافة الراشدة.",
    632,661,"🏴","epic",["rashidun.event.conquest-sham","rashidun.event.conquest-iraq","rashidun.event.conquest-egypt"]],
  ["sword-khalid","سيف خالد بن الوليد","Sword of Khalid ibn al-Walid",
    "سيف سيف الله المسلول الذي حمله في أكثر من مئة معركة من حرب الردة إلى اليرموك دون أن يهتزّ في يده.",
    632,642,"🗡️","legendary",["rashidun.figure.khalid","rashidun.battle.yarmouk","rashidun.battle.ajnadayn","rashidun.event.ridda-wars"]],
  ["caliphate-seal","ختم الخلافة الراشدة","Seal of the Rashidun Caliphate",
    "ختم الخلفاء الراشدين على رسائلهم إلى الأمصار وقادة الجيوش، رمز السلطة الشرعية الأولى في الإسلام.",
    632,661,"🪧","epic",["rashidun.figure.abu-bakr","rashidun.figure.umar","rashidun.figure.uthman","rashidun.figure.ali"]],
  ["umar-letter","رسالة عمر إلى الأمصار","Umar's Letter to the Provinces",
    "رسائل عمر بن الخطاب إلى الولاة والقادة في الأمصار، أعظم نموذج للإدارة العادلة في تاريخ الإسلام.",
    634,644,"📜","legendary",["rashidun.figure.umar","rashidun.landmark.bayt-al-mal","rashidun.artifact.diwan-jund"]],
  ["rashidun-map","خريطة الفتوحات الراشدة","Map of the Rashidun Conquests",
    "خريطةٌ تبيّن اتساع دولة الخلافة من حدود إفريقيا غربًا إلى خراسان شرقًا في نحو ثلاثين سنة.",
    640,661,"🗺️","epic",["rashidun.event.conquest-sham","rashidun.event.conquest-iraq","rashidun.event.conquest-egypt","rashidun.event.conquest-jerusalem"]],
  ["diwan-jund","ديوان الجند","Diwan al-Jund",
    "أوّل ديوان نظامي للجند في الإسلام، أنشأه عمر بن الخطاب وفرض فيه العطاء على المقاتلين وأبنائهم.",
    636,661,"📚","epic",["rashidun.figure.umar","rashidun.landmark.bayt-al-mal","rashidun.event.conquest-sham"]],
  ["manuscript-qadisiyya","مخطوطة القادسية","Manuscript of al-Qadisiyya",
    "وثيقةٌ تروي تفاصيل المعركة ومراسلات سعد مع عمر، ومجلس رستم قبل المعركة، ومشهد سقوط الفرس.",
    636,661,"📜","legendary",["rashidun.battle.qadisiyya","rashidun.figure.sad-ibn-abi-waqqas","rashidun.figure.umar"]],
  ["manuscript-yarmouk","مخطوطة اليرموك","Manuscript of Yarmouk",
    "وثيقةٌ تروي تفاصيل اليرموك وعزل خالد عن القيادة وتولّي أبي عبيدة وكتاب عمر إلى الجيش.",
    636,661,"📜","legendary",["rashidun.battle.yarmouk","rashidun.figure.khalid","rashidun.figure.abu-ubaidah","rashidun.figure.umar"]],
  ["sabiqun-medal","وسام السابقين الأوّلين","Medal of the First Forerunners",
    "وسامٌ شرفي يُمنح لمن أتمّ مسار صحابة رسول الله ﷺ في الخلافة الراشدة من أبي بكر إلى علي.",
    632,661,"🏵️","legendary",["rashidun.figure.abu-bakr","rashidun.figure.umar","rashidun.figure.uthman","rashidun.figure.ali","rashidun.figure.khalid","rashidun.figure.ammar"]],
] as const;

// ---------- ACHIEVEMENTS ----------
const ACHIEVEMENT_IDS = [
  ["sham-conqueror","فاتح الشام","Conqueror of Greater Syria",
    "يُمنح لمن أكمل قصص اليرموك ودمشق والقدس وخالد وأبي عبيدة.",
    ["rashidun.battle.yarmouk","rashidun.battle.damascus-conquest","rashidun.event.conquest-sham","rashidun.event.conquest-jerusalem","rashidun.figure.khalid","rashidun.figure.abu-ubaidah"]],
  ["iraq-conqueror","فاتح العراق","Conqueror of Iraq",
    "يُمنح لمن أكمل قصص القادسية ونهاوند والكوفة وسعد بن أبي وقاص.",
    ["rashidun.battle.qadisiyya","rashidun.battle.nahavand","rashidun.event.conquest-iraq","rashidun.figure.sad-ibn-abi-waqqas","rashidun.city.kufa","rashidun.city.madain"]],
  ["rashidun-historian","مؤرّخ الخلافة الراشدة","Historian of the Rashidun Caliphate",
    "يُمنح لمن قرأ جميع شخصيات وأحداث الخلافة الراشدة في الموسوعة.",
    ["rashidun.state.rashidun","rashidun.figure.abu-bakr","rashidun.figure.umar","rashidun.figure.uthman","rashidun.figure.ali","rashidun.event.great-fitna"]],
  ["rashidun-collector","جامع التراث الراشدي","Collector of Rashidun Heritage",
    "يُمنح لمن جمع كلّ الآثار والمخطوطات الراشدة في مجموعته.",
    ["rashidun.artifact.uthmanic-mushaf","rashidun.artifact.sword-khalid","rashidun.artifact.umar-letter","rashidun.artifact.manuscript-qadisiyya","rashidun.artifact.manuscript-yarmouk","rashidun.artifact.sabiqun-medal"]],
  ["caliphs-companion","رفيق الخلفاء","Companion of the Caliphs",
    "يُمنح لمن أتمّ مسار الخلفاء الأربعة وصحابتهم في القرارات والمواقف الكبرى.",
    ["rashidun.figure.abu-bakr","rashidun.figure.umar","rashidun.figure.uthman","rashidun.figure.ali","rashidun.figure.ammar","rashidun.figure.zayd-ibn-thabit"]],
] as const;

// ---------- FUTURE CAMPAIGN PLACEHOLDERS (locked) ----------
const FUTURE_CAMPAIGN_IDS = [
  ["future-abu-bakr",  "حملة أبي بكر الصديق",  632,634,"حملةٌ قادمة عن الردة وأوائل الفتوح في عهد الصديق. (قريبًا)"],
  ["future-khalid",    "حملة خالد بن الوليد",  633,638,"حملةٌ قادمة عن سيف الله المسلول من العراق إلى الشام. (قريبًا)"],
  ["future-yarmouk",   "معركة اليرموك",        636,636,"حملةٌ قادمة عن يومٍ غيّر وجه الشام. (قريبًا)"],
  ["future-qadisiyya", "معركة القادسية",       636,636,"حملةٌ قادمة عن سعد ورستم وانهيار الفرس. (قريبًا)"],
  ["future-amr",       "حملة عمرو بن العاص",   640,642,"حملةٌ قادمة عن فتح مصر وتأسيس الفسطاط. (قريبًا)"],
  ["future-umar",      "عهد عمر بن الخطاب",    634,644,"حملةٌ قادمة عن أعظم خلافةٍ في تنظيم الدواوين والفتوح. (قريبًا)"],
] as const;

const entities: PackEntity[] = [
  // ---------- STATE ----------
  E({
    id: "rashidun.state.rashidun",
    title: "الخلافة الراشدة",
    latin: "Rashidun Caliphate",
    type: "state",
    description:
      "الخلافة الراشدة، أوّل خلافة في الإسلام، قامت بعد وفاة النبي ﷺ سنة ١١هـ/٦٣٢م في المدينة المنورة، تولّاها أبو بكر فعمر فعثمان فعلي، فُتحت في عهدها الشام والعراق ومصر وفارس وبيت المقدس، وانتهت ببيعة الحسن بن علي لمعاوية سنة ٤١هـ/٦٦١م.",
    period: { label: "١١ – ٤١ هـ / ٦٣٢ – ٦٦١ م", startYear: 632, endYear: 661 },
    relatedEntities: [
      "rashidun.figure.abu-bakr","rashidun.figure.umar","rashidun.figure.uthman","rashidun.figure.ali",
      "rashidun.figure.khalid","rashidun.figure.abu-ubaidah","rashidun.figure.amr-ibn-al-as",
      "rashidun.figure.sad-ibn-abi-waqqas","rashidun.figure.hasan","rashidun.figure.husayn",
      "rashidun.city.medina","rashidun.city.mecca","rashidun.city.jerusalem","rashidun.city.damascus",
      "rashidun.city.kufa","rashidun.city.basra","rashidun.city.fustat","rashidun.city.madain",
      "rashidun.battle.yarmouk","rashidun.battle.qadisiyya","rashidun.battle.nahavand",
      "rashidun.battle.jerusalem-conquest","rashidun.battle.egypt-conquest",
      "rashidun.battle.siffin","rashidun.battle.jamal",
      "rashidun.event.prophet-death","rashidun.event.bayah-abu-bakr","rashidun.event.ridda-wars",
      "rashidun.event.collect-quran","rashidun.event.conquest-sham","rashidun.event.conquest-iraq",
      "rashidun.event.conquest-egypt","rashidun.event.conquest-jerusalem",
      "rashidun.event.uthmanic-mushaf","rashidun.event.great-fitna","rashidun.event.end-rashidun",
    ],
    unlockables: [
      { kind: "campaign", refId: "rashidun", label: "حملات الخلافة الراشدة" },
    ],
    image: { alt: "راية الخلافة الراشدة", glyph: "🕋", tone: "from-emerald-800/40 to-stone-900" },
    timelinePosition: 632,
    rarity: "legendary",
    meta: {
      founder: "أبو بكر الصديق رضي الله عنه",
      capital: "المدينة المنورة (ثم الكوفة)",
      majorCities: ["المدينة","مكة","القدس","دمشق","الكوفة","البصرة","الفسطاط","المدائن","حمص"],
      majorFigures: ["أبو بكر","عمر","عثمان","علي","خالد","أبو عبيدة","عمرو بن العاص","سعد بن أبي وقاص","الحسن","الحسين"],
      majorBattles: ["اليرموك","القادسية","نهاوند","الجسر","أجنادين","فتح دمشق","فتح القدس","فتح مصر","صفّين","الجمل"],
      majorEvents: ["بيعة أبي بكر","حروب الردة","جمع القرآن","فتح الشام","فتح العراق","فتح مصر","فتح القدس","المصحف العثماني","الفتنة الكبرى","نهاية الخلافة الراشدة"],
    },
    bridges: { era: "rashidun" },
  }),

  // ---------- FIGURES ----------
  ...FIGURE_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `rashidun.figure.${slug}`,
    title, latin, type: "figure", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["rashidun.state.rashidun", ...related],
    unlockables: [{ kind: "figure", refId: `rashidun.figure.${slug}`, label: title }],
    image: { alt: title, glyph: "🕋", tone: "from-emerald-800/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "epic",
    meta: { titles: [title] },
    bridges: { era: "rashidun" },
  })),

  // ---------- SCHOLARS ----------
  ...SCHOLAR_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `rashidun.figure.${slug}`,
    title, latin, type: "figure", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["rashidun.state.rashidun", ...related],
    unlockables: [{ kind: "figure", refId: `rashidun.figure.${slug}`, label: title }],
    image: { alt: title, glyph: "📚", tone: "from-emerald-800/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "epic",
    meta: { kind: "scholar", titles: [title] },
    bridges: { era: "rashidun" },
  })),

  // ---------- CITIES ----------
  ...CITY_IDS.map(([slug, title, latin, description, startYear, endYear, related]) => E({
    id: `rashidun.city.${slug}`,
    title, latin, type: "city", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["rashidun.state.rashidun", ...related],
    unlockables: [{ kind: "city", refId: `rashidun.city.${slug}`, label: title }],
    image: { alt: title, glyph: "🏙️", tone: "from-emerald-800/30 to-stone-900" },
    timelinePosition: startYear,
    rarity: "rare",
    bridges: { cityId: slug, era: "rashidun" },
  })),

  // ---------- BATTLES ----------
  ...BATTLE_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `rashidun.battle.${slug}`,
    title, latin, type: "battle", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["rashidun.state.rashidun", ...related],
    unlockables: [{ kind: "battle", refId: `rashidun.battle.${slug}`, label: title }],
    image: { alt: title, glyph: "⚔️", tone: "from-red-800/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "epic",
    bridges: { era: "rashidun" },
  })),

  // ---------- EVENTS ----------
  ...EVENT_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `rashidun.event.${slug}`,
    title, latin, type: "event", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["rashidun.state.rashidun", ...related],
    unlockables: [{ kind: "event", refId: `rashidun.event.${slug}`, label: title }],
    image: { alt: title, glyph: "📜", tone: "from-emerald-800/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "rare",
    bridges: { era: "rashidun" },
  })),

  // ---------- LANDMARKS ----------
  ...LANDMARK_IDS.map(([slug, title, latin, description, startYear, endYear, related]) => E({
    id: `rashidun.landmark.${slug}`,
    title, latin, type: "landmark", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["rashidun.state.rashidun", ...related],
    unlockables: [{ kind: "landmark", refId: `rashidun.landmark.${slug}`, label: title }],
    image: { alt: title, glyph: "🕌", tone: "from-emerald-800/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "epic",
    bridges: { era: "rashidun" },
  })),

  // ---------- ARTIFACTS ----------
  ...ARTIFACT_IDS.map(([slug, title, latin, description, startYear, endYear, glyph, rarity, related]) => E({
    id: `rashidun.artifact.${slug}`,
    title, latin, type: "artifact", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["rashidun.state.rashidun", ...related],
    unlockables: [{ kind: "artifact", refId: `rashidun.artifact.${slug}`, label: title }],
    image: { alt: title, glyph: glyph as string, tone: "from-emerald-800/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: rarity as "common" | "rare" | "epic" | "legendary",
    bridges: { era: "rashidun" },
  })),

  // ---------- ACHIEVEMENTS ----------
  ...ACHIEVEMENT_IDS.map(([slug, title, latin, description, related]) => E({
    id: `rashidun.achievement.${slug}`,
    title, latin, type: "achievement", description,
    period: { label: "٦٣٢ – ٦٦١ م", startYear: 632, endYear: 661 },
    relatedEntities: ["rashidun.state.rashidun", ...related],
    unlockables: [{ kind: "title", refId: `rashidun.achievement.${slug}`, label: title }],
    image: { alt: title, glyph: "🏅", tone: "from-amber-600/40 to-stone-900" },
    timelinePosition: 645,
    rarity: "legendary",
    bridges: { era: "rashidun" },
  })),

  // ---------- FUTURE CAMPAIGN PLACEHOLDERS (locked) ----------
  ...FUTURE_CAMPAIGN_IDS.map(([slug, title, startYear, endYear, description]) => E({
    id: `rashidun.event.${slug}`,
    title, type: "event", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["rashidun.state.rashidun"],
    unlockables: [],
    image: { alt: title, glyph: "🔒", tone: "from-stone-700/40 to-slate-900" },
    timelinePosition: startYear,
    rarity: "legendary",
    meta: { locked: true, kind: "campaign-placeholder" },
    bridges: { era: "rashidun" },
  })),
];

export const RASHIDUN_PACK: ContentPack = {
  id: "pack-007-rashidun",
  order: 0, // earliest era — show first chronologically
  title: "الخلافة الراشدة",
  subtitle: "المجموعة ٧ · خلفاء النبوّة وفاتحو الأمصار",
  summary:
    "حزمة محتوى تاريخية شاملة عن الخلافة الراشدة من بيعة أبي بكر بعد وفاة النبي ﷺ إلى تنازل الحسن بن علي لمعاوية في عام الجماعة، تشمل الفتوح الكبرى للشام والعراق ومصر والقدس وجمع المصحف والفتنة الكبرى.",
  era: "rashidun",
  period: { label: "١١ – ٤١ هـ / ٦٣٢ – ٦٦١ م", startYear: 632, endYear: 661 },
  cover: { alt: "غلاف الخلافة الراشدة", glyph: "🕋", tone: "from-emerald-800/40 to-stone-900" },
  entities,
};