import type { ContentPack, PackEntity } from "./types";

// ============================================================
// Content Pack 008 — الدولة السلجوقية (Seljuk State)
// 1037 – 1194 CE. Capitals: Nishapur → Isfahan.
// Pure data; auto-registers via packs/registry.ts.
// ============================================================

const E = (e: PackEntity): PackEntity => e;

// ---------- FIGURES ----------
const FIGURE_IDS = [
  ["tughril","طغرل بك","Tughril Beg",990,1063,
    "مؤسس الدولة السلجوقية الكبرى، انتصر في دندانقان سنة 431هـ ودخل بغداد سنة 447هـ فأنهى نفوذ البويهيين وأحيا الخلافة العباسية السنية.",
    ["seljuk.battle.dandanaqan","seljuk.event.enter-baghdad","seljuk.event.end-buyids","seljuk.event.rise-seljuk","seljuk.city.nishapur","seljuk.city.baghdad","seljuk.figure.alp-arslan"]],
  ["alp-arslan","ألب أرسلان","Alp Arslan",1029,1072,
    "السلطان الثاني، فاتح الأناضول، حقق نصر ملاذكرد سنة 463هـ على الروم وأسر الإمبراطور رومانوس ديوجانس، ففتح أبواب آسيا الصغرى للإسلام.",
    ["seljuk.battle.manzikert","seljuk.event.anatolia-islamization","seljuk.figure.nizam-al-mulk","seljuk.figure.malik-shah","seljuk.city.isfahan","seljuk.artifact.sword-alp-arslan"]],
  ["malik-shah","ملكشاه","Malik-Shah I",1055,1092,
    "السلطان الثالث وذروة مجد السلاجقة، اتسعت دولته من كاشغر إلى الشام، وفي عهده أُنشئت المدارس النظامية وازدهر العلم والعمارة.",
    ["seljuk.event.malik-shah-era","seljuk.event.scholar-bloom","seljuk.figure.nizam-al-mulk","seljuk.figure.omar-khayyam","seljuk.landmark.malik-shah-palace","seljuk.landmark.isfahan-mosque","seljuk.artifact.malik-shah-seal","seljuk.city.isfahan"]],
  ["sanjar","أحمد سنجر","Ahmad Sanjar",1085,1157,
    "آخر سلاطين السلاجقة العظام، حكم خراسان نحو ستين سنة، هُزم في معركة قطوان أمام القراخطاي سنة 536هـ، فبدأ انحدار الدولة.",
    ["seljuk.battle.qatwan","seljuk.event.weakness","seljuk.event.split-state","seljuk.city.merv","seljuk.city.nishapur"]],
  ["nizam-al-mulk","نظام الملك","Nizam al-Mulk",1018,1092,
    "الوزير الأشهر في تاريخ السلاجقة، صاحب كتاب سياسة نامه ومؤسس المدارس النظامية في بغداد ونيسابور، اغتيل على يد الباطنية سنة 485هـ.",
    ["seljuk.event.nizamiyya-schools","seljuk.event.nizam-death","seljuk.landmark.nizamiyya","seljuk.artifact.nizam-manuscript","seljuk.artifact.siyasatnama","seljuk.figure.malik-shah","seljuk.figure.al-ghazali","seljuk.figure.al-juwayni"]],
  ["tutush","تتش بن ألب أرسلان","Tutush I",1066,1095,
    "أمير السلاجقة في الشام، أسّس فرع سلاجقة الشام في دمشق وحلب، صراعه مع أخيه ملكشاه قسم الدولة شرقًا وغربًا.",
    ["seljuk.city.damascus","seljuk.city.aleppo","seljuk.event.split-state","seljuk.figure.alp-arslan","seljuk.figure.malik-shah"]],
  ["qilij-arslan","قلج أرسلان الأول","Kilij Arslan I",1079,1107,
    "سلطان سلاجقة الروم، واجه الحملة الصليبية الأولى عند نيقية ودوريليوم، عاصمته قونية أصبحت قاعدة المسلمين في الأناضول.",
    ["seljuk.city.konya","seljuk.event.first-crusade","seljuk.event.anatolia-islamization","seljuk.figure.suleiman-ibn-qutalmish"]],
  ["suleiman-ibn-qutalmish","سليمان بن قتلمش","Suleiman ibn Qutalmish",1040,1086,
    "مؤسّس سلطنة سلاجقة الروم في الأناضول بعد ملاذكرد، اتخذ نيقية ثم قونية عاصمة، أبو سلاطين الروم السلاجقة.",
    ["seljuk.city.konya","seljuk.event.anatolia-islamization","seljuk.battle.manzikert","seljuk.figure.alp-arslan","seljuk.figure.qilij-arslan"]],
  ["imad-zengi","عماد الدين زنكي","Imad al-Din Zengi",1085,1146,
    "أتابك الموصل وحلب من أمراء السلاجقة، فاتح الرها سنة 539هـ، مؤسّس الدولة الزنكية وممهّد لجهاد نور الدين وصلاح الدين.",
    ["seljuk.battle.edessa","seljuk.event.zengid-rise","seljuk.city.mosul","seljuk.city.aleppo","seljuk.figure.nur-zengi"]],
  ["nur-zengi","نور الدين زنكي","Nur al-Din Zengi",1118,1174,
    "ابن عماد الدين زنكي، وحّد الشام تحت راية الجهاد ضد الصليبيين، مرسل صلاح الدين إلى مصر، رمز العدل والتقوى في عصره.",
    ["seljuk.city.damascus","seljuk.city.aleppo","seljuk.event.zengid-rise","seljuk.figure.imad-zengi"]],
  ["arslan-khatun","أرسلان خاتون","Arslan Khatun",1030,1090,
    "ابنة جغري بك السلجوقي وزوجة الخليفة العباسي القائم بأمر الله، رمز التحالف بين دار الخلافة وسلاجقة بغداد.",
    ["seljuk.event.enter-baghdad","seljuk.city.baghdad","seljuk.figure.tughril"]],
] as const;

// ---------- SCHOLARS ----------
const SCHOLAR_IDS = [
  ["al-ghazali","أبو حامد الغزالي","Abu Hamid al-Ghazali",1058,1111,
    "حجّة الإسلام، تولّى تدريس النظامية ببغداد ثم اعتزل للتصوف، صاحب إحياء علوم الدين والمنقذ من الضلال، أعظم رموز العلم في العصر السلجوقي.",
    ["seljuk.landmark.nizamiyya","seljuk.artifact.ghazali-manuscript","seljuk.figure.nizam-al-mulk","seljuk.figure.al-juwayni","seljuk.city.baghdad","seljuk.city.nishapur"]],
  ["al-juwayni","إمام الحرمين الجويني","Imam al-Haramayn al-Juwayni",1028,1085,
    "شيخ الشافعية في عصره وأستاذ الغزالي، درّس بالنظامية النيسابورية تحت رعاية نظام الملك، صاحب البرهان والورقات.",
    ["seljuk.landmark.nizamiyya","seljuk.figure.al-ghazali","seljuk.figure.nizam-al-mulk","seljuk.city.nishapur"]],
  ["omar-khayyam","عمر الخيام","Omar Khayyam",1048,1131,
    "العالم والشاعر والفلكي، أصلح التقويم الجلالي بأمر ملكشاه، له الجبر والمقابلة، ومرصده في أصفهان من معالم العصر السلجوقي العلمية.",
    ["seljuk.landmark.khayyam-observatory","seljuk.figure.malik-shah","seljuk.figure.nizam-al-mulk","seljuk.city.isfahan","seljuk.event.scholar-bloom"]],
  ["al-shirazi","أبو إسحاق الشيرازي","Abu Ishaq al-Shirazi",1003,1083,
    "شيخ الشافعية ببغداد وأوّل من تولّى مشيخة المدرسة النظامية فيها، صاحب المهذّب واللمع في أصول الفقه.",
    ["seljuk.landmark.nizamiyya","seljuk.figure.nizam-al-mulk","seljuk.city.baghdad"]],
  ["al-baghawi","الإمام البغوي","Al-Baghawi",1044,1122,
    "محيي السنّة، صاحب شرح السنّة ومعالم التنزيل في التفسير، من علماء خراسان الكبار في عصر السلاجقة.",
    ["seljuk.figure.al-ghazali","seljuk.city.nishapur","seljuk.event.scholar-bloom"]],
  ["al-samani","الإمام السمعاني","Al-Sam'ani",1113,1166,
    "صاحب كتاب الأنساب، الرحّالة المؤرخ السلجوقي، طاف الأمصار يجمع أخبار الرواة والقبائل في خراسان والعراق.",
    ["seljuk.city.merv","seljuk.city.nishapur","seljuk.city.baghdad"]],
] as const;

// ---------- CITIES ----------
const CITY_IDS = [
  ["nishapur","نيسابور","Nishapur",
    "أوّل عواصم السلاجقة بعد دندانقان، حاضرة خراسان العلمية، فيها النظامية النيسابورية ومقابر الغزالي والخيام.",
    1037,1194,["seljuk.battle.dandanaqan","seljuk.event.rise-seljuk","seljuk.figure.tughril","seljuk.figure.al-ghazali","seljuk.landmark.nishapur-walls","seljuk.landmark.nizamiyya"]],
  ["isfahan","أصفهان","Isfahan",
    "عاصمة السلاجقة الكبرى في عهد ملكشاه، حاضرة العلم والعمارة، فيها الجامع الكبير ومرصد الخيام وقصور السلاطين.",
    1051,1194,["seljuk.figure.malik-shah","seljuk.figure.omar-khayyam","seljuk.landmark.isfahan-mosque","seljuk.landmark.khayyam-observatory","seljuk.landmark.malik-shah-palace","seljuk.event.malik-shah-era"]],
  ["rayy","الري","Rayy",
    "حاضرة الجبال شمالي إيران، انتزعها طغرل بك من البويهيين 420هـ، اتخذها قاعدةً قبل الزحف إلى بغداد.",
    1029,1194,["seljuk.figure.tughril","seljuk.landmark.rayy-citadel","seljuk.battle.rayy","seljuk.event.end-buyids"]],
  ["merv","مرو","Merv",
    "حاضرة سنجر وعاصمة سلاجقة خراسان في القرن السادس، من أعظم مدن الإسلام علمًا وعمرانًا قبل الغزو المغولي.",
    1118,1157,["seljuk.figure.sanjar","seljuk.figure.al-samani","seljuk.battle.qatwan"]],
  ["baghdad","بغداد","Baghdad",
    "دار الخلافة العباسية، دخلها طغرل بك سنة 447هـ فأنهى نفوذ البويهيين وأقام الخلافة السنية، فيها النظامية الكبرى.",
    1055,1194,["seljuk.event.enter-baghdad","seljuk.event.end-buyids","seljuk.landmark.nizamiyya","seljuk.landmark.baghdad-libraries","seljuk.figure.tughril","seljuk.figure.arslan-khatun","seljuk.figure.al-ghazali"]],
  ["aleppo","حلب","Aleppo",
    "قاعدة سلاجقة الشام بعد تتش، صارت لاحقًا حاضرة الزنكيين، مركز الجهاد ضد الصليبيين في الشمال الشامي.",
    1086,1194,["seljuk.figure.tutush","seljuk.figure.imad-zengi","seljuk.figure.nur-zengi","seljuk.event.split-state"]],
  ["damascus","دمشق","Damascus",
    "تولّاها تتش بن ألب أرسلان وجعلها عاصمة سلاجقة الشام، آلت لاحقًا إلى البوريين ثم نور الدين زنكي.",
    1078,1154,["seljuk.figure.tutush","seljuk.figure.nur-zengi","seljuk.event.split-state"]],
  ["mosul","الموصل","Mosul",
    "حاضرة الجزيرة الفراتية في العصر السلجوقي، صارت قاعدة عماد الدين زنكي ومنطلق فتح الرها.",
    1127,1194,["seljuk.figure.imad-zengi","seljuk.battle.edessa","seljuk.battle.harran","seljuk.event.zengid-rise"]],
  ["konya","قونية","Konya",
    "عاصمة سلاجقة الروم في الأناضول بعد سليمان بن قتلمش وقلج أرسلان، نواة الحضارة السلجوقية في آسيا الصغرى.",
    1097,1194,["seljuk.figure.suleiman-ibn-qutalmish","seljuk.figure.qilij-arslan","seljuk.event.anatolia-islamization","seljuk.landmark.konya-seljuk"]],
  ["hamadan","همدان","Hamadan",
    "عاصمة سلاجقة العراق والجبل في القرن السادس، فيها قبر طغرل الثاني ومركز سلطنة سلاجقة العجم في آخر عهد الدولة.",
    1118,1194,["seljuk.event.split-state","seljuk.figure.sanjar"]],
] as const;

// ---------- BATTLES ----------
const BATTLE_IDS = [
  ["dandanaqan","معركة دندانقان","Battle of Dandanaqan",1040,1040,
    "المعركة المؤسِّسة للدولة السلجوقية بقيادة طغرل وجغري ضد مسعود الغزنوي قرب مرو، أسقطت الغزنويين من خراسان وفتحت طريق إيران.",
    ["seljuk.figure.tughril","seljuk.event.rise-seljuk","seljuk.city.nishapur","seljuk.city.merv"]],
  ["manzikert","معركة ملاذكرد","Battle of Manzikert",1071,1071,
    "نصر ألب أرسلان الفاصل على الروم بقيادة رومانوس ديوجانس، فتحت أبواب الأناضول للإسلام وكانت من أعظم معارك التاريخ الإسلامي.",
    ["seljuk.figure.alp-arslan","seljuk.event.anatolia-islamization","seljuk.artifact.manzikert-medal","seljuk.artifact.sword-alp-arslan","seljuk.figure.suleiman-ibn-qutalmish"]],
  ["qatwan","معركة قطوان","Battle of Qatwan",1141,1141,
    "هزيمة السلطان سنجر أمام جيش القراخطاي قرب سمرقند، أعظم نكسة عسكرية للسلاجقة في الشرق، أعلنت بداية انحدارهم.",
    ["seljuk.figure.sanjar","seljuk.event.weakness","seljuk.city.merv"]],
  ["jerusalem-seljuk","فتح القدس السلجوقي","Seljuk Capture of Jerusalem",1073,1073,
    "انتزع السلاجقة بقيادة أتسز الخوارزمي القدس من الفاطميين سنة 465هـ، فظلت بأيديهم حتى احتلها الصليبيون سنة 492هـ.",
    ["seljuk.event.first-crusade","seljuk.figure.malik-shah"]],
  ["zallaqa","معركة الزلاقة","Battle of Sagrajas (al-Zallaqa)",1086,1086,
    "نصر المرابطين بقيادة يوسف بن تاشفين في الأندلس على ألفونسو السادس، عاصر عصر ملكشاه السلجوقي وأنقذ الإسلام في الغرب.",
    ["seljuk.figure.malik-shah","seljuk.event.malik-shah-era"]],
  ["harran","معركة حران","Battle of Harran",1104,1104,
    "نصر سلاجقة الموصل وحلب بقيادة جكرمش وسقمان على الصليبيين، أوّل هزيمة كبرى لهم في الجزيرة بعد سقوط الرها بأيديهم.",
    ["seljuk.city.mosul","seljuk.event.first-crusade","seljuk.figure.imad-zengi"]],
  ["edessa","معركة الرها","Capture of Edessa",1144,1144,
    "فتح عماد الدين زنكي الرها وأسقط أوّل إمارة صليبية في الشرق، فأشعل الحملة الصليبية الثانية وممهّدًا لجهاد نور الدين وصلاح الدين.",
    ["seljuk.figure.imad-zengi","seljuk.figure.nur-zengi","seljuk.city.mosul","seljuk.event.zengid-rise"]],
  ["rayy","معركة الري","Battle of Rayy",1029,1029,
    "موقعة طغرل بك أمام البويهيين عند الري قبل دخوله بغداد، مهّدت لتمكين السلاجقة من شمال إيران.",
    ["seljuk.figure.tughril","seljuk.city.rayy","seljuk.event.end-buyids"]],
] as const;

// ---------- EVENTS ----------
const EVENT_IDS = [
  ["rise-seljuk","قيام الدولة السلجوقية","Rise of the Seljuk State",1037,1040,
    "اجتمع الأتراك السلاجقة حول طغرل وجغري في خراسان، انتصروا في دندانقان فقامت الدولة الكبرى على أنقاض الغزنويين.",
    ["seljuk.figure.tughril","seljuk.battle.dandanaqan","seljuk.city.nishapur"]],
  ["enter-baghdad","دخول بغداد","Entry into Baghdad",1055,1055,
    "دخل طغرل بك بغداد سنة 447هـ بدعوة من الخليفة العباسي القائم بأمر الله فأنهى نفوذ البويهيين الشيعة ولُقّب بسلطان المشرق والمغرب.",
    ["seljuk.figure.tughril","seljuk.city.baghdad","seljuk.event.end-buyids","seljuk.figure.arslan-khatun"]],
  ["end-buyids","نهاية الدولة البويهية","End of the Buyids",1055,1055,
    "أسقط دخول طغرل بغداد ما تبقّى من الدولة البويهية الشيعية في العراق وفارس، فعادت السلطة السنية إلى دار الخلافة بعد قرنٍ من النفوذ البويهي.",
    ["seljuk.figure.tughril","seljuk.event.enter-baghdad","seljuk.city.baghdad","seljuk.city.rayy"]],
  ["nizamiyya-schools","إنشاء المدارس النظامية","Founding of the Nizamiyya Schools",1067,1091,
    "أسّس نظام الملك سلسلة من المدارس السنية الكبرى في بغداد ونيسابور والبصرة والموصل وأصفهان، أعظم نظام تعليمي في تاريخ الإسلام الوسيط.",
    ["seljuk.figure.nizam-al-mulk","seljuk.landmark.nizamiyya","seljuk.figure.al-ghazali","seljuk.figure.al-juwayni","seljuk.figure.al-shirazi","seljuk.city.baghdad","seljuk.city.nishapur"]],
  ["manzikert-event","معركة ملاذكرد","Day of Manzikert",1071,1071,
    "النصر الذي فتح الأناضول، حسم ألب أرسلان مصير الروم وأسر إمبراطورهم، وبدأت بعدها هجرة الأتراك الواسعة إلى آسيا الصغرى.",
    ["seljuk.battle.manzikert","seljuk.figure.alp-arslan","seljuk.event.anatolia-islamization"]],
  ["anatolia-islamization","بداية أسلمة الأناضول","Islamization of Anatolia",1071,1194,
    "بعد ملاذكرد توافدت قبائل الأوغوز على آسيا الصغرى وأسّس سليمان بن قتلمش سلطنة سلاجقة الروم، نواة الوجود التركي الإسلامي في الأناضول إلى اليوم.",
    ["seljuk.figure.suleiman-ibn-qutalmish","seljuk.figure.qilij-arslan","seljuk.city.konya","seljuk.battle.manzikert","seljuk.event.first-crusade"]],
  ["malik-shah-era","عصر ملكشاه","The Reign of Malik-Shah",1072,1092,
    "ذروة الدولة السلجوقية: اتساع جغرافي من كاشغر إلى الشام، إصلاح إداري وتقويم جلالي، ازدهار مدارس وعمارة، ووزارة نظام الملك.",
    ["seljuk.figure.malik-shah","seljuk.figure.nizam-al-mulk","seljuk.figure.omar-khayyam","seljuk.landmark.malik-shah-palace","seljuk.landmark.isfahan-mosque","seljuk.event.scholar-bloom"]],
  ["scholar-bloom","ازدهار العلم","Flourishing of the Sciences",1067,1131,
    "في ظل النظاميات والرعاية السلجوقية ازدهرت علوم الكلام والفقه والفلك والرياضيات، رموزها الغزالي والجويني والخيام والشيرازي.",
    ["seljuk.figure.al-ghazali","seljuk.figure.al-juwayni","seljuk.figure.omar-khayyam","seljuk.figure.al-shirazi","seljuk.landmark.nizamiyya","seljuk.landmark.khayyam-observatory"]],
  ["nizam-death","وفاة نظام الملك","Assassination of Nizam al-Mulk",1092,1092,
    "اغتيل نظام الملك على يد فدائي من الباطنية قرب نهاوند، ومات ملكشاه بعده بأشهر فدخلت الدولة في صراع داخلي طويل.",
    ["seljuk.figure.nizam-al-mulk","seljuk.figure.malik-shah","seljuk.event.weakness","seljuk.event.split-state"]],
  ["first-crusade","الحملة الصليبية الأولى","First Crusade",1096,1099,
    "اجتاحت جيوش الفرنجة الأناضول والشام مستغلّة انقسام السلاجقة بعد ملكشاه، احتلت أنطاكية وبيت المقدس وأسّست الإمارات الصليبية.",
    ["seljuk.figure.qilij-arslan","seljuk.event.split-state","seljuk.event.weakness","seljuk.battle.jerusalem-seljuk","seljuk.figure.imad-zengi"]],
  ["weakness","ضعف الدولة السلجوقية","Decline of the Seljuks",1092,1157,
    "بعد ملكشاه ونظام الملك تنازع الأبناء، وضعفت المركزية، وانفصلت الفروع، وانتهت السلطة الفعلية في خراسان بهزيمة قطوان وموت سنجر.",
    ["seljuk.figure.sanjar","seljuk.battle.qatwan","seljuk.event.split-state","seljuk.event.nizam-death"]],
  ["split-state","انقسام الدولة","Fragmentation of the Empire",1092,1194,
    "انقسم البيت السلجوقي إلى فروع: سلاجقة العراق والجبل، سلاجقة كرمان، سلاجقة الشام، سلاجقة الروم، حتى سقطت السلطنة الكبرى نهائيًا 1194م.",
    ["seljuk.figure.tutush","seljuk.figure.sanjar","seljuk.figure.qilij-arslan","seljuk.city.aleppo","seljuk.city.konya","seljuk.city.hamadan"]],
  ["zengid-rise","ظهور الزنكيين","Rise of the Zengids",1127,1174,
    "نهض عماد الدين زنكي من أتابكية الموصل ليؤسس الدولة الزنكية، ثم ابنه نور الدين وحّد الشام في مواجهة الصليبيين تحت راية الجهاد.",
    ["seljuk.figure.imad-zengi","seljuk.figure.nur-zengi","seljuk.battle.edessa","seljuk.city.mosul","seljuk.city.aleppo","seljuk.city.damascus"]],
] as const;

// ---------- LANDMARKS ----------
const LANDMARK_IDS = [
  ["nizamiyya","المدرسة النظامية","Nizamiyya Madrasa",
    "أعظم مدرسة سنية في تاريخ الإسلام الوسيط، أسّسها نظام الملك في بغداد ونيسابور وأصفهان، درّس فيها الغزالي والشيرازي.",
    1067,1194,["seljuk.figure.nizam-al-mulk","seljuk.figure.al-ghazali","seljuk.figure.al-juwayni","seljuk.figure.al-shirazi","seljuk.event.nizamiyya-schools","seljuk.city.baghdad","seljuk.city.nishapur"]],
  ["isfahan-mosque","جامع أصفهان","Friday Mosque of Isfahan",
    "الجامع الكبير في أصفهان، وسّعه السلاجقة في عهد ملكشاه ونظام الملك وأضافوا قبة نظام الملك وقبة تاج الملك، تحفة العمارة السلجوقية.",
    1072,1092,["seljuk.figure.malik-shah","seljuk.figure.nizam-al-mulk","seljuk.city.isfahan","seljuk.event.malik-shah-era"]],
  ["nishapur-walls","أسوار نيسابور","Walls of Nishapur",
    "أسوار العاصمة الأولى للسلاجقة في خراسان، حصون حمت حاضرة العلم حتى دمّرها الغُز ثم المغول لاحقًا.",
    1040,1194,["seljuk.city.nishapur","seljuk.figure.tughril","seljuk.figure.al-ghazali"]],
  ["rayy-citadel","قلعة الري","Citadel of Rayy",
    "حصن الري الذي اتخذه طغرل بك قاعدة قبل دخول بغداد، شاهدٌ على نهاية البويهيين وبداية القوة السلجوقية في الجبال.",
    1029,1194,["seljuk.city.rayy","seljuk.figure.tughril","seljuk.battle.rayy","seljuk.event.end-buyids"]],
  ["konya-seljuk","قونية السلجوقية","Seljuk Konya",
    "قصور ومساجد سلاجقة الروم في قونية، نواة الفن السلجوقي الأناضولي الذي ازدهر لاحقًا في عمارة العثمانيين.",
    1097,1194,["seljuk.figure.qilij-arslan","seljuk.figure.suleiman-ibn-qutalmish","seljuk.city.konya","seljuk.event.anatolia-islamization"]],
  ["khayyam-observatory","مرصد عمر الخيام","Khayyam's Observatory",
    "مرصد أصفهان الذي بُني في عهد ملكشاه ووضع فيه الخيام التقويم الجلالي، من أدقّ تقاويم العالم القديم.",
    1074,1092,["seljuk.figure.omar-khayyam","seljuk.figure.malik-shah","seljuk.city.isfahan","seljuk.event.scholar-bloom"]],
  ["malik-shah-palace","قصور ملكشاه","Palaces of Malik-Shah",
    "قصور السلطنة في أصفهان وبغداد، مركز الحكم والديوان في ذروة الدولة السلجوقية الكبرى.",
    1072,1092,["seljuk.figure.malik-shah","seljuk.figure.nizam-al-mulk","seljuk.city.isfahan","seljuk.event.malik-shah-era"]],
  ["baghdad-libraries","مكتبات بغداد السلجوقية","Seljuk Libraries of Baghdad",
    "خزائن كتب النظامية ودار الخلافة في بغداد، حافظت على تراث الإسلام في الفقه والكلام والعلوم تحت الرعاية السلجوقية.",
    1067,1194,["seljuk.landmark.nizamiyya","seljuk.city.baghdad","seljuk.event.scholar-bloom","seljuk.figure.al-ghazali"]],
] as const;

// ---------- ARTIFACTS ----------
const ARTIFACT_IDS = [
  ["seljuk-banner","راية السلاجقة","Banner of the Seljuks",
    "الراية التي رُفعت من دندانقان إلى ملاذكرد إلى الرها، رمز قوة السنة الكبرى في القرنين الخامس والسادس الهجريين.",
    1040,1194,"🏴","epic",["seljuk.battle.dandanaqan","seljuk.battle.manzikert","seljuk.event.rise-seljuk"]],
  ["sword-alp-arslan","سيف ألب أرسلان","Sword of Alp Arslan",
    "سيف السلطان فاتح الأناضول، حمله يوم ملاذكرد وأسر به إمبراطور الروم، أيقونة الجهاد السلجوقي.",
    1063,1072,"🗡️","legendary",["seljuk.figure.alp-arslan","seljuk.battle.manzikert","seljuk.event.anatolia-islamization"]],
  ["nizam-manuscript","مخطوطة نظام الملك","Manuscript of Nizam al-Mulk",
    "مخطوطة بخط الوزير في الإدارة والوصايا، شاهد على عقل أعظم وزراء الإسلام.",
    1067,1092,"📜","epic",["seljuk.figure.nizam-al-mulk","seljuk.event.nizamiyya-schools","seljuk.artifact.siyasatnama"]],
  ["siyasatnama","كتاب سياسة نامه","Siyasatnama (Book of Government)",
    "كتاب نظام الملك في فقه الحكم والإدارة، أعظم نص سياسي إسلامي في العصر الوسيط ومرجع الوزراء والسلاطين.",
    1086,1091,"📚","legendary",["seljuk.figure.nizam-al-mulk","seljuk.figure.malik-shah","seljuk.event.nizamiyya-schools"]],
  ["ghazali-manuscript","مخطوطة الغزالي","Manuscript of al-Ghazali",
    "نسخة من إحياء علوم الدين بخط قريب من زمن المؤلف، شاهدة على ذروة فكر العصر السلجوقي.",
    1095,1111,"📖","legendary",["seljuk.figure.al-ghazali","seljuk.landmark.nizamiyya","seljuk.event.scholar-bloom"]],
  ["seljuk-map","خريطة الدولة السلجوقية","Map of the Seljuk Empire",
    "خريطة تبيّن امتداد السلطنة الكبرى من كاشغر إلى الشام في عهد ملكشاه، أوسع امتدادٍ للسلاجقة على الإطلاق.",
    1080,1092,"🗺️","epic",["seljuk.figure.malik-shah","seljuk.event.malik-shah-era","seljuk.event.split-state"]],
  ["malik-shah-seal","ختم ملكشاه","Seal of Malik-Shah",
    "ختم السلطان على مراسيمه وأوامره إلى ولاة الأمصار، رمز السلطة العليا في ذروة الدولة.",
    1072,1092,"🪧","epic",["seljuk.figure.malik-shah","seljuk.figure.nizam-al-mulk","seljuk.event.malik-shah-era"]],
  ["seljuk-dinar","دينار سلجوقي","Seljuk Dinar",
    "عملة ذهبية ضُربت في عهد ملكشاه وسنجر تحمل اسم السلطان والخليفة العباسي، شاهدة على شراكة السلطنة والخلافة.",
    1063,1157,"🪙","rare",["seljuk.figure.malik-shah","seljuk.figure.sanjar","seljuk.city.baghdad","seljuk.city.isfahan"]],
  ["manzikert-medal","وسام ملاذكرد","Medal of Manzikert",
    "وسامٌ شرفي يُمنح لمن أتمّ مسار ألب أرسلان وملاذكرد وفتح الأناضول.",
    1071,1194,"🏵️","legendary",["seljuk.battle.manzikert","seljuk.figure.alp-arslan","seljuk.event.anatolia-islamization"]],
  ["sultani-decree","مرسوم سلطاني","Sultanic Decree",
    "مرسوم بخط ديوان السلاجقة في تعيين الولاة والقضاة، وثيقة من وثائق الإدارة السلجوقية النموذجية.",
    1063,1157,"📜","rare",["seljuk.figure.malik-shah","seljuk.figure.nizam-al-mulk","seljuk.figure.sanjar","seljuk.artifact.siyasatnama"]],
] as const;

// ---------- ACHIEVEMENTS ----------
const ACHIEVEMENT_IDS = [
  ["anatolia-conqueror","فاتح الأناضول","Conqueror of Anatolia",
    "يُمنح لمن أكمل قصص ألب أرسلان وملاذكرد وسلاجقة الروم.",
    ["seljuk.figure.alp-arslan","seljuk.battle.manzikert","seljuk.event.anatolia-islamization","seljuk.figure.suleiman-ibn-qutalmish","seljuk.figure.qilij-arslan","seljuk.city.konya"]],
  ["seljuk-historian","مؤرّخ السلاجقة","Historian of the Seljuks",
    "يُمنح لمن قرأ جميع شخصيات وأحداث الدولة السلجوقية في الموسوعة.",
    ["seljuk.state.seljuk","seljuk.figure.tughril","seljuk.figure.alp-arslan","seljuk.figure.malik-shah","seljuk.figure.sanjar","seljuk.event.rise-seljuk","seljuk.event.split-state"]],
  ["seljuk-collector","جامع التراث السلجوقي","Collector of Seljuk Heritage",
    "يُمنح لمن جمع كلّ آثار ومخطوطات السلاجقة في مجموعته.",
    ["seljuk.artifact.seljuk-banner","seljuk.artifact.sword-alp-arslan","seljuk.artifact.siyasatnama","seljuk.artifact.ghazali-manuscript","seljuk.artifact.malik-shah-seal","seljuk.artifact.manzikert-medal"]],
  ["lord-isfahan","سيد أصفهان","Lord of Isfahan",
    "يُمنح لمن أتمّ مسار ملكشاه ونظام الملك والخيام وعمارة العاصمة.",
    ["seljuk.figure.malik-shah","seljuk.figure.nizam-al-mulk","seljuk.figure.omar-khayyam","seljuk.city.isfahan","seljuk.landmark.isfahan-mosque","seljuk.landmark.malik-shah-palace","seljuk.landmark.khayyam-observatory"]],
  ["caliphate-protector","حامي الخلافة","Protector of the Caliphate",
    "يُمنح لمن أكمل قصة دخول طغرل بغداد ونهاية البويهيين وإحياء سلطة الخلافة السنية.",
    ["seljuk.figure.tughril","seljuk.event.enter-baghdad","seljuk.event.end-buyids","seljuk.city.baghdad","seljuk.figure.arslan-khatun"]],
] as const;

// ---------- FUTURE CAMPAIGN PLACEHOLDERS (locked) ----------
const FUTURE_CAMPAIGN_IDS = [
  ["future-tughril",     "حملة طغرل بك",       1037,1063,"حملةٌ قادمة عن مؤسس الدولة من دندانقان إلى بغداد. (قريبًا)"],
  ["future-alp-arslan",  "حملة ألب أرسلان",    1063,1072,"حملةٌ قادمة عن فاتح الأناضول وبطل ملاذكرد. (قريبًا)"],
  ["future-manzikert",   "معركة ملاذكرد",      1071,1071,"حملةٌ قادمة عن اليوم الذي فتح آسيا الصغرى. (قريبًا)"],
  ["future-malik-shah",  "عصر ملكشاه",         1072,1092,"حملةٌ قادمة عن ذروة السلطنة الكبرى. (قريبًا)"],
  ["future-nizam",       "نظام الملك",         1067,1092,"حملةٌ قادمة عن أعظم وزير في تاريخ الإسلام الوسيط. (قريبًا)"],
  ["future-zengids",     "ظهور الزنكيين",      1127,1174,"حملةٌ قادمة عن جهاد عماد الدين ونور الدين زنكي. (قريبًا)"],
] as const;

const entities: PackEntity[] = [
  // ---------- STATE ----------
  E({
    id: "seljuk.state.seljuk",
    title: "الدولة السلجوقية",
    latin: "Seljuk Empire",
    type: "state",
    description:
      "الدولة السلجوقية الكبرى، قامت سنة 429هـ/1037م بعد انتصار طغرل بك على الغزنويين، اتخذت نيسابور ثم أصفهان عاصمة، أحيت الخلافة العباسية السنية وفتحت الأناضول في ملاذكرد، وفي عهدها ازدهرت المدارس النظامية والعلم، وانتهت سنة 590هـ/1194م بسقوط آخر سلاطينها على يد الخوارزميين.",
    period: { label: "429 – 590 هـ / 1037 – 1194 م", startYear: 1037, endYear: 1194 },
    relatedEntities: [
      "seljuk.figure.tughril","seljuk.figure.alp-arslan","seljuk.figure.malik-shah","seljuk.figure.sanjar",
      "seljuk.figure.nizam-al-mulk","seljuk.figure.tutush","seljuk.figure.qilij-arslan","seljuk.figure.suleiman-ibn-qutalmish",
      "seljuk.figure.imad-zengi","seljuk.figure.nur-zengi","seljuk.figure.arslan-khatun",
      "seljuk.figure.al-ghazali","seljuk.figure.al-juwayni","seljuk.figure.omar-khayyam",
      "seljuk.city.nishapur","seljuk.city.isfahan","seljuk.city.rayy","seljuk.city.merv",
      "seljuk.city.baghdad","seljuk.city.aleppo","seljuk.city.damascus","seljuk.city.mosul",
      "seljuk.city.konya","seljuk.city.hamadan",
      "seljuk.battle.dandanaqan","seljuk.battle.manzikert","seljuk.battle.qatwan",
      "seljuk.battle.jerusalem-seljuk","seljuk.battle.edessa","seljuk.battle.harran","seljuk.battle.rayy",
      "seljuk.event.rise-seljuk","seljuk.event.enter-baghdad","seljuk.event.end-buyids",
      "seljuk.event.nizamiyya-schools","seljuk.event.malik-shah-era","seljuk.event.scholar-bloom",
      "seljuk.event.nizam-death","seljuk.event.first-crusade","seljuk.event.weakness",
      "seljuk.event.split-state","seljuk.event.zengid-rise","seljuk.event.anatolia-islamization",
    ],
    unlockables: [
      { kind: "campaign", refId: "seljuk", label: "حملات الدولة السلجوقية" },
    ],
    image: { alt: "راية الدولة السلجوقية", glyph: "🏹", tone: "from-indigo-800/40 to-stone-900" },
    timelinePosition: 1037,
    rarity: "legendary",
    meta: {
      founder: "طغرل بك السلجوقي",
      capital: "نيسابور (ثم أصفهان)",
      majorCities: ["نيسابور","أصفهان","الري","مرو","بغداد","حلب","دمشق","الموصل","قونية","همدان"],
      majorFigures: ["طغرل","ألب أرسلان","ملكشاه","سنجر","نظام الملك","تتش","قلج أرسلان","عماد الدين زنكي"],
      majorBattles: ["دندانقان","ملاذكرد","قطوان","الرها","حران","الري","فتح القدس"],
      majorEvents: ["قيام الدولة","دخول بغداد","نهاية البويهيين","المدارس النظامية","عصر ملكشاه","ازدهار العلم","الحملة الصليبية الأولى","انقسام الدولة","ظهور الزنكيين"],
    },
    bridges: { era: "seljuk" },
  }),

  // ---------- FIGURES ----------
  ...FIGURE_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `seljuk.figure.${slug}`,
    title, latin, type: "figure", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["seljuk.state.seljuk", ...related],
    unlockables: [{ kind: "figure", refId: `seljuk.figure.${slug}`, label: title }],
    image: { alt: title, glyph: "🏹", tone: "from-indigo-800/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "epic",
    meta: { titles: [title] },
    bridges: { era: "seljuk" },
  })),

  // ---------- SCHOLARS ----------
  ...SCHOLAR_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `seljuk.figure.${slug}`,
    title, latin, type: "figure", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["seljuk.state.seljuk", ...related],
    unlockables: [{ kind: "figure", refId: `seljuk.figure.${slug}`, label: title }],
    image: { alt: title, glyph: "📚", tone: "from-indigo-800/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "epic",
    meta: { kind: "scholar", titles: [title] },
    bridges: { era: "seljuk" },
  })),

  // ---------- CITIES ----------
  ...CITY_IDS.map(([slug, title, latin, description, startYear, endYear, related]) => E({
    id: `seljuk.city.${slug}`,
    title, latin, type: "city", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["seljuk.state.seljuk", ...related],
    unlockables: [{ kind: "city", refId: `seljuk.city.${slug}`, label: title }],
    image: { alt: title, glyph: "🏙️", tone: "from-indigo-800/30 to-stone-900" },
    timelinePosition: startYear,
    rarity: "rare",
    bridges: { cityId: slug, era: "seljuk" },
  })),

  // ---------- BATTLES ----------
  ...BATTLE_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `seljuk.battle.${slug}`,
    title, latin, type: "battle", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["seljuk.state.seljuk", ...related],
    unlockables: [{ kind: "battle", refId: `seljuk.battle.${slug}`, label: title }],
    image: { alt: title, glyph: "⚔️", tone: "from-red-800/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "epic",
    bridges: { era: "seljuk" },
  })),

  // ---------- EVENTS ----------
  ...EVENT_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `seljuk.event.${slug}`,
    title, latin, type: "event", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["seljuk.state.seljuk", ...related],
    unlockables: [{ kind: "event", refId: `seljuk.event.${slug}`, label: title }],
    image: { alt: title, glyph: "📜", tone: "from-indigo-800/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "rare",
    bridges: { era: "seljuk" },
  })),

  // ---------- LANDMARKS ----------
  ...LANDMARK_IDS.map(([slug, title, latin, description, startYear, endYear, related]) => E({
    id: `seljuk.landmark.${slug}`,
    title, latin, type: "landmark", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["seljuk.state.seljuk", ...related],
    unlockables: [{ kind: "landmark", refId: `seljuk.landmark.${slug}`, label: title }],
    image: { alt: title, glyph: "🕌", tone: "from-indigo-800/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "epic",
    bridges: { era: "seljuk" },
  })),

  // ---------- ARTIFACTS ----------
  ...ARTIFACT_IDS.map(([slug, title, latin, description, startYear, endYear, glyph, rarity, related]) => E({
    id: `seljuk.artifact.${slug}`,
    title, latin, type: "artifact", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["seljuk.state.seljuk", ...related],
    unlockables: [{ kind: "artifact", refId: `seljuk.artifact.${slug}`, label: title }],
    image: { alt: title, glyph: glyph as string, tone: "from-indigo-800/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: rarity as "common" | "rare" | "epic" | "legendary",
    bridges: { era: "seljuk" },
  })),

  // ---------- ACHIEVEMENTS ----------
  ...ACHIEVEMENT_IDS.map(([slug, title, latin, description, related]) => E({
    id: `seljuk.achievement.${slug}`,
    title, latin, type: "achievement", description,
    period: { label: "1037 – 1194 م", startYear: 1037, endYear: 1194 },
    relatedEntities: ["seljuk.state.seljuk", ...related],
    unlockables: [{ kind: "title", refId: `seljuk.achievement.${slug}`, label: title }],
    image: { alt: title, glyph: "🏅", tone: "from-amber-600/40 to-stone-900" },
    timelinePosition: 1100,
    rarity: "legendary",
    bridges: { era: "seljuk" },
  })),

  // ---------- FUTURE CAMPAIGN PLACEHOLDERS (locked) ----------
  ...FUTURE_CAMPAIGN_IDS.map(([slug, title, startYear, endYear, description]) => E({
    id: `seljuk.event.${slug}`,
    title, type: "event", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["seljuk.state.seljuk"],
    unlockables: [],
    image: { alt: title, glyph: "🔒", tone: "from-stone-700/40 to-slate-900" },
    timelinePosition: startYear,
    rarity: "legendary",
    meta: { locked: true, kind: "campaign-placeholder" },
    bridges: { era: "seljuk" },
  })),
];

export const SELJUK_PACK: ContentPack = {
  id: "pack-008-seljuk",
  order: 25, // between Abbasid (early) and Ayyubid (late 12th c.)
  title: "الدولة السلجوقية",
  subtitle: "المجموعة 8 · سلاطين الترك وحماة الخلافة السنية",
  summary:
    "حزمة محتوى تاريخية شاملة عن الدولة السلجوقية الكبرى من دندانقان إلى ملاذكرد إلى عصر ملكشاه ونظام الملك، تشمل دخول طغرل بغداد ونهاية البويهيين، والمدارس النظامية، والحملة الصليبية الأولى، وانقسام الدولة وظهور الزنكيين.",
  era: "seljuk",
  period: { label: "429 – 590 هـ / 1037 – 1194 م", startYear: 1037, endYear: 1194 },
  cover: { alt: "غلاف الدولة السلجوقية", glyph: "🏹", tone: "from-indigo-800/40 to-stone-900" },
  entities,
};