import type { ContentPack, PackEntity } from "./types";

// ============================================================
// Content Pack 002 — الدولة الأموية (The Umayyad State)
// ------------------------------------------------------------
// Same architecture as Pack 001 (Ayyubid). Adds figures, cities,
// battles, events, landmarks, artifacts, achievements, and locked
// campaign placeholders. `bridges` connect entities back to the
// legacy data in src/lib/data.ts / src/lib/cities.ts so the
// existing routes, knowledge graph, timeline, museum and world
// map pick them up automatically.
// ============================================================

const E = (e: PackEntity): PackEntity => e;

const FIGURE_IDS = [
  ["muawiya",       "معاوية بن أبي سفيان", "Muawiya I",          661, 680,
    "مؤسّس الدولة الأموية أوّل خلفائها، نقل العاصمة إلى دمشق وأسّس نظامًا إداريًّا وعسكريًّا بحريًّا متينًا.",
    ["umayyad.city.damascus","umayyad.event.found-umayyad","umayyad.event.move-capital-damascus","umayyad.battle.constantinople-1"]],
  ["yazid-i",       "يزيد بن معاوية",     "Yazid I",            680, 683,
    "ثاني خلفاء بني أمية، شهد عهده أحداثًا مفصليّة في تاريخ الأمة.",
    ["umayyad.figure.muawiya","umayyad.city.damascus"]],
  ["abd-al-malik",  "عبد الملك بن مروان", "Abd al-Malik",       685, 705,
    "مُجدّد الدولة الأموية، عرّب الدواوين وسكّ العملة الإسلامية وبنى قبة الصخرة في القدس.",
    ["umayyad.event.arabize-divans","umayyad.event.islamic-coinage","umayyad.landmark.dome-of-rock","umayyad.artifact.seal-abd-al-malik"]],
  ["al-walid-i",    "الوليد بن عبد الملك","Al-Walid I",         705, 715,
    "بلغت الدولة في عهده أوج اتّساعها: فُتحت الأندلس والسند وما وراء النهر، وبُني المسجد الأموي بدمشق.",
    ["umayyad.event.conquer-andalus","umayyad.event.conquer-sind","umayyad.landmark.umayyad-mosque","umayyad.figure.tariq","umayyad.figure.musa-bin-nusayr","umayyad.figure.muhammad-bin-qasim"]],
  ["sulayman",      "سليمان بن عبد الملك","Sulayman ibn Abd al-Malik", 715, 717,
    "خليفةٌ أمويّ قاد محاولة فتح القسطنطينية الكبرى بقيادة أخيه مَسْلَمة.",
    ["umayyad.battle.constantinople-2","umayyad.city.damascus"]],
  ["umar-bin-abd-al-aziz","عمر بن عبد العزيز","Umar II",        717, 720,
    "الخليفة العادل الذي أعاد سيرة العدل الراشدي إلى الدولة الأموية، وأصلح الإدارة وردّ المظالم.",
    ["umayyad.event.umar-caliphate","umayyad.achievement.master-of-damascus"]],
  ["hisham",        "هشام بن عبد الملك",  "Hisham ibn Abd al-Malik", 724, 743,
    "آخر الخلفاء الكبار من بني أمية، نظّم الإدارة وحفظ الحدود رغم بوادر الضعف.",
    ["umayyad.city.damascus","umayyad.event.weakening"]],
  ["marwan-ii",     "مروان بن محمد",      "Marwan II",          744, 750,
    "آخر خلفاء بني أمية في المشرق، انتهت في عهده الدولة بثورة العباسيين.",
    ["umayyad.event.abbasid-revolution","umayyad.event.fall-umayyad"]],
  ["al-hajjaj",     "الحجاج بن يوسف",     "Al-Hajjaj ibn Yusuf",694, 714,
    "والي العراق القويّ في زمن عبد الملك والوليد، أسّس مدينة واسط وأخمد الفتن وأطلق الفتوحات شرقًا.",
    ["umayyad.city.wasit","umayyad.city.kufa","umayyad.city.basra","umayyad.figure.muhammad-bin-qasim"]],
  ["musa-bin-nusayr","موسى بن نصير",      "Musa ibn Nusayr",    705, 716,
    "والي إفريقية وقائد فتح الأندلس مع طارق بن زياد، أحد أعمدة التوسع الأموي في المغرب.",
    ["umayyad.event.conquer-andalus","umayyad.city.qairawan","umayyad.figure.tariq"]],
  ["tariq",         "طارق بن زياد",       "Tariq ibn Ziyad",    711, 720,
    "القائد البربري المسلم، عبر المضيق الذي حمل اسمه وحقّق نصر وادي لكّة سنة 711م، فاتحًا أبواب الأندلس.",
    ["umayyad.battle.guadalete","umayyad.event.conquer-andalus","umayyad.city.cordoba","umayyad.artifact.tariq-sword"]],
  ["muhammad-bin-qasim","محمد بن القاسم الثقفي","Muhammad ibn al-Qasim", 711, 715,
    "الفاتح الشاب لبلاد السند في عهد الوليد، فتح المُلتان والديبل وأرسى الإسلام في وادي السند.",
    ["umayyad.event.conquer-sind","umayyad.battle.sind"]],
  ["uqba",          "عقبة بن نافع",       "Uqba ibn Nafi",      666, 683,
    "فاتح إفريقية، باني مدينة القيروان قاعدةً للفتح في الغرب الإسلامي.",
    ["umayyad.city.qairawan","umayyad.event.conquer-ifriqiya","umayyad.event.conquer-maghrib"]],
  ["yusuf-fihri",   "يوسف بن عبد الرحمن الفهري","Yusuf al-Fihri", 747, 756,
    "آخر ولاة الأندلس قبل قيام إمارة بني أمية الأندلسية على يد عبد الرحمن الداخل.",
    ["umayyad.city.cordoba","umayyad.event.fall-umayyad"]],
] as const;

const CITY_IDS = [
  ["damascus","دمشق","Damascus","عاصمة الدولة الأموية ومركز الخلافة الإسلامية في المشرق، احتضنت المسجد الأموي ودواوين الدولة.",661,750,
    ["umayyad.figure.muawiya","umayyad.figure.abd-al-malik","umayyad.landmark.umayyad-mosque","umayyad.landmark.damascus-walls"]],
  ["qairawan","القيروان","Qairawan","المدينة التي أسّسها عقبة بن نافع سنة 670م لتكون قاعدة الفتح في المغرب، وقلب علوم المالكية لاحقًا.",670,750,
    ["umayyad.figure.uqba","umayyad.event.conquer-ifriqiya","umayyad.landmark.qairawan-city"]],
  ["cordoba","قرطبة","Cordoba","عاصمة الأندلس الإسلامية في عهد الولاة الأمويين، وعاصمة الدولة الأموية الأندلسية لاحقًا.",711,750,
    ["umayyad.figure.tariq","umayyad.event.conquer-andalus","umayyad.landmark.cordoba-mosque"]],
  ["wasit","واسط","Wasit","مدينةٌ أسّسها الحجاج بن يوسف بين الكوفة والبصرة لتكون مركزًا إداريًّا وعسكريًّا في العراق.",702,750,
    ["umayyad.figure.al-hajjaj","umayyad.landmark.wasit-citadel"]],
  ["kufa","الكوفة","Kufa","مصرٌ عراقيّ كبير، شهد أحداثًا سياسيّة مفصليّة طوال العصر الأموي.",661,750,
    ["umayyad.figure.al-hajjaj"]],
  ["basra","البصرة","Basra","ميناء العراق على الخليج، منطلق فتوحات المشرق والهند في العصر الأموي.",661,750,
    ["umayyad.figure.al-hajjaj","umayyad.event.conquer-sind"]],
  ["makkah","مكة","Mecca","الحرم المكي، قبلة المسلمين وموسم الحج، احتضنت الأحداث الكبرى بين الأمويين وخصومهم السياسيين.",661,750,
    ["umayyad.figure.muawiya"]],
  ["madina","المدينة","Medina","مدينة النبي ﷺ، مركز الفقه والحديث في العصر الأموي.",661,750,
    []],
  ["samarqand","سمرقند","Samarkand","لؤلؤة ما وراء النهر، فتحت في عهد الوليد، وأصبحت قاعدةً للإسلام في آسيا الوسطى.",712,750,
    ["umayyad.event.conquer-samarqand","umayyad.event.expand-central-asia"]],
  ["malatya","ملطية","Malatya","ثغر الأناضول الأموي، منطلق الغزوات الصيفية ضد البيزنطيين.",661,750,
    ["umayyad.battle.constantinople-1","umayyad.battle.constantinople-2"]],
] as const;

const BATTLE_IDS = [
  ["conquest-andalus","فتح الأندلس","Conquest of Hispania",711,718,
    "حملة طارق بن زياد وموسى بن نصير التي أسقطت مملكة القوط الغربيين في إيبيريا.",
    ["umayyad.figure.tariq","umayyad.figure.musa-bin-nusayr","umayyad.battle.guadalete","umayyad.city.cordoba"]],
  ["guadalete","معركة وادي لكة","Battle of Guadalete",711,711,
    "المعركة الفاصلة سنة 711م التي سحق فيها طارق بن زياد جيش لذريق ملك القوط، فانهارت دولة القوط في أيام.",
    ["umayyad.figure.tariq","umayyad.event.conquer-andalus"]],
  ["tours","معركة بلاط الشهداء","Battle of Tours",732,732,
    "معركة بين والي الأندلس عبد الرحمن الغافقي وفرنجة شارل مارتل في فرنسا، أوقفت توسّع المسلمين شمالًا.",
    ["umayyad.event.conquer-andalus"]],
  ["sind","فتح السند","Conquest of Sindh",711,713,
    "حملة محمد بن القاسم الثقفي التي فتحت بلاد السند ووصلت إلى الملتان.",
    ["umayyad.figure.muhammad-bin-qasim","umayyad.event.conquer-sind"]],
  ["samarqand-battle","فتح سمرقند","Conquest of Samarkand",712,712,
    "حملة قتيبة بن مسلم الباهلي التي ضمّت سمرقند وبخارى إلى الدولة الأموية.",
    ["umayyad.city.samarqand","umayyad.event.expand-central-asia"]],
  ["constantinople-1","حصار القسطنطينية الأول","First Siege of Constantinople",674,678,
    "حصار بحري وبري في عهد معاوية بن أبي سفيان، أوّل اختبار لقدرة المسلمين على ضرب عاصمة الروم.",
    ["umayyad.figure.muawiya","umayyad.city.malatya"]],
  ["constantinople-2","حصار القسطنطينية الثاني","Second Siege of Constantinople",717,718,
    "حصارٌ كبير بقيادة مَسْلَمة بن عبد الملك في عهد سليمان وعمر بن عبد العزيز، انتهى دون فتح المدينة.",
    ["umayyad.figure.sulayman","umayyad.figure.umar-bin-abd-al-aziz"]],
  ["ifriqiya","فتح إفريقية","Conquest of Ifriqiya",647,705,
    "سلسلة حملات بدأها عقبة بن نافع وأكملها حسان بن النعمان وموسى بن نصير حتى ضمّ شمال إفريقيا.",
    ["umayyad.figure.uqba","umayyad.city.qairawan","umayyad.event.conquer-ifriqiya"]],
  ["maghrib","فتح المغرب","Conquest of the Maghreb",681,710,
    "حملات المسلمين التي وصلت إلى المحيط الأطلسي وأسلمت قبائل البربر.",
    ["umayyad.figure.uqba","umayyad.figure.musa-bin-nusayr","umayyad.event.conquer-maghrib"]],
  ["bukhara","فتح بخارى","Conquest of Bukhara",709,709,
    "فتح قتيبة بن مسلم لبخارى، فتح الباب لتوسّع الإسلام في خراسان وما وراء النهر.",
    ["umayyad.city.samarqand","umayyad.event.expand-central-asia"]],
] as const;

const EVENT_IDS = [
  ["found-umayyad","تأسيس الدولة الأموية","Founding of the Umayyad State",661,661,
    "إعلان معاوية بن أبي سفيان قيام الخلافة الأموية بعد عام الجماعة.",
    ["umayyad.figure.muawiya","umayyad.state.umayyad"]],
  ["move-capital-damascus","نقل العاصمة إلى دمشق","Move of Capital to Damascus",661,661,
    "اختيار معاوية لدمشق عاصمةً للدولة، فبدأت مرحلة جديدة من الإدارة المركزية.",
    ["umayyad.city.damascus","umayyad.figure.muawiya"]],
  ["arabize-divans","تعريب الدواوين","Arabization of the Divans",696,700,
    "قرار عبد الملك بن مروان بتعريب دواوين الدولة، وكان لها أثرٌ حضاري بعيد المدى.",
    ["umayyad.figure.abd-al-malik","umayyad.event.islamic-coinage"]],
  ["islamic-coinage","سك العملة الإسلامية","Islamic Coinage Reform",696,696,
    "إصلاح عبد الملك للنقد بسكّ دينار ودرهم إسلاميَّيْن خاليَيْن من الصور.",
    ["umayyad.figure.abd-al-malik","umayyad.artifact.dinar-umayyad","umayyad.artifact.dirham-umayyad"]],
  ["build-dome-of-rock","بناء قبة الصخرة","Construction of the Dome of the Rock",688,692,
    "بناء قبة الصخرة في القدس بأمر عبد الملك بن مروان، أوّل أيقونة معمارية للإسلام.",
    ["umayyad.figure.abd-al-malik","umayyad.landmark.dome-of-rock"]],
  ["build-umayyad-mosque","بناء المسجد الأموي","Construction of the Umayyad Mosque",706,715,
    "تشييد الوليد بن عبد الملك للجامع الأموي في دمشق، تحفةٌ معمارية باقية إلى اليوم.",
    ["umayyad.figure.al-walid-i","umayyad.landmark.umayyad-mosque"]],
  ["conquer-andalus","فتح الأندلس","Conquest of al-Andalus",711,718,
    "حملة طارق وموسى التي أسقطت مملكة القوط وأدخلت إيبيريا في دار الإسلام.",
    ["umayyad.figure.tariq","umayyad.figure.musa-bin-nusayr","umayyad.battle.guadalete","umayyad.city.cordoba","umayyad.artifact.andalus-manuscript"]],
  ["conquer-sind","فتح السند","Conquest of Sindh",711,713,
    "حملة محمد بن القاسم في وادي السند، فتحت آفاق الإسلام في شبه القارة.",
    ["umayyad.figure.muhammad-bin-qasim","umayyad.battle.sind","umayyad.artifact.sind-manuscript"]],
  ["expand-central-asia","التوسع في آسيا الوسطى","Expansion in Central Asia",705,715,
    "حملات قتيبة بن مسلم في خراسان وما وراء النهر التي أوصلت الإسلام إلى الصين.",
    ["umayyad.city.samarqand","umayyad.battle.samarqand-battle","umayyad.battle.bukhara"]],
  ["siege-constantinople","حصار القسطنطينية","Sieges of Constantinople",674,718,
    "محاولتان كبيرتان لفتح عاصمة الروم في عهدي معاوية وسليمان.",
    ["umayyad.battle.constantinople-1","umayyad.battle.constantinople-2"]],
  ["umar-caliphate","خلافة عمر بن عبد العزيز","Caliphate of Umar ibn Abd al-Aziz",717,720,
    "سنواتٌ معدودة أعاد فيها عمر سيرة العدل الراشدي إلى الدولة، فاعتُبر خامس الخلفاء الراشدين.",
    ["umayyad.figure.umar-bin-abd-al-aziz","umayyad.achievement.master-of-damascus"]],
  ["weakening","بداية الضعف الأموي","Beginnings of Umayyad Decline",743,747,
    "اضطرابات داخلية وثورات هاشمية وزنجية وخارجية بدأت تنخر في كيان الدولة.",
    ["umayyad.figure.hisham","umayyad.figure.marwan-ii"]],
  ["abbasid-revolution","الثورة العباسية","Abbasid Revolution",747,750,
    "ثورة بني العباس في خراسان بقيادة أبي مسلم الخراساني التي قلبت موازين الخلافة.",
    ["umayyad.figure.marwan-ii","umayyad.event.fall-umayyad"]],
  ["fall-umayyad","سقوط الدولة الأموية","Fall of the Umayyad State",750,750,
    "هزيمة مروان بن محمد في معركة الزاب وقيام الدولة العباسية في المشرق.",
    ["umayyad.figure.marwan-ii","umayyad.event.abbasid-revolution","umayyad.figure.yusuf-fihri"]],
  ["conquer-ifriqiya","فتح إفريقية","Conquest of Ifriqiya",647,705,
    "السلسلة الطويلة من الحملات التي ضمّت شمال إفريقيا إلى الدولة.",
    ["umayyad.figure.uqba","umayyad.city.qairawan"]],
  ["conquer-maghrib","فتح المغرب","Conquest of the Maghreb",681,710,
    "وصول جيوش الإسلام إلى المحيط الأطلسي وإسلام قبائل البربر.",
    ["umayyad.figure.uqba","umayyad.figure.musa-bin-nusayr"]],
] as const;

const LANDMARK_IDS = [
  ["umayyad-mosque","المسجد الأموي","Umayyad Mosque","تحفةٌ معمارية بدمشق بناها الوليد بن عبد الملك سنة 706م، أحد أبرز معالم الحضارة الإسلامية.",
    706,715,["umayyad.figure.al-walid-i","umayyad.city.damascus","umayyad.event.build-umayyad-mosque"]],
  ["dome-of-rock","قبة الصخرة","Dome of the Rock","أوّل تحفة معمارية إسلامية، شيّدها عبد الملك بن مروان فوق الصخرة المشرّفة في القدس.",
    688,692,["umayyad.figure.abd-al-malik","umayyad.event.build-dome-of-rock"]],
  ["qairawan-city","مدينة القيروان","City of Qairawan","المدينة التي أنشأها عقبة بن نافع لتكون قاعدة الفتح في إفريقية، وحاضنة جامع عقبة.",
    670,750,["umayyad.figure.uqba","umayyad.city.qairawan"]],
  ["cordoba-mosque","جامع قرطبة","Great Mosque of Cordoba","نواةٌ بناها الأمويون في قرطبة، توسّعت لتصير أعجوبة المعمار الأندلسي.",
    784,750,["umayyad.city.cordoba","umayyad.figure.tariq"]],
  ["wasit-citadel","واسط","Wasit","مدينة الحجاج بين الكوفة والبصرة، رمزٌ للقدرة الإدارية الأموية في العراق.",
    702,750,["umayyad.figure.al-hajjaj","umayyad.city.wasit"]],
  ["damascus-walls","أسوار دمشق","Walls of Damascus","تحصينات العاصمة الأموية، حرست قلب الخلافة قرنًا من الزمان.",
    661,750,["umayyad.city.damascus"]],
  ["umayyad-acre-port","ميناء عكا الأموي","Umayyad Port of Acre","ميناء بحري على الساحل الشامي، نقطة انطلاق لأساطيل الدولة في المتوسط.",
    661,750,["umayyad.city.damascus","umayyad.battle.constantinople-1"]],
  ["hajj-road-shami","طريق الحج الشامي","Shami Hajj Route","الطريق الذي نظّمه الأمويون لقوافل الحج من دمشق إلى الحرمين.",
    661,750,["umayyad.city.damascus","umayyad.city.madina","umayyad.city.makkah"]],
] as const;

const ARTIFACT_IDS = [
  ["dinar-umayyad","الدينار الأموي","Umayyad Gold Dinar","عملةٌ ذهبية سكّها عبد الملك بن مروان سنة 77هـ، أوّل دينارٍ إسلاميّ خالص.",
    696,750,"💰","epic",["umayyad.event.islamic-coinage","umayyad.figure.abd-al-malik"]],
  ["dirham-umayyad","الدرهم الأموي","Umayyad Silver Dirham","عملةٌ فضّيةٌ أمويّةٌ بإصلاح عبد الملك، تحمل النصوص القرآنية بدلًا من الصور.",
    696,750,"🪙","epic",["umayyad.event.islamic-coinage","umayyad.figure.abd-al-malik"]],
  ["banner-umayyad","راية الدولة الأموية","Umayyad Banner","الرايةُ البيضاء، شارة الجند الأموي من المحيط إلى أطراف الصين.",
    661,750,"🏳️","rare",["umayyad.state.umayyad"]],
  ["seal-abd-al-malik","ختم عبد الملك بن مروان","Seal of Abd al-Malik","ختمٌ خليفيّ يعكس سلطة الإصلاحات الأموية الكبرى.",
    685,705,"🪧","epic",["umayyad.figure.abd-al-malik"]],
  ["mushaf-umayyad","مصحف أموي","Umayyad Mushaf","نسخةٌ من المصحف الشريف تعود إلى العصر الأموي بخطٍّ كوفيّ مبكّر.",
    700,750,"📖","legendary",["umayyad.city.damascus"]],
  ["andalus-manuscript","مخطوطة فتح الأندلس","Manuscript of the Conquest of Andalus","مخطوطةٌ تاريخيّة تروي تفاصيل حملة طارق بن زياد وعبور المضيق.",
    711,750,"📜","epic",["umayyad.event.conquer-andalus","umayyad.figure.tariq"]],
  ["sind-manuscript","مخطوطة فتح السند","Manuscript of the Conquest of Sindh","مخطوطةٌ تاريخيّة عن حملة محمد بن القاسم وفتح بلاد السند.",
    711,750,"📜","epic",["umayyad.event.conquer-sind","umayyad.figure.muhammad-bin-qasim"]],
  ["map-umayyad","خريطة التوسعات الأموية","Map of Umayyad Expansion","خارطة توضّح اتساع الدولة الأموية من الأندلس إلى السند.",
    750,750,"🗺️","rare",["umayyad.state.umayyad"]],
  ["tariq-sword","سيف طارق بن زياد","Sword of Tariq ibn Ziyad","سيفُ القائد البربري المسلم الذي خاض به معركة وادي لكّة.",
    711,720,"🗡️","legendary",["umayyad.figure.tariq","umayyad.battle.guadalete"]],
  ["conquerors-medal","وسام الفاتحين","Medal of the Conquerors","وسامٌ تكريميٌّ يُمنح لقادة الفتوحات الأموية الكبرى.",
    715,750,"🏅","legendary",["umayyad.figure.tariq","umayyad.figure.musa-bin-nusayr","umayyad.figure.muhammad-bin-qasim"]],
] as const;

const ACHIEVEMENT_IDS = [
  ["conqueror-andalus","فاتح الأندلس","Conqueror of al-Andalus",
    "يُمنح لمن أكمل قصص فتح الأندلس وأتقن اختباراتها.",
    ["umayyad.event.conquer-andalus","umayyad.figure.tariq"]],
  ["umayyad-historian","مؤرخ الدولة الأموية","Umayyad Historian",
    "يُمنح لمن قرأ جميع الشخصيات والأحداث الأموية في المتحف.",
    ["umayyad.state.umayyad"]],
  ["umayyad-collector","جامع الآثار الأموية","Collector of Umayyad Artifacts",
    "يُمنح لمن جمع كلّ آثار الدولة الأموية في مجموعته.",
    ["umayyad.artifact.dinar-umayyad","umayyad.artifact.dirham-umayyad","umayyad.artifact.banner-umayyad"]],
  ["islamic-conquests-expert","خبير الفتوحات الإسلامية","Expert of the Islamic Conquests",
    "يُمنح لمن أتقن جميع معارك العصر الأموي.",
    ["umayyad.battle.guadalete","umayyad.battle.sind","umayyad.battle.constantinople-2"]],
  ["master-of-damascus","سيد دمشق","Master of Damascus",
    "لقبٌ شرفي يُمنح لمن أتمّ مسار العاصمة الأموية والمسجد الأموي وقبة الصخرة.",
    ["umayyad.city.damascus","umayyad.landmark.umayyad-mosque","umayyad.landmark.dome-of-rock"]],
] as const;

const FUTURE_CAMPAIGN_IDS = [
  ["future-muawiya",      "حملة معاوية بن أبي سفيان",661,680,"حملةٌ قادمة تروي تأسيس الدولة وقيام الأسطول الإسلامي البحري. (قريبًا)"],
  ["future-abd-al-malik", "حملة عبد الملك بن مروان", 685,705,"حملةٌ قادمة عن تجديد الدولة وتعريب الدواوين وسك العملة. (قريبًا)"],
  ["future-umar",         "حملة عمر بن عبد العزيز",  717,720,"حملةٌ قادمة عن خامس الراشدين والعدل المُستعاد. (قريبًا)"],
  ["future-andalus",      "حملة فتح الأندلس",        711,718,"حملةٌ قادمة عن طارق وموسى ووادي لكّة وقرطبة. (قريبًا)"],
  ["future-sind",         "حملة فتح السند",          711,713,"حملةٌ قادمة عن محمد بن القاسم وفتح وادي السند. (قريبًا)"],
  ["future-fall-umayyad", "سقوط الدولة الأموية",     743,750,"حملةٌ قادمة عن نهاية الأمويين وقيام العباسيين. (قريبًا)"],
] as const;

const entities: PackEntity[] = [
  // ---------- STATE ----------
  E({
    id: "umayyad.state.umayyad",
    title: "الدولة الأموية",
    latin: "Umayyad State",
    type: "state",
    description:
      "أوّل دولة وراثيّة في الإسلام، أسّسها معاوية بن أبي سفيان سنة 661م، عاصمتها دمشق، اتّسعت من الأندلس غربًا إلى السند والصين شرقًا، وانتهت بثورة العباسيين سنة 750م.",
    period: { label: "661 – 750 م", startYear: 661, endYear: 750 },
    relatedEntities: [
      "umayyad.figure.muawiya","umayyad.figure.abd-al-malik","umayyad.figure.al-walid-i",
      "umayyad.figure.umar-bin-abd-al-aziz","umayyad.figure.marwan-ii",
      "umayyad.city.damascus","umayyad.city.cordoba","umayyad.city.qairawan","umayyad.city.samarqand",
      "umayyad.event.found-umayyad","umayyad.event.conquer-andalus","umayyad.event.conquer-sind",
      "umayyad.event.fall-umayyad",
    ],
    unlockables: [
      { kind: "campaign", refId: "umayyad", label: "حملات الدولة الأموية" },
    ],
    image: { alt: "راية الدولة الأموية", glyph: "🏳️", tone: "from-stone-600/40 to-slate-900" },
    timelinePosition: 661,
    rarity: "legendary",
    meta: {
      founder: "معاوية بن أبي سفيان",
      capital: "دمشق",
      majorCities: ["دمشق","القيروان","قرطبة","واسط","سمرقند"],
      majorFigures: ["معاوية","عبد الملك","الوليد","عمر بن عبد العزيز","طارق بن زياد","موسى بن نصير","محمد بن القاسم"],
      majorBattles: ["وادي لكة","فتح السند","حصار القسطنطينية","بلاط الشهداء"],
      majorEvents: ["تأسيس الدولة","تعريب الدواوين","سك العملة","فتح الأندلس","فتح السند","سقوط الدولة"],
    },
    bridges: { era: "umayyad" },
  }),

  // ---------- FIGURES ----------
  ...FIGURE_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `umayyad.figure.${slug}`,
    title, latin, type: "figure", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["umayyad.state.umayyad", ...related],
    unlockables: [{ kind: "figure", refId: `umayyad.figure.${slug}`, label: title }],
    image: { alt: title, glyph: "🪶", tone: "from-stone-600/40 to-slate-900" },
    timelinePosition: startYear,
    rarity: "epic",
    meta: { titles: [title] },
    bridges: { era: "umayyad" },
  })),

  // ---------- CITIES ----------
  ...CITY_IDS.map(([slug, title, latin, description, startYear, endYear, related]) => E({
    id: `umayyad.city.${slug}`,
    title, latin, type: "city", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["umayyad.state.umayyad", ...related],
    unlockables: [{ kind: "city", refId: `umayyad.city.${slug}`, label: title }],
    image: { alt: title, glyph: "🏙️", tone: "from-amber-700/30 to-slate-900" },
    timelinePosition: startYear,
    rarity: "rare",
    bridges: { cityId: slug, era: "umayyad" },
  })),

  // ---------- BATTLES ----------
  ...BATTLE_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `umayyad.battle.${slug}`,
    title, latin, type: "battle", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["umayyad.state.umayyad", ...related],
    unlockables: [{ kind: "battle", refId: `umayyad.battle.${slug}`, label: title }],
    image: { alt: title, glyph: "⚔️", tone: "from-red-800/40 to-slate-900" },
    timelinePosition: startYear,
    rarity: "epic",
    bridges: { battleId: slug, era: "umayyad" },
  })),

  // ---------- EVENTS ----------
  ...EVENT_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `umayyad.event.${slug}`,
    title, latin, type: "event", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["umayyad.state.umayyad", ...related],
    unlockables: [{ kind: "event", refId: `umayyad.event.${slug}`, label: title }],
    image: { alt: title, glyph: "📜", tone: "from-emerald-800/40 to-slate-900" },
    timelinePosition: startYear,
    rarity: "rare",
    bridges: { era: "umayyad" },
  })),

  // ---------- LANDMARKS ----------
  ...LANDMARK_IDS.map(([slug, title, latin, description, startYear, endYear, related]) => E({
    id: `umayyad.landmark.${slug}`,
    title, latin, type: "landmark", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["umayyad.state.umayyad", ...related],
    unlockables: [{ kind: "landmark", refId: `umayyad.landmark.${slug}`, label: title }],
    image: { alt: title, glyph: "🕌", tone: "from-amber-700/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "epic",
    bridges: { era: "umayyad" },
  })),

  // ---------- ARTIFACTS ----------
  ...ARTIFACT_IDS.map(([slug, title, latin, description, startYear, endYear, glyph, rarity, related]) => E({
    id: `umayyad.artifact.${slug}`,
    title, latin, type: "artifact", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["umayyad.state.umayyad", ...related],
    unlockables: [{ kind: "artifact", refId: `umayyad.artifact.${slug}`, label: title }],
    image: { alt: title, glyph: glyph as string, tone: "from-amber-700/40 to-slate-900" },
    timelinePosition: startYear,
    rarity: rarity as "common" | "rare" | "epic" | "legendary",
    bridges: { era: "umayyad" },
  })),

  // ---------- ACHIEVEMENTS ----------
  ...ACHIEVEMENT_IDS.map(([slug, title, latin, description, related]) => E({
    id: `umayyad.achievement.${slug}`,
    title, latin, type: "achievement", description,
    period: { label: "661 – 750 م", startYear: 661, endYear: 750 },
    relatedEntities: ["umayyad.state.umayyad", ...related],
    unlockables: [{ kind: "title", refId: `umayyad.achievement.${slug}`, label: title }],
    image: { alt: title, glyph: "🏅", tone: "from-gold/40 to-slate-900" },
    timelinePosition: 700,
    rarity: "legendary",
    bridges: { era: "umayyad" },
  })),

  // ---------- FUTURE CAMPAIGN PLACEHOLDERS (locked) ----------
  ...FUTURE_CAMPAIGN_IDS.map(([slug, title, startYear, endYear, description]) => E({
    id: `umayyad.event.${slug}`,
    title, type: "event", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["umayyad.state.umayyad"],
    unlockables: [],
    image: { alt: title, glyph: "🔒", tone: "from-stone-700/40 to-slate-900" },
    timelinePosition: startYear,
    rarity: "legendary",
    meta: { locked: true, kind: "campaign-placeholder" },
    bridges: { era: "umayyad" },
  })),
];

export const UMAYYAD_PACK: ContentPack = {
  id: "pack-002-umayyad",
  order: 2,
  title: "الدولة الأموية",
  subtitle: "المجموعة 2 · من دمشق إلى أطراف الأرض",
  summary:
    "حزمة محتوى تاريخية شاملة عن الدولة الأموية: التأسيس، الفتوحات، الإصلاحات، والسقوط.",
  era: "umayyad",
  period: { label: "661 – 750 م", startYear: 661, endYear: 750 },
  cover: { alt: "غلاف الدولة الأموية", glyph: "🏳️", tone: "from-stone-600/40 to-slate-900" },
  entities,
};