import type { ContentPack, PackEntity } from "./types";

// ============================================================
// Content Pack 009 — الدولة الزنكية (Zengid State)
// 1127 – 1250 CE. Capitals: Mosul → Aleppo & Damascus.
// ============================================================

const E = (e: PackEntity): PackEntity => e;

// ---------- FIGURES ----------
const FIGURE_IDS = [
  ["imad-zengi","عماد الدين زنكي","Imad al-Din Zengi",1085,1146,
    "أتابك الموصل وحلب، مؤسس الدولة الزنكية، فتح الرها سنة ٥٣٩هـ فأسقط أوّل إمارة صليبية، ممهّد طريق نور الدين وصلاح الدين في الجهاد.",
    ["zengid.event.foundation","zengid.event.unify-mosul-aleppo","zengid.battle.edessa-conquest","zengid.event.edessa-recovery","zengid.event.organized-jihad","zengid.city.mosul","zengid.city.aleppo","zengid.city.edessa","zengid.figure.nur-zengi","zengid.figure.sayf-ghazi","zengid.artifact.edessa-manuscript"]],
  ["nur-zengi","نور الدين محمود زنكي","Nur al-Din Mahmud Zengi",1118,1174,
    "أعظم سلاطين الزنكيين وأعدلهم، وحّد الشام تحت راية الجهاد، أنشأ البيمارستانات والمدارس وأرسل شيركوه إلى مصر، رمز التقوى والحزم في عصره.",
    ["zengid.event.nur-rise","zengid.event.unify-damascus","zengid.event.send-shirkuh","zengid.event.organized-jihad","zengid.event.hospitals-schools","zengid.battle.inab","zengid.battle.harim","zengid.battle.damascus-siege","zengid.city.aleppo","zengid.city.damascus","zengid.landmark.nuri-mosque","zengid.landmark.nuri-bimaristan","zengid.landmark.nuriyya-madrasa","zengid.artifact.sword-nur-din","zengid.artifact.nur-seal","zengid.figure.shirkuh","zengid.figure.salah-din","zengid.figure.najm-ayyub"]],
  ["sayf-ghazi","سيف الدين غازي","Sayf al-Din Ghazi I",1122,1149,
    "أتابك الموصل بعد أبيه عماد الدين، صاحب فروع الموصل من الزنكيين، حافظ على ميراث والده شرق الفرات بينما تولّى نور الدين الشام.",
    ["zengid.city.mosul","zengid.city.sinjar","zengid.figure.imad-zengi","zengid.figure.qutb-mawdud","zengid.event.foundation"]],
  ["qutb-mawdud","قطب الدين مودود","Qutb al-Din Mawdud",1126,1170,
    "أتابك الموصل بعد أخيه سيف الدين، حكم نحو عشرين سنة، عاصر نور الدين وأمدّه بالعون ضد الصليبيين في الشمال.",
    ["zengid.city.mosul","zengid.city.sinjar","zengid.city.nisibis","zengid.figure.sayf-ghazi","zengid.figure.nur-zengi"]],
  ["shirkuh","أسد الدين شيركوه","Asad al-Din Shirkuh",1110,1169,
    "قائد جيوش نور الدين الكبير، عمّ صلاح الدين، قاد ثلاث حملات إلى مصر انتهت بدخوله القاهرة وزيرًا للخلافة الفاطمية سنة ٥٦٤هـ.",
    ["zengid.event.send-shirkuh","zengid.event.salah-rise","zengid.figure.nur-zengi","zengid.figure.salah-din","zengid.figure.najm-ayyub","zengid.battle.babein"]],
  ["salah-din","صلاح الدين الأيوبي","Salah al-Din (Saladin)",1138,1193,
    "تلميذ مدرسة نور الدين، خلَف عمّه شيركوه في وزارة مصر، أسقط الخلافة الفاطمية، وبعد وفاة نور الدين أسّس الدولة الأيوبية وحرّر القدس سنة ٥٨٣هـ.",
    ["zengid.figure.nur-zengi","zengid.figure.shirkuh","zengid.figure.najm-ayyub","zengid.event.send-shirkuh","zengid.event.salah-rise","zengid.event.legacy-ayyubid","zengid.event.end-zengid"]],
  ["najm-ayyub","نجم الدين أيوب","Najm al-Din Ayyub",1100,1173,
    "والد صلاح الدين وأخو شيركوه، من أبرز قادة نور الدين في الشام، وُلّي دمشق بعد ضمّها، جدّ الدولة الأيوبية.",
    ["zengid.figure.nur-zengi","zengid.figure.shirkuh","zengid.figure.salah-din","zengid.city.damascus","zengid.event.unify-damascus"]],
  ["mujir-abaq","مجير الدين أبق","Mujir al-Din Abaq",1119,1169,
    "آخر أمراء البوريين في دمشق، تحالف وتنازع مع نور الدين حتى ضمّ نور الدين دمشق سنة ٥٤٩هـ سلمًا فأكمل توحيد الشام.",
    ["zengid.city.damascus","zengid.event.unify-damascus","zengid.figure.nur-zengi","zengid.battle.damascus-siege"]],
  ["joscelin-ii","جوسلين الثاني","Joscelin II of Edessa",1113,1159,
    "آخر كونتات إمارة الرها الصليبية، خسر الرها أمام عماد الدين زنكي سنة ٥٣٩هـ، ثم سقطت إمارته كلها على يد نور الدين.",
    ["zengid.figure.imad-zengi","zengid.figure.nur-zengi","zengid.city.edessa","zengid.battle.edessa-conquest","zengid.event.edessa-recovery"]],
  ["baldwin-iii","بلدوين الثالث","Baldwin III of Jerusalem",1130,1163,
    "ملك بيت المقدس الصليبي، عاصر صعود نور الدين، حاصر بانياس ودمشق وفشل، شاهد على تحوّل ميزان القوى لصالح الجهاد الإسلامي.",
    ["zengid.figure.nur-zengi","zengid.battle.damascus-siege","zengid.battle.banyas-siege","zengid.battle.buqaia","zengid.event.organized-jihad"]],
] as const;

// ---------- SCHOLARS ----------
const SCHOLAR_IDS = [
  ["ibn-asakir","ابن عساكر","Ibn Asakir",1105,1175,
    "محدّث الشام في عصر نور الدين، صاحب تاريخ دمشق، ولّاه نور الدين دار الحديث النورية، أعظم مؤرخي المدن في الإسلام.",
    ["zengid.figure.nur-zengi","zengid.landmark.nuriyya-madrasa","zengid.city.damascus","zengid.event.hospitals-schools"]],
  ["abd-ghani-maqdisi","عبد الغني المقدسي","Abd al-Ghani al-Maqdisi",1146,1203,
    "محدّث الحنابلة وحافظ الشام، من أبناء بيت المقدس الذين هاجروا إلى دمشق في زمن الزنكيين والأيوبيين، صاحب الكمال في معرفة الرجال.",
    ["zengid.figure.ibn-qudamah","zengid.city.damascus","zengid.figure.muwaffaq-qudamah"]],
  ["ibn-qudamah","ابن قدامة المقدسي","Ibn Qudamah al-Maqdisi",1147,1223,
    "صاحب المغني، أحد أعلام الحنابلة الكبار، نشأ في دمشق في حيّ الصالحية بعد هجرة أهله من القدس بسبب الصليبيين.",
    ["zengid.figure.muwaffaq-qudamah","zengid.figure.abd-ghani-maqdisi","zengid.city.damascus","zengid.event.organized-jihad"]],
  ["abu-shama","أبو شامة المقدسي","Abu Shama al-Maqdisi",1203,1267,
    "مؤرخ الدولتين النورية والصلاحية، صاحب الروضتين في أخبار الدولتين، أوثق مصادر تاريخ نور الدين وصلاح الدين.",
    ["zengid.figure.nur-zengi","zengid.figure.salah-din","zengid.city.damascus","zengid.artifact.jihad-manuscript"]],
  ["al-samani","الإمام السمعاني","Al-Sam'ani",1113,1166,
    "صاحب كتاب الأنساب، الرحّالة المؤرخ الذي عاش في عصر زنكي ونور الدين، طاف خراسان والعراق والشام يجمع أخبار العلماء.",
    ["zengid.city.mosul","zengid.city.aleppo","zengid.figure.nur-zengi"]],
  ["ibn-al-jawzi","ابن الجوزي","Ibn al-Jawzi",1116,1201,
    "إمام الوعّاظ والمؤرخين في بغداد، عاش في عصر الزنكيين والأيوبيين، صاحب المنتظم وصيد الخاطر.",
    ["zengid.figure.nur-zengi","zengid.event.organized-jihad"]],
  ["muwaffaq-qudamah","موفق الدين بن قدامة","Muwaffaq al-Din ibn Qudamah",1147,1223,
    "شيخ الحنابلة في زمنه، صاحب العمدة والمقنع والكافي والمغني، رحل إلى بغداد وعاد إلى دمشق وصار مرجع المذهب.",
    ["zengid.figure.ibn-qudamah","zengid.figure.abd-ghani-maqdisi","zengid.city.damascus"]],
] as const;

// ---------- CITIES ----------
const CITY_IDS = [
  ["mosul","الموصل","Mosul",
    "العاصمة الأولى للزنكيين على دجلة، انطلق منها عماد الدين لفتح الجزيرة والرها، ظلّت قاعدة فرع زنكيي الموصل بعد ابنه سيف الدين.",
    1127,1250,["zengid.figure.imad-zengi","zengid.figure.sayf-ghazi","zengid.figure.qutb-mawdud","zengid.event.foundation","zengid.event.unify-mosul-aleppo","zengid.landmark.mosul-walls","zengid.landmark.nuri-mosque","zengid.landmark.hadba-minaret"]],
  ["aleppo","حلب","Aleppo",
    "حاضرة الزنكيين في الشمال الشامي، انتقلت إلى عماد الدين سنة ٥٢٢هـ، وصارت قاعدة نور الدين قبل دمشق، فيها قلعتها الشهيرة.",
    1128,1183,["zengid.figure.imad-zengi","zengid.figure.nur-zengi","zengid.event.unify-mosul-aleppo","zengid.landmark.aleppo-citadel","zengid.battle.aleppo-siege"]],
  ["damascus","دمشق","Damascus",
    "عاصمة نور الدين بعد توحيدها سنة ٥٤٩هـ، حاضرة الشام السياسية والعلمية، فيها الجامع النوري والبيمارستان والمدرسة النورية.",
    1154,1250,["zengid.figure.nur-zengi","zengid.figure.najm-ayyub","zengid.figure.mujir-abaq","zengid.event.unify-damascus","zengid.battle.damascus-siege","zengid.landmark.damascus-citadel","zengid.landmark.nuri-bimaristan","zengid.landmark.nuriyya-madrasa"]],
  ["hama","حماة","Hama",
    "حاضرة وسط الشام على العاصي، تولّاها الزنكيون ضمن ميراث نور الدين، صارت لاحقًا مقرّ فرع أيوبيي حماة.",
    1129,1250,["zengid.figure.nur-zengi","zengid.figure.imad-zengi","zengid.event.organized-jihad"]],
  ["homs","حمص","Homs",
    "ثغر داخلي بين دمشق وحلب، تولّاها أسد الدين شيركوه قبل رحيله إلى مصر، صارت قاعدة لفرع شيركوه ثم الأيوبيين.",
    1129,1250,["zengid.figure.shirkuh","zengid.figure.nur-zengi","zengid.battle.buqaia"]],
  ["edessa","الرها","Edessa",
    "حاضرة الجزيرة العليا وأوّل إمارة صليبية في الشرق، فتحها عماد الدين زنكي سنة ٥٣٩هـ فأشعل الجهاد المنظّم ضدّ الفرنجة.",
    1144,1146,["zengid.figure.imad-zengi","zengid.figure.joscelin-ii","zengid.battle.edessa-conquest","zengid.event.edessa-recovery","zengid.artifact.edessa-manuscript","zengid.artifact.edessa-medal"]],
  ["baalbek","بعلبك","Baalbek",
    "حصنٌ في البقاع، تولّاه نجم الدين أيوب من قبل البوريين ثم الزنكيين، شهد نشأة صلاح الدين في بيت أبيه.",
    1146,1250,["zengid.figure.najm-ayyub","zengid.figure.salah-din","zengid.figure.nur-zengi"]],
  ["sinjar","سنجار","Sinjar",
    "حصنٌ غربي الموصل، تولّاه فرع من الزنكيين، فيه قلعة سنجار الشهيرة، حارس الجزيرة الفراتية.",
    1127,1250,["zengid.figure.sayf-ghazi","zengid.figure.qutb-mawdud","zengid.city.mosul","zengid.landmark.sinjar-citadel"]],
  ["nisibis","نصيبين","Nisibis",
    "ثغر بين الموصل وماردين، من ميراث عماد الدين زنكي في الجزيرة، حلقة وصل بين زنكيي الموصل وأرتقيي ماردين.",
    1127,1250,["zengid.figure.qutb-mawdud","zengid.figure.imad-zengi","zengid.city.mardin"]],
  ["mardin","ماردين","Mardin",
    "قاعدة الأرتقيين في الجزيرة، تحالفوا ونازعوا الزنكيين في زمن عماد الدين ونور الدين، من جيرة الموصل ومجالها السياسي.",
    1127,1250,["zengid.city.nisibis","zengid.city.mosul","zengid.figure.imad-zengi"]],
] as const;

// ---------- BATTLES ----------
const BATTLE_IDS = [
  ["edessa-conquest","فتح الرها","Capture of Edessa",1144,1144,
    "حاصر عماد الدين زنكي الرها وفتحها بعد ٢٨ يومًا، أسقط أوّل إمارة صليبية وأشعل الحملة الصليبية الثانية، أعظم انتصارات الزنكيين.",
    ["zengid.figure.imad-zengi","zengid.figure.joscelin-ii","zengid.city.edessa","zengid.event.edessa-recovery","zengid.event.organized-jihad","zengid.artifact.edessa-manuscript","zengid.artifact.edessa-medal"]],
  ["damascus-siege","حصار دمشق","Siege of Damascus",1148,1148,
    "حصار الحملة الصليبية الثانية بقيادة لويس السابع وكونراد الثالث وبلدوين الثالث لدمشق، أنقذها نور الدين وأخوه سيف الدين فانكسر الفرنجة.",
    ["zengid.figure.nur-zengi","zengid.figure.sayf-ghazi","zengid.figure.baldwin-iii","zengid.city.damascus","zengid.event.organized-jihad"]],
  ["inab","معركة إنب","Battle of Inab",1149,1149,
    "نصر نور الدين الفاصل على ريموند أمير أنطاكية الصليبية قرب إنب، قُتل فيها ريموند وانهار الوجود الصليبي شمالي الشام.",
    ["zengid.figure.nur-zengi","zengid.city.aleppo","zengid.event.organized-jihad"]],
  ["harim","معركة حارم","Battle of Harim",1164,1164,
    "نصر نور الدين الكبير على تحالف صليبي يضمّ بوهيموند الثالث وريموند الثالث وتورنال البيزنطي، أسر فيها عددًا من ملوك الفرنجة.",
    ["zengid.figure.nur-zengi","zengid.city.aleppo","zengid.event.organized-jihad"]],
  ["buqaia","معركة البقيعة","Battle of al-Buqaia",1163,1163,
    "هزيمة لنور الدين أمام تحالف صليبي في البقيعة قرب حمص، نهض منها بسرعة وثأر في حارم وبانياس فحقق التوازن لصالحه.",
    ["zengid.figure.nur-zengi","zengid.city.homs","zengid.figure.baldwin-iii"]],
  ["banyas-siege","حصار بانياس","Siege of Banyas",1164,1164,
    "حاصر نور الدين بانياس وفتحها سنة ٥٥٩هـ فقطع طريق الصليبيين بين دمشق والساحل، أحد مفاتيح تأمين الشام الجنوبي.",
    ["zengid.figure.nur-zengi","zengid.figure.baldwin-iii","zengid.event.organized-jihad"]],
  ["tell-danith","معركة تل دانيث","Battle of Tell Danith",1119,1119,
    "موقعة أرتقية كبرى قبل الزنكيين على الفرنجة قرب حلب (يوم سرمدا)، مهّدت لانتقال حلب لاحقًا إلى عماد الدين زنكي.",
    ["zengid.city.aleppo","zengid.figure.imad-zengi","zengid.event.foundation"]],
  ["aleppo-siege","حصار حلب","Siege of Aleppo",1124,1125,
    "حصار صليبي وأرتقي طويل لحلب قبل وصول عماد الدين زنكي، انتهى بفشل الحصار وتمهيد ضمّ المدينة إلى الزنكيين.",
    ["zengid.city.aleppo","zengid.figure.imad-zengi","zengid.event.unify-mosul-aleppo"]],
  ["babein","معركة البابين","Battle of al-Babein",1167,1167,
    "موقعة في صعيد مصر بين شيركوه وصلاح الدين من جهة، والصليبيين والفاطميين من جهة أخرى، مهّدت لدخول الزنكيين القاهرة لاحقًا.",
    ["zengid.figure.shirkuh","zengid.figure.salah-din","zengid.event.send-shirkuh","zengid.event.salah-rise"]],
] as const;

// ---------- EVENTS ----------
const EVENT_IDS = [
  ["foundation","تأسيس الدولة الزنكية","Founding of the Zengid State",1127,1128,
    "وُلّي عماد الدين زنكي أتابكية الموصل سنة ٥٢١هـ، ثم ضمّ حلب فقامت الدولة الزنكية على الموصل والجزيرة وشمال الشام.",
    ["zengid.figure.imad-zengi","zengid.city.mosul","zengid.city.aleppo","zengid.event.unify-mosul-aleppo"]],
  ["unify-mosul-aleppo","توحيد الموصل وحلب","Union of Mosul and Aleppo",1128,1128,
    "ضمّ عماد الدين زنكي حلب إلى الموصل سنة ٥٢٢هـ فجمع لأوّل مرة شمال الجزيرة وشمال الشام تحت إمارة واحدة في وجه الصليبيين.",
    ["zengid.figure.imad-zengi","zengid.city.mosul","zengid.city.aleppo","zengid.event.foundation","zengid.event.organized-jihad"]],
  ["edessa-recovery","فتح الرها","Recovery of Edessa",1144,1144,
    "فتح عماد الدين الرها بعد حصارٍ قصير، إسقاط أوّل إمارة صليبية في الشرق، يُعدّ من علامات تحوّل التاريخ الإسلامي ضدّ الصليبيين.",
    ["zengid.figure.imad-zengi","zengid.battle.edessa-conquest","zengid.city.edessa","zengid.event.organized-jihad","zengid.artifact.edessa-manuscript"]],
  ["organized-jihad","بداية الجهاد المنظم ضد الصليبيين","Birth of Organized Jihad",1144,1174,
    "تحوّل الجهاد ضد الصليبيين من غاراتٍ متفرقة إلى مشروع دولة شاملة في عهد عماد الدين ونور الدين، يقوم على وحدة الشام وتربية الناس.",
    ["zengid.figure.imad-zengi","zengid.figure.nur-zengi","zengid.event.edessa-recovery","zengid.event.unify-damascus","zengid.event.hospitals-schools","zengid.artifact.jihad-manuscript"]],
  ["hospitals-schools","بناء المستشفيات والمدارس","Building of Hospitals and Madrasas",1154,1174,
    "أنشأ نور الدين البيمارستان النوري ودار الحديث النورية والمدارس النورية في دمشق وحلب وحماة، نموذج المؤسسات الإسلامية الكبرى.",
    ["zengid.figure.nur-zengi","zengid.landmark.nuri-bimaristan","zengid.landmark.nuriyya-madrasa","zengid.landmark.nuri-mosque","zengid.figure.ibn-asakir","zengid.artifact.bimaristan-waqf"]],
  ["nur-rise","صعود نور الدين","Rise of Nur al-Din",1146,1149,
    "تولّى نور الدين حلب بعد مقتل أبيه عماد الدين، صدّ الحملة الصليبية الثانية، انتصر في إنب فبدأت مرحلة قيادة الجهاد.",
    ["zengid.figure.nur-zengi","zengid.figure.imad-zengi","zengid.battle.damascus-siege","zengid.battle.inab","zengid.city.aleppo"]],
  ["unify-damascus","توحيد دمشق","Unification of Damascus",1154,1154,
    "ضمّ نور الدين دمشق سنة ٥٤٩هـ صلحًا من البوريين ومجير الدين أبق، فاكتمل توحيد الشام تحت رايته من حلب إلى دمشق.",
    ["zengid.figure.nur-zengi","zengid.figure.mujir-abaq","zengid.figure.najm-ayyub","zengid.city.damascus","zengid.event.organized-jihad"]],
  ["send-shirkuh","إرسال شيركوه إلى مصر","Shirkuh's Expeditions to Egypt",1163,1169,
    "أرسل نور الدين أسد الدين شيركوه ومعه ابن أخيه صلاح الدين في ثلاث حملات إلى مصر انتهت بدخولهم القاهرة ووزارة شيركوه للفاطميين.",
    ["zengid.figure.nur-zengi","zengid.figure.shirkuh","zengid.figure.salah-din","zengid.battle.babein","zengid.event.salah-rise"]],
  ["salah-rise","صعود صلاح الدين","Rise of Salah al-Din",1169,1174,
    "خلَف صلاح الدين عمّه شيركوه في وزارة مصر، أسقط الخلافة الفاطمية سنة ٥٦٧هـ ودعا للعباسي، ثم انفرد بأمره بعد وفاة نور الدين.",
    ["zengid.figure.salah-din","zengid.figure.nur-zengi","zengid.figure.shirkuh","zengid.event.end-zengid","zengid.event.legacy-ayyubid"]],
  ["end-zengid","نهاية الدولة الزنكية","End of the Zengid State",1174,1250,
    "بعد وفاة نور الدين سنة ٥٦٩هـ تفتّتت الدولة بين أولاده وأقاربه، استولى صلاح الدين على دمشق وحلب، وبقي فرع الموصل حتى استولى عليه بدر الدين لؤلؤ ثم سقط نهائيًا.",
    ["zengid.figure.nur-zengi","zengid.figure.salah-din","zengid.city.mosul","zengid.city.aleppo","zengid.city.damascus","zengid.event.legacy-ayyubid"]],
  ["legacy-ayyubid","انتقال الإرث إلى الأيوبيين","Transition to the Ayyubids",1174,1183,
    "ورث صلاح الدين والأيوبيون مشروع الزنكيين في توحيد الشام ومصر والجهاد ضد الصليبيين، فتحرّرت القدس بعد ١٣ سنة من وفاة نور الدين.",
    ["zengid.figure.salah-din","zengid.figure.nur-zengi","zengid.event.end-zengid","zengid.event.organized-jihad"]],
] as const;

// ---------- LANDMARKS ----------
const LANDMARK_IDS = [
  ["nuri-mosque","الجامع النوري","Great Nuri Mosque",
    "جامع نور الدين الكبير في الموصل، من أعظم آثار الزنكيين، يضمّ منارة الحدباء الشهيرة، شاهد على العمارة الزنكية حتى دمّره داعش حديثًا.",
    1172,1250,["zengid.figure.nur-zengi","zengid.city.mosul","zengid.landmark.hadba-minaret","zengid.event.hospitals-schools"]],
  ["hadba-minaret","منارة الحدباء","Al-Hadba Minaret",
    "منارة الجامع النوري في الموصل المائلة، أيقونة المدينة وعمارة الزنكيين لثمانية قرون، حتى تدميرها سنة ٢٠١٧م.",
    1172,2017,["zengid.landmark.nuri-mosque","zengid.figure.nur-zengi","zengid.city.mosul"]],
  ["aleppo-citadel","قلعة حلب","Citadel of Aleppo",
    "قلعة حلب التاريخية، عزّزها الزنكيون وعصرنوا تحصيناتها، صارت لاحقًا تحفة العمارة الإسلامية مع الأيوبيين والمماليك.",
    1128,1250,["zengid.figure.nur-zengi","zengid.figure.imad-zengi","zengid.city.aleppo","zengid.battle.aleppo-siege"]],
  ["damascus-citadel","قلعة دمشق","Citadel of Damascus",
    "قلعة دمشق التي عزّزها نور الدين بعد توحيد المدينة، صارت مقرّ السلاطين، شاهدة على دفاع الشام في وجه الصليبيين.",
    1154,1250,["zengid.figure.nur-zengi","zengid.city.damascus","zengid.event.unify-damascus"]],
  ["nuri-bimaristan","البيمارستان النوري","Nuri Hospital",
    "أعظم مستشفى في تاريخ الإسلام الوسيط، أنشأه نور الدين في دمشق سنة ٥٤٩هـ، خدم العلاج والتعليم الطبي معًا لقرون.",
    1154,1250,["zengid.figure.nur-zengi","zengid.city.damascus","zengid.event.hospitals-schools","zengid.artifact.bimaristan-waqf"]],
  ["nuriyya-madrasa","المدرسة النورية","Nuriyya Madrasa",
    "مدرسة نور الدين في دمشق، مركز الفقه والحديث الشافعي والحنبلي، فيها درّس ابن عساكر وكُتب جزء من تاريخ دمشق.",
    1167,1250,["zengid.figure.nur-zengi","zengid.figure.ibn-asakir","zengid.city.damascus","zengid.event.hospitals-schools"]],
  ["mosul-walls","أسوار الموصل","Walls of Mosul",
    "تحصينات الموصل التي عزّزها عماد الدين زنكي وأبناؤه، حمت العاصمة الأولى للزنكيين حتى الغزو المغولي.",
    1127,1250,["zengid.city.mosul","zengid.figure.imad-zengi","zengid.figure.sayf-ghazi","zengid.figure.qutb-mawdud"]],
  ["sinjar-citadel","قلعة سنجار","Citadel of Sinjar",
    "حصن غربي الموصل في يد فرع الزنكيين، حارس الجزيرة الفراتية ضدّ الأرتقيين والصليبيين.",
    1127,1250,["zengid.city.sinjar","zengid.figure.sayf-ghazi","zengid.figure.qutb-mawdud"]],
] as const;

// ---------- ARTIFACTS ----------
const ARTIFACT_IDS = [
  ["sword-nur-din","سيف نور الدين","Sword of Nur al-Din",
    "سيف السلطان العادل الذي حمله من إنب إلى حارم، رمز الجهاد المنظّم في الشام، حُفظ بعده في مشهد دمشق.",
    1146,1174,"🗡️","legendary",["zengid.figure.nur-zengi","zengid.battle.inab","zengid.battle.harim","zengid.event.organized-jihad"]],
  ["zengid-banner","راية الزنكيين","Banner of the Zengids",
    "الراية الحمراء للزنكيين التي رُفعت في فتح الرها وتوحيد الشام، رمز الجهاد المنظم قبل صلاح الدين.",
    1127,1183,"🏴","epic",["zengid.figure.imad-zengi","zengid.figure.nur-zengi","zengid.event.foundation","zengid.event.organized-jihad"]],
  ["edessa-manuscript","مخطوطة فتح الرها","Manuscript of the Edessa Conquest",
    "وثيقة تروي تفاصيل حصار عماد الدين زنكي للرها وفتحها سنة ٥٣٩هـ، شاهدة على أعظم انتصارات الزنكيين.",
    1144,1200,"📜","legendary",["zengid.figure.imad-zengi","zengid.battle.edessa-conquest","zengid.city.edessa","zengid.event.edessa-recovery"]],
  ["bimaristan-waqf","وقف البيمارستان النوري","Endowment of the Nuri Hospital",
    "وثيقة وقف نور الدين على البيمارستان النوري في دمشق، نموذج المؤسسات الخيرية الإسلامية ورعاية المرضى مجانًا.",
    1154,1250,"📜","epic",["zengid.figure.nur-zengi","zengid.landmark.nuri-bimaristan","zengid.event.hospitals-schools","zengid.city.damascus"]],
  ["zengid-map","خريطة الدولة الزنكية","Map of the Zengid State",
    "خريطة تبيّن امتداد الزنكيين من الموصل والجزيرة إلى حلب ودمشق وبعلبك في ذروة عهد نور الدين.",
    1154,1174,"🗺️","epic",["zengid.figure.nur-zengi","zengid.city.mosul","zengid.city.aleppo","zengid.city.damascus","zengid.event.unify-damascus"]],
  ["nur-seal","ختم نور الدين","Seal of Nur al-Din",
    "ختم السلطان نور الدين على مراسيمه ووقفياته، نقش بسيط زاهد يعكس شخصية صاحبه التقيّة.",
    1146,1174,"🪧","epic",["zengid.figure.nur-zengi","zengid.event.organized-jihad","zengid.artifact.bimaristan-waqf"]],
  ["zengid-dinar","دينار زنكي","Zengid Dinar",
    "عملة ذهبية ضربها نور الدين باسمه واسم الخليفة العباسي، شاهدة على شرعية الدولة الزنكية واتصالها ببغداد.",
    1146,1183,"🪙","rare",["zengid.figure.nur-zengi","zengid.figure.imad-zengi","zengid.city.aleppo","zengid.city.damascus"]],
  ["edessa-medal","وسام محرر الرها","Medal of the Liberator of Edessa",
    "وسام شرفي يُمنح لمن أكمل مسار عماد الدين زنكي وفتح الرها.",
    1144,1250,"🏵️","legendary",["zengid.battle.edessa-conquest","zengid.figure.imad-zengi","zengid.city.edessa","zengid.event.edessa-recovery"]],
  ["sultani-decree","مرسوم سلطاني","Sultanic Decree",
    "مرسوم بخط ديوان نور الدين في تعيين القضاة والولاة، نموذج من وثائق الإدارة الزنكية القائمة على الشرع.",
    1146,1174,"📜","rare",["zengid.figure.nur-zengi","zengid.event.hospitals-schools","zengid.figure.ibn-asakir"]],
  ["jihad-manuscript","مخطوطة الجهاد","Manuscript of the Jihad",
    "وثيقة من تأليف أبي شامة المقدسي ضمن الروضتين، تروي مشروع الجهاد المنظم بين نور الدين وصلاح الدين.",
    1230,1267,"📚","legendary",["zengid.figure.abu-shama","zengid.figure.nur-zengi","zengid.figure.salah-din","zengid.event.organized-jihad","zengid.event.legacy-ayyubid"]],
] as const;

// ---------- ACHIEVEMENTS ----------
const ACHIEVEMENT_IDS = [
  ["edessa-liberator","محرّر الرها","Liberator of Edessa",
    "يُمنح لمن أكمل قصص عماد الدين زنكي وفتح الرها وسقوط أوّل إمارة صليبية.",
    ["zengid.figure.imad-zengi","zengid.battle.edessa-conquest","zengid.city.edessa","zengid.event.edessa-recovery","zengid.artifact.edessa-manuscript","zengid.artifact.edessa-medal"]],
  ["zengid-historian","مؤرّخ الدولة الزنكية","Historian of the Zengid State",
    "يُمنح لمن قرأ جميع شخصيات وأحداث الدولة الزنكية في الموسوعة.",
    ["zengid.state.zengid","zengid.figure.imad-zengi","zengid.figure.nur-zengi","zengid.figure.shirkuh","zengid.event.foundation","zengid.event.end-zengid","zengid.event.legacy-ayyubid"]],
  ["zengid-collector","جامع التراث الزنكي","Collector of Zengid Heritage",
    "يُمنح لمن جمع كلّ آثار ومخطوطات الزنكيين في مجموعته.",
    ["zengid.artifact.sword-nur-din","zengid.artifact.zengid-banner","zengid.artifact.edessa-manuscript","zengid.artifact.bimaristan-waqf","zengid.artifact.nur-seal","zengid.artifact.jihad-manuscript","zengid.artifact.edessa-medal"]],
  ["nur-disciple","تلميذ نور الدين","Disciple of Nur al-Din",
    "يُمنح لمن أتمّ مسار نور الدين في توحيد الشام والجهاد وبناء البيمارستانات والمدارس.",
    ["zengid.figure.nur-zengi","zengid.event.unify-damascus","zengid.event.organized-jihad","zengid.event.hospitals-schools","zengid.landmark.nuri-bimaristan","zengid.landmark.nuriyya-madrasa","zengid.landmark.nuri-mosque"]],
  ["sham-protector","حامي الشام","Protector of Greater Syria",
    "يُمنح لمن أكمل قصص صدّ الحملة الصليبية الثانية وانتصارات إنب وحارم وبانياس.",
    ["zengid.battle.damascus-siege","zengid.battle.inab","zengid.battle.harim","zengid.battle.banyas-siege","zengid.figure.nur-zengi","zengid.event.organized-jihad"]],
] as const;

// ---------- FUTURE CAMPAIGN PLACEHOLDERS (locked) ----------
const FUTURE_CAMPAIGN_IDS = [
  ["future-imad",      "حملة عماد الدين زنكي",  1127,1146,"حملةٌ قادمة عن مؤسس الدولة وفاتح الرها. (قريبًا)"],
  ["future-nur",       "حملة نور الدين محمود",  1146,1174,"حملةٌ قادمة عن أعدل سلاطين الشام وقائد الجهاد المنظم. (قريبًا)"],
  ["future-edessa",    "فتح الرها",             1144,1144,"حملةٌ قادمة عن إسقاط أوّل إمارة صليبية. (قريبًا)"],
  ["future-unify-sham","توحيد الشام",           1146,1154,"حملةٌ قادمة عن جمع حلب ودمشق تحت راية واحدة. (قريبًا)"],
  ["future-shirkuh",   "شيركوه في مصر",         1163,1169,"حملةٌ قادمة عن الحملات الثلاث إلى القاهرة. (قريبًا)"],
  ["future-salah-road","الطريق إلى صلاح الدين", 1169,1174,"حملةٌ قادمة عن وراثة المشروع الزنكي. (قريبًا)"],
] as const;

const entities: PackEntity[] = [
  // ---------- STATE ----------
  E({
    id: "zengid.state.zengid",
    title: "الدولة الزنكية",
    latin: "Zengid State",
    type: "state",
    description:
      "الدولة الزنكية، أسّسها عماد الدين زنكي سنة ٥٢١هـ/١١٢٧م في الموصل وحلب، وبلغت ذروتها في عهد ابنه نور الدين محمود الذي وحّد الشام من حلب إلى دمشق، فأطلق مشروع الجهاد المنظّم ضدّ الصليبيين وبنى البيمارستانات والمدارس، وانتقل ميراثها إلى صلاح الدين والأيوبيين، حتى سقط آخر فروعها في الموصل سنة ٦٤٨هـ/١٢٥٠م.",
    period: { label: "٥٢١ – ٦٤٨ هـ / ١١٢٧ – ١٢٥٠ م", startYear: 1127, endYear: 1250 },
    relatedEntities: [
      "zengid.figure.imad-zengi","zengid.figure.nur-zengi","zengid.figure.sayf-ghazi","zengid.figure.qutb-mawdud",
      "zengid.figure.shirkuh","zengid.figure.salah-din","zengid.figure.najm-ayyub","zengid.figure.mujir-abaq",
      "zengid.figure.joscelin-ii","zengid.figure.baldwin-iii",
      "zengid.figure.ibn-asakir","zengid.figure.ibn-qudamah","zengid.figure.abu-shama","zengid.figure.muwaffaq-qudamah",
      "zengid.city.mosul","zengid.city.aleppo","zengid.city.damascus","zengid.city.hama","zengid.city.homs",
      "zengid.city.edessa","zengid.city.baalbek","zengid.city.sinjar","zengid.city.nisibis","zengid.city.mardin",
      "zengid.battle.edessa-conquest","zengid.battle.damascus-siege","zengid.battle.inab","zengid.battle.harim",
      "zengid.battle.buqaia","zengid.battle.banyas-siege","zengid.battle.tell-danith","zengid.battle.aleppo-siege","zengid.battle.babein",
      "zengid.event.foundation","zengid.event.unify-mosul-aleppo","zengid.event.edessa-recovery",
      "zengid.event.organized-jihad","zengid.event.hospitals-schools","zengid.event.nur-rise",
      "zengid.event.unify-damascus","zengid.event.send-shirkuh","zengid.event.salah-rise",
      "zengid.event.end-zengid","zengid.event.legacy-ayyubid",
    ],
    unlockables: [
      { kind: "campaign", refId: "zengid", label: "حملات الدولة الزنكية" },
    ],
    image: { alt: "راية الدولة الزنكية", glyph: "🏴", tone: "from-rose-900/40 to-stone-900" },
    timelinePosition: 1127,
    rarity: "legendary",
    meta: {
      founder: "عماد الدين زنكي",
      capital: "الموصل (ثم حلب ودمشق)",
      majorCities: ["الموصل","حلب","دمشق","حماة","حمص","الرها","بعلبك","سنجار","نصيبين","ماردين"],
      majorFigures: ["عماد الدين زنكي","نور الدين محمود","سيف الدين غازي","قطب الدين مودود","شيركوه","نجم الدين أيوب","صلاح الدين"],
      majorBattles: ["فتح الرها","حصار دمشق","إنب","حارم","البقيعة","بانياس","تل دانيث","حصار حلب","البابين"],
      majorEvents: ["تأسيس الدولة","توحيد الموصل وحلب","فتح الرها","الجهاد المنظم","بناء البيمارستانات","صعود نور الدين","توحيد دمشق","شيركوه في مصر","صعود صلاح الدين","نهاية الدولة","انتقال الإرث إلى الأيوبيين"],
    },
    bridges: { era: "zengid" },
  }),

  // ---------- FIGURES ----------
  ...FIGURE_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `zengid.figure.${slug}`,
    title, latin, type: "figure", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["zengid.state.zengid", ...related],
    unlockables: [{ kind: "figure", refId: `zengid.figure.${slug}`, label: title }],
    image: { alt: title, glyph: "🏴", tone: "from-rose-900/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "epic",
    meta: { titles: [title] },
    bridges: { era: "zengid" },
  })),

  // ---------- SCHOLARS ----------
  ...SCHOLAR_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `zengid.figure.${slug}`,
    title, latin, type: "figure", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["zengid.state.zengid", ...related],
    unlockables: [{ kind: "figure", refId: `zengid.figure.${slug}`, label: title }],
    image: { alt: title, glyph: "📚", tone: "from-rose-900/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "epic",
    meta: { kind: "scholar", titles: [title] },
    bridges: { era: "zengid" },
  })),

  // ---------- CITIES ----------
  ...CITY_IDS.map(([slug, title, latin, description, startYear, endYear, related]) => E({
    id: `zengid.city.${slug}`,
    title, latin, type: "city", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["zengid.state.zengid", ...related],
    unlockables: [{ kind: "city", refId: `zengid.city.${slug}`, label: title }],
    image: { alt: title, glyph: "🏙️", tone: "from-rose-900/30 to-stone-900" },
    timelinePosition: startYear,
    rarity: "rare",
    bridges: { cityId: slug, era: "zengid" },
  })),

  // ---------- BATTLES ----------
  ...BATTLE_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `zengid.battle.${slug}`,
    title, latin, type: "battle", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["zengid.state.zengid", ...related],
    unlockables: [{ kind: "battle", refId: `zengid.battle.${slug}`, label: title }],
    image: { alt: title, glyph: "⚔️", tone: "from-red-800/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "epic",
    bridges: { era: "zengid" },
  })),

  // ---------- EVENTS ----------
  ...EVENT_IDS.map(([slug, title, latin, startYear, endYear, description, related]) => E({
    id: `zengid.event.${slug}`,
    title, latin, type: "event", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["zengid.state.zengid", ...related],
    unlockables: [{ kind: "event", refId: `zengid.event.${slug}`, label: title }],
    image: { alt: title, glyph: "📜", tone: "from-rose-900/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "rare",
    bridges: { era: "zengid" },
  })),

  // ---------- LANDMARKS ----------
  ...LANDMARK_IDS.map(([slug, title, latin, description, startYear, endYear, related]) => E({
    id: `zengid.landmark.${slug}`,
    title, latin, type: "landmark", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["zengid.state.zengid", ...related],
    unlockables: [{ kind: "landmark", refId: `zengid.landmark.${slug}`, label: title }],
    image: { alt: title, glyph: "🕌", tone: "from-rose-900/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: "epic",
    bridges: { era: "zengid" },
  })),

  // ---------- ARTIFACTS ----------
  ...ARTIFACT_IDS.map(([slug, title, latin, description, startYear, endYear, glyph, rarity, related]) => E({
    id: `zengid.artifact.${slug}`,
    title, latin, type: "artifact", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["zengid.state.zengid", ...related],
    unlockables: [{ kind: "artifact", refId: `zengid.artifact.${slug}`, label: title }],
    image: { alt: title, glyph: glyph as string, tone: "from-rose-900/40 to-stone-900" },
    timelinePosition: startYear,
    rarity: rarity as "common" | "rare" | "epic" | "legendary",
    bridges: { era: "zengid" },
  })),

  // ---------- ACHIEVEMENTS ----------
  ...ACHIEVEMENT_IDS.map(([slug, title, latin, description, related]) => E({
    id: `zengid.achievement.${slug}`,
    title, latin, type: "achievement", description,
    period: { label: "١١٢٧ – ١٢٥٠ م", startYear: 1127, endYear: 1250 },
    relatedEntities: ["zengid.state.zengid", ...related],
    unlockables: [{ kind: "title", refId: `zengid.achievement.${slug}`, label: title }],
    image: { alt: title, glyph: "🏅", tone: "from-amber-600/40 to-stone-900" },
    timelinePosition: 1160,
    rarity: "legendary",
    bridges: { era: "zengid" },
  })),

  // ---------- FUTURE CAMPAIGN PLACEHOLDERS (locked) ----------
  ...FUTURE_CAMPAIGN_IDS.map(([slug, title, startYear, endYear, description]) => E({
    id: `zengid.event.${slug}`,
    title, type: "event", description,
    period: { label: `${startYear} – ${endYear} م`, startYear, endYear },
    relatedEntities: ["zengid.state.zengid"],
    unlockables: [],
    image: { alt: title, glyph: "🔒", tone: "from-stone-700/40 to-slate-900" },
    timelinePosition: startYear,
    rarity: "legendary",
    meta: { locked: true, kind: "campaign-placeholder" },
    bridges: { era: "zengid" },
  })),
];

export const ZENGID_PACK: ContentPack = {
  id: "pack-009-zengid",
  order: 27, // between Seljuk (25) and Ayyubid
  title: "الدولة الزنكية",
  subtitle: "المجموعة ٩ · أتابكة الموصل والشام وقادة الجهاد المنظم",
  summary:
    "حزمة محتوى تاريخية شاملة عن الدولة الزنكية من تأسيس عماد الدين زنكي إلى ذروة عهد نور الدين محمود، تشمل فتح الرها وتوحيد الشام وصدّ الحملة الصليبية الثانية، وبناء البيمارستان النوري والمدارس النورية، وحملات شيركوه إلى مصر وانتقال الميراث إلى صلاح الدين.",
  era: "zengid",
  period: { label: "٥٢١ – ٦٤٨ هـ / ١١٢٧ – ١٢٥٠ م", startYear: 1127, endYear: 1250 },
  cover: { alt: "غلاف الدولة الزنكية", glyph: "🏴", tone: "from-rose-900/40 to-stone-900" },
  entities,
};