// Shared Irth brand tokens for auth emails (Arabic RTL, navy + gold).
// Body bg stays #ffffff per email client best-practice; the inner card is navy.

export const BRAND = {
  navy: '#0b1424',
  navyDeep: '#070e1c',
  navyLine: '#1a2740',
  gold: '#d4af37',
  goldSoft: '#e8c66a',
  parchment: '#f6efe1',
  textOnNavy: '#f6efe1',
  textMuted: '#a8b3c7',
  siteUrl: 'https://irth-develop.lovable.app',
  logoUrl: 'https://irth-develop.lovable.app/irth-icon.png',
  brandName: 'إرث',
  brandNameLatin: 'Irth',
}

export const styles = {
  main: {
    backgroundColor: '#ffffff',
    fontFamily:
      "'IBM Plex Sans Arabic','Cairo','Segoe UI',Tahoma,Arial,sans-serif",
    margin: 0,
    padding: '24px 12px',
  } as const,
  card: {
    backgroundColor: BRAND.navy,
    borderRadius: '16px',
    padding: '36px 28px',
    maxWidth: '560px',
    margin: '0 auto',
    border: `1px solid ${BRAND.navyLine}`,
    direction: 'rtl' as const,
    textAlign: 'right' as const,
  },
  header: {
    textAlign: 'center' as const,
    paddingBottom: '20px',
    borderBottom: `1px solid ${BRAND.navyLine}`,
    marginBottom: '24px',
  },
  logo: { width: '64px', height: '64px', margin: '0 auto 12px' },
  brand: {
    color: BRAND.gold,
    fontSize: '22px',
    fontWeight: 700 as const,
    margin: 0,
    letterSpacing: '2px',
  },
  tagline: {
    color: BRAND.textMuted,
    fontSize: '12px',
    margin: '4px 0 0',
    letterSpacing: '1px',
  },
  h1: {
    color: BRAND.goldSoft,
    fontSize: '22px',
    fontWeight: 700 as const,
    margin: '0 0 16px',
    textAlign: 'right' as const,
  },
  text: {
    color: BRAND.textOnNavy,
    fontSize: '15px',
    lineHeight: '1.9',
    margin: '0 0 18px',
    textAlign: 'right' as const,
  },
  button: {
    backgroundColor: BRAND.gold,
    color: BRAND.navyDeep,
    fontSize: '15px',
    fontWeight: 700 as const,
    borderRadius: '10px',
    padding: '14px 28px',
    textDecoration: 'none',
    display: 'inline-block',
  },
  buttonWrap: {
    textAlign: 'center' as const,
    margin: '28px 0',
  },
  fallbackLabel: {
    color: BRAND.textMuted,
    fontSize: '12px',
    margin: '0 0 6px',
    textAlign: 'right' as const,
  },
  fallbackUrl: {
    color: BRAND.goldSoft,
    fontSize: '12px',
    wordBreak: 'break-all' as const,
    backgroundColor: BRAND.navyDeep,
    border: `1px solid ${BRAND.navyLine}`,
    borderRadius: '8px',
    padding: '10px 12px',
    display: 'block',
    textAlign: 'left' as const,
    direction: 'ltr' as const,
    margin: '0 0 24px',
  },
  code: {
    fontFamily: "'Courier New', monospace",
    fontSize: '28px',
    fontWeight: 700 as const,
    color: BRAND.gold,
    letterSpacing: '8px',
    textAlign: 'center' as const,
    backgroundColor: BRAND.navyDeep,
    border: `1px solid ${BRAND.navyLine}`,
    borderRadius: '10px',
    padding: '18px',
    margin: '0 0 24px',
    direction: 'ltr' as const,
  },
  footer: {
    color: BRAND.textMuted,
    fontSize: '11px',
    lineHeight: '1.8',
    margin: '24px 0 0',
    paddingTop: '20px',
    borderTop: `1px solid ${BRAND.navyLine}`,
    textAlign: 'center' as const,
  },
  link: { color: BRAND.goldSoft, textDecoration: 'underline' },
}
