// AUTO-GENERATED by scripts/build-emblem-manifest — do not edit by hand.
// Source: 10 Signature Premium Historical Emblems (Phase 9 / Batch 1).

import type { EmblemSize, EmblemFormat } from "./asset-manifest";

export type PremiumAssetMatrix = Record<EmblemSize, Record<EmblemFormat, string>>;

export const PREMIUM_EMBLEM_ASSETS: Record<string, PremiumAssetMatrix> = {
  "banner_abbasid": {
    "128": {
      "webp": "/__l5e/assets-v1/3c280a38-5f65-420d-9399-a4371905bf67/banner_abbasid_128.webp",
      "avif": "/__l5e/assets-v1/6d615930-9e07-40aa-b543-4e4d1dcaca5f/banner_abbasid_128.avif"
    },
    "256": {
      "webp": "/__l5e/assets-v1/914c729a-0947-4368-b459-2f15448e51ef/banner_abbasid_256.webp",
      "avif": "/__l5e/assets-v1/e367bf40-07e3-42ab-83ce-eba804b78cca/banner_abbasid_256.avif"
    },
    "512": {
      "webp": "/__l5e/assets-v1/2ca8e0f3-38b0-4c85-8884-edfce05ab7fa/banner_abbasid_512.webp",
      "avif": "/__l5e/assets-v1/67123ca0-5e99-4a75-9e5f-3e56d2184571/banner_abbasid_512.avif"
    },
    "1024": {
      "webp": "/__l5e/assets-v1/5466a9cc-92b6-413a-bfcf-bb53ce744d08/banner_abbasid_1024.webp",
      "avif": "/__l5e/assets-v1/b8f6587c-1240-4f95-b724-502fcdab1042/banner_abbasid_1024.avif"
    }
  },
  "banner_umayyad": {
    "128": {
      "webp": "/__l5e/assets-v1/1af91385-dfcb-42a8-af4d-201bc00fa348/banner_umayyad_128.webp",
      "avif": "/__l5e/assets-v1/94a4b372-4f51-4261-8880-e196590b6c1e/banner_umayyad_128.avif"
    },
    "256": {
      "webp": "/__l5e/assets-v1/29742932-4349-4010-b7a0-5ce3dd72bbf1/banner_umayyad_256.webp",
      "avif": "/__l5e/assets-v1/94e906a6-abec-439d-8553-ad5e3aefe3db/banner_umayyad_256.avif"
    },
    "512": {
      "webp": "/__l5e/assets-v1/8ef1f79e-0d79-4b6d-8170-7055f99d5e4a/banner_umayyad_512.webp",
      "avif": "/__l5e/assets-v1/3b3f10f5-1bf7-4620-8f69-fe6bc4ca367b/banner_umayyad_512.avif"
    },
    "1024": {
      "webp": "/__l5e/assets-v1/34e35b54-a819-46ef-9769-90cb828ce93c/banner_umayyad_1024.webp",
      "avif": "/__l5e/assets-v1/1f4fe971-f44b-49a4-b71b-e6185a4588a9/banner_umayyad_1024.avif"
    }
  },
  "banner_rashidun": {
    "128": {
      "webp": "/__l5e/assets-v1/e85de3c1-b503-43d0-931d-e005b1836658/banner_rashidun_128.webp",
      "avif": "/__l5e/assets-v1/dfd04d4e-c5a9-48a1-8347-2a7011b9fe71/banner_rashidun_128.avif"
    },
    "256": {
      "webp": "/__l5e/assets-v1/4b494302-f020-4aa9-aede-9b31ecb8f065/banner_rashidun_256.webp",
      "avif": "/__l5e/assets-v1/b457656c-6727-41cf-b5a0-52db1625b275/banner_rashidun_256.avif"
    },
    "512": {
      "webp": "/__l5e/assets-v1/63602b81-6c53-4675-b93f-8ade6da50f92/banner_rashidun_512.webp",
      "avif": "/__l5e/assets-v1/c55bc7ca-67ce-429b-a44d-af1dbfb58211/banner_rashidun_512.avif"
    },
    "1024": {
      "webp": "/__l5e/assets-v1/351864de-83f8-43db-99c5-221ebf524199/banner_rashidun_1024.webp",
      "avif": "/__l5e/assets-v1/0e0a15bb-0940-4a73-a44c-e8802df2b6e2/banner_rashidun_1024.avif"
    }
  },
  "banner_andalus": {
    "128": {
      "webp": "/__l5e/assets-v1/624380dc-7951-4932-bfb4-dfb0ad164a88/banner_andalus_128.webp",
      "avif": "/__l5e/assets-v1/700bb3a2-9f59-47ec-8ffd-2835f4762dfb/banner_andalus_128.avif"
    },
    "256": {
      "webp": "/__l5e/assets-v1/61803e38-d5dd-4f39-a7e3-8ad4e7356f59/banner_andalus_256.webp",
      "avif": "/__l5e/assets-v1/7d5c2053-da81-4fdf-8ec7-d1bd8c77c61a/banner_andalus_256.avif"
    },
    "512": {
      "webp": "/__l5e/assets-v1/a86261ea-0532-45c2-b0e5-df2a6c91dea9/banner_andalus_512.webp",
      "avif": "/__l5e/assets-v1/2146e912-c426-4695-b66d-9f4cabfe8b4a/banner_andalus_512.avif"
    },
    "1024": {
      "webp": "/__l5e/assets-v1/9702411f-3761-46bd-ab56-1bab81c12f47/banner_andalus_1024.webp",
      "avif": "/__l5e/assets-v1/efd799dd-e567-4d3d-8299-affd666d3acb/banner_andalus_1024.avif"
    }
  },
  "banner_ottoman": {
    "128": {
      "webp": "/__l5e/assets-v1/a754d2cf-6765-4c44-8b66-79a18b24db97/banner_ottoman_128.webp",
      "avif": "/__l5e/assets-v1/e2c00c4e-ca09-4eca-a93a-faac144d1692/banner_ottoman_128.avif"
    },
    "256": {
      "webp": "/__l5e/assets-v1/1f470720-05a3-4c27-8e58-f35c6bbd1b13/banner_ottoman_256.webp",
      "avif": "/__l5e/assets-v1/77d2162b-601b-46d2-9d7e-64b4ff054eaa/banner_ottoman_256.avif"
    },
    "512": {
      "webp": "/__l5e/assets-v1/56ebaf76-63ad-4a14-b3a5-a082b6438e90/banner_ottoman_512.webp",
      "avif": "/__l5e/assets-v1/acc3883b-18bf-4965-9587-62142a7bcdaf/banner_ottoman_512.avif"
    },
    "1024": {
      "webp": "/__l5e/assets-v1/678f03df-abc2-4fc1-9b11-c7e4ec52082c/banner_ottoman_1024.webp",
      "avif": "/__l5e/assets-v1/0db6f635-69a0-4718-8e2c-bfea9329968c/banner_ottoman_1024.avif"
    }
  },
  "sword": {
    "128": {
      "webp": "/__l5e/assets-v1/da872a93-c564-4ebd-ae11-723fe232a659/sword_128.webp",
      "avif": "/__l5e/assets-v1/5e15c0a8-9f1f-4049-973e-571746a1b72c/sword_128.avif"
    },
    "256": {
      "webp": "/__l5e/assets-v1/788d0df8-5c46-4351-8cb4-8b9192712d3f/sword_256.webp",
      "avif": "/__l5e/assets-v1/a9283687-801b-40f3-8b52-6bfcc37b51b5/sword_256.avif"
    },
    "512": {
      "webp": "/__l5e/assets-v1/9de9e58d-3182-408b-b257-cf2ca6757b6f/sword_512.webp",
      "avif": "/__l5e/assets-v1/7d42cd44-060a-42cc-b93d-293da667270b/sword_512.avif"
    },
    "1024": {
      "webp": "/__l5e/assets-v1/fef4aace-2329-4f19-aad7-5d8cc57dd944/sword_1024.webp",
      "avif": "/__l5e/assets-v1/8f54feae-38ce-4092-b8c1-66f1dfe10740/sword_1024.avif"
    }
  },
  "shield": {
    "128": {
      "webp": "/__l5e/assets-v1/3ba41754-8bc9-4582-9a1a-2aee4c457e5a/shield_128.webp",
      "avif": "/__l5e/assets-v1/17fa46a3-332f-4dc5-a784-ee7a9638b950/shield_128.avif"
    },
    "256": {
      "webp": "/__l5e/assets-v1/e1eefc90-e9a6-44bd-83dc-aebb2122dcac/shield_256.webp",
      "avif": "/__l5e/assets-v1/8fcf5fc2-5492-4159-aabb-629657787e6b/shield_256.avif"
    },
    "512": {
      "webp": "/__l5e/assets-v1/31e53a81-d124-4c08-a4f5-a1cf90caf738/shield_512.webp",
      "avif": "/__l5e/assets-v1/42d0e247-239d-4113-b1c1-d646ea81d69e/shield_512.avif"
    },
    "1024": {
      "webp": "/__l5e/assets-v1/4fb1b677-38e9-4fa9-8dbd-c30e7c789b52/shield_1024.webp",
      "avif": "/__l5e/assets-v1/b8ba16c0-952b-4f3a-bef0-d6dc272da152/shield_1024.avif"
    }
  },
  "book": {
    "128": {
      "webp": "/__l5e/assets-v1/08546f3e-fcb9-4651-b45b-f4aed7a06414/book_128.webp",
      "avif": "/__l5e/assets-v1/2b8624e7-f046-4990-9262-7c2cf42180ba/book_128.avif"
    },
    "256": {
      "webp": "/__l5e/assets-v1/d6910985-256c-47a1-a4ba-dc76b398cd22/book_256.webp",
      "avif": "/__l5e/assets-v1/27a2ed37-b416-4a27-8824-3c03fc0fad6e/book_256.avif"
    },
    "512": {
      "webp": "/__l5e/assets-v1/8ee1f9d1-a4e6-4d82-a2b7-e293431a4239/book_512.webp",
      "avif": "/__l5e/assets-v1/34a38836-6d5d-4a2b-b005-7e57fb141095/book_512.avif"
    },
    "1024": {
      "webp": "/__l5e/assets-v1/f03bd66a-137b-423e-b0b0-64d1a2d483f0/book_1024.webp",
      "avif": "/__l5e/assets-v1/95b3cdf8-fb99-459f-a5af-021b7b6abad6/book_1024.avif"
    }
  },
  "scholar": {
    "128": {
      "webp": "/__l5e/assets-v1/8da1409b-10d2-44d0-aa25-6d96e2b1c35e/scholar_128.webp",
      "avif": "/__l5e/assets-v1/7eea19a4-7a01-41dc-96b6-25bbee64774c/scholar_128.avif"
    },
    "256": {
      "webp": "/__l5e/assets-v1/bc815d0f-a74e-47cd-bb79-60046b4d9ebe/scholar_256.webp",
      "avif": "/__l5e/assets-v1/70110ef5-6083-4905-813f-70895fc9facc/scholar_256.avif"
    },
    "512": {
      "webp": "/__l5e/assets-v1/22d28b0d-bd16-440e-a540-abb2e4fc5a27/scholar_512.webp",
      "avif": "/__l5e/assets-v1/f53151d4-4117-4a71-a1d6-401bd0457529/scholar_512.avif"
    },
    "1024": {
      "webp": "/__l5e/assets-v1/4c003b8d-01b2-4bb0-9a9d-e7f2d420e435/scholar_1024.webp",
      "avif": "/__l5e/assets-v1/29935824-7589-44c7-97a1-6858664c344e/scholar_1024.avif"
    }
  },
  "star": {
    "128": {
      "webp": "/__l5e/assets-v1/c338bfb4-2a40-464a-b01f-9e90924de16f/star_128.webp",
      "avif": "/__l5e/assets-v1/eba86117-7906-4a9d-8651-38d715cdd3f3/star_128.avif"
    },
    "256": {
      "webp": "/__l5e/assets-v1/ab09d634-956e-470e-91e1-29fac93250c5/star_256.webp",
      "avif": "/__l5e/assets-v1/3e93b976-fda9-45ef-9e8f-61f1fd02da2e/star_256.avif"
    },
    "512": {
      "webp": "/__l5e/assets-v1/c3630e0a-4501-4dc5-8940-91a781d462bd/star_512.webp",
      "avif": "/__l5e/assets-v1/ae12f319-ecd2-454f-adf6-f6401c563825/star_512.avif"
    },
    "1024": {
      "webp": "/__l5e/assets-v1/6d03dc5e-e527-4865-b89a-4e0655a99acc/star_1024.webp",
      "avif": "/__l5e/assets-v1/c2480cbe-1b60-4329-9e11-b67574cc461f/star_1024.avif"
    }
  }
};
