// ============================================================
// Cinematic Opening — Bundled Config
// ------------------------------------------------------------
// Static, typed configuration. Bundled into the app — never
// fetched at runtime. Every image + audio URL points at a
// locally-bundled asset under `public/cinematic/` or
// `public/assets/splash/`.
//
// Update this file to change the opening; do not read the
// legacy JSON at `/data/cinematic-opening.json` — kept only
// for reference and no longer consumed by the engine.
// ============================================================

import type { CinematicOpeningConfig } from "./types";

/** Local, bundled logo used by the final scene's overlay layer. */
export const CINEMATIC_LOGO_URL = "/assets/splash/irth-logo.png";

const GOLD_HIGHLIGHT = true;

export const CINEMATIC_OPENING_DATA: CinematicOpeningConfig = {
  version: "irth.cinematic-opening.2026-07-19",
  replayForAllUsers: false,
  soundtrack: {
    url: "/cinematic/cinematic-ambience.m4a",
    defaultLevel: 0.42,
  },
  scenes: [
    {
      id: "scene-1-mount-al-nour",
      image: "/cinematic/scene1-mount-al-nour.webp",
      contextLabel: "جبل النور — نحو 610م",
      title: "قبل أكثر من أربعة عشر قرنًا...",
      titleSegments: [
        { text: "قبل أكثر من " },
        { text: "أربعة عشر قرنًا", highlight: GOLD_HIGHLIGHT },
        { text: "..." },
      ],
      durationMs: 6000,
      textDelayMs: 900,
      textHoldMs: 4200,
      transitionIn: "fade-from-black",
      transitionOut: "crossfade",
      particles: "dust",
      particleIntensity: 0.25,
      overlayDarkness: 0.15,
      kenBurns: true,
      soundtrackLevel: 0.32,
    },
    {
      id: "scene-2-cave-hira",
      image: "/cinematic/scene2-cave-hira.webp",
      contextLabel: "غار حراء — نحو 610م",
      title: "هنا...",
      subtitle: "بدأت أعظم قصة غيّرت وجه العالم.",
      subtitleSegments: [
        { text: "بدأت " },
        { text: "أعظم قصة", highlight: GOLD_HIGHLIGHT },
        { text: " غيّرت " },
        { text: "وجه العالم", highlight: GOLD_HIGHLIGHT },
        { text: "." },
      ],
      durationMs: 6000,
      textDelayMs: 900,
      subtitleDelayMs: 900,
      textHoldMs: 4000,
      transitionIn: "crossfade",
      transitionOut: "crossfade",
      particles: "dust",
      particleIntensity: 0.3,
      overlayDarkness: 0.1,
      kenBurns: true,
      soundtrackLevel: 0.42,
    },
    {
      id: "scene-3-1-medina",
      image: "/cinematic/scene3-1-medina.webp",
      contextLabel: "المدينة المنورة — 622م",
      title: "من الإيمان...",
      titleSegments: [
        { text: "من " },
        { text: "الإيمان", highlight: GOLD_HIGHLIGHT },
        { text: "..." },
      ],
      durationMs: 4500,
      textDelayMs: 700,
      textHoldMs: 2900,
      transitionIn: "crossfade",
      transitionOut: "crossfade",
      particles: "dust",
      particleIntensity: 0.3,
      overlayDarkness: 0.05,
      kenBurns: true,
      soundtrackLevel: 0.52,
    },
    {
      id: "scene-3-2-qadisiyyah",
      image: "/cinematic/scene3-2-qadisiyyah.webp",
      contextLabel: "القادسية — 636م",
      title: "وُلد العزم.",
      titleSegments: [
        { text: "وُلد " },
        { text: "العزم", highlight: GOLD_HIGHLIGHT },
        { text: "." },
      ],
      durationMs: 4500,
      textDelayMs: 700,
      textHoldMs: 2900,
      transitionIn: "crossfade",
      transitionOut: "crossfade",
      particles: "smoke",
      particleIntensity: 0.35,
      overlayDarkness: 0.1,
      kenBurns: true,
      soundtrackLevel: 0.66,
    },
    {
      id: "scene-3-3-baghdad-cordoba",
      image: "/cinematic/scene3-3-baghdad-cordoba.webp",
      contextLabel: "بغداد وقرطبة — القرنان 9–10م",
      title: "وازدهر العلم.",
      titleSegments: [
        { text: "وازدهر " },
        { text: "العلم", highlight: GOLD_HIGHLIGHT },
        { text: "." },
      ],
      durationMs: 4500,
      textDelayMs: 700,
      textHoldMs: 2900,
      transitionIn: "crossfade",
      transitionOut: "crossfade",
      particles: "gold",
      particleIntensity: 0.3,
      overlayDarkness: 0.05,
      kenBurns: true,
      soundtrackLevel: 0.78,
    },
    {
      id: "scene-3-4-constantinople",
      image: "/cinematic/scene3-4-constantinople.webp",
      contextLabel: "القسطنطينية — 1453م",
      title: "وامتد الأثر.",
      titleSegments: [
        { text: "وامتد " },
        { text: "الأثر", highlight: GOLD_HIGHLIGHT },
        { text: "." },
      ],
      durationMs: 4500,
      textDelayMs: 700,
      textHoldMs: 2900,
      transitionIn: "crossfade",
      transitionOut: "crossfade",
      particles: "fog",
      particleIntensity: 0.35,
      overlayDarkness: 0.1,
      kenBurns: true,
      soundtrackLevel: 0.88,
    },
    {
      id: "scene-4-1-abdul-hamid",
      image: "/cinematic/scene4-1-abdul-hamid.webp",
      contextLabel: "أواخر القرن ١٩م",
      title: "ثم...",
      durationMs: 5500,
      textDelayMs: 900,
      textHoldMs: 3700,
      transitionIn: "crossfade",
      transitionOut: "crossfade",
      particles: "fog",
      particleIntensity: 0.3,
      overlayDarkness: 0.15,
      kenBurns: true,
      soundtrackLevel: 0.58,
    },
    {
      id: "scene-4-2-partition-map",
      image: "/cinematic/scene4-2-partition-map.webp",
      contextLabel: "تقسيم الشرق — ١٩١٦م",
      title: "تفرّقت صفحات الحكاية.",
      titleSegments: [
        { text: "تفرّقت " },
        { text: "صفحات الحكاية", highlight: GOLD_HIGHLIGHT },
        { text: "." },
      ],
      durationMs: 5500,
      textDelayMs: 900,
      textHoldMs: 3700,
      transitionIn: "crossfade",
      transitionOut: "crossfade",
      particles: "dust",
      particleIntensity: 0.25,
      overlayDarkness: 0.15,
      kenBurns: true,
      soundtrackLevel: 0.38,
    },
    {
      id: "scene-5-journey",
      image: "/cinematic/scene5-journey.webp",
      contextLabel: "رحلة إرث",
      title: "لكن الحكاية لم تنتهِ.",
      titleSegments: [
        { text: "لكن " },
        { text: "الحكاية", highlight: GOLD_HIGHLIGHT },
        { text: " لم تنتهِ." },
      ],
      subtitle: "ما زالت تنتظر من يكتشفها.",
      subtitleSegments: [
        { text: "ما زالت تنتظر من " },
        { text: "يكتشفها", highlight: GOLD_HIGHLIGHT },
        { text: "." },
      ],
      durationMs: 6500,
      textDelayMs: 900,
      subtitleDelayMs: 1100,
      textHoldMs: 4500,
      transitionIn: "crossfade",
      transitionOut: "crossfade",
      particles: "gold",
      particleIntensity: 0.4,
      overlayDarkness: 0.05,
      kenBurns: true,
      soundtrackLevel: 0.76,
    },
    {
      id: "scene-6-final-logo",
      image: "/cinematic/scene6-final-logo-bg.webp",
      durationMs: 5000,
      transitionIn: "crossfade",
      transitionOut: "fade-to-black",
      particles: "gold",
      particleIntensity: 0.25,
      overlayDarkness: 0.1,
      kenBurns: false,
      showFinalLogo: true,
      soundtrackLevel: 0.48,
    },
  ],
};
