/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ShareCardRouteImport } from './routes/share-card'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SeasonsRouteImport } from './routes/seasons'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnThisDayRouteImport } from './routes/on-this-day'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MapRouteImport } from './routes/map'
import { Route as InvestigationsRouteImport } from './routes/investigations'
import { Route as HistoryCalendarRouteImport } from './routes/history-calendar'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as EncyclopediaRouteImport } from './routes/encyclopedia'
import { Route as ContentAuditRouteImport } from './routes/content-audit'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorldsIndexRouteImport } from './routes/worlds.index'
import { Route as EncyclopediaIndexRouteImport } from './routes/encyclopedia.index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WorldsSlugRouteImport } from './routes/worlds.$slug'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as StoryIdRouteImport } from './routes/story.$id'
import { Route as PlayTimelineRouteImport } from './routes/play.timeline'
import { Route as PlayInvestigateRouteImport } from './routes/play.investigate'
import { Route as PlayDecisionsRouteImport } from './routes/play.decisions'
import { Route as PlayChapterRouteImport } from './routes/play.chapter'
import { Route as InvestigationIdRouteImport } from './routes/investigation.$id'
import { Route as FigureIdRouteImport } from './routes/figure.$id'
import { Route as CompareIdRouteImport } from './routes/compare.$id'
import { Route as CityIdRouteImport } from './routes/city.$id'
import { Route as BattleIdRouteImport } from './routes/battle.$id'
import { Route as AdminWorldMembershipReviewRouteImport } from './routes/admin.world-membership-review'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminOfflineRouteImport } from './routes/admin.offline'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMuseumProvenanceRouteImport } from './routes/admin.museum-provenance'
import { Route as AdminMigrationRouteImport } from './routes/admin.migration'
import { Route as AdminMapRouteImport } from './routes/admin.map'
import { Route as AdminInvestigationsRouteImport } from './routes/admin.investigations'
import { Route as AdminImportRouteImport } from './routes/admin.import'
import { Route as AdminHubBuilderRouteImport } from './routes/admin.hub-builder'
import { Route as AdminHistoricalHubsAuditRouteImport } from './routes/admin.historical-hubs-audit'
import { Route as AdminGamesRouteImport } from './routes/admin.games'
import { Route as AdminExplorationPathRepairRouteImport } from './routes/admin.exploration-path-repair'
import { Route as AdminEraNormalizationRouteImport } from './routes/admin.era-normalization'
import { Route as AdminEncyclopediaAuditRouteImport } from './routes/admin.encyclopedia-audit'
import { Route as AdminEncyclopediaRouteImport } from './routes/admin.encyclopedia'
import { Route as AdminCrossHubLinksRouteImport } from './routes/admin.cross-hub-links'
import { Route as AdminContentInventoryRouteImport } from './routes/admin.content-inventory'
import { Route as AdminContentIntegrityRepairRouteImport } from './routes/admin.content-integrity-repair'
import { Route as AdminContentIntegrityRouteImport } from './routes/admin.content-integrity'
import { Route as AdminContentFoundationRouteImport } from './routes/admin.content-foundation'
import { Route as AdminContentCleanupRouteImport } from './routes/admin.content-cleanup'
import { Route as AdminContentAutoHealRouteImport } from './routes/admin.content-auto-heal'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminCanonicalDuplicatesRouteImport } from './routes/admin.canonical-duplicates'
import { Route as AdminCampaignsRouteImport } from './routes/admin.campaigns'
import { Route as AdminCampaignRelationshipsRouteImport } from './routes/admin.campaign-relationships'
import { Route as AdminAtlasReviewRouteImport } from './routes/admin.atlas-review'
import { Route as AdminAtlasRepairRouteImport } from './routes/admin.atlas-repair'
import { Route as AdminAtlasImportRouteImport } from './routes/admin.atlas-import'
import { Route as AdminAtlasEntitiesRouteImport } from './routes/admin.atlas-entities'
import { Route as AdminAtlasCalibrationRouteImport } from './routes/admin.atlas-calibration'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminGamesIndexRouteImport } from './routes/admin.games.index'
import { Route as EncyclopediaTypeTypeRouteImport } from './routes/encyclopedia.type.$type'
import { Route as EncyclopediaStateIdRouteImport } from './routes/encyclopedia.state.$id'
import { Route as EncyclopediaPathIdRouteImport } from './routes/encyclopedia.path.$id'
import { Route as EncyclopediaEntityIdRouteImport } from './routes/encyclopedia.entity.$id'
import { Route as AdminGamesModeRouteImport } from './routes/admin.games.$mode'
import { Route as CampaignsImportedIdIndexRouteImport } from './routes/campaigns.imported.$id.index'
import { Route as CampaignsImportedIdChapterChapterRouteImport } from './routes/campaigns.imported.$id.chapter.$chapter'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareCardRoute = ShareCardRouteImport.update({
  id: '/share-card',
  path: '/share-card',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonsRoute = SeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnThisDayRoute = OnThisDayRouteImport.update({
  id: '/on-this-day',
  path: '/on-this-day',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsRoute = InvestigationsRouteImport.update({
  id: '/investigations',
  path: '/investigations',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryCalendarRoute = HistoryCalendarRouteImport.update({
  id: '/history-calendar',
  path: '/history-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const EncyclopediaRoute = EncyclopediaRouteImport.update({
  id: '/encyclopedia',
  path: '/encyclopedia',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentAuditRoute = ContentAuditRouteImport.update({
  id: '/content-audit',
  path: '/content-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldsIndexRoute = WorldsIndexRouteImport.update({
  id: '/worlds/',
  path: '/worlds/',
  getParentRoute: () => rootRouteImport,
} as any)
const EncyclopediaIndexRoute = EncyclopediaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EncyclopediaRoute,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldsSlugRoute = WorldsSlugRouteImport.update({
  id: '/worlds/$slug',
  path: '/worlds/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryIdRoute = StoryIdRouteImport.update({
  id: '/story/$id',
  path: '/story/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayTimelineRoute = PlayTimelineRouteImport.update({
  id: '/play/timeline',
  path: '/play/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayInvestigateRoute = PlayInvestigateRouteImport.update({
  id: '/play/investigate',
  path: '/play/investigate',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayDecisionsRoute = PlayDecisionsRouteImport.update({
  id: '/play/decisions',
  path: '/play/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayChapterRoute = PlayChapterRouteImport.update({
  id: '/play/chapter',
  path: '/play/chapter',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationIdRoute = InvestigationIdRouteImport.update({
  id: '/investigation/$id',
  path: '/investigation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FigureIdRoute = FigureIdRouteImport.update({
  id: '/figure/$id',
  path: '/figure/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIdRoute = CompareIdRouteImport.update({
  id: '/compare/$id',
  path: '/compare/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CityIdRoute = CityIdRouteImport.update({
  id: '/city/$id',
  path: '/city/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleIdRoute = BattleIdRouteImport.update({
  id: '/battle/$id',
  path: '/battle/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorldMembershipReviewRoute =
  AdminWorldMembershipReviewRouteImport.update({
    id: '/admin/world-membership-review',
    path: '/admin/world-membership-review',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOfflineRoute = AdminOfflineRouteImport.update({
  id: '/admin/offline',
  path: '/admin/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMuseumProvenanceRoute = AdminMuseumProvenanceRouteImport.update({
  id: '/admin/museum-provenance',
  path: '/admin/museum-provenance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMigrationRoute = AdminMigrationRouteImport.update({
  id: '/admin/migration',
  path: '/admin/migration',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMapRoute = AdminMapRouteImport.update({
  id: '/admin/map',
  path: '/admin/map',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInvestigationsRoute = AdminInvestigationsRouteImport.update({
  id: '/admin/investigations',
  path: '/admin/investigations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/admin/import',
  path: '/admin/import',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHubBuilderRoute = AdminHubBuilderRouteImport.update({
  id: '/admin/hub-builder',
  path: '/admin/hub-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHistoricalHubsAuditRoute =
  AdminHistoricalHubsAuditRouteImport.update({
    id: '/admin/historical-hubs-audit',
    path: '/admin/historical-hubs-audit',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminGamesRoute = AdminGamesRouteImport.update({
  id: '/admin/games',
  path: '/admin/games',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExplorationPathRepairRoute =
  AdminExplorationPathRepairRouteImport.update({
    id: '/admin/exploration-path-repair',
    path: '/admin/exploration-path-repair',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminEraNormalizationRoute = AdminEraNormalizationRouteImport.update({
  id: '/admin/era-normalization',
  path: '/admin/era-normalization',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEncyclopediaAuditRoute = AdminEncyclopediaAuditRouteImport.update({
  id: '/admin/encyclopedia-audit',
  path: '/admin/encyclopedia-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEncyclopediaRoute = AdminEncyclopediaRouteImport.update({
  id: '/admin/encyclopedia',
  path: '/admin/encyclopedia',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrossHubLinksRoute = AdminCrossHubLinksRouteImport.update({
  id: '/admin/cross-hub-links',
  path: '/admin/cross-hub-links',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentInventoryRoute = AdminContentInventoryRouteImport.update({
  id: '/admin/content-inventory',
  path: '/admin/content-inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentIntegrityRepairRoute =
  AdminContentIntegrityRepairRouteImport.update({
    id: '/admin/content-integrity-repair',
    path: '/admin/content-integrity-repair',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminContentIntegrityRoute = AdminContentIntegrityRouteImport.update({
  id: '/admin/content-integrity',
  path: '/admin/content-integrity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentFoundationRoute = AdminContentFoundationRouteImport.update({
  id: '/admin/content-foundation',
  path: '/admin/content-foundation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentCleanupRoute = AdminContentCleanupRouteImport.update({
  id: '/admin/content-cleanup',
  path: '/admin/content-cleanup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentAutoHealRoute = AdminContentAutoHealRouteImport.update({
  id: '/admin/content-auto-heal',
  path: '/admin/content-auto-heal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCanonicalDuplicatesRoute =
  AdminCanonicalDuplicatesRouteImport.update({
    id: '/admin/canonical-duplicates',
    path: '/admin/canonical-duplicates',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/admin/campaigns',
  path: '/admin/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCampaignRelationshipsRoute =
  AdminCampaignRelationshipsRouteImport.update({
    id: '/admin/campaign-relationships',
    path: '/admin/campaign-relationships',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAtlasReviewRoute = AdminAtlasReviewRouteImport.update({
  id: '/admin/atlas-review',
  path: '/admin/atlas-review',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAtlasRepairRoute = AdminAtlasRepairRouteImport.update({
  id: '/admin/atlas-repair',
  path: '/admin/atlas-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAtlasImportRoute = AdminAtlasImportRouteImport.update({
  id: '/admin/atlas-import',
  path: '/admin/atlas-import',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAtlasEntitiesRoute = AdminAtlasEntitiesRouteImport.update({
  id: '/admin/atlas-entities',
  path: '/admin/atlas-entities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAtlasCalibrationRoute = AdminAtlasCalibrationRouteImport.update({
  id: '/admin/atlas-calibration',
  path: '/admin/atlas-calibration',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGamesIndexRoute = AdminGamesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminGamesRoute,
} as any)
const EncyclopediaTypeTypeRoute = EncyclopediaTypeTypeRouteImport.update({
  id: '/type/$type',
  path: '/type/$type',
  getParentRoute: () => EncyclopediaRoute,
} as any)
const EncyclopediaStateIdRoute = EncyclopediaStateIdRouteImport.update({
  id: '/state/$id',
  path: '/state/$id',
  getParentRoute: () => EncyclopediaRoute,
} as any)
const EncyclopediaPathIdRoute = EncyclopediaPathIdRouteImport.update({
  id: '/path/$id',
  path: '/path/$id',
  getParentRoute: () => EncyclopediaRoute,
} as any)
const EncyclopediaEntityIdRoute = EncyclopediaEntityIdRouteImport.update({
  id: '/entity/$id',
  path: '/entity/$id',
  getParentRoute: () => EncyclopediaRoute,
} as any)
const AdminGamesModeRoute = AdminGamesModeRouteImport.update({
  id: '/$mode',
  path: '/$mode',
  getParentRoute: () => AdminGamesRoute,
} as any)
const CampaignsImportedIdIndexRoute =
  CampaignsImportedIdIndexRouteImport.update({
    id: '/imported/$id/',
    path: '/imported/$id/',
    getParentRoute: () => CampaignsRoute,
  } as any)
const CampaignsImportedIdChapterChapterRoute =
  CampaignsImportedIdChapterChapterRouteImport.update({
    id: '/imported/$id/chapter/$chapter',
    path: '/imported/$id/chapter/$chapter',
    getParentRoute: () => CampaignsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/collection': typeof CollectionRoute
  '/content-audit': typeof ContentAuditRoute
  '/encyclopedia': typeof EncyclopediaRouteWithChildren
  '/friends': typeof FriendsRoute
  '/history-calendar': typeof HistoryCalendarRoute
  '/investigations': typeof InvestigationsRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/on-this-day': typeof OnThisDayRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRoute
  '/seasons': typeof SeasonsRoute
  '/security': typeof SecurityRoute
  '/share-card': typeof ShareCardRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/atlas-calibration': typeof AdminAtlasCalibrationRoute
  '/admin/atlas-entities': typeof AdminAtlasEntitiesRoute
  '/admin/atlas-import': typeof AdminAtlasImportRoute
  '/admin/atlas-repair': typeof AdminAtlasRepairRoute
  '/admin/atlas-review': typeof AdminAtlasReviewRoute
  '/admin/campaign-relationships': typeof AdminCampaignRelationshipsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/canonical-duplicates': typeof AdminCanonicalDuplicatesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/content-auto-heal': typeof AdminContentAutoHealRoute
  '/admin/content-cleanup': typeof AdminContentCleanupRoute
  '/admin/content-foundation': typeof AdminContentFoundationRoute
  '/admin/content-integrity': typeof AdminContentIntegrityRoute
  '/admin/content-integrity-repair': typeof AdminContentIntegrityRepairRoute
  '/admin/content-inventory': typeof AdminContentInventoryRoute
  '/admin/cross-hub-links': typeof AdminCrossHubLinksRoute
  '/admin/encyclopedia': typeof AdminEncyclopediaRoute
  '/admin/encyclopedia-audit': typeof AdminEncyclopediaAuditRoute
  '/admin/era-normalization': typeof AdminEraNormalizationRoute
  '/admin/exploration-path-repair': typeof AdminExplorationPathRepairRoute
  '/admin/games': typeof AdminGamesRouteWithChildren
  '/admin/historical-hubs-audit': typeof AdminHistoricalHubsAuditRoute
  '/admin/hub-builder': typeof AdminHubBuilderRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/investigations': typeof AdminInvestigationsRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/migration': typeof AdminMigrationRoute
  '/admin/museum-provenance': typeof AdminMuseumProvenanceRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/offline': typeof AdminOfflineRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/world-membership-review': typeof AdminWorldMembershipReviewRoute
  '/battle/$id': typeof BattleIdRoute
  '/city/$id': typeof CityIdRoute
  '/compare/$id': typeof CompareIdRoute
  '/figure/$id': typeof FigureIdRoute
  '/investigation/$id': typeof InvestigationIdRoute
  '/play/chapter': typeof PlayChapterRoute
  '/play/decisions': typeof PlayDecisionsRoute
  '/play/investigate': typeof PlayInvestigateRoute
  '/play/timeline': typeof PlayTimelineRoute
  '/story/$id': typeof StoryIdRoute
  '/u/$username': typeof UUsernameRoute
  '/worlds/$slug': typeof WorldsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/encyclopedia/': typeof EncyclopediaIndexRoute
  '/worlds/': typeof WorldsIndexRoute
  '/admin/games/$mode': typeof AdminGamesModeRoute
  '/encyclopedia/entity/$id': typeof EncyclopediaEntityIdRoute
  '/encyclopedia/path/$id': typeof EncyclopediaPathIdRoute
  '/encyclopedia/state/$id': typeof EncyclopediaStateIdRoute
  '/encyclopedia/type/$type': typeof EncyclopediaTypeTypeRoute
  '/admin/games/': typeof AdminGamesIndexRoute
  '/campaigns/imported/$id/': typeof CampaignsImportedIdIndexRoute
  '/campaigns/imported/$id/chapter/$chapter': typeof CampaignsImportedIdChapterChapterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/collection': typeof CollectionRoute
  '/content-audit': typeof ContentAuditRoute
  '/friends': typeof FriendsRoute
  '/history-calendar': typeof HistoryCalendarRoute
  '/investigations': typeof InvestigationsRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/on-this-day': typeof OnThisDayRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRoute
  '/seasons': typeof SeasonsRoute
  '/security': typeof SecurityRoute
  '/share-card': typeof ShareCardRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/atlas-calibration': typeof AdminAtlasCalibrationRoute
  '/admin/atlas-entities': typeof AdminAtlasEntitiesRoute
  '/admin/atlas-import': typeof AdminAtlasImportRoute
  '/admin/atlas-repair': typeof AdminAtlasRepairRoute
  '/admin/atlas-review': typeof AdminAtlasReviewRoute
  '/admin/campaign-relationships': typeof AdminCampaignRelationshipsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/canonical-duplicates': typeof AdminCanonicalDuplicatesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/content-auto-heal': typeof AdminContentAutoHealRoute
  '/admin/content-cleanup': typeof AdminContentCleanupRoute
  '/admin/content-foundation': typeof AdminContentFoundationRoute
  '/admin/content-integrity': typeof AdminContentIntegrityRoute
  '/admin/content-integrity-repair': typeof AdminContentIntegrityRepairRoute
  '/admin/content-inventory': typeof AdminContentInventoryRoute
  '/admin/cross-hub-links': typeof AdminCrossHubLinksRoute
  '/admin/encyclopedia': typeof AdminEncyclopediaRoute
  '/admin/encyclopedia-audit': typeof AdminEncyclopediaAuditRoute
  '/admin/era-normalization': typeof AdminEraNormalizationRoute
  '/admin/exploration-path-repair': typeof AdminExplorationPathRepairRoute
  '/admin/historical-hubs-audit': typeof AdminHistoricalHubsAuditRoute
  '/admin/hub-builder': typeof AdminHubBuilderRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/investigations': typeof AdminInvestigationsRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/migration': typeof AdminMigrationRoute
  '/admin/museum-provenance': typeof AdminMuseumProvenanceRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/offline': typeof AdminOfflineRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/world-membership-review': typeof AdminWorldMembershipReviewRoute
  '/battle/$id': typeof BattleIdRoute
  '/city/$id': typeof CityIdRoute
  '/compare/$id': typeof CompareIdRoute
  '/figure/$id': typeof FigureIdRoute
  '/investigation/$id': typeof InvestigationIdRoute
  '/play/chapter': typeof PlayChapterRoute
  '/play/decisions': typeof PlayDecisionsRoute
  '/play/investigate': typeof PlayInvestigateRoute
  '/play/timeline': typeof PlayTimelineRoute
  '/story/$id': typeof StoryIdRoute
  '/u/$username': typeof UUsernameRoute
  '/worlds/$slug': typeof WorldsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/encyclopedia': typeof EncyclopediaIndexRoute
  '/worlds': typeof WorldsIndexRoute
  '/admin/games/$mode': typeof AdminGamesModeRoute
  '/encyclopedia/entity/$id': typeof EncyclopediaEntityIdRoute
  '/encyclopedia/path/$id': typeof EncyclopediaPathIdRoute
  '/encyclopedia/state/$id': typeof EncyclopediaStateIdRoute
  '/encyclopedia/type/$type': typeof EncyclopediaTypeTypeRoute
  '/admin/games': typeof AdminGamesIndexRoute
  '/campaigns/imported/$id': typeof CampaignsImportedIdIndexRoute
  '/campaigns/imported/$id/chapter/$chapter': typeof CampaignsImportedIdChapterChapterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/collection': typeof CollectionRoute
  '/content-audit': typeof ContentAuditRoute
  '/encyclopedia': typeof EncyclopediaRouteWithChildren
  '/friends': typeof FriendsRoute
  '/history-calendar': typeof HistoryCalendarRoute
  '/investigations': typeof InvestigationsRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/on-this-day': typeof OnThisDayRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRoute
  '/seasons': typeof SeasonsRoute
  '/security': typeof SecurityRoute
  '/share-card': typeof ShareCardRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/atlas-calibration': typeof AdminAtlasCalibrationRoute
  '/admin/atlas-entities': typeof AdminAtlasEntitiesRoute
  '/admin/atlas-import': typeof AdminAtlasImportRoute
  '/admin/atlas-repair': typeof AdminAtlasRepairRoute
  '/admin/atlas-review': typeof AdminAtlasReviewRoute
  '/admin/campaign-relationships': typeof AdminCampaignRelationshipsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/canonical-duplicates': typeof AdminCanonicalDuplicatesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/content-auto-heal': typeof AdminContentAutoHealRoute
  '/admin/content-cleanup': typeof AdminContentCleanupRoute
  '/admin/content-foundation': typeof AdminContentFoundationRoute
  '/admin/content-integrity': typeof AdminContentIntegrityRoute
  '/admin/content-integrity-repair': typeof AdminContentIntegrityRepairRoute
  '/admin/content-inventory': typeof AdminContentInventoryRoute
  '/admin/cross-hub-links': typeof AdminCrossHubLinksRoute
  '/admin/encyclopedia': typeof AdminEncyclopediaRoute
  '/admin/encyclopedia-audit': typeof AdminEncyclopediaAuditRoute
  '/admin/era-normalization': typeof AdminEraNormalizationRoute
  '/admin/exploration-path-repair': typeof AdminExplorationPathRepairRoute
  '/admin/games': typeof AdminGamesRouteWithChildren
  '/admin/historical-hubs-audit': typeof AdminHistoricalHubsAuditRoute
  '/admin/hub-builder': typeof AdminHubBuilderRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/investigations': typeof AdminInvestigationsRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/migration': typeof AdminMigrationRoute
  '/admin/museum-provenance': typeof AdminMuseumProvenanceRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/offline': typeof AdminOfflineRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/world-membership-review': typeof AdminWorldMembershipReviewRoute
  '/battle/$id': typeof BattleIdRoute
  '/city/$id': typeof CityIdRoute
  '/compare/$id': typeof CompareIdRoute
  '/figure/$id': typeof FigureIdRoute
  '/investigation/$id': typeof InvestigationIdRoute
  '/play/chapter': typeof PlayChapterRoute
  '/play/decisions': typeof PlayDecisionsRoute
  '/play/investigate': typeof PlayInvestigateRoute
  '/play/timeline': typeof PlayTimelineRoute
  '/story/$id': typeof StoryIdRoute
  '/u/$username': typeof UUsernameRoute
  '/worlds/$slug': typeof WorldsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/encyclopedia/': typeof EncyclopediaIndexRoute
  '/worlds/': typeof WorldsIndexRoute
  '/admin/games/$mode': typeof AdminGamesModeRoute
  '/encyclopedia/entity/$id': typeof EncyclopediaEntityIdRoute
  '/encyclopedia/path/$id': typeof EncyclopediaPathIdRoute
  '/encyclopedia/state/$id': typeof EncyclopediaStateIdRoute
  '/encyclopedia/type/$type': typeof EncyclopediaTypeTypeRoute
  '/admin/games/': typeof AdminGamesIndexRoute
  '/campaigns/imported/$id/': typeof CampaignsImportedIdIndexRoute
  '/campaigns/imported/$id/chapter/$chapter': typeof CampaignsImportedIdChapterChapterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/auth'
    | '/campaigns'
    | '/collection'
    | '/content-audit'
    | '/encyclopedia'
    | '/friends'
    | '/history-calendar'
    | '/investigations'
    | '/map'
    | '/notifications'
    | '/on-this-day'
    | '/privacy'
    | '/profile'
    | '/referrals'
    | '/seasons'
    | '/security'
    | '/share-card'
    | '/terms'
    | '/timeline'
    | '/admin/analytics'
    | '/admin/atlas-calibration'
    | '/admin/atlas-entities'
    | '/admin/atlas-import'
    | '/admin/atlas-repair'
    | '/admin/atlas-review'
    | '/admin/campaign-relationships'
    | '/admin/campaigns'
    | '/admin/canonical-duplicates'
    | '/admin/content'
    | '/admin/content-auto-heal'
    | '/admin/content-cleanup'
    | '/admin/content-foundation'
    | '/admin/content-integrity'
    | '/admin/content-integrity-repair'
    | '/admin/content-inventory'
    | '/admin/cross-hub-links'
    | '/admin/encyclopedia'
    | '/admin/encyclopedia-audit'
    | '/admin/era-normalization'
    | '/admin/exploration-path-repair'
    | '/admin/games'
    | '/admin/historical-hubs-audit'
    | '/admin/hub-builder'
    | '/admin/import'
    | '/admin/investigations'
    | '/admin/map'
    | '/admin/migration'
    | '/admin/museum-provenance'
    | '/admin/notifications'
    | '/admin/offline'
    | '/admin/users'
    | '/admin/world-membership-review'
    | '/battle/$id'
    | '/city/$id'
    | '/compare/$id'
    | '/figure/$id'
    | '/investigation/$id'
    | '/play/chapter'
    | '/play/decisions'
    | '/play/investigate'
    | '/play/timeline'
    | '/story/$id'
    | '/u/$username'
    | '/worlds/$slug'
    | '/admin/'
    | '/campaigns/'
    | '/encyclopedia/'
    | '/worlds/'
    | '/admin/games/$mode'
    | '/encyclopedia/entity/$id'
    | '/encyclopedia/path/$id'
    | '/encyclopedia/state/$id'
    | '/encyclopedia/type/$type'
    | '/admin/games/'
    | '/campaigns/imported/$id/'
    | '/campaigns/imported/$id/chapter/$chapter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/auth'
    | '/collection'
    | '/content-audit'
    | '/friends'
    | '/history-calendar'
    | '/investigations'
    | '/map'
    | '/notifications'
    | '/on-this-day'
    | '/privacy'
    | '/profile'
    | '/referrals'
    | '/seasons'
    | '/security'
    | '/share-card'
    | '/terms'
    | '/timeline'
    | '/admin/analytics'
    | '/admin/atlas-calibration'
    | '/admin/atlas-entities'
    | '/admin/atlas-import'
    | '/admin/atlas-repair'
    | '/admin/atlas-review'
    | '/admin/campaign-relationships'
    | '/admin/campaigns'
    | '/admin/canonical-duplicates'
    | '/admin/content'
    | '/admin/content-auto-heal'
    | '/admin/content-cleanup'
    | '/admin/content-foundation'
    | '/admin/content-integrity'
    | '/admin/content-integrity-repair'
    | '/admin/content-inventory'
    | '/admin/cross-hub-links'
    | '/admin/encyclopedia'
    | '/admin/encyclopedia-audit'
    | '/admin/era-normalization'
    | '/admin/exploration-path-repair'
    | '/admin/historical-hubs-audit'
    | '/admin/hub-builder'
    | '/admin/import'
    | '/admin/investigations'
    | '/admin/map'
    | '/admin/migration'
    | '/admin/museum-provenance'
    | '/admin/notifications'
    | '/admin/offline'
    | '/admin/users'
    | '/admin/world-membership-review'
    | '/battle/$id'
    | '/city/$id'
    | '/compare/$id'
    | '/figure/$id'
    | '/investigation/$id'
    | '/play/chapter'
    | '/play/decisions'
    | '/play/investigate'
    | '/play/timeline'
    | '/story/$id'
    | '/u/$username'
    | '/worlds/$slug'
    | '/admin'
    | '/campaigns'
    | '/encyclopedia'
    | '/worlds'
    | '/admin/games/$mode'
    | '/encyclopedia/entity/$id'
    | '/encyclopedia/path/$id'
    | '/encyclopedia/state/$id'
    | '/encyclopedia/type/$type'
    | '/admin/games'
    | '/campaigns/imported/$id'
    | '/campaigns/imported/$id/chapter/$chapter'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/achievements'
    | '/auth'
    | '/campaigns'
    | '/collection'
    | '/content-audit'
    | '/encyclopedia'
    | '/friends'
    | '/history-calendar'
    | '/investigations'
    | '/map'
    | '/notifications'
    | '/on-this-day'
    | '/privacy'
    | '/profile'
    | '/referrals'
    | '/seasons'
    | '/security'
    | '/share-card'
    | '/terms'
    | '/timeline'
    | '/admin/analytics'
    | '/admin/atlas-calibration'
    | '/admin/atlas-entities'
    | '/admin/atlas-import'
    | '/admin/atlas-repair'
    | '/admin/atlas-review'
    | '/admin/campaign-relationships'
    | '/admin/campaigns'
    | '/admin/canonical-duplicates'
    | '/admin/content'
    | '/admin/content-auto-heal'
    | '/admin/content-cleanup'
    | '/admin/content-foundation'
    | '/admin/content-integrity'
    | '/admin/content-integrity-repair'
    | '/admin/content-inventory'
    | '/admin/cross-hub-links'
    | '/admin/encyclopedia'
    | '/admin/encyclopedia-audit'
    | '/admin/era-normalization'
    | '/admin/exploration-path-repair'
    | '/admin/games'
    | '/admin/historical-hubs-audit'
    | '/admin/hub-builder'
    | '/admin/import'
    | '/admin/investigations'
    | '/admin/map'
    | '/admin/migration'
    | '/admin/museum-provenance'
    | '/admin/notifications'
    | '/admin/offline'
    | '/admin/users'
    | '/admin/world-membership-review'
    | '/battle/$id'
    | '/city/$id'
    | '/compare/$id'
    | '/figure/$id'
    | '/investigation/$id'
    | '/play/chapter'
    | '/play/decisions'
    | '/play/investigate'
    | '/play/timeline'
    | '/story/$id'
    | '/u/$username'
    | '/worlds/$slug'
    | '/admin/'
    | '/campaigns/'
    | '/encyclopedia/'
    | '/worlds/'
    | '/admin/games/$mode'
    | '/encyclopedia/entity/$id'
    | '/encyclopedia/path/$id'
    | '/encyclopedia/state/$id'
    | '/encyclopedia/type/$type'
    | '/admin/games/'
    | '/campaigns/imported/$id/'
    | '/campaigns/imported/$id/chapter/$chapter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  AuthRoute: typeof AuthRoute
  CampaignsRoute: typeof CampaignsRouteWithChildren
  CollectionRoute: typeof CollectionRoute
  ContentAuditRoute: typeof ContentAuditRoute
  EncyclopediaRoute: typeof EncyclopediaRouteWithChildren
  FriendsRoute: typeof FriendsRoute
  HistoryCalendarRoute: typeof HistoryCalendarRoute
  InvestigationsRoute: typeof InvestigationsRoute
  MapRoute: typeof MapRoute
  NotificationsRoute: typeof NotificationsRoute
  OnThisDayRoute: typeof OnThisDayRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ReferralsRoute: typeof ReferralsRoute
  SeasonsRoute: typeof SeasonsRoute
  SecurityRoute: typeof SecurityRoute
  ShareCardRoute: typeof ShareCardRoute
  TermsRoute: typeof TermsRoute
  TimelineRoute: typeof TimelineRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAtlasCalibrationRoute: typeof AdminAtlasCalibrationRoute
  AdminAtlasEntitiesRoute: typeof AdminAtlasEntitiesRoute
  AdminAtlasImportRoute: typeof AdminAtlasImportRoute
  AdminAtlasRepairRoute: typeof AdminAtlasRepairRoute
  AdminAtlasReviewRoute: typeof AdminAtlasReviewRoute
  AdminCampaignRelationshipsRoute: typeof AdminCampaignRelationshipsRoute
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminCanonicalDuplicatesRoute: typeof AdminCanonicalDuplicatesRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminContentAutoHealRoute: typeof AdminContentAutoHealRoute
  AdminContentCleanupRoute: typeof AdminContentCleanupRoute
  AdminContentFoundationRoute: typeof AdminContentFoundationRoute
  AdminContentIntegrityRoute: typeof AdminContentIntegrityRoute
  AdminContentIntegrityRepairRoute: typeof AdminContentIntegrityRepairRoute
  AdminContentInventoryRoute: typeof AdminContentInventoryRoute
  AdminCrossHubLinksRoute: typeof AdminCrossHubLinksRoute
  AdminEncyclopediaRoute: typeof AdminEncyclopediaRoute
  AdminEncyclopediaAuditRoute: typeof AdminEncyclopediaAuditRoute
  AdminEraNormalizationRoute: typeof AdminEraNormalizationRoute
  AdminExplorationPathRepairRoute: typeof AdminExplorationPathRepairRoute
  AdminGamesRoute: typeof AdminGamesRouteWithChildren
  AdminHistoricalHubsAuditRoute: typeof AdminHistoricalHubsAuditRoute
  AdminHubBuilderRoute: typeof AdminHubBuilderRoute
  AdminImportRoute: typeof AdminImportRoute
  AdminInvestigationsRoute: typeof AdminInvestigationsRoute
  AdminMapRoute: typeof AdminMapRoute
  AdminMigrationRoute: typeof AdminMigrationRoute
  AdminMuseumProvenanceRoute: typeof AdminMuseumProvenanceRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOfflineRoute: typeof AdminOfflineRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWorldMembershipReviewRoute: typeof AdminWorldMembershipReviewRoute
  BattleIdRoute: typeof BattleIdRoute
  CityIdRoute: typeof CityIdRoute
  CompareIdRoute: typeof CompareIdRoute
  FigureIdRoute: typeof FigureIdRoute
  InvestigationIdRoute: typeof InvestigationIdRoute
  PlayChapterRoute: typeof PlayChapterRoute
  PlayDecisionsRoute: typeof PlayDecisionsRoute
  PlayInvestigateRoute: typeof PlayInvestigateRoute
  PlayTimelineRoute: typeof PlayTimelineRoute
  StoryIdRoute: typeof StoryIdRoute
  UUsernameRoute: typeof UUsernameRoute
  WorldsSlugRoute: typeof WorldsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  WorldsIndexRoute: typeof WorldsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share-card': {
      id: '/share-card'
      path: '/share-card'
      fullPath: '/share-card'
      preLoaderRoute: typeof ShareCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasons': {
      id: '/seasons'
      path: '/seasons'
      fullPath: '/seasons'
      preLoaderRoute: typeof SeasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/on-this-day': {
      id: '/on-this-day'
      path: '/on-this-day'
      fullPath: '/on-this-day'
      preLoaderRoute: typeof OnThisDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations': {
      id: '/investigations'
      path: '/investigations'
      fullPath: '/investigations'
      preLoaderRoute: typeof InvestigationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history-calendar': {
      id: '/history-calendar'
      path: '/history-calendar'
      fullPath: '/history-calendar'
      preLoaderRoute: typeof HistoryCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encyclopedia': {
      id: '/encyclopedia'
      path: '/encyclopedia'
      fullPath: '/encyclopedia'
      preLoaderRoute: typeof EncyclopediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-audit': {
      id: '/content-audit'
      path: '/content-audit'
      fullPath: '/content-audit'
      preLoaderRoute: typeof ContentAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worlds/': {
      id: '/worlds/'
      path: '/worlds'
      fullPath: '/worlds/'
      preLoaderRoute: typeof WorldsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encyclopedia/': {
      id: '/encyclopedia/'
      path: '/'
      fullPath: '/encyclopedia/'
      preLoaderRoute: typeof EncyclopediaIndexRouteImport
      parentRoute: typeof EncyclopediaRoute
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worlds/$slug': {
      id: '/worlds/$slug'
      path: '/worlds/$slug'
      fullPath: '/worlds/$slug'
      preLoaderRoute: typeof WorldsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$id': {
      id: '/story/$id'
      path: '/story/$id'
      fullPath: '/story/$id'
      preLoaderRoute: typeof StoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/timeline': {
      id: '/play/timeline'
      path: '/play/timeline'
      fullPath: '/play/timeline'
      preLoaderRoute: typeof PlayTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/investigate': {
      id: '/play/investigate'
      path: '/play/investigate'
      fullPath: '/play/investigate'
      preLoaderRoute: typeof PlayInvestigateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/decisions': {
      id: '/play/decisions'
      path: '/play/decisions'
      fullPath: '/play/decisions'
      preLoaderRoute: typeof PlayDecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/chapter': {
      id: '/play/chapter'
      path: '/play/chapter'
      fullPath: '/play/chapter'
      preLoaderRoute: typeof PlayChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigation/$id': {
      id: '/investigation/$id'
      path: '/investigation/$id'
      fullPath: '/investigation/$id'
      preLoaderRoute: typeof InvestigationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/figure/$id': {
      id: '/figure/$id'
      path: '/figure/$id'
      fullPath: '/figure/$id'
      preLoaderRoute: typeof FigureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$id': {
      id: '/compare/$id'
      path: '/compare/$id'
      fullPath: '/compare/$id'
      preLoaderRoute: typeof CompareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/$id': {
      id: '/city/$id'
      path: '/city/$id'
      fullPath: '/city/$id'
      preLoaderRoute: typeof CityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle/$id': {
      id: '/battle/$id'
      path: '/battle/$id'
      fullPath: '/battle/$id'
      preLoaderRoute: typeof BattleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/world-membership-review': {
      id: '/admin/world-membership-review'
      path: '/admin/world-membership-review'
      fullPath: '/admin/world-membership-review'
      preLoaderRoute: typeof AdminWorldMembershipReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/offline': {
      id: '/admin/offline'
      path: '/admin/offline'
      fullPath: '/admin/offline'
      preLoaderRoute: typeof AdminOfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/museum-provenance': {
      id: '/admin/museum-provenance'
      path: '/admin/museum-provenance'
      fullPath: '/admin/museum-provenance'
      preLoaderRoute: typeof AdminMuseumProvenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/migration': {
      id: '/admin/migration'
      path: '/admin/migration'
      fullPath: '/admin/migration'
      preLoaderRoute: typeof AdminMigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/map': {
      id: '/admin/map'
      path: '/admin/map'
      fullPath: '/admin/map'
      preLoaderRoute: typeof AdminMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/investigations': {
      id: '/admin/investigations'
      path: '/admin/investigations'
      fullPath: '/admin/investigations'
      preLoaderRoute: typeof AdminInvestigationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hub-builder': {
      id: '/admin/hub-builder'
      path: '/admin/hub-builder'
      fullPath: '/admin/hub-builder'
      preLoaderRoute: typeof AdminHubBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/historical-hubs-audit': {
      id: '/admin/historical-hubs-audit'
      path: '/admin/historical-hubs-audit'
      fullPath: '/admin/historical-hubs-audit'
      preLoaderRoute: typeof AdminHistoricalHubsAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/games': {
      id: '/admin/games'
      path: '/admin/games'
      fullPath: '/admin/games'
      preLoaderRoute: typeof AdminGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/exploration-path-repair': {
      id: '/admin/exploration-path-repair'
      path: '/admin/exploration-path-repair'
      fullPath: '/admin/exploration-path-repair'
      preLoaderRoute: typeof AdminExplorationPathRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/era-normalization': {
      id: '/admin/era-normalization'
      path: '/admin/era-normalization'
      fullPath: '/admin/era-normalization'
      preLoaderRoute: typeof AdminEraNormalizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/encyclopedia-audit': {
      id: '/admin/encyclopedia-audit'
      path: '/admin/encyclopedia-audit'
      fullPath: '/admin/encyclopedia-audit'
      preLoaderRoute: typeof AdminEncyclopediaAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/encyclopedia': {
      id: '/admin/encyclopedia'
      path: '/admin/encyclopedia'
      fullPath: '/admin/encyclopedia'
      preLoaderRoute: typeof AdminEncyclopediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cross-hub-links': {
      id: '/admin/cross-hub-links'
      path: '/admin/cross-hub-links'
      fullPath: '/admin/cross-hub-links'
      preLoaderRoute: typeof AdminCrossHubLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content-inventory': {
      id: '/admin/content-inventory'
      path: '/admin/content-inventory'
      fullPath: '/admin/content-inventory'
      preLoaderRoute: typeof AdminContentInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content-integrity-repair': {
      id: '/admin/content-integrity-repair'
      path: '/admin/content-integrity-repair'
      fullPath: '/admin/content-integrity-repair'
      preLoaderRoute: typeof AdminContentIntegrityRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content-integrity': {
      id: '/admin/content-integrity'
      path: '/admin/content-integrity'
      fullPath: '/admin/content-integrity'
      preLoaderRoute: typeof AdminContentIntegrityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content-foundation': {
      id: '/admin/content-foundation'
      path: '/admin/content-foundation'
      fullPath: '/admin/content-foundation'
      preLoaderRoute: typeof AdminContentFoundationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content-cleanup': {
      id: '/admin/content-cleanup'
      path: '/admin/content-cleanup'
      fullPath: '/admin/content-cleanup'
      preLoaderRoute: typeof AdminContentCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content-auto-heal': {
      id: '/admin/content-auto-heal'
      path: '/admin/content-auto-heal'
      fullPath: '/admin/content-auto-heal'
      preLoaderRoute: typeof AdminContentAutoHealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/canonical-duplicates': {
      id: '/admin/canonical-duplicates'
      path: '/admin/canonical-duplicates'
      fullPath: '/admin/canonical-duplicates'
      preLoaderRoute: typeof AdminCanonicalDuplicatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/admin/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/campaign-relationships': {
      id: '/admin/campaign-relationships'
      path: '/admin/campaign-relationships'
      fullPath: '/admin/campaign-relationships'
      preLoaderRoute: typeof AdminCampaignRelationshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/atlas-review': {
      id: '/admin/atlas-review'
      path: '/admin/atlas-review'
      fullPath: '/admin/atlas-review'
      preLoaderRoute: typeof AdminAtlasReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/atlas-repair': {
      id: '/admin/atlas-repair'
      path: '/admin/atlas-repair'
      fullPath: '/admin/atlas-repair'
      preLoaderRoute: typeof AdminAtlasRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/atlas-import': {
      id: '/admin/atlas-import'
      path: '/admin/atlas-import'
      fullPath: '/admin/atlas-import'
      preLoaderRoute: typeof AdminAtlasImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/atlas-entities': {
      id: '/admin/atlas-entities'
      path: '/admin/atlas-entities'
      fullPath: '/admin/atlas-entities'
      preLoaderRoute: typeof AdminAtlasEntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/atlas-calibration': {
      id: '/admin/atlas-calibration'
      path: '/admin/atlas-calibration'
      fullPath: '/admin/atlas-calibration'
      preLoaderRoute: typeof AdminAtlasCalibrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/games/': {
      id: '/admin/games/'
      path: '/'
      fullPath: '/admin/games/'
      preLoaderRoute: typeof AdminGamesIndexRouteImport
      parentRoute: typeof AdminGamesRoute
    }
    '/encyclopedia/type/$type': {
      id: '/encyclopedia/type/$type'
      path: '/type/$type'
      fullPath: '/encyclopedia/type/$type'
      preLoaderRoute: typeof EncyclopediaTypeTypeRouteImport
      parentRoute: typeof EncyclopediaRoute
    }
    '/encyclopedia/state/$id': {
      id: '/encyclopedia/state/$id'
      path: '/state/$id'
      fullPath: '/encyclopedia/state/$id'
      preLoaderRoute: typeof EncyclopediaStateIdRouteImport
      parentRoute: typeof EncyclopediaRoute
    }
    '/encyclopedia/path/$id': {
      id: '/encyclopedia/path/$id'
      path: '/path/$id'
      fullPath: '/encyclopedia/path/$id'
      preLoaderRoute: typeof EncyclopediaPathIdRouteImport
      parentRoute: typeof EncyclopediaRoute
    }
    '/encyclopedia/entity/$id': {
      id: '/encyclopedia/entity/$id'
      path: '/entity/$id'
      fullPath: '/encyclopedia/entity/$id'
      preLoaderRoute: typeof EncyclopediaEntityIdRouteImport
      parentRoute: typeof EncyclopediaRoute
    }
    '/admin/games/$mode': {
      id: '/admin/games/$mode'
      path: '/$mode'
      fullPath: '/admin/games/$mode'
      preLoaderRoute: typeof AdminGamesModeRouteImport
      parentRoute: typeof AdminGamesRoute
    }
    '/campaigns/imported/$id/': {
      id: '/campaigns/imported/$id/'
      path: '/imported/$id'
      fullPath: '/campaigns/imported/$id/'
      preLoaderRoute: typeof CampaignsImportedIdIndexRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/campaigns/imported/$id/chapter/$chapter': {
      id: '/campaigns/imported/$id/chapter/$chapter'
      path: '/imported/$id/chapter/$chapter'
      fullPath: '/campaigns/imported/$id/chapter/$chapter'
      preLoaderRoute: typeof CampaignsImportedIdChapterChapterRouteImport
      parentRoute: typeof CampaignsRoute
    }
  }
}

interface CampaignsRouteChildren {
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  CampaignsImportedIdIndexRoute: typeof CampaignsImportedIdIndexRoute
  CampaignsImportedIdChapterChapterRoute: typeof CampaignsImportedIdChapterChapterRoute
}

const CampaignsRouteChildren: CampaignsRouteChildren = {
  CampaignsIndexRoute: CampaignsIndexRoute,
  CampaignsImportedIdIndexRoute: CampaignsImportedIdIndexRoute,
  CampaignsImportedIdChapterChapterRoute:
    CampaignsImportedIdChapterChapterRoute,
}

const CampaignsRouteWithChildren = CampaignsRoute._addFileChildren(
  CampaignsRouteChildren,
)

interface EncyclopediaRouteChildren {
  EncyclopediaIndexRoute: typeof EncyclopediaIndexRoute
  EncyclopediaEntityIdRoute: typeof EncyclopediaEntityIdRoute
  EncyclopediaPathIdRoute: typeof EncyclopediaPathIdRoute
  EncyclopediaStateIdRoute: typeof EncyclopediaStateIdRoute
  EncyclopediaTypeTypeRoute: typeof EncyclopediaTypeTypeRoute
}

const EncyclopediaRouteChildren: EncyclopediaRouteChildren = {
  EncyclopediaIndexRoute: EncyclopediaIndexRoute,
  EncyclopediaEntityIdRoute: EncyclopediaEntityIdRoute,
  EncyclopediaPathIdRoute: EncyclopediaPathIdRoute,
  EncyclopediaStateIdRoute: EncyclopediaStateIdRoute,
  EncyclopediaTypeTypeRoute: EncyclopediaTypeTypeRoute,
}

const EncyclopediaRouteWithChildren = EncyclopediaRoute._addFileChildren(
  EncyclopediaRouteChildren,
)

interface AdminGamesRouteChildren {
  AdminGamesModeRoute: typeof AdminGamesModeRoute
  AdminGamesIndexRoute: typeof AdminGamesIndexRoute
}

const AdminGamesRouteChildren: AdminGamesRouteChildren = {
  AdminGamesModeRoute: AdminGamesModeRoute,
  AdminGamesIndexRoute: AdminGamesIndexRoute,
}

const AdminGamesRouteWithChildren = AdminGamesRoute._addFileChildren(
  AdminGamesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  AuthRoute: AuthRoute,
  CampaignsRoute: CampaignsRouteWithChildren,
  CollectionRoute: CollectionRoute,
  ContentAuditRoute: ContentAuditRoute,
  EncyclopediaRoute: EncyclopediaRouteWithChildren,
  FriendsRoute: FriendsRoute,
  HistoryCalendarRoute: HistoryCalendarRoute,
  InvestigationsRoute: InvestigationsRoute,
  MapRoute: MapRoute,
  NotificationsRoute: NotificationsRoute,
  OnThisDayRoute: OnThisDayRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ReferralsRoute: ReferralsRoute,
  SeasonsRoute: SeasonsRoute,
  SecurityRoute: SecurityRoute,
  ShareCardRoute: ShareCardRoute,
  TermsRoute: TermsRoute,
  TimelineRoute: TimelineRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAtlasCalibrationRoute: AdminAtlasCalibrationRoute,
  AdminAtlasEntitiesRoute: AdminAtlasEntitiesRoute,
  AdminAtlasImportRoute: AdminAtlasImportRoute,
  AdminAtlasRepairRoute: AdminAtlasRepairRoute,
  AdminAtlasReviewRoute: AdminAtlasReviewRoute,
  AdminCampaignRelationshipsRoute: AdminCampaignRelationshipsRoute,
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminCanonicalDuplicatesRoute: AdminCanonicalDuplicatesRoute,
  AdminContentRoute: AdminContentRoute,
  AdminContentAutoHealRoute: AdminContentAutoHealRoute,
  AdminContentCleanupRoute: AdminContentCleanupRoute,
  AdminContentFoundationRoute: AdminContentFoundationRoute,
  AdminContentIntegrityRoute: AdminContentIntegrityRoute,
  AdminContentIntegrityRepairRoute: AdminContentIntegrityRepairRoute,
  AdminContentInventoryRoute: AdminContentInventoryRoute,
  AdminCrossHubLinksRoute: AdminCrossHubLinksRoute,
  AdminEncyclopediaRoute: AdminEncyclopediaRoute,
  AdminEncyclopediaAuditRoute: AdminEncyclopediaAuditRoute,
  AdminEraNormalizationRoute: AdminEraNormalizationRoute,
  AdminExplorationPathRepairRoute: AdminExplorationPathRepairRoute,
  AdminGamesRoute: AdminGamesRouteWithChildren,
  AdminHistoricalHubsAuditRoute: AdminHistoricalHubsAuditRoute,
  AdminHubBuilderRoute: AdminHubBuilderRoute,
  AdminImportRoute: AdminImportRoute,
  AdminInvestigationsRoute: AdminInvestigationsRoute,
  AdminMapRoute: AdminMapRoute,
  AdminMigrationRoute: AdminMigrationRoute,
  AdminMuseumProvenanceRoute: AdminMuseumProvenanceRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOfflineRoute: AdminOfflineRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWorldMembershipReviewRoute: AdminWorldMembershipReviewRoute,
  BattleIdRoute: BattleIdRoute,
  CityIdRoute: CityIdRoute,
  CompareIdRoute: CompareIdRoute,
  FigureIdRoute: FigureIdRoute,
  InvestigationIdRoute: InvestigationIdRoute,
  PlayChapterRoute: PlayChapterRoute,
  PlayDecisionsRoute: PlayDecisionsRoute,
  PlayInvestigateRoute: PlayInvestigateRoute,
  PlayTimelineRoute: PlayTimelineRoute,
  StoryIdRoute: StoryIdRoute,
  UUsernameRoute: UUsernameRoute,
  WorldsSlugRoute: WorldsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  WorldsIndexRoute: WorldsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
