/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnThisDayRouteImport } from './routes/on-this-day'
import { Route as MapRouteImport } from './routes/map'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoryIdRouteImport } from './routes/story.$id'
import { Route as PlayTimelineRouteImport } from './routes/play.timeline'
import { Route as PlayInvestigateRouteImport } from './routes/play.investigate'
import { Route as PlayDecisionsRouteImport } from './routes/play.decisions'

const OnThisDayRoute = OnThisDayRouteImport.update({
  id: '/on-this-day',
  path: '/on-this-day',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryIdRoute = StoryIdRouteImport.update({
  id: '/story/$id',
  path: '/story/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayTimelineRoute = PlayTimelineRouteImport.update({
  id: '/play/timeline',
  path: '/play/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayInvestigateRoute = PlayInvestigateRouteImport.update({
  id: '/play/investigate',
  path: '/play/investigate',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayDecisionsRoute = PlayDecisionsRouteImport.update({
  id: '/play/decisions',
  path: '/play/decisions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRoute
  '/map': typeof MapRoute
  '/on-this-day': typeof OnThisDayRoute
  '/play/decisions': typeof PlayDecisionsRoute
  '/play/investigate': typeof PlayInvestigateRoute
  '/play/timeline': typeof PlayTimelineRoute
  '/story/$id': typeof StoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRoute
  '/map': typeof MapRoute
  '/on-this-day': typeof OnThisDayRoute
  '/play/decisions': typeof PlayDecisionsRoute
  '/play/investigate': typeof PlayInvestigateRoute
  '/play/timeline': typeof PlayTimelineRoute
  '/story/$id': typeof StoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRoute
  '/map': typeof MapRoute
  '/on-this-day': typeof OnThisDayRoute
  '/play/decisions': typeof PlayDecisionsRoute
  '/play/investigate': typeof PlayInvestigateRoute
  '/play/timeline': typeof PlayTimelineRoute
  '/story/$id': typeof StoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaigns'
    | '/map'
    | '/on-this-day'
    | '/play/decisions'
    | '/play/investigate'
    | '/play/timeline'
    | '/story/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campaigns'
    | '/map'
    | '/on-this-day'
    | '/play/decisions'
    | '/play/investigate'
    | '/play/timeline'
    | '/story/$id'
  id:
    | '__root__'
    | '/'
    | '/campaigns'
    | '/map'
    | '/on-this-day'
    | '/play/decisions'
    | '/play/investigate'
    | '/play/timeline'
    | '/story/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignsRoute: typeof CampaignsRoute
  MapRoute: typeof MapRoute
  OnThisDayRoute: typeof OnThisDayRoute
  PlayDecisionsRoute: typeof PlayDecisionsRoute
  PlayInvestigateRoute: typeof PlayInvestigateRoute
  PlayTimelineRoute: typeof PlayTimelineRoute
  StoryIdRoute: typeof StoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/on-this-day': {
      id: '/on-this-day'
      path: '/on-this-day'
      fullPath: '/on-this-day'
      preLoaderRoute: typeof OnThisDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$id': {
      id: '/story/$id'
      path: '/story/$id'
      fullPath: '/story/$id'
      preLoaderRoute: typeof StoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/timeline': {
      id: '/play/timeline'
      path: '/play/timeline'
      fullPath: '/play/timeline'
      preLoaderRoute: typeof PlayTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/investigate': {
      id: '/play/investigate'
      path: '/play/investigate'
      fullPath: '/play/investigate'
      preLoaderRoute: typeof PlayInvestigateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/decisions': {
      id: '/play/decisions'
      path: '/play/decisions'
      fullPath: '/play/decisions'
      preLoaderRoute: typeof PlayDecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignsRoute: CampaignsRoute,
  MapRoute: MapRoute,
  OnThisDayRoute: OnThisDayRoute,
  PlayDecisionsRoute: PlayDecisionsRoute,
  PlayInvestigateRoute: PlayInvestigateRoute,
  PlayTimelineRoute: PlayTimelineRoute,
  StoryIdRoute: StoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
