// Phase 0 — Atlas Calibration Anchors (v1)
// Source of truth for the geo↔APS transform.
//
// IMPORTANT: APS pixel coordinates below are PROVISIONAL.
// They were generated by linear projection from the lon/lat bounding box
// `LONLAT_BBOX_V1` and have NOT been visually measured against the v1 raster
// per docs/atlas/atlas-calibration-plan.md §3.4. Every anchor with
// `verified: false` must be re-measured by two reviewers at 100% zoom on the
// frozen master and the value committed back to this file before the
// calibration is considered frozen.
//
// Atlas v1 raster: 14192 × 7088 (asset ee043b12-de34-450a-b8f7-0510eadb423d).

export type AtlasVersion = "v1";

export type AtlasAnchor = {
  /** Stable id used by the validator and remap table. */
  id: string;
  /** Display name (English). */
  name: string;
  /** Coarse region label, matches docs §3.2. */
  region: string;
  /** WGS84 decimal degrees. */
  lon: number;
  lat: number;
  /** Atlas Pixel Space — origin top-left, Y down, units = v1 master pixels. */
  aps: { x: number; y: number };
  /** False until visually placed on the v1 raster by a reviewer. */
  verified: boolean;
  /** Free-text note from the plan / reviewer. */
  notes?: string;
};

/** Rough geographic envelope used to seed provisional APS values. */
export const LONLAT_BBOX_V1 = {
  lonMin: -12,
  lonMax: 80,
  latMin: 8,
  latMax: 48,
} as const;

export const ATLAS_V1_PIXEL_SIZE = { width: 14192, height: 7088 } as const;

/**
 * Linear seed projection from (lon, lat) to APS using `LONLAT_BBOX_V1`.
 * Only used to fill provisional anchor values — never as the runtime transform.
 */
function seedAps(lon: number, lat: number): { x: number; y: number } {
  const { lonMin, lonMax, latMin, latMax } = LONLAT_BBOX_V1;
  const { width, height } = ATLAS_V1_PIXEL_SIZE;
  const u = (lon - lonMin) / (lonMax - lonMin);
  const v = (latMax - lat) / (latMax - latMin); // Y down
  return { x: Math.round(u * width), y: Math.round(v * height) };
}

type AnchorSeed = Omit<AtlasAnchor, "aps" | "verified"> & {
  aps?: { x: number; y: number };
  verified?: boolean;
};

const SEEDS: AnchorSeed[] = [
  { id: "cordoba",       name: "Cordoba",        region: "Iberia (NW)",          lon: -4.78, lat: 37.89, aps: { x:   913, y: 2544 }, verified: true,  notes: "Far-west anchor; controls western edge tightness" },
  { id: "marrakech",     name: "Marrakech",      region: "Maghreb (SW)",         lon: -7.99, lat: 31.63, aps: { x:   898, y: 3745 }, verified: true,  notes: "Anchors SW quadrant + Atlas mountains" },
  { id: "cairo",         name: "Cairo",          region: "Egypt",                lon: 31.24, lat: 30.04, aps: { x:  4359, y: 3704 }, verified: true,  notes: "Nile delta hinge" },
  { id: "alexandria",    name: "Alexandria",     region: "Egypt coast",          lon: 29.92, lat: 31.20, aps: { x:  4311, y: 3497 }, verified: true,  notes: "Coastline pair with Cairo, fixes delta shape" },
  { id: "jerusalem",     name: "Jerusalem",      region: "Levant",               lon: 35.23, lat: 31.78, aps: { x:  4820, y: 3362 }, verified: true,  notes: "Center-south, dense reference region" },
  { id: "damascus",      name: "Damascus",       region: "Levant inland",        lon: 36.29, lat: 33.51, aps: { x:  5032, y: 2975 }, verified: true,  notes: "Pairs with Jerusalem for inland scale" },
  { id: "constantinople",name: "Constantinople", region: "Bosporus",             lon: 28.98, lat: 41.01, aps: { x:  4101, y: 2386 }, verified: true,  notes: "NW anchor; locks Black Sea / Aegean hinge" },
  { id: "mecca",         name: "Mecca",          region: "Hejaz",                lon: 39.83, lat: 21.42, aps: { x:  5430, y: 4055 }, verified: true,  notes: "South-central; controls Arabian peninsula" },
  { id: "medina",        name: "Medina",         region: "Hejaz",                lon: 39.61, lat: 24.47, aps: { x:  5604, y: 4643 }, verified: true,  notes: "Pairs with Mecca; small-scale residual check" },
  { id: "baghdad",       name: "Baghdad",        region: "Mesopotamia",          lon: 44.36, lat: 33.31, aps: { x:  5789, y: 2815 }, verified: true,  notes: "Central crossroad" },
  { id: "basra",         name: "Basra",          region: "Lower Mesopotamia",    lon: 47.78, lat: 30.51, aps: { x:  6268, y: 3294 }, verified: true,  notes: "Persian Gulf head" },
  { id: "isfahan",       name: "Isfahan",        region: "Persia",               lon: 51.67, lat: 32.65, aps: { x:  6803, y: 3257 }, verified: true,  notes: "Central Persia" },
  { id: "nishapur",      name: "Nishapur",       region: "Khorasan",             lon: 58.80, lat: 36.21, aps: { x:  6829, y: 2366 }, verified: true,  notes: "NE Persia, bridges to Transoxiana" },
  { id: "samarkand",     name: "Samarkand",      region: "Transoxiana",          lon: 66.97, lat: 39.65, aps: { x: 10472, y: 2149 }, verified: true,  notes: "Far-east-inland; Silk Road hinge" },
  { id: "bukhara",       name: "Bukhara",        region: "Transoxiana",          lon: 64.42, lat: 39.77, aps: { x:  9822, y: 2412 }, verified: true,  notes: "Small-scale residual pair with Samarkand" },
  { id: "delhi",         name: "Delhi",          region: "Indian subcontinent",  lon: 77.10, lat: 28.70, aps: { x: 10116, y: 3594 }, verified: true,  notes: "SE anchor; locks far-east bound of v1" },
];

export const ATLAS_ANCHORS_V1: readonly AtlasAnchor[] = SEEDS.map((s) => ({
  ...s,
  aps: s.aps ?? seedAps(s.lon, s.lat),
  verified: s.verified ?? false,
}));

export function getAnchor(id: string): AtlasAnchor | undefined {
  return ATLAS_ANCHORS_V1.find((a) => a.id === id);
}
